### ISSUE TITLE
[Bug]: Batch import Sales channel not parsing array

### ISSUE THREAD

**Issue by minimino** [medusajs/medusa#10001]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

v20.18.0

### Database and its version

17.0

### Operating system name and version

Ubuntu 24.04.1 LTS

### Browser name

Edge

### What happended?

When importing products using the GUI, if there is a column named _Product Sales Channels_, the import will fail. I know this column is not in the official template provided, but it is terribly inefficient to import hundreds of products and manually setting the sales channels in each one of them. 

I have managed to get it working, though I feel my solution is not ideal. I think the possible solutions are the following:

1. Modify the function `createProductsWorkflow` inside `medusa/packages/core/core-flows/src/product/workflows/create-products.ts`. This is the approach I have done. We would need to modify/add the following code:
```
  if (inputProduct.sales_channels) {
      inputProduct.sales_channels = JSON.parse(inputProduct.sales_channels.replace(/'/g, '"')); 
  }

  return (inputProduct.sales_channels?.map((salesChannel) => ({
      sales_channel_id: salesChannel.id ?? salesChannel,
      product_id: createdProduct.id,
  })) ?? []);
```
I think this solution is not ideal because we are doing the job of the CSV parser inside an unrelated function. I did it because I needed a quick and dirty fix. In this case, the imported CSV has a column named _Product Sales Channels_, whose rows are arrays containing the IDs of the Sales Channels of the product.
2. Modify the CSV Parser in order to parse arrays. I feeld this approach is cleaner. We would need to modify `convertCsvToJson` in `packages/core/core-flows/src/product/utlils/csvtojson.ts`, or use another parser which supports parsing string arrays (supposing it exists).
3. Prevent the user from adding the Sales Channel when bulk importing. This is, for obvious reasons, the worst solution.

### Expected behavior

The user should be able to import products and set the Sales channels in the imported CSV.

### Actual behavior

The following error is raised in the console when importing a CSV file with products:

```
error:   import-products:batch-products-as-step:invoke - inputProduct.sales_channels?.map is not a function
TypeError: inputProduct.sales_channels?.map is not a function
    at node_modules/@medusajs/core-flows/src/product/workflows/create-products.ts:87:11 at Array.map (<anonymous>)
    at Function.<anonymous> (node_modules/@medusajs/core-flows/src/product/workflows/create-products.ts:79:10)
    at Proxy.returnFn (node_modules/@medusajs/workflows-sdk/src/utils/composer/transform.ts:192:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveProperty (node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:17:11)
    at async unwrapInput (node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:61:9)
    at async resolveValue (node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:79:7)
    at async Object.invoke (node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:71:32)
    at async DistributedTransaction.handler (node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)
⮑ sat node_modules/@medusajs/core-flows/dist/product/workflows/create-products.js: [create-products -> associate-products-with-channels (invoke)]
⮑ sat node_modules/@medusajs/core-flows/dist/product/workflows/batch-products.js: [batch-products -> create-products-as-step (invoke)]
⮑ sat node_modules/@medusajs/core-flows/dist/product/workflows/import-products.js: [import-products -> batch-products-as-step (invoke)]
```

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by sgirones** [comment]
hey @minimino, thanks for opening the issue.

I understand the friction of the scenario you are describing. Could you open a Feature Request in the Discussions tab though? The current behaviour is intentional, so any change to it should be treated as a Feature Request.
