### ISSUE TITLE
unable to start medusa server

### ISSUE THREAD

**Issue by rishabh1811** [medusajs/medusa#1004]
getting this error 

'D:\Web' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: D:\Web Development\medusa\my-medusa-store\node_modules\.bin\babel src -d dist
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at D:\Web Development\medusa\my-medusa-store\node_modules\@medusajs\medusa\dist\commands\develop.js:82:42
    at step (D:\Web Development\medusa\my-medusa-store\node_modules\@medusajs\medusa\dist\commands\develop.js:33:23)
    at Object.next (D:\Web Development\medusa\my-medusa-store\node_modules\@medusajs\medusa\dist\commands\develop.js:14:53)
    at D:\Web Development\medusa\my-medusa-store\node_modules\@medusajs\medusa\dist\commands\develop.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Web Development\medusa\my-medusa-store\node_modules\@medusajs\medusa\dist\commands\develop.js:4:12)
    at default_1 (D:\Web Development\medusa\my-medusa-store\node_modules\@medusajs\medusa\dist\commands\develop.js:74:12)
    at D:\Web Development\medusa\my-medusa-store\node_modules\@medusajs\medusa-cli\dist\create-cli.js:260:7 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3424,
  stdout: null,
  stderr: null
}

**Comment by ymaheshwari1** [comment]
Hi,
I was having the same issue, and I found that if you have a folder name with space in between `Web Development` then the medusa command does not work, try creating the project in a directory with no space in between.

**Comment by rishabh1811** [comment]
> Hi, I was having the same issue, and I found that if you have a folder name with space in between `Web Development` then the medusa command does not work, try creating the project in a directory with no space in between.

thanks 👍🏻, This solved my problem.
