### ISSUE TITLE
Can't insert null value in field fulfillment_id on insert in table tracking_link

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#10057]
Medusa `1.20.10`.

Two things:

1. Where did the `Mark as shipped` (`{{medusa-host}}/admin/orders/:id/shipment`) go? I cannot find it in the docs anymore.
2. When I call this, I get the following `400 bad request` on a specific order:
```json
{
    "type": "invalid_data",
    "message": "Can't insert null value in field fulfillment_id on insert in table tracking_link"
}
```

All my other orders worked so far.

In the logs I see this:

```shell
2024-11-12T12:46:20.754021368Z app[web.1]: 172.71.99.47 - - [12/Nov/2024:12:46:20 +0000] "POST /admin/orders/order_01JBTARNF3BYSE2HW43S0STFWB/shipment HTTP/1.1" 400 138 "-" "PostmanRuntime/7.42.0"
2024-11-12T12:46:20.754709722Z app[web.1]: SyntaxError: Expected double-quoted property name in JSON at position 58
2024-11-12T12:46:20.754819517Z app[web.1]:     at JSON.parse (<anonymous>)
2024-11-12T12:46:20.754891160Z app[web.1]:     at parse (/app/node_modules/body-parser/lib/types/json.js:92:19)
2024-11-12T12:46:20.754904089Z app[web.1]:     at /app/node_modules/body-parser/lib/read.js:128:18
2024-11-12T12:46:20.754916106Z app[web.1]:     at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
2024-11-12T12:46:20.754926702Z app[web.1]:     at invokeCallback (/app/node_modules/raw-body/index.js:238:16)
2024-11-12T12:46:20.754937231Z app[web.1]:     at done (/app/node_modules/raw-body/index.js:227:7)
2024-11-12T12:46:20.754947647Z app[web.1]:     at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)
2024-11-12T12:46:20.754958438Z app[web.1]:     at IncomingMessage.emit (node:events:519:28)
2024-11-12T12:46:20.754968845Z app[web.1]:     at IncomingMessage.emit (node:domain:488:12)
2024-11-12T12:46:20.754979523Z app[web.1]:     at endReadableNT (node:internal/streams/readable:1696:12)
2024-11-12T12:46:21.915287509Z app[web.1]: {"level":"error","message":"Can't insert null value in field fulfillment_id on insert in table tracking_link","stack":[{"columnNumber":20,"fileName":"/app/node_modules/@medusajs/medusa/dist/utils/exception-formatter.js","functionName":"formatException","lineNumber":30,"methodName":null,"native":false,"typeName":null},{"columnNumber":43,"fileName":"/app/node_modules/@medusajs/medusa/dist/api/middlewares/error-handler.js","functionName":"exports.default","lineNumber":14,"methodName":"default","native":false,"typeName":"exports"},{"columnNumber":41,"fileName":"/app/node_modules/medusa-plugin-sentry/api/index.js","functionName":null,"lineNumber":86,"methodName":null,"native":false,"typeName":null},{"columnNumber":5,"fileName":"/app/node_modules/express/lib/router/layer.js","functionName":"Layer.handle_error","lineNumber":71,"methodName":"handle_error","native":false,"typeName":"Layer"},{"columnNumber":13,"fileName":"/app/node_modules/express/lib/router/index.js","functionName":"trim_prefix","lineNumber":326,"methodName":null,"native":false,"typeName":null},{"columnNumber":9,"fileName":"/app/node_modules/express/lib/router/index.js","functionName":null,"lineNumber":286,"methodName":null,"native":false,"typeName":null},{"columnNumber":12,"fileName":"/app/node_modules/express/lib/router/index.js","functionName":"Function.process_params","lineNumber":346,"methodName":"process_params","native":false,"typeName":"Function"},{"columnNumber":34,"fileName":"/app/node_modules/@sentry-internal/tracing/cjs/node/integrations/express.js","functionName":"Function.process_params","lineNumber":314,"methodName":"process_params","native":false,"typeName":"Function"},{"columnNumber":10,"fileName":"/app/node_modules/express/lib/router/index.js","functionName":"next","lineNumber":280,"methodName":null,"native":false,"typeName":null},{"columnNumber":15,"fileName":"/app/node_modules/express/lib/router/index.js","functionName":null,"lineNumber":646,"methodName":null,"native":false,"typeName":null}],"timestamp":"2024-11-12 12:46:21"}
```

This is my request:
```json
{
    "fulfillment_id": "ful_01JBTDZCZMGWHH2SMVQ4YJY7JK",
    "tracking_numbers": ["https://todays.picqer.com/s/gRAf2gYSl0Kv3txqfIHKFoUeV9SZfAzK"]
}
```

What is this?

**Comment by BorisKamp** [comment]
Okay I think it happens when you try to mark a fulfilment as shipped a second time. We get incoming webhooks from out fulfillment provider, so it might occur in our case that we get a 'marked as ship' webhook twice for the same order. then when the first one succeeded, the second one fails with this error. 

This is very unclear of you ask me.

**Comment by olivermrbl** [comment]
@BorisKamp, thanks for the report. We generally do not patch versions < 2.0.0 unless they are critical issues. That said, you are more than welcome to send a PR with a fix, if you are up for it and we will accept it and cut a new release.

Alternatively, perhaps you could introduce some logic in your webhook endpoint that checks for an existing shipment before attempting to create it?

As for the question about the endpoint itself, I believe it hasn't moved anywhere: https://github.com/medusajs/medusa/blob/09b36adb7667b365f359d5055acb67d75b0a8e52/packages/medusa/src/api/routes/admin/orders/index.ts#L241-L251

**Comment by thetutlage** [comment]
I will close this issue and as @olivermrbl mentioned you can create a PR for the same 🙂
