### ISSUE TITLE
[Bug]: Fail to update customer email address

### ISSUE THREAD

**Issue by iamkabelomoobi** [medusajs/medusa#10146]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "predeploy": "medusa db:migrate",
    "start": "cd .medusa/server && npm run predeploy && npm run start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/file-s3": "^2.0.3",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "medusa-file-cloudinary": "^1.0.2",
    "medusa-payment-paystack": "^2.0.0-next.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.15.0

### Database and its version

psql (PostgreSQL) 16.3 (Debian 16.3-1+b1)

### Operating system name and version

 Kali GNU/Linux Rolling x 

### Browser name

Firefox

### What happended?

When i update my logged-in customer email

### Expected behavior

Successfully updated customer email

### Actual behavior

```jsx
http:    GET /store/customers/me ← http://localhost:5173/ (304) - 1734.612 ms
http:    OPTIONS /store/customers/me ← http://localhost:5173/ (204) - 1.352 ms
error:   Invalid request: Unrecognized fields: 'email'
MedusaError: Invalid request: Unrecognized fields: 'email'
    at zodValidator (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/@medusajs/framework/src/zod/zod-helpers.ts:126:13)            
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateBody (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/@medusajs/framework/src/http/utils/validate-body.ts:30:27) {
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2024-11-18T19:15:24.832Z
}
```

```
ice&region_id=reg_01JCPAB1SAMV1XSQ2QCPWH31JQ ← http://localhost:5173/ (304) - 6015.809 ms
http:    OPTIONS /auth/customer/emailpass/update ← http://localhost:5173/ (204) - 5.410 ms
error:   Invalid token
MedusaError: Invalid token
    at /home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/@medusajs/medusa/src/api/auth/utils/validate-token.ts:27:25
    at Layer.handle [as handle_request] (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/layer.js:95:5)         
    at next (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/route.js:149:13)
    at /home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/@medusajs/medusa/src/api/auth/utils/validate-scope-provider-association.ts:36:5
    at Layer.handle [as handle_request] (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/layer.js:95:5)         
    at next (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/route.js:119:3)                          
    at Layer.handle [as handle_request] (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/layer.js:95:5)         
    at /home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/index.js:284:15
    at param (/home/the-berufegoru/Workspace/Closesource/buntuthreads/backend/node_modules/express/lib/router/index.js:365:14) {
  __isMedusaError: true,
  type: 'unauthorized',
  code: undefined,
  date: 2024-11-18T18:59:43.071Z
}
```

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by olivermrbl** [comment]
@the-berufegoru, can you provide reproducible steps? That would help a lot in our debugging.

**Comment by iamkabelomoobi** [comment]
![config](https://github.com/user-attachments/assets/12998e92-3b96-47a8-acec-65de1959684b)
![customer-update](https://github.com/user-attachments/assets/aa2bbf78-781a-4ca7-9abc-ab1693f8edd7)
![customer-update-error](https://github.com/user-attachments/assets/c819f01d-13e8-438e-babe-0c3314c8ab55)

**Comment by olivermrbl** [comment]
Regardless of the token issue, this won't work. We currently don't support updating the email of your identity, only the password. Did you find a guide for this in our documentation or elsewhere? If so, we will need to get it updated.

**Comment by olivermrbl** [comment]
Also, right now, we only support updates via a token flow. You can read more about it [here](https://docs.medusajs.com/resources/commerce-modules/auth/reset-password).

**Comment by iamkabelomoobi** [comment]
@olivermrbl my customers wont be able to update their email addresses at the moment?
