### ISSUE TITLE
[Bug]: Could not find index.html in the admin build directory. Make sure to run 'medusa build' before starting the server.

### ISSUE THREAD

**Issue by kanrio** [medusajs/medusa#10147]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.16.0

### Database and its version

15.7

### Operating system name and version

MacOs, sonoma 14.5

### Browser name

Chrome

### What happended?

npm run seed or yarn seed after building with npm or yarn
error:   Could not find index.html in the admin build directory. Make sure to run 'medusa build' before starting the server.
Error: Could not find index.html in the admin build directory. Make sure to run 'medusa build' before starting the server.

### Expected behavior

Seeding database

### Actual behavior

not seeding an error occurs
$ medusa exec ./src/scripts/seed.ts
info:    Executing script at ./src/scripts/seed.ts...
info:    Connection to Redis in module 'cache-redis' established
info:    Connection to Redis in module 'event-bus-redis' established
info:    Connection to Redis in module 'workflow-engine-redis' established
info:    Connection to Redis PubSub in module 'workflow-engine-redis' established
info:    Locking module: Using "in-memory" as default.
info:    No job to load from /Users/x/Projects/xx/node_modules/@medusajs/medusa/dist/jobs. skipped.
error:   Error running script
error:   Could not find index.html in the admin build directory. Make sure to run 'medusa build' before starting the server.
Error: Could not find index.html in the admin build directory. Make sure to run 'medusa build' before starting the server.
    at serve (/Users/x/Projects/xx/node_modules/@medusajs/admin-bundler/dist/index.js:1344:11)
    at serveProductionBuild (/Users/x/Projects/xx/node_modules/@medusajs/medusa/src/loaders/admin.ts:75:28)
    at async loadEntrypoints (/Users/x/Projects/xx/node_modules/@medusajs/medusa/src/loaders/index.ts:108:3)
    at async exports.default (/Users/x/Projects/xx/node_modules/@medusajs/medusa/src/loaders/index.ts:164:31)
    at async exec (/Users/x/Projects/xx/node_modules/@medusajs/medusa/src/commands/exec.ts:35:27)
error Command failed with exit code 1.

### Link to reproduction repo

fresh install

**Comment by slimsaelim** [comment]
I solved this issue by adding NODE_ENV to development like this

`NODE_ENV=development npm run seed`

**Comment by riqwan** [comment]
Hey @kanrio, can you confirm that your node env is development or production?

**Comment by grgmgd** [comment]
@riqwan I have the same problem running medusa start inside docker with NODE_ENV set to `production`

**Comment by riqwan** [comment]
Thanks @grgmgd, can you open a PR with the docker changes? I can take a look.

**Comment by grgmgd** [comment]
@riqwan I tested it outside docker and the same problem happens. I just upgraded from the preview version to latest and I noticed the outDir changed to `.medusa`. So, I updated my `tsconfig.json` to match the latest default stater and the issue is still present. Am I missing something? the admin loader is trying to load the admin from `src/admin` instead of `.medusa/server/public/admin`

**Comment by riqwan** [comment]
Let me try to reproduce, in the meantime can you share your tsconfig, package.json & medusa-config? @grgmgd

**Comment by filiotech** [comment]
Hi everyone,

I’ve recently started exploring Medusa and wanted to try it out, but I’ve encountered an issue. After testing with version **2.0.4**, I can confirm the same problem as others have reported. Here are the details:

The issue only occurs when running with **NODE_ENV=production**.
The server gives the following error:

```
{"level":"error","message":"Could not find index.html in the admin build directory. Make sure to run 'medusa build' before starting the server.","stack":[{"columnNumber":11,"fileName":"/var/www/backend/node_modules/@medusajs/admin-bundler/dist/index.js","functionName":"serve","lineNumber":1344,"methodName":null,"native":false,"typeName":null},{"columnNumber":28,"fileName":"/var/www/backend/node_modules/@medusajs/medusa/src/loaders/admin.ts","functionName":"serveProductionBuild","lineNumber":75,"methodName":null,"native":false,"typeName":null},{"columnNumber":3,"fileName":"/var/www/backend/node_modules/@medusajs/medusa/src/loaders/index.ts","functionName":"async loadEntrypoints","lineNumber":108,"methodName":null,"native":false,"typeName":null},{"columnNumber":31,"fileName":"/var/www/backend/node_modules/@medusajs/medusa/src/loaders/index.ts","functionName":"async exports.default","lineNumber":164,"methodName":"default","native":false,"typeName":"async exports"},{"columnNumber":50,"fileName":"/var/www/backend/node_modules/@medusajs/medusa/src/commands/start.ts","functionName":"async internalStart","lineNumber":123,"methodName":null,"native":false,"typeName":null},{"columnNumber":5,"fileName":"/var/www/backend/node_modules/@medusajs/medusa/src/commands/start.ts","functionName":"async start","lineNumber":227,"methodName":null,"native":false,"typeName":null}],"timestamp":"2024-11-24 11:33:47"}
error Command failed with exit code 1.
```

Key observations:

- The server starts successfully in development mode, but the error above is thrown in production.
- I’ve done a fresh installation and included all dependencies (listed below) for clarity.
- Using Node.js v20.18.1.

Dependencies:

{
  "@medusajs/admin-sdk": "^2.0.4",
  "@medusajs/cli": "latest",
  "@medusajs/event-bus-redis": "^2.0.4",
  "@medusajs/framework": "latest",
  "@medusajs/medusa": "latest",
  "@mikro-orm/core": "5.9.7",
  "@mikro-orm/knex": "5.9.7",
  "@mikro-orm/migrations": "5.9.7",
  "@mikro-orm/postgresql": "5.9.7",
  "awilix": "^8.0.1",
  "express-session": "^1.18.1",
  "memorystore": "^1.6.7",
  "pg": "^8.13.0"
}

if anyone has resolved this or has insights into the root cause, I’d appreciate your guidance.
Thank you in advance!

**Comment by thunderwin** [comment]
I have the same problme, I just Drop "        

// NODE_ENV: 'production',
 "
 
 for now.. I dont know how to solve it!

**Comment by Saboor-Hakimi** [comment]
updating your `build` script to `medusa build && ln -s .medusa/server/public/ public` will fix this issue
```
"scripts": {
    "build": "medusa build && ln -s .medusa/server/public/ public",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "NODE_ENV=production medusa start -H 0.0.0.0",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  }
  ```

**Comment by rafalkukla** [comment]
@Saboor-Hakimi awesome! Yep, server start in production! 
Now, I seems to have 401 (Unauthorized) issue while trying to login. Didn't have that in dev. I'll have to investigate!

Thanks!

**Comment by kkmehta-sudo** [comment]
@rafalkukla Did you resolve this? I'm facing the same problem

**Comment by rafalkukla** [comment]
@kkmehta-sudo nope, even with domain over SSL I have the same issue. Dev env works fine, but it doesn't in prod.

**Comment by kkmehta-sudo** [comment]
@rafalkukla is your domain in any of the public suffixes? apparently your domain should not be in any of them plus your storefront and backend have to be in the same domain.

Checkout [this](https://github.com/medusajs/medusa/issues/2314#issuecomment-1422429232) link. See if you pass all in the checklist

**Comment by rafalkukla** [comment]
If you use your own domain, it doesn't apply to you. I only tried on my own subdomain e.g. store.domain.com

**Comment by kkmehta-sudo** [comment]
@rafalkukla one more thing, if your redis database requires SSL, make sure you do "rediss://" instead of just "redis://"

**Comment by rafalkukla** [comment]
Thanks @kkmehta-sudo  my redis was installed on localhost so I think redis:// was okay is it. Saying "was" as I moved away from testing Medusa, as I could't get it to work on production after deploying. May give another go in the next couple of weeks / months again.

**Comment by kkmehta-sudo** [comment]
@rafalkukla oh okay!

**Comment by IgorKhomenko** [comment]
What I found is that `npm run build` does not always produce `.medusa` dir. Any ideas why?

**Comment by IgorKhomenko** [comment]
Answering my own question ^^^:

In my case, the output goes to `dist` instead of `.medusa/server`

The reason of this is that I have `tsconfig.json` file in my repo where I have `  "outDir": "./dist",`, and in medusa code there is this line `const distFolder = tsConfig.options.outDir ?? ".medusa/server"`
which does make sense in the end

**Comment by difrisul-dev1** [comment]
> Thanks [@kkmehta-sudo](https://github.com/kkmehta-sudo) my redis was installed on localhost so I think redis:// was okay is it. Saying "was" as I moved away from testing Medusa, as I could't get it to work on production after deploying. May give another go in the next couple of weeks / months again.

Medusa needs HTTPS for testing in prod.

Here is a guide to setup caddy to do that (provided by deepseek).

```md

### Step 1: Install caddy

sudo apt install caddy # or whatever your package manager is

### Step 2: Set Up Local HTTPS Domain

sudo vim /etc/hosts

127.0.0.1 medusa.local # add this line

### Step 3: Configure Caddyfile /etc/caddy/Caddyfile):

medusa.local {
  reverse_proxy localhost:9000  # Forward to Medusa's default port (adjust if needed)
  tls internal                  # Auto-generate local HTTPS cert
}

### Step 4: Run

NODE_ENV=production medusa start
sudo caddy run --config etc/caddy/Caddyfile

### Step 5: Try it

connect to https://medusa.local/app/login

```

**Comment by farscape-io** [comment]
For version 2.8*, where admin is installed as a bundle and not externally.
Issue
At yarn start, the server fails to start, citing the error "couldn't find index.html in admin build directory." This will cause the server to crash. If you are doing it inside Docker with autostart, the server will keep booting and crashing.

Solution
Medusa treats both internal and external admin as a plugin, and so relevant declarations, env, medusa-config.ts and medusa-config.js (yep, the admin build can't read ts, so you also have to create a medusa-config.js)

The Medusa system builds at XYZ/.medusa/admin/build/, and when running the server, it somehow looks for admin/index.html at XYZ/public/admin/. This creates the irritating error and server crashes. The setup works fine if you are on the external admin app and not within.

So, manually copy the files after every build, or create a script with the below.

cp -r XYZ/.medusa/admin/build/* XYZ/public/admin/

look at xyz/node_modules/@medusajs/medusa/dist/loaders/admin.js ; it calls for admin_relative_output_dir. But when you set this output directory in medusa-config.ts, it gets ignored.
```
const adminOptions = {
disable: false,
sources,
plugins: pluginAdminPaths,
...admin,
outDir: path_1.default.join(rootDirectory, utils_1.ADMIN_RELATIVE_OUTPUT_DIR),
};
if (adminOptions?.disable) {
return app;

   -----------------

**the declaration for Admin relative output dir is coming from  "XYZ/node_modules/@medusajs/medusa/nd/node_modules/@medusajs/medusa/"  which defines the directory as "./public/admin"**

-------------------


export declare const ADMIN_RELATIVE_OUTPUT_DIR = "./public/admin";
XYZ/node_modules/@medusajs/medusa/dist/utils/admin-consts.js:exports.ADMIN_ONLY_OUTPUT_DIR = exports.ADMIN_RELATIVE_OUTPUT_DIR = exports.ADMIN_SOURCE_DIR = void 0;

----------------

`XYZ/node_modules/@medusajs/medusa/dist/utils/admin-consts.js:exports.ADMIN_RELATIVE_OUTPUT_DIR = "./public/admin";`

--------------

**Comment by BetterLuke** [comment]
All bro see here:
1. [How build medusa follow right way](https://docs.medusajs.com/learn/build)
2. [Could not find index.html Error](https://docs.medusajs.com/resources/troubleshooting/medusa-admin/build-error)

**Comment by fluxtrading544** [comment]
## 1. Admin Dashboard "index.html Not Found" Error
**The Problem:** 
After deploying the backend, navigating to the Admin URL resulted in a blank page or an `index.html not found` error.
**The Cause:**
Medusa v2 compiles its Admin Dashboard into a hidden folder structure (`.medusa/server/public/admin`). In our `docker-compose.yml`, we had a `volumes` mapping that was overwriting the container's freshly built files with the empty folders from the host machine.
**The Solution:**
1. Removed the `volumes: - ./medusa-dentalanti:/app` mapping for the backend in `docker-compose.yml`. The container must rely on its own internal built files.
2. Updated the `Dockerfile` to automatically locate the built admin files and explicitly copy them to `/app/public/admin/` so the Medusa server can serve them correctly.
