### ISSUE TITLE
TypeError: cmd is not a function

### ISSUE THREAD

**Issue by jzatarain** [medusajs/medusa#1014]
I installed medusa, then medusa-admin, I ran them, and then I ran ` medusa user -e admin -p admin`, and I got this error:
`TypeError: cmd is not a function
    at C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\dist\create-cli.js:309:7
    at C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\dist\create-cli.js:108:24
    at Object.handler (C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\dist\create-cli.js:54:24)
    at Object.runCommand (C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.parse (C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\node_modules\yargs\build\lib\yargs.js:584:29)
    at module.exports (C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\dist\create-cli.js:392:6)
    at Object.<anonymous> (C:\Users\ejosu\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\dist\index.js:70:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)`

**Comment by kasperkristensen** [comment]
Hey, @jzatarain! first thing that I can think of is that you forgot to cd into the root folder of your Medusa server?

**Comment by jzatarain** [comment]
I am in that folder 
![image](https://user-images.githubusercontent.com/20093580/151263468-10fbd10c-0ba9-4479-a70e-4cc63e780d9d.png)

**Comment by adamfils** [comment]
Any update on this?

**Comment by kasperkristensen** [comment]
Hi again @jzatarain, from the naming of your folder I am assuming that you are cd'ed into your admin project and not the actual server, which should look like [this](https://github.com/medusajs/medusa-starter-default). Please make sure that you are currently in the server project when issuing the command. Also make sure that you have [medusa-cli](https://www.npmjs.com/package/@medusajs/medusa-cli) installed globally

**Comment by jzatarain** [comment]
Ok, so I ran the command inside /my-medusa-store, and it worked, but the command is listed after step 4 of medusa admin https://github.com/medusajs/admin ... Isn't that super confusing?

**Comment by olivermrbl** [comment]
Very good point @jzatarain! Will make sure to change it up to make it more obvious, that you need to be in your server directory for this command to work. 

Closing this issue down, as it seems to be solved :)
