### ISSUE TITLE
[Bug]: I can't run db:migrate command - Failed with error The server does not support SSL connections

### ISSUE THREAD

**Issue by jgatto1** [medusajs/medusa#10162]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "migrate": "npx medusa db:migrate"
  },
  "dependencies": {
    "@hello-pangea/dnd": "^16.6.0",
    "@medusajs/admin-sdk": "2.0.4",
    "@medusajs/cli": "2.0.4",
    "@medusajs/framework": "2.0.4",
    "@medusajs/icons": "^1.2.1",
    "@medusajs/js-sdk": "^2.0.4",
    "@medusajs/medusa": "2.0.4",
    "@medusajs/types": "^2.0.4",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@opentelemetry/instrumentation": "^0.55.0",
    "@opentelemetry/instrumentation-pg": "^0.47.1",
    "@opentelemetry/resources": "^1.28.0",
    "@opentelemetry/sdk-node": "^0.55.0",
    "@opentelemetry/sdk-trace-node": "^1.28.0",
    "@sentry/node": "^8.38.0",
    "@sentry/opentelemetry-node": "^7.114.0",
    "@sentry/profiling-node": "^8.38.0",
    "@tanstack/react-table": "^8.17.3",
    "awilix": "^8.0.1",
    "axios": "^1.7.2",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "ioredis": "^5.4.1",
    "jose": "^5.9.6",
    "jwt-decode": "^4.0.0",
    "moment": "^2.30.1",
    "pg": "^8.13.0",
    "prism-react-renderer": "^2.0.4",
    "quill": "^2.0.2",
    "react-hook-form": "^7.52.0",
    "react-hot-toast": "^2.4.1",
    "react-quilljs": "^2.0.3",
    "react-select": "^5.8.1",
    "tailwind-merge": "^2.4.0",
    "tus-js-client": "^4.1.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/test-utils": "2.0.4",
    "@mikro-orm/cli": "5.9.7",
    "@stdlib/number-float64-base-normalize": "0.0.8",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/express": "^4.17.13",
    "@types/jest": "^29.5.13",
    "@types/mime": "1.3.5",
    "@types/node": "^20.0.0",
    "@types/quill": "^2.0.14",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "jest": {
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.spec.json"
      }
    },
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "<rootDir>/node_modules/"
    ],
    "rootDir": "src",
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|js)$",
    "transform": {
      ".ts": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node"
  },
  "resolutions": {
    "glob": "^7.1.6"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.17.0

### Database and its version

PostgreSQL 13.16

### Operating system name and version

MacOS 14.0 (23A344)

### What happended?

Modules can't connect to the db after running `npx medusa db:migrate`

```
info:    Syncing links...
error:   The server does not support SSL connections
Error: The server does not support SSL connections
```

Tried with `sslmode=disable` and `ssl_mode=disable`. I think the `DATABASE_URL` is not being read for some modules like fulfillment, file, auth and others. I'm using the proper url because `npx medusa develop` works fine! 

### Expected behavior

Should not throw errors and migrate the db.

### Actual behavior

Throws multiple errors:
```
info:    MODULE: auth
error:   Failed with error The server does not support SSL connections
error:   The server does not support SSL connections
Error: The server does not support SSL connections

info:    MODULE: order
error:   Failed with error The server does not support SSL connections
error:   The server does not support SSL connections
Error: The server does not support SSL connections

... other modules
```

### Link to reproduction repo

not apply

**Comment by AlexAntonides** [comment]
I'm experiencing the same. 
It used to work fine, locally, but now my migrations are failing.

**medusa-config.js**
```js
module.exports = defineConfig({
   projectConfig: {
        [...],
        databaseUrl: `postgres://username:password@host:port/database?ssl_mode=prefer`,
        databaseDriverOptions: {
              ssl: {
                    rejectUnauthorized: false
              }
        }
        [...],
   }
})
```

**Error**
```
2024-11-19T14:57:46.964027109Z {"level":"info","message":"MODULE: cache","timestamp":"2024-11-19 14:57:46"}
2024-11-19T14:57:47.006536927Z {"level":"error","message":"Failed with error node is running secure mode, SSL connection required","timestamp":"2024-11-19 14:57:47"}
{"level":"error","message":"node is running secure mode, SSL connection required","stack":[{"columnNumber":69,"fileName":"/app/node_modules/pg-protocol/src/parser.ts","functionName":"Parser.parseErrorMessage","lineNumber":368,"methodName":"parseErrorMessage","native":false,"typeName":"Parser"},{"columnNumber":21,"fileName":"/app/node_modules/pg-protocol/src/parser.ts","functionName":"Parser.handlePacket","lineNumber":187,"methodName":"handlePacket","native":false,"typeName":"Parser"},{"columnNumber":30,"fileName":"/app/node_modules/pg-protocol/src/parser.ts","functionName":"Parser.parse","lineNumber":102,"methodName":"parse","native":false,"typeName":"Parser"},{"columnNumber":48,"fileName":"/app/node_modules/pg-protocol/src/index.ts","functionName":null,"lineNumber":7,"methodName":null,"native":false,"typeName":"Socket"},{"columnNumber":28,"fileName":"node:events","functionName":"Socket.emit","lineNumber":519,"methodName":"emit","native":false,"typeName":"Socket"},{"columnNumber":12,"fileName":"node:domain","functionName":"Socket.emit","lineNumber":488,"methodName":"emit","native":false,"typeName":"Socket"},{"columnNumber":12,"fileName":"node:internal/streams/readable","functionName":"addChunk","lineNumber":559,"methodName":null,"native":false,"typeName":null},{"columnNumber":3,"fileName":"node:internal/streams/readable","functionName":"readableAddChunkPushByteMode","lineNumber":510,"methodName":null,"native":false,"typeName":null},{"columnNumber":5,"fileName":"node:internal/streams/readable","functionName":"Socket.Readable.push","lineNumber":390,"methodName":"push","native":false,"typeName":"Socket.Readable"},{"columnNumber":23,"fileName":"node:internal/stream_base_commons","functionName":"TCP.onStreamRead","lineNumber":191,"methodName":"onStreamRead","native":false,"typeName":"TCP"}],"timestamp":"2024-11-19 14:57:47"}
2024-11-19T14:57:47.013689901Z 
2024-11-19T14:57:47.013728800Z 
2024-11-19T14:57:47.014067133Z {"level":"info","message":"MODULE: event_bus","timestamp":"2024-11-19 
14:57:47"}
2024-11-19T14:57:47.049732798Z {"level":"error","message":"Failed with error node is running secure mode, SSL connection required","timestamp":"2024-11-19 14:57:47"}
2024-11-19T14:57:47.050046805Z {"level":"error","message":"node is running secure mode, SSL connection required","stack":[{"columnNumber":69,"fileName":"/app/node_modules/pg-protocol/src/parser.ts","functionName":"Parser.parseErrorMessage","lineNumber":368,"methodName":"parseErrorMessage","native":false,"typeName":"Parser"},{"columnNumber":21,"fileName":"/app/node_modules/pg-protocol/src/parser.ts","functionName":"Parser.handlePacket","lineNumber":187,"methodName":"handlePacket","native":false,"typeName":"Parser"},{"columnNumber":30,"fileName":"/app/node_modules/pg-protocol/src/parser.ts","functionName":"Parser.parse","lineNumber":102,"methodName":"parse","native":false,"typeName":"Parser"},{"columnNumber":48,"fileName":"/app/node_modules/pg-protocol/src/index.ts","functionName":null,"lineNumber":7,"methodName":null,"native":false,"typeName":"Socket"},{"columnNumber":28,"fileName":"node:events","functionName":"Socket.emit","lineNumber":519,"methodName":"emit","native":false,"typeName":"Socket"},{"columnNumber":12,"fileName":"node:domain","functionName":"Socket.emit","lineNumber":488,"methodName":"emit","native":false,"typeName":"Socket"},{"columnNumber":12,"fileName":"node:internal/streams/readable","functionName":"addChunk","lineNumber":559,"methodName":null,"native":false,"typeName":null},{"columnNumber":3,"fileName":"node:internal/streams/readable","functionName":"readableAddChunkPushByteMode","lineNumber":510,"methodName":null,"native":false,"typeName":null},{"columnNumber":5,"fileName":"node:internal/streams/readable","functionName":"Socket.Readable.push","lineNumber":390,"methodName":"push","native":false,"typeName":"Socket.Readable"},{"columnNumber":23,"fileName":"node:internal/stream_base_commons","functionName":"TCP.onStreamRead","lineNumber":191,"methodName":"onStreamRead","native":false,"typeName":"TCP"}],"timestamp":"2024-11-19
 14:57:47"}
2024-11-19T14:57:47.051760786Z 
```

**Comment by riqwan** [comment]
@AlexAntonides can you try this instead:

```
databaseDriverOptions: {
  connection: {
    ssl: {
      rejectUnauthorized: false,
    },
  },
},
```

**Comment by riqwan** [comment]
@jgatto1 - can you share your medusa-config and your DATABASE_URL shape?

**Comment by jgatto1** [comment]
> @jgatto1 - can you share your medusa-config and your DATABASE_URL shape?

@riqwan Here you go:
```
DATABASE_URL=postgres://user:pass@localhost:5432/medusa-my-medusa-store?sslmode=disable
DATABASE_URL=postgres://user:pass@localhost:5432/medusa-my-medusa-store?ssl_mode=disable
```

I tried with both.

Thanks!

**Comment by riqwan** [comment]
THanks @jgatto1 , also need the `medusa-config.ts/js` file

**Comment by jgatto1** [comment]
> THanks @jgatto1 , also need the `medusa-config.ts/js` file

@riqwan sure:
```
import { ProjectConfigOptions } from "@medusajs/framework";
import { loadEnv, defineConfig } from '@medusajs/framework/utils'

loadEnv(process.env.NODE_ENV, process.cwd());

// CORS when consuming Medusa from admin
const ADMIN_CORS = process.env.ADMIN_CORS;
// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS;
const DATABASE_URL = process.env.DATABASE_URL;
const REDIS_URL = process.env.REDIS_URL;

const projectConfig: ProjectConfigOptions = {
  databaseUrl: DATABASE_URL,
  databaseDriverOptions: {
    connection: {
      ssl: {
        rejectUnauthorized: false
      }
    }
  },
  http: {
    adminCors: ADMIN_CORS,
    storeCors: STORE_CORS,
    authCors: ADMIN_CORS,
    jwtSecret: process.env.JWT_SECRET,
    cookieSecret: process.env.COOKIE_SECRET,
    authMethodsPerActor: {
      customer: ["logto", 'emailpass'],
      user: ['logto', 'emailpass']
    }
  },
  redisUrl: REDIS_URL,
};

module.exports = defineConfig({
  projectConfig,
  modules: [
    // Manual fulfillment is registered by default.
    // Manual payment is registered by default.
    // Local File Module Provider is registered by default.
    // TODO: Missing: @weframetechsolutions/medusa-order-affiliate
    {
      resolve: "@medusajs/medusa/event-bus-redis",
      options: {
        redisUrl: REDIS_URL,
      },
    },
    {
      resolve: "./modules/lms",
    },
    {
      resolve: "@medusajs/auth",
      options: {
        providers: [
          {
            resolve: "@medusajs/auth-emailpass",
            id: "emailpass",
            options: {
              // provider options...
            },
          },
          {
            resolve: "./src/modules/auth-logto",
            id: "logto",
            options: {
              endpoint: process.env.LOGTO_ENDPOINT,
              clientId: process.env.LOGTO_CLIENT_ID,
              clientSecret: process.env.LOGTO_CLIENT_SECRET,
              callbackUrl: process.env.LOGTO_CALLBACK_URL,
              postLogoutUrl: process.env.LOGTO_POSTLOGOUT_URL,
              resource: process.env.LOGTO_RESOURCE,
              machineClientId: process.env.LOGTO_MACHINE_CLIENT_ID,
              machineClientSecret: process.env.LOGTO_MACHINE_CLIENT_SECRET,
              machineResource: process.env.LOGTO_MACHINE_RESOURCE,
            },
          },
        ],
      },
    },
    {
      resolve: "@medusajs/user",
      options: {
        jwt_secret: process.env.JWT_SECRET,
      },
    }
  ],
});

```

**Comment by riqwan** [comment]
Thanks @jgatto1 , can you try removing `databaseDriverOptions` entirely and try again?

**Comment by jgatto1** [comment]
@riqwan it works thanks!

**Comment by riqwan** [comment]
nice! great to hear! 🎉

**Comment by iluozhiqiang** [comment]
I have encountered this problem too, and it still doesn't work after following your method. This is version 2.1.1.

error:   The server does not support SSL connections
Error: The server does not support SSL connections
    at Socket.<anonymous> (/app/medusa/.medusa/server/node_modules/@mikro-orm/postgresql/node_modules/pg/lib/connection.js:77:37)
    at Object.onceWrapper (node:events:639:26)
    at Socket.emit (node:events:524:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Socket.Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)


**medusa-config.ts**
```code
databaseUrl: process.env.DATABASE_URL,
databaseDriverOptions: {
    connection: {
      ssl: {
        rejectUnauthorized: false
      }
    }
  }
```
**.env** 
```code
DATABASE_URL=postgres://xxx:xxx@xxx:5432/medusa?sslmode=disable
```

**Comment by riqwan** [comment]
@iluozhiqiang delete the databaseDriverOptions entirely and try again

**Comment by arnabtarwani** [comment]
@riqwan  I removed the databaseDriverOptions entirely and it still doesn't work - I am on Node v23.4.0
and my DATABASE_URL=postgres://user:somePassword@localhost:5432/medusa-store?sslmode=disable

here's the error stack 

```
info:    MODULE: notification
error:   Failed with error The server does not support SSL connections
error:   The server does not support SSL connections
Error: The server does not support SSL connections
    at Socket.<anonymous> (/Users/arnabtarwani/Documents/projects/development/shops/store/node_modules/pg/lib/connection.js:76:37)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
------------------------------------------------------------------------------------------------------------------------------

info:    MODULE: notification
error:   Failed with error The server does not support SSL connections
error:   The server does not support SSL connections
Error: The server does not support SSL connections
    at Socket.<anonymous> (/Users/arnabtarwani/Documents/projects/development/shops/store/node_modules/pg/lib/connection.js:76:37)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
------------------------------------------------------------------------------------------------------------------------------
info:    Migrations completed
------------------------------------------------------------------------------------------------------------------------------
info:    Syncing links...
error:   The server does not support SSL connections
Error: The server does not support SSL connections
    at Socket.<anonymous> (/Users/arnabtarwani/Documents/projects/development/shops/store/node_modules/pg/lib/connection.js:76:37)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
 ```

@riqwan tagging again just in case you didn't see this.

**Comment by riqwan** [comment]
@arnabtarwani whats the error?

**Comment by AlexAntonides** [comment]
@arnabtarwani the parameter should be `ssl_mode` and not `sslmode`.
