### ISSUE TITLE
[Bug]: TypeError: cmd is not a function

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa#10174]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "predeploy": "medusa db:migrate",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20

### Database and its version

16

### Operating system name and version

22.04

### What happended?

App is deployed successfully but the server doest start says:

yarn run v1.22.22
$ medusa start
medusa start

Start development server.

Options:
  --verbose                Turn on verbose output  [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output  [boolean] [default: false]
  --json                   Turn on the JSON logger  [boolean] [default: false]
  -H, --host               Set host. Defaults to localhost  [string] [default: "localhost"]
  -p, --port               Set port. Defaults to 9000 (set by env.PORT) (otherwise defaults 9000)  [string] [default: "9000"]
  -h, --help               Show help  [boolean]
  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project  [boolean]
TypeError: cmd is not a function
    at /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:198:13
    at /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:48:30
    at Object.handler (/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:16:21)
    at Object.runCommand (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:584:29)
    at exports.default (/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:353:10)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/index.js:38:26)
    at Module._compile (node:internal/modules/cjs/loader:1550:14)
    at Object..js (node:internal/modules/cjs/loader:1702:10)
Done in 1.91s.

### Expected behavior

The server must start

### Actual behavior

yarn run v1.22.22
$ medusa start
medusa start

Start development server.

Options:
  --verbose                Turn on verbose output  [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output  [boolean] [default: false]
  --json                   Turn on the JSON logger  [boolean] [default: false]
  -H, --host               Set host. Defaults to localhost  [string] [default: "localhost"]
  -p, --port               Set port. Defaults to 9000 (set by env.PORT) (otherwise defaults 9000)  [string] [default: "9000"]
  -h, --help               Show help  [boolean]
  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project  [boolean]
TypeError: cmd is not a function
    at /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:198:13
    at /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:48:30
    at Object.handler (/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:16:21)
    at Object.runCommand (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:584:29)
    at exports.default (/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:353:10)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/index.js:38:26)
    at Module._compile (node:internal/modules/cjs/loader:1550:14)
    at Object..js (node:internal/modules/cjs/loader:1702:10)
Done in 1.91s.

### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default.git

**Comment by chillpilllike** [comment]
Dockerfile:


# Use a stable Node version
FROM node:latest

# Set working directory
WORKDIR /app

COPY . .

RUN yarn global add @medusajs/medusa-cli

RUN yarn install

RUN yarn build

WORKDIR /app/.medusa/server

CMD yarn run predeploy && yarn run start

**Comment by chillpilllike** [comment]
dockerfile was incorrect.
