### ISSUE TITLE
Error Running First Migration

### ISSUE THREAD

**Issue by webface** [medusajs/medusa#1030]
I tried running medusa api with a newly created postgres db. I expect the db tables to be created but I get 2 errors.

```
QueryFailedError: relation "staged_job" does not exist
    at QueryFailedError.TypeORMError [as constructor]
    
    QueryFailedError: relation "country" does not exist
    at QueryFailedError.TypeORMError [as constructor]```
  
This did not happen the first time i set up medusa. I am using the latest version

**Comment by webface** [comment]
`Initializing defaults(node:66026) UnhandledPromiseRejectionWarning: QueryFailedError: relation "staged_job" does not exist
    at QueryFailedError.TypeORMError [as constructor] (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:250:31)
    at step (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:124:57)
    at rejected (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could not connect to strapi. Please make sure strapi is running.

(node:66026) UnhandledPromiseRejectionWarning: QueryFailedError: relation "country" does not exist
    at QueryFailedError.TypeORMError [as constructor] (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:250:31)
    at step (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:124:57)
    at rejected (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:66026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
⠦ Initializing defaults`

**Comment by srindom** [comment]
Did you run the migrations before starting your server? 

```
$ medusa migrations run
```

**Comment by webface** [comment]
Thanks @srindom

**Comment by zubairfayyaz** [comment]
unfortunately, my medusa cli is not working you have any other idea?
