### ISSUE TITLE
[Bug]: Admin UI allows an Order to be cancelled multiple times

### ISSUE THREAD

**Issue by roberttolton** [medusajs/medusa#10332]
### Package.json file

```JSON
{
    "name": "medusa-starter-default",
    "version": "0.0.1",
    "description": "A starter for Medusa projects.",
    "author": "Medusa (https://medusajs.com)",
    "license": "MIT",
    "keywords": [
        "sqlite",
        "postgres",
        "typescript",
        "ecommerce",
        "headless",
        "medusa"
    ],
    "scripts": {
        "build": "medusa build",
        "seed": "medusa exec ./src/scripts/seed.ts",
        "start": "medusa start",
        "dev": "medusa develop",
        "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
        "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
        "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
    },
    "dependencies": {
        "@medusajs/admin-sdk": "^2.0.7",
        "@medusajs/cli": "^2.0.7",
        "@medusajs/framework": "^2.0.7",
        "@medusajs/medusa": "^2.0.7",
        "@mikro-orm/core": "5.9.7",
        "@mikro-orm/knex": "5.9.7",
        "@mikro-orm/migrations": "5.9.7",
        "@mikro-orm/postgresql": "5.9.7",
        "awilix": "^8.0.1",
        "pg": "^8.13.0"
    },
    "devDependencies": {
        "@medusajs/test-utils": "^2.0.7",
        "@mikro-orm/cli": "5.9.7",
        "@swc/core": "1.5.7",
        "@swc/jest": "^0.2.36",
        "@types/jest": "^29.5.13",
        "@types/node": "^20.0.0",
        "@types/react": "^18.3.2",
        "@types/react-dom": "^18.2.25",
        "jest": "^29.7.0",
        "prop-types": "^15.8.1",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "ts-node": "^10.9.2",
        "typescript": "^5.6.2",
        "vite": "^5.2.11"
    },
    "engines": {
        "node": ">=20"
    },
    "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

v20.18.0

### Database and its version

PostgreSQL 16

### Operating system name and version

macOS 15.1.1

### Browser name

Google Chrome

### What happended?

The Admin UI does not correctly show via some top-level display that the Order has been cancelled.

The button for cancelling an Order is still active and clickable.

![localhost8502appordersorder_01JDR5DXS1C9Y7J4M87Y27CYCZ 2024-11-28 at 12 02 46 pm](https://github.com/user-attachments/assets/aa824675-7721-46ee-a07c-b4b7f2342e80)

### Expected behavior

The Order page should display prominently the correct current status of the Order, in this case it should be 'Cancelled'.

The cancel button should not be clickable.

### Actual behavior

You can still click the cancel button and see this error in the logs:

```
error:   Order with id order_01JDR5DXS1C9Y7J4M87Y27CYCZ has been canceled.
{
  message: 'Order with id order_01JDR5DXS1C9Y7J4M87Y27CYCZ has been canceled.',
  name: 'Error',
  stack: 'Error: Order with id order_01JDR5DXS1C9Y7J4M87Y27CYCZ has been canceled.\n' +
    '    at throwIfOrderIsCancelled (/redacted/api-medusa/node_modules/@medusajs/core-flows/src/order/utils/order-validation.ts:17:11)\n' +
    '    at Object.<anonymous> (/redacted/api-medusa/node_modules/@medusajs/core-flows/src/order/workflows/cancel-order.ts:43:28)\n' +
    '    at Object.invoke (/redacted/api-medusa/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:72:67)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DistributedTransaction.handler (/redacted/api-medusa/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (/redacted/api-medusa/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:827:20)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '    at async promiseAll (/redacted/api-medusa/node_modules/@medusajs/utils/src/common/promise-all.ts:23:18)\n' +
    '    at async TransactionOrchestrator.executeNext (/redacted/api-medusa/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:965:7)\n' +
    '    at async executeNext (/redacted/api-medusa/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:1013:14)\n' +
    '⮑ sat /redacted/api-medusa/node_modules/@medusajs/core-flows/dist/order/workflows/cancel-order.js: [cancel-order -> cancel-validate-order (invoke)]',
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2024-11-28T03:00:24.136Z
}
```

### Link to reproduction repo

n/a

**Comment by fPolic** [comment]
Thanks for the report @roberttolton, we will fix this.

**Comment by HarleySalas** [comment]
also here, wondering when this will get fixed... there should be a status update as well, which says "canceled" in the ui, instead of "not fulfilled"

statuses like "awaiting fulfillment" should go away as well. it's a confusing experience to people fulfilling orders.
