### ISSUE TITLE
Error when trying to use Meilisearch Plugin in Medusa Config

### ISSUE THREAD

**Issue by shivaylamba** [medusajs/medusa#1033]
I am trying to integrate Meilisearch in Medusa config but run into an error that is shared below. Here's how my config looks like : 
```
  {
    resolve: "medusa-plugin-meilisearch",
    options: {
      // config object passed when creating an instance of the MeiliSearch client
      config: {
        host: "http://localhost:7700",
        apiKey: "masterKey",
      },
      settings: {
        // index name
        product: {
          // MeiliSearch's setting options to be set on a particular index
          searchableAttributes: ["title", "description"],
          displayedAttributes: ["title", "description"],
        },
      },
    },
  },
];
```

This is the error : 
```
⠋ Initializing pluginserror:   Services must inherit from BaseService, please check /Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/medusa-plugin-meilisearch/services/meilisearch.js
Error: Services must inherit from BaseService, please check /Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/medusa-plugin-meilisearch/services/meilisearch.js
    at /Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:286:51
    at step (/Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (/Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
    at /Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:4:12)
    at /Users/shivaylamba/Desktop/ecommerce/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:274:87
    at Array.map (<anonymous>)
```

**Comment by olivermrbl** [comment]
Thanks for reporting it @shivaylamba !

I've just tried to reproduce but can't seem to make it happen. 

I did the following:
1. `medusa new test-store`
2. `yarn add medusa-plugin-meilisearch`
3. Added your config file to `medusa-config.js`
4. `yarn start`

Are you able to reproduce the error yourself? Would make it a lot easier for me to investigate :)

**Comment by shivaylamba** [comment]
Thanks @olivermrbl based on our discussion, the issue is resolved by updating the packages to latest for both medusa and medusa-plugin-meilisearch
