### ISSUE TITLE
[Bug]: Medusa Admin Login Issue

### ISSUE THREAD

**Issue by ABAGDevelopment** [medusajs/medusa#10365]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v21

### Database and its version

Postgres 16.2

### Operating system name and version

Windows 11

### Browser name

Chrome

### What happended?

Admin User invite and login functionality not working and causing errors

Below is the traceCreating a new user : - Below are the steps
 
•	Invite a user and enter email address
•	Copy the invite link open in the browser and enter details and click create account, below message appears
 
 
Below is the response from medusa API
 
http:    POST /auth/user/emailpass/register ← [http://localhost:9000/app/invite?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imludml0ZV8wMUpEUk1XM0sxQkJYRks5QlY0TThOWjBSNSIsImVtYWlsIjoiYWRtaW5AeW9wbWFpbC5jb20iLCJpYXQiOjE3MzI3NzI3NjEsImV4cCI6MTgxOTE3Mjc2MSwianRpIjoiZjUxMjZhMWItNGJlZS00ZTNlLWI2NjQtZGIwZGNlNWI2ZTIxIn0.yrq-qWHwZ1Etwp6UusBNGuJwYuUTLKhBSZCWYvxKpVY](https://urldefense.com/v3/__http:/localhost:9000/app/invite?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imludml0ZV8wMUpEUk1XM0sxQkJYRks5QlY0TThOWjBSNSIsImVtYWlsIjoiYWRtaW5AeW9wbWFpbC5jb20iLCJpYXQiOjE3MzI3NzI3NjEsImV4cCI6MTgxOTE3Mjc2MSwianRpIjoiZjUxMjZhMWItNGJlZS00ZTNlLWI2NjQtZGIwZGNlNWI2ZTIxIn0.yrq-qWHwZ1Etwp6UusBNGuJwYuUTLKhBSZCWYvxKpVY__;!!Ga2p65tv!I7o1kg14oKlWcu21-QIUP2eAHuVaB-mJ2rse9JUvyVZTC_CqGsNL4Kj0nALW9Dbj-lS8MdtJ0DFmr_o$) (200) - 103.347 ms
error:   The user is already authenticated and cannot accept an invite.
MedusaError: The user is already authenticated and cannot accept an invite.
    at POST (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\@medusajs\medusa\src\api\admin\invites\accept\route.ts:15:11)
    at C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\@medusajs\utils\src\common\wrap-handler.ts:17:20
    at Layer.handle [as handle_request] (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\layer.js:95:5)
    at C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\index.js:280:10)
    at next (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\express\lib\router\route.js:141:14) {
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2024-11-28T06:01:52.872Z
}
 
The user is already authenticated and cannot accept an invite. :  - User table does not have any entry for the mentioned user
 
 
 
So above message returned from the API is misleading
 
 
Attempt 2 with the invite link
 
 
 
http:    GET /app/index.css ← [http://localhost:9000/app/entry.tsx](https://urldefense.com/v3/__http:/localhost:9000/app/entry.tsx__;!!Ga2p65tv!I7o1kg14oKlWcu21-QIUP2eAHuVaB-mJ2rse9JUvyVZTC_CqGsNL4Kj0nALW9Dbj-lS8MdtJyrTEaeg$) (200) - 2.296 ms
error:   Identity with email already exists
MedusaError: Identity with email already exists
    at POST (C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\@medusajs\medusa\src\api\auth\[actor_type]\[auth_provider]\register\route.ts:52:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Projects\Medusa\basicsetup\my-medusa-store\node_modules\@medusajs\utils\src\common\wrap-handler.ts:17:14 {
  __isMedusaError: true,
  type: 'unauthorized',
  code: undefined,
  date: 2024-11-28T06:13:24.488Z
}
 
 
New entry in auth_identity table with app_metadata as null
 
 
Now regardless of number of attempts to create admin user, Application will keep throwing Server Error.
![Trace](https://github.com/user-attachments/assets/544f61a6-c677-449c-8587-b51faa52b2c4)

### Expected behavior

User Should be able to seemlessly login

### Actual behavior

Admin User invite and login functionality not working and causing errors

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by olivermrbl** [comment]
@ABAGDevelopment, any chance you can provide the exact steps to reproduce the error?

The error you are seeing on the first attempt to accept an invite is thrown in case the HTTP request already carries authentication, potentially from a separate, earlier session. I'd like to understand how you managed to reach this state, as it should generally not be possible in Medusa Admin.

**Comment by ABAGDevelopment** [comment]
@olivermrbl : - Below are the steps.
•	Invite a user and enter email address
•	Copy the invite link open in the browser and enter details and click create account, " UI Message the invite is invalid or expired", Api response in mentioned in the description above

**Comment by olivermrbl** [comment]
@ABAGDevelopment, can I get you to ensure you are signed out of the dashboard with your other user (the one that invited the new user)? Otherwise, the authentication context from that session will be part of the HTTP request to accept the token.

**Comment by olivermrbl** [comment]
Closing this issue, as we are unable to reproduce it. Feel free to re-open, if the described solution doesn't solve it.

**Comment by ABAGDevelopment** [comment]
@olivermrbl :-  Issue is not always reproducible, It is intermittent, We initally faced it after creating 3 users, second time it occurred on second user creation, Hope this helps

**Comment by Lacapsule66** [comment]
I have exactly the same problem, 2 users ok, the 3rd not

**Comment by ABAGDevelopment** [comment]
@Lacapsule66 : -  In each installation, we faced the same issue, It seems some intermitted bug is present in medusa code base @olivermrbl

**Comment by ABAGDevelopment** [comment]
@olivermrbl :- Can you please open the bug and trace the intermittent behavior, It will require few user creations to replicate

**Comment by olivermrbl** [comment]
Sure, please provide exact reproducible steps, and we will look into it.

**Comment by edenjiga** [comment]
I have the same issue, diging a little bit in the code I can see that the error is because we `sdk.auth.register` and never call  `sdk.store.customer.create`. so if we try to generate a token again calling `sdk.auth.register` we get the error :  Identity with email already exists.
Another bug related with this, it is that if we succesfully register and create the user, and then remove the user from the admin dashboard. the user is never remove from the `provider_identity`, so if we try to register the user again, we will get the same Identity with email already exists error.  
hope this help

**Comment by drewes** [comment]
I'm not sure if this helps anyone. Was chasing my tail a bit with this one. Had the error and tried to run tests with cURL.

I had used the B2B starter template. With the latest changes to the `routeConfig` in API routes, I changed all lines with `fields: req.remoteQueryConfig.fields` to `fields: req.queryConfig.fields`.

This got the straight API calls working. Then still had the error when registered a new company in the template.

Followed @olivermrbl advice and opened the form in Chrome guest mode to ensure no authentication sessions are floating around.

That seemed to resolve the issue.

**Comment by pxue** [comment]
There's definitely a bug here.

https://github.com/medusajs/medusa/blob/develop/packages/modules/auth/src/services/auth-module.ts#L274
lists the authIdentities and only returns error if length is zero or more than one.

When an invitation is sent out, authIdentity already exists.
This doesn't happen every time.
![Image](https://github.com/user-attachments/assets/523a6a72-fccf-4b0c-957c-4fbc853b932c)

**Comment by ZeroSaaS** [comment]
I'm also experiencing this issue. Invited 3 users and all get the same error as reported above. Looking at the logs I can see the following: 
MedusaError: Identity with email already exists

    at POST (/app/.medusa/server/node_modules/.pnpm/@medusajs+medusa@2.6.1_zb6kin3yfdtqy3occrxk744fpu/node_modules/@medusajs/medusa/src/api/auth/[actor_type]/[auth_provider]/register/route.ts:52:9)

    at processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async POST (/app/.medusa/server/node_modules/.pnpm/@medusajs+framework@2.6.1_@medusajs+cli@2.6.1_@mikro-orm+core@6.4.3_@mikro-orm+knex@6.4.3_@mi_wo5dyfqlzx6g2ns4njz6nysbdy/node_modules/@medusajs/framework/src/http/utils/wrap-handler.ts:27:14) {

  __isMedusaError: true,

  type: 'unauthorized',

  code: undefined,

  date: 2025-05-18T22:07:01.973Z

}

Identity with email already exists

 

2025-05-18 22:07:55.729 UTC [73] LOG:  checkpoint starting: time

2025-05-18 22:07:56.960 UTC [73] LOG:  checkpoint complete: wrote 13 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.208 s, sync=0.009 s, total=1.232 s; sync files=13, longest=0.005 s, average=0.001 s; distance=17 kB, estimate=3209 kB; lsn=0/1F167A0, redo lsn=0/1F16768

**Comment by surfer-kim** [comment]
Leaving a record here for people having this issue.
1. Make sure your are on the latest "@medusajs/admin-sdk": "2.8.8", I believe 2.8.7 has the issue.
2. Make sure you clean the record in public.auth_identity and public.invite.
3. Retry again.

This resolved my case

**Comment by mu-ab** [comment]
> I have the same issue, diging a little bit in the code I can see that the error is because we `sdk.auth.register` and never call `sdk.store.customer.create`. so if we try to generate a token again calling `sdk.auth.register` we get the error : Identity with email already exists. Another bug related with this, it is that if we succesfully register and create the user, and then remove the user from the admin dashboard. the user is never remove from the `provider_identity`, so if we try to register the user again, we will get the same Identity with email already exists error. hope this help

Hello [edenjiga](https://github.com/edenjiga) I currently have a similar issue as this, I an trying to  implement auth on my nuxt 4 frontend using the sdk, Please could you guide me on how you had it resolved.

I have also looked into this part of the documentation (https://docs.medusajs.com/resources/commerce-modules/customer/customer-accounts)  and found it strange even though I didn't understand their fix.

If you use vue/nuxt, I would also love if you could walk me through your approach, I am new to vue/nuxt and my current approach feels hacky. 

Thank you in advance
