### ISSUE TITLE
[Bug]: New Workflow issue. TypeError: brands is not iterable

### ISSUE THREAD

**Issue by homosape** [medusajs/medusa#10421]
### Package.json file

```JSON
{
  "name": "qnari-commerce",
  "version": "0.0.1",
  "author": "Nari Solutions",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.0.7",
    "@medusajs/cli": "^2.0.7",
    "@medusajs/framework": "^2.0.7",
    "@medusajs/medusa": "^2.0.7",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0",
    "zod": "^3.22"
  },
  "devDependencies": {
    "@medusajs/test-utils": "^2.0.7",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```
```


### Node.js version

v22.11.0

### Database and its version

supabase

### Operating system name and version

macOS Sequoia 15.1.1

### Browser name

_No response_

### What happended?

I've created a fresh workflow according documentation but it throws an error when i run `medusa start`.

My workflow

  import { MARKETPLACE_MODULE } from "@/modules/marketplace";
  import MarketplaceModuleService from "@/modules/marketplace/service";
  import schemas from "@/schemas";
  import { Brand } from "@/types/brand";
  import {
    createWorkflow,
    WorkflowResponse,
    createStep,
    StepResponse,
  } from "@medusajs/framework/workflows-sdk";
  
  interface CreateBrandsWorkflowInput {
    brands: Brand[];
    vendor_ids: string[];
  }
  
  const createBrandsWorkflow = createWorkflow(
    "create-brands",
    ({ brands = [], vendor_ids = [] }: CreateBrandsWorkflowInput) => {
      const ids: { brand_id: string; vendor_id: string }[] = [];
  
      for (const brand of brands) {
        const randomNum = Math.floor(Math.random() * vendor_ids.length);
        const vendor_id = vendor_ids[randomNum];
  
        const result = createBrandStep({ brand, vendor_id });
        ids.push(result);
      }
  
      return new WorkflowResponse(ids);
    }
  );
  
  interface CreateBrandStepInput {
    brand: Brand;
    vendor_id: string;
  }
  
  const createBrandStep = createStep(
    "create-brand-step",
    async ({ brand, vendor_id }: CreateBrandStepInput, { container }) => {
      const marketplaceModule: MarketplaceModuleService =
        container.resolve(MARKETPLACE_MODULE);
  
      const data = schemas.brand.parse(brand);
      const result = await marketplaceModule.createBrands({ ...data, vendor_id });
  
      return new StepResponse({
        brand_id: result.id,
        vendor_id: result.vendor_id,
      });
    }
  );
  
  export default createBrandsWorkflow;


### Expected behavior

I expect it to start without any issue.

### Actual behavior

Throws an error

  error:   Error starting server
  error:   brands is not iterable
  TypeError: brands is not iterable
      at Object.<anonymous> (/Users/ika/Desktop/qnari-commerce/src/workflows/create-brands.ts:22:25)
      at createWorkflow (/Users/ika/Desktop/qnari-commerce/node_modules/@medusajs/workflows-sdk/src/utils/composer/create-workflow.ts:145:33)
      at Object.<anonymous> (/Users/ika/Desktop/qnari-commerce/src/workflows/create-brands.ts:17:44)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Module.m._compile (/Users/ika/Desktop/qnari-commerce/node_modules/ts-node/src/index.ts:1618:23)
      at node:internal/modules/cjs/loader:1689:10
      at Object.require.extensions.<computed> [as .ts] (/Users/ika/Desktop/qnari-commerce/node_modules/ts-node/src/index.ts:1621:12)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)

### Link to reproduction repo

n/a

**Comment by christiananese** [comment]
Hey @homosape,
`createWorkflow` creates an internal representation  to track and store its steps. Because of this you can't directly manipulate data.

You can use `transform`, to prepare the input data and pass it to the step

**Comment by homosape** [comment]
Hi @christiananese 
I've added transform but I still get the issue when I run `medusa develop`

```
import { MARKETPLACE_MODULE } from "@/modules/marketplace";
import MarketplaceModuleService from "@/modules/marketplace/service";
import schemas from "@/schemas";
import { Brand } from "@/types/brand";
import {
  createWorkflow,
  WorkflowResponse,
  createStep,
  StepResponse,
  transform,
} from "@medusajs/framework/workflows-sdk";

interface CreateBrandsWorkflowInput {
  brands: Brand[];
  vendor_ids: string[];
}

const createBrandsWorkflow = createWorkflow(
  "create-brands",
  (input: CreateBrandsWorkflowInput) => {
    const { brands, vendor_ids } = transform({ input }, (data) => ({
      brands: data.input.brands ?? [],
      vendor_ids: data.input.vendor_ids ?? [],
    }));
    console.log("brands", brands);

    const ids: { brand_id: string; vendor_id: string }[] = [];

    for (const brand of brands) {
      const randomNum = Math.floor(Math.random() * vendor_ids.length);
      const vendor_id = vendor_ids[randomNum];

      const result = createBrandStep({ brand, vendor_id });
      ids.push(result);
    }

    return new WorkflowResponse(ids);
  }
);
```

And here is the output I get
```
brands {
  __id: '01JE8XEZPH54XH82DD36KSA388',
  __type: 'Symbol(WorkflowStepTransformer)',
  __resolver: [AsyncFunction: returnFn]
}
error:   Error starting server
error:   brands is not iterable
TypeError: brands is not iterable
    at Object.<anonymous> (/Users/ika/Desktop/qnari-commerce/src/workflows/create-brands.ts:29:25)
    at createWorkflow (/Users/ika/Desktop/qnari-commerce/node_modules/@medusajs/workflows-sdk/src/utils/composer/create-workflow.ts:145:33)
    at Object.<anonymous> (/Users/ika/Desktop/qnari-commerce/src/workflows/create-brands.ts:18:44)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module.m._compile (/Users/ika/Desktop/qnari-commerce/node_modules/ts-node/src/index.ts:1618:23)
    at node:internal/modules/cjs/loader:1689:10
    at Object.require.extensions.<computed> [as .ts] (/Users/ika/Desktop/qnari-commerce/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
```

**Comment by christiananese** [comment]
Hey @homosape 

In the code you posted you are still trying to manipulate the code inside `createWorkflow`

```typescript
const createBrandsWorkflow = createWorkflow(
  "create-brands",
  (input: CreateBrandsWorkflowInput) => {
  // this works
    const { brands, vendor_ids } = transform({ input }, (data) => ({
      brands: data.input.brands ?? [],
      vendor_ids: data.input.vendor_ids ?? [],
    }));
    console.log("brands", brands);

// everything from here doesn't work
    const ids: { brand_id: string; vendor_id: string }[] = [];

    for (const brand of brands) {
      const randomNum = Math.floor(Math.random() * vendor_ids.length);
      const vendor_id = vendor_ids[randomNum];

      const result = createBrandStep({ brand, vendor_id });
      ids.push(result);
    }

    return new WorkflowResponse(ids);
  }
);
```

You should move the logic to the step.

```typescript
const createBrandsWorkflow = createWorkflow(
  "create-brands",
  (input: CreateBrandsWorkflowInput) => {
      const result = createBrandsStep(input);

    return new WorkflowResponse(ids);
  }
);

  
const createBrandStep = createStep(
    "create-brand-step",
    async ({ brand, vendor_id }: CreateBrandsWorkflowInput { container }) => {
      const marketplaceModule: MarketplaceModuleService =
        container.resolve(MARKETPLACE_MODULE);
      const ids: { brand_id: string; vendor_id: string }[] = [];
  
      for (const brand of brands) {
        // DO STUFF
      }
    }
  );

```

**Comment by homosape** [comment]
Ok it seems to work now

thanks for help @christiananese
