### ISSUE TITLE
[Bug]: Could not resolve dependency: peer react@">=16.8.0" from @hookform/error-message@2.0.1

### ISSUE THREAD

**Issue by sebastianbk** [medusajs/medusa#10443]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.11.0

### Database and its version

PostgreSQL 17.0

### Operating system name and version

macOS 15.1.1 (24B91)

### Browser name

Microsoft Edge

### What happended?

Hi. I ran your getting started guide and immediately ran into the following issue. I've attached my console output and `npm` log files below.

Am I doing something wrong?

```
> npx create-medusa-app@latest
Need to install the following packages:
create-medusa-app@2.1.0
Ok to proceed? (y) y

╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Medusa collects anonymous usage analytics                            ║
║   to help improve Medusa for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `medusa telemetry --disable`   ║
║                                                                        ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
? What's the name of your project? medusa-test
? Would you like to create the Next.js storefront? You can also create it later Yes
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
⠋ Installing Next.js Storefront...

   ┌──────────────────────────────── 💡 Medusa Tips ─────────────────────────────────┐
   │                                                                                 │
   │   You can listen to events to perform asynchronous actions using Subscribers.   │
   │                                                                                 │
   └─────────────────────────────────────────────────────────────────────────────────┘
An error occurred while installing Next.js storefront: Error: Command failed: npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: medusa-next@1.0.3
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">=16.8.0" from @hookform/error-message@2.0.1
npm error node_modules/@hookform/error-message
npm error   @hookform/error-message@"^2.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-debug-0.log
```

Contents of `/Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-debug-0.log`:

```
0 verbose cli /Users/sebastian/.nvm/versions/node/v22.11.0/bin/node /Users/sebastian/.nvm/versions/node/v22.11.0/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/sebastian/Projects/sebastianbk/medusa-tast/medusa-test-storefront/.npmrc
5 silly config load:file:/Users/sebastian/.npmrc
6 silly config load:file:/Users/sebastian/.nvm/versions/node/v22.11.0/etc/npmrc
7 verbose title npm install
8 verbose argv "install"
9 verbose logfile logs-max:10 dir:/Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-
10 verbose logfile /Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest @headlessui/react@^2.2.0
16 silly packumentCache full:https://registry.npmjs.org/@headlessui%2freact cache-miss
17 http fetch GET 200 https://registry.npmjs.org/@headlessui%2freact 186ms (cache miss)
18 silly packumentCache full:https://registry.npmjs.org/@headlessui%2freact set size:undefined disposed:false
19 silly fetch manifest react@19.0.0-rc-66855b96-20241106
20 silly packumentCache full:https://registry.npmjs.org/react cache-miss
21 http fetch GET 200 https://registry.npmjs.org/react 114ms (cache miss)
22 silly packumentCache full:https://registry.npmjs.org/react set size:undefined disposed:false
23 silly fetch manifest react-dom@19.0.0-rc-66855b96-20241106
24 silly packumentCache full:https://registry.npmjs.org/react-dom cache-miss
25 http fetch GET 200 https://registry.npmjs.org/react-dom 116ms (cache miss)
26 silly packumentCache full:https://registry.npmjs.org/react-dom set size:undefined disposed:false
27 silly fetch manifest @hookform/error-message@^2.0.0
28 silly packumentCache full:https://registry.npmjs.org/@hookform%2ferror-message cache-miss
29 http fetch GET 200 https://registry.npmjs.org/@hookform%2ferror-message 670ms (cache miss)
30 silly packumentCache full:https://registry.npmjs.org/@hookform%2ferror-message set size:undefined disposed:false
31 silly fetch manifest react@>=16.8.0
32 silly packumentCache full:https://registry.npmjs.org/react cache-miss
33 http fetch GET 200 https://registry.npmjs.org/react 14ms (cache hit)
34 silly packumentCache full:https://registry.npmjs.org/react set size:5200078 disposed:false
35 verbose stack Error: unable to resolve dependency tree
35 verbose stack     at #failPeerConflict (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1363:25)
35 verbose stack     at #loadPeerSet (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1329:33)
35 verbose stack     at async #buildDepStep (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:904:11)
35 verbose stack     at async Arborist.buildIdealTree (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
35 verbose stack     at async Promise.all (index 1)
35 verbose stack     at async Arborist.reify (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
35 verbose stack     at async Install.exec (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/lib/commands/install.js:150:5)
35 verbose stack     at async Npm.exec (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/lib/npm.js:207:9)
35 verbose stack     at async module.exports (/Users/sebastian/.nvm/versions/node/v22.11.0/lib/node_modules/npm/lib/cli/entry.js:74:5)
36 error code ERESOLVE
37 error ERESOLVE unable to resolve dependency tree
38 error
39 error While resolving: medusa-next@1.0.3
39 error Found: react@19.0.0-rc-66855b96-20241106
39 error node_modules/react
39 error   react@"19.0.0-rc-66855b96-20241106" from the root project
39 error
39 error Could not resolve dependency:
39 error peer react@">=16.8.0" from @hookform/error-message@2.0.1
39 error node_modules/@hookform/error-message
39 error   @hookform/error-message@"^2.0.0" from the root project
39 error
39 error Fix the upstream dependency conflict, or retry
39 error this command with --force or --legacy-peer-deps
39 error to accept an incorrect (and potentially broken) dependency resolution.
40 error
40 error
40 error For a full report see:
40 error /Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-eresolve-report.txt
41 silly unfinished npm timer reify 1733390602140
42 silly unfinished npm timer reify:loadTrees 1733390602141
43 silly unfinished npm timer idealTree:buildDeps 1733390602148
44 silly unfinished npm timer idealTree:#root 1733390602148
45 verbose cwd /Users/sebastian/Projects/sebastianbk/medusa-tast/medusa-test-storefront
46 verbose os Darwin 24.1.0
47 verbose node v22.11.0
48 verbose npm  v10.9.0
49 verbose exit 1
50 verbose code 1
51 error A complete log of this run can be found in: /Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-debug-0.log
```

### Expected behavior

A successful installation of Medusa.js and its default storefront.

### Actual behavior

```
'Log files:
/Users/sebastian/.npm/_logs/2024-12-05T09_23_21_906Z-debug-0.log

# npm resolution error report

While resolving: medusa-next@1.0.3
Found: react@19.0.0-rc-66855b96-20241106
node_modules/react
  react@"19.0.0-rc-66855b96-20241106" from the root project

Could not resolve dependency:
peer react@">=16.8.0" from @hookform/error-message@2.0.1
node_modules/@hookform/error-message
  @hookform/error-message@"^2.0.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by lbudakov** [comment]
I managed to work around a similar issue when the CLI was setting up the storefront.

I see that the CLI might be trying to install the modules for the storefront using npm, as npm is known to have some issues with module resolution in some versions, I updated node to the latest LTS but this did not work out.

I tried manually installing the modules after navigating to the newly created storefront folder and running yarn manually. This did not work at first as the project is configured to use yarn 3.2.3( if I remember correctly ) as I was lazy i deleted "packageManager" from package.json and yarn install worked like a charm

I'm recently more and more using pnpm and I want to also mention that the installation works without problems.

Happy coding!
