### ISSUE TITLE
[Bug]: Unable to create user after deploying to railway (getaddrinfo ENOTFOUND redis.railway.internal)

### ISSUE THREAD

**Issue by XigeTime** [medusajs/medusa#10494]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "predeploy": "medusa db:migrate",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@paypal/paypal-server-sdk": "^0.6.1",
    "awilix": "^8.0.1",
    "cache-redis": "link:@medusajs/medusa/cache-redis",
    "event-bus-redis": "link:@medusajs/medusa/event-bus-redis",
    "payment": "link:@medusajs/medusa/payment",
    "pg": "^8.13.0",
    "workflow-engine-redis": "link:@medusajs/medusa/workflow-engine-redis"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.12.0

### Database and its version

PostgreSQL 16

### Operating system name and version

MacOS Ventura 13.3

### What happended?

Deployed Medusa Application to railway following the documentation, built successfully but when running `railway run npx medusa user -e email@email.com -p password` the command fails, with the following error:

```
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
error:   An error occurred while connecting to Redis in module 'cache-redis': Error: Connection is closed.
```

Full output:
```
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
error:   An error occurred while connecting to Redis in module 'cache-redis': Error: Connection is closed.
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
info:    Connection to Redis in module 'event-bus-redis' established
Error: Connection is closed.
    at EventEmitter.connectionCloseHandler (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/ioredis@5.4.1/node_modules/ioredis/built/Redis.js:207:28)
    at Object.onceWrapper (node:events:639:26)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.emit (node:domain:489:12)
    at processTicksAndRejections (node:internal/process/task_queues:85:11)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
Error: Connection is closed.
    at EventEmitter.connectionCloseHandler (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/ioredis@5.4.1/node_modules/ioredis/built/Redis.js:207:28)
    at Object.onceWrapper (node:events:639:26)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.emit (node:domain:489:12)
    at processTicksAndRejections (node:internal/process/task_queues:85:11)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
info:    Connection to Redis in module 'workflow-engine-redis' established
Error: Connection is closed.
    at EventEmitter.connectionCloseHandler (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/ioredis@5.4.1/node_modules/ioredis/built/Redis.js:207:28)
    at Object.onceWrapper (node:events:639:26)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.emit (node:domain:489:12)
    at processTicksAndRejections (node:internal/process/task_queues:85:11)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
Error: Connection is closed.
    at EventEmitter.connectionCloseHandler (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/ioredis@5.4.1/node_modules/ioredis/built/Redis.js:207:28)
    at Object.onceWrapper (node:events:639:26)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.emit (node:domain:489:12)
    at processTicksAndRejections (node:internal/process/task_queues:85:11)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
info:    Connection to Redis PubSub in module 'workflow-engine-redis' established
Error: Connection is closed.
    at EventEmitter.connectionCloseHandler (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/ioredis@5.4.1/node_modules/ioredis/built/Redis.js:207:28)
    at Object.onceWrapper (node:events:639:26)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.emit (node:domain:489:12)
    at processTicksAndRejections (node:internal/process/task_queues:85:11)
info:    Locking module: Using "in-memory" as default.
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis.railway.internal
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
warn:    Failed to load countries, skipping loader. Original error: getaddrinfo ENOTFOUND postgres.railway.internal
warn:    Failed to load currencies, skipping loader. Original error: getaddrinfo ENOTFOUND postgres.railway.internal
error:   Could not resolve module: Payment. Error: Loaders for module Payment failed: getaddrinfo ENOTFOUND postgres.railway.internal

Error: Loaders for module Payment failed: getaddrinfo ENOTFOUND postgres.railway.internal
    at runLoaders (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:667:14)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async loadInternalModule (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:286:17)
    at async loadModule (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:82:10)
    at async moduleLoader (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:21:32)
    at async Function.bootstrap_ (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:476:9)
    at async Function.bootstrapAll (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:302:12)
    at async loadModules (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:152:19)
    at async MedusaApp_ (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:384:22)
    at async MedusaApp (/Users/harryknowles/Documents/Clients/solstice-medusa/solstice/node_modules/.pnpm/@medusajs+modules-sdk@2.1.0_@mikro-orm+core@5.9.7_@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_b4or7gc7tv3z2jzkxklxuhkqku/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:585:10)

```

### Expected behavior

A new user should be created

### Actual behavior

Fails to create the user with `Error: getaddrinfo ENOTFOUND redis.railway.internal`

### Link to reproduction repo

https://github.com/XigeTime/solstice-medusa-app

**Comment by fPolic** [comment]
Hey @XigeTime, seems that `REDIS_URL` variable in your Medusa service is misconfigured or the Redis service is down.
Have you set the value to: `${{<<name_of_your_redis_service>>.REDIS_URL}}?family=0`

**Comment by XigeTime** [comment]
Hi @fPolic, yes I have it set to `${{Redis.REDIS_URL}}?family=0` which is showing as `${{1d2eb751-baae-42c4-9f71-0f42dfe0cb1d.REDIS_URL}}?family=0` in the build details, and Redis is showing as active in railway. Migrations seem to have run correctly according to the logs too.

**Comment by thetutlage** [comment]
Can you please log the value of `process.env.REDIS_URL` inside the `medusa-config.ts` file and share what that value is?

Also, as the error indicates, the issue is indeed with connecting to Redis, so necessary debugging has to be done at your end to see what that is the problem.

**Comment by XigeTime** [comment]
The value it outputs is: `redis://default:IkZiLcdxgqbfXdEfdttftLuIJZjTSytQ@redis.railway.internal:6379?family=0`

This is both in the server logs when deployed, and at the beginning when running the `railway run npx medusa user -e email@email.com -p password` command.

I noticed there was another variable for redis in Railway, so I updated it to that; `${{Redis.REDIS_PUBLIC_URL}}?family=0`. This outputs as `redis://default:IkZiLcdxgqbfXdEfdttftLuIJZjTSytQ@autorack.proxy.rlwy.net:28061?family=0` and looks to have fixed connection to the cache-redis module, but I was still getting the connection error for the payment module which was a postgres connection issue.

Updating the DATABASE_URL from `${{Postgres.DATABASE_URL}}` too `${{Postgres.DATABASE_PUBLIC_URL}}`

Which has fixed the issue, and I was able to create the user successfully.

This surely can't be the suggested fix though? Railway adds a message on the public variables stating:
> This variable references a public endpoint through this variable:
> 
> DATABASE_URL -> Postgres.DATABASE_PUBLIC_URL -> Postgres.RAILWAY_TCP_PROXY_DOMAIN
> Connecting to a public endpoint will incur egress fees. That might happen if this variable, DATABASE_URL, is used to establish a connection to a database or another service.
> 
> You can avoid the egress fees by switching to a private endpoint (e.g., RAILWAY_PRIVATE_DOMAIN). Check out our > [documentation](https://docs.railway.com/guides/private-networking#using-reference-variables) for more information!

Should I be fine switching back to the private URL once the user has been created?

**Comment by thetutlage** [comment]
I think the private URLs should work fine for creating the user and running the migrations since both the calls are made internally without hitting any networks from the outside.

As mentioned earlier, this is something you need to debug further with your setup on Railway and unfortunately there isn't much we can do about it :)

**Comment by XigeTime** [comment]
Thanks @thetutlage, I raised this same issue on the Railway support forum and one of the employees mentioned that we must use the public host and port when connecting via the CLI using railway run. https://help.railway.com/questions/unable-to-connect-to-redis-via-cli-geta-2ff2c4e3

It would be ideal if we can set the variable to use via the CLI too if that is the case but I can't find any docs on it.

But anyway, issue fixed! Thanks for your help - maybe we need to mention this in the docs for railway deployment if this is the case?

**Comment by stevebrowndotco** [comment]
This problem still persists if following the railway guide verbatim.

I found the problem is easily solved by tweaking the documentation like so.

Under the  "Add Environment Variables"

Change these two variables FROM

`DATABASE_URL=${{Postgres.DATABASE_URL}}`
`REDIS_URL=${{Redis.REDIS_URL}}?family=0`

to

`DATABASE_URL=${{Postgres.DATABASE_PUBLIC_URL}}`
`REDIS_URL=${{Redis.REDIS_PUBLIC_URL}}?family=0 `

This sovled the problem for me

**Comment by williammoreno** [comment]
the solution by @stevebrowndotco does solve the issue but its problematic that private networking doesn't work on Railway with Medusa 2
