### ISSUE TITLE
[Bug]: Unable to create user after deploying to railway

### ISSUE THREAD

**Issue by kb-0912** [medusajs/medusa#10573]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "predeploy": "medusa db:migrate",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.1.1",
    "@medusajs/cli": "2.1.1",
    "@medusajs/framework": "2.1.1",
    "@medusajs/medusa": "2.1.1",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@rokmohar/medusa-plugin-meilisearch": "^0.1.1",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.1.1",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

v20.16.0

### Database and its version

16.2

### Operating system name and version

Mac OS Sonoma 14.6

### What happended?
```
info:    Connection to Redis in module 'cache-redis' established
info:    Connection to Redis in module 'event-bus-redis' established
info:    Connection to Redis in module 'workflow-engine-redis' established
info:    Connection to Redis PubSub in module 'workflow-engine-redis' established
info:    Locking module: Using "in-memory" as default.
warn:    Failed to load countries, skipping loader. Original error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
warn:    Failed to load currencies, skipping loader. Original error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
error:   Could not resolve module: Payment. Error: Loaders for module Payment failed: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

Error: Loaders for module Payment failed: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at runLoaders (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:667:14)
    at async loadInternalModule (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:286:17)
    at async loadModule (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:82:10)
    at async moduleLoader (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:21:32)
    at async Function.bootstrap_ (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:476:9)
    at async Function.bootstrapAll (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:302:12)
    at async loadModules (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:152:19)
    at async MedusaApp_ (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:384:22)
    at async MedusaApp (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:585:10)
    at async MedusaAppLoader.load (/Users/kb/Documents/GitHub/kollect-backend-20/node_modules/@medusajs/framework/src/medusa-app-loader.ts:246:23)
kb@192 kollect-backend-20 % 
```
### Expected behavior

After deploy to railway, I tried to run ```railway run npx medusa user -e xxxxx@x.com -p xxxxxxx``` but it return error

**Comment by kb-0912** [comment]
Anyone has same problem should change url for Redis & Postgres from REDIS_URL & DATABASE_URL to PUBLIC_REDIS_URL and PUBLIC_DATABASE_URL
