### ISSUE TITLE
[Bug]: Model called "relay" creates TS definitions as "createRelaies" and "deleteRelaies" but actual functions are "createRelays" and "deleteRelays"#10646

### ISSUE THREAD

**Issue by amunrarara** [medusajs/medusa#10647]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.1.2",
    "@medusajs/cli": "2.1.2",
    "@medusajs/framework": "2.1.2",
    "@medusajs/medusa": "2.1.2",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.1.2",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.10.0

### Database and its version

PostgreSQL (default with npx create-medusa-app@latest on 12/17/24)

### Operating system name and version

MacOS Sonoma 14.5 (23F79)

### Browser name

Arc

### What happended?

When I create a model called `relay`, the Medusa auto-generated CRUD functions replace the ending "y" with "ies" in the TypeScript generated types, but _not_ the actual function names. 

My IDE's TypeScript integration (VS Code) detects the presence of `relayPoolModuleService.createRelaies` and `relayPoolModuleService.deleteRelaies`, but these functions throw:

```
❯ curl -X POST http://localhost:9000/admin/relay-pool/relays
{"code":"unknown_error","type":"unknown_error","message":"An unknown error occurred."}%     
```

Server logs:
```
error:   relayPoolModuleService.createRelaies is not a function
{
  message: 'relayPoolModuleService.createRelaies is not a function',
  name: 'TypeError',
  stack: 'TypeError: relayPoolModuleService.createRelaies is not a function\n' +
    '    at Object.async.container.container (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/src/workflows/create-relay.ts:19:52)\n' +
    '    at Object.invoke (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:72:67)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DistributedTransaction.handler (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:827:20)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '    at async promiseAll (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/node_modules/@medusajs/utils/src/common/promise-all.ts:27:18)\n' +
    '    at async TransactionOrchestrator.executeNext (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:965:7)\n' +
    '    at async executeNext (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:1013:14)\n' +
    '    at async TransactionOrchestrator.resume (/Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:1028:5)\n' +
    '⮑ sat /Users/aceaspades/Projects/conduit/projects/medusa-commerce-coordinator/src/workflows/create-relay.ts: [create-relay -> create-relay (invoke)]'
}
http:    POST /admin/relay-pool/relays ← - (500) - 18.849 ms
```

When I change the function calls to `relayPoolModuleService.createRelays` and `relayPoolModuleService.createRelays`, I get expected behavior, but a TypeScript complaint in my IDE.

```
❯ curl -X POST http://localhost:9000/admin/relay-pool/relays
{"relay":{"id":"01JFC4B08FF1PBF5Q7ADSWM31H","url":"wss://localhost:7777","created_at":"2024-12-18T05:37:33.967Z","updated_at":"2024-12-18T05:37:33.968Z","deleted_at":null}}%   
```

![Screenshot 2024-12-17 at 9 06 15 PM](https://github.com/user-attachments/assets/8fa10593-f4d1-4f70-849e-7b5b0a0bae10)

### Expected behavior

Generated functions retain the `y` at the end of `relay`, thus creating `relayPoolModuleService.createRelays`, `relayPoolModuleService.deleteRelays`, etc.

TypeScript types should reflect the same.

### Actual behavior

TypeScript generates model service type with function names `relayPoolModuleService.createRelaies` and `relayPoolModuleService.deleteRelaies`, but these functions throw. 

Actual functions created are `relayPoolModuleService.createRelays`, `relayPoolModuleService.deleteRelays`, but IDE TypeScript integration complains about these names.

### Link to reproduction repo

https://github.com/amunrarara/medusa-model-name-bug/blob/main/README.md

**Comment by fPolic** [comment]
Thanks for the report @amunrarara, we will look into it.

**Comment by amunrarara** [comment]
Cheers @fPolic, 

I see the linear bot closed the issue, but I don't see a PR linked. How was this issue resolved?
