### ISSUE TITLE
[Bug]: Facing issues when enabling workflow engine

### ISSUE THREAD

**Issue by nishit-g** [medusajs/medusa#10733]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "predeploy": "medusa db:migrate",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0",
    "flydrive": "^1.1.0",
    "http-status-codes": "^2.3.0",
    "multer": "^1.4.5-lts.1",
    "nanoid": "^5.0.7"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@types/multer": "^1.4.12",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.10.0

### Database and its version

PostgreSql 16.3.1

### Operating system name and version

Ubuntu WSL 20.02

### What happended?

When enabling I am not able to migrate `npm run predeploy` nor am I able to start the service

```
  modules: {
    workflowEngine: {
      resolve: "@medusajs/medusa/workflow-engine-redis",
      options: {
        redis: {
          url: process.env.WE_REDIS_URL,
        },
      },
    },
}
```

### Expected behavior

I should be able to migrate and the service should start

### Actual behavior

1. When running `npm run predeploy` : I get this issue 
```
❯ npm run predeploy

> medusa-starter-default@0.0.1 predeploy
> medusa db:migrate

redisUrl not found. A fake redis instance will be used.
info:    Running migrations...
error:   Service "workflows" is already defined.
Error: Service "workflows" is already defined.
    at RemoteJoiner.buildReferences (/home/master/personal/yb-app/yb2/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:192:15)
    at new RemoteJoiner (/home/master/personal/yb-app/yb2/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:163:10)
    at new RemoteQuery (/home/master/personal/yb-app/yb2/node_modules/@medusajs/modules-sdk/src/remote-query/remote-query.ts:72:25)
    at MedusaApp_ (/home/master/personal/yb-app/yb2/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:457:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MedusaAppMigrateUp (/home/master/personal/yb-app/yb2/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:593:29)
    at async MedusaAppLoader.runModulesMigrations (/home/master/personal/yb-app/yb2/node_modules/@medusajs/framework/src/medusa-app-loader.ts:176:7)
    at async migrate (/home/master/personal/yb-app/yb2/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:50:3)
    at async main (/home/master/personal/yb-app/yb2/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:77:22)
```

2. When starting the service `npm run dev` I run into this issue 
```
❯ npm run dev

> medusa-starter-default@0.0.1 dev
> medusa develop

info:    Watching filesystem to reload dev server on file change
info:    Skipping instrumentation registration. No register function found.
redisUrl not found. A fake redis instance will be used.
warn:    Local Event Bus installed. This is not recommended for production.
warn:    No default locking provider explicit defined. Using "in-memory" as default.
info:    Connection to Redis in module 'cache-redis' established
info:    Connection to Redis in module 'event-bus-redis' established
info:    Connection to Redis in module 'workflow-engine-redis' established
info:    Connection to Redis PubSub in module 'workflow-engine-redis' established
info:    Initializing file provider: s3
info:    File provider initialized: s3
error:   Error starting server
AwilixResolutionError: Could not resolve 'sharedContainer'.

Resolution path: workflowOrchestratorService -> sharedContainer
    at resolve (/home/master/personal/yb-app/yb2/node_modules/awilix/src/container.ts:497:15)
    at Object.get (/home/master/personal/yb-app/yb2/node_modules/awilix/src/container.ts:269:52)
    at new WorkflowOrchestratorService (/home/master/personal/yb-app/yb2/node_modules/@medusajs/workflow-engine-redis/src/services/workflow-orchestrator.ts:102:5)
    at newClass (/home/master/personal/yb-app/yb2/node_modules/awilix/src/resolvers.ts:202:20)
    at Object.resolve (/home/master/personal/yb-app/yb2/node_modules/awilix/src/resolvers.ts:470:14)
    at resolve (/home/master/personal/yb-app/yb2/node_modules/awilix/src/container.ts:515:33)
    at Object.get (/home/master/personal/yb-app/yb2/node_modules/awilix/src/container.ts:269:52)
    at new WorkflowsModuleService (/home/master/personal/yb-app/yb2/node_modules/@medusajs/workflow-engine-redis/src/services/workflows-module.ts:41:7)
    at /home/master/personal/yb-app/yb2/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:361:16
    at Object.resolve (/home/master/personal/yb-app/yb2/node_modules/awilix/src/resolvers.ts:470:14)

```

### Link to reproduction repo

https://github.com/nishit-g/yb2

**Comment by shahednasser** [comment]
Hello, please register the workflow engine module as explained [here](https://docs.medusajs.com/resources/architectural-modules/workflow-engine/redis#register-the-redis-workflow-engine-module).

If you got the above code snippet you shared from somewhere in the documentation, please let us know so that we can correct it. I'll close this issue for now.
