### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by teddybee** [medusajs/medusa#1424]
It would be nice if you could support other dbs, not just postgresql.
Lots of ordinary server hosting company offers only mysql for db.

**Comment by adrien2p** [comment]
did you try to setup mysql already with medusa? We are using typeorm under the hood, and it support mysql

**Comment by teddybee** [comment]
I have tried, but there are errors when I started the server and it was trying to run initial migrations.
I have used mysql 8 in docker-compose, and will try out with 5.7 as well.

```
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'medusa-docker' AND `TABLE_NAME` = 'migrations'                                                                                                                                                                                                                                                    
query: CREATE TABLE `migrations` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB                                                                                                                                                                                                              
query: SELECT * FROM `medusa-docker`.`migrations` `migrations` ORDER BY `id` DESC                                                                                                                                                                                                                                                                                             
query: START TRANSACTION                                                                                                                                                                                                                                                                                                                                                      
query: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))                                                                                                                                                                                    
query failed: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))                                                                                                                                                                             
error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean ' at line 1                                                                                                              
    at Query.Sequence._packetToError (/app/medusa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)                                                                                                                                                                                                                                                                
    at Query.ErrorPacket (/app/medusa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)                                                                                                                                                                                                                                                                               
    at Protocol._parsePacket (/app/medusa/node_modules/mysql/lib/protocol/Protocol.js:291:23)                                                                                                                                                                                                                                                                                 
    at Parser._parsePacket (/app/medusa/node_modules/mysql/lib/protocol/Parser.js:433:10)                                                                                                                                                                                                                                                                                     
    at Parser.write (/app/medusa/node_modules/mysql/lib/protocol/Parser.js:43:10)                                                                                                                                                                                                                                                                                             
    at Protocol.write (/app/medusa/node_modules/mysql/lib/protocol/Protocol.js:38:16)                                                                                                                                                                                                                                                                                         
    at Socket.<anonymous> (/app/medusa/node_modules/mysql/lib/Connection.js:88:28)                                                                                                                                                                                                                                                                                            
    at Socket.<anonymous> (/app/medusa/node_modules/mysql/lib/Connection.js:526:10)                                                                                                                                                                                                                                                                                           
    at Socket.emit (node:events:526:28)                                                                                                                                                                                                                                                                                                                                       
    at addChunk (node:internal/streams/readable:315:12)                                                                                                                                                                                                                                                                                                                       
    --------------------                                                                                                                                                                                                                                                                                                                                                      
    at Protocol._enqueue (/app/medusa/node_modules/mysql/lib/protocol/Protocol.js:144:48)                                                                                                                                                                                                                                                                                     
    at PoolConnection.query (/app/medusa/node_modules/mysql/lib/Connection.js:198:25)                                                                                                                                                                                                                                                                                         
    at MysqlQueryRunner.<anonymous> (/app/medusa/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:211:56)                                                                                                                                                                                                                                                                
    at step (/app/medusa/node_modules/tslib/tslib.js:144:27)                                                                                                                                                                                                                                                                                                                  
    at Object.next (/app/medusa/node_modules/tslib/tslib.js:125:57)                                                                                                                                                                                                                                                                                                           
    at fulfilled (/app/medusa/node_modules/tslib/tslib.js:115:62)                                                                                                                                                                                                                                                                                                             
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {                                                                                                                                                                                                                                                                                                   
  code: 'ER_PARSE_ERROR',                                                                                                                                                                                                                                                                                                                                                     
  errno: 1064,                                                                                                                                                                                                                                                                                                                                                                
  sqlMessage: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean ' at line 1`,                                                                                                                           
  sqlState: '42000',                                                                                                                                                                                                                                                                                                                                                          
  index: 0,                                                                                                                                                                                                                                                                                                                                                                   
  sql: 'CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))'                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                             
Migration "initialSchema1611063162649" failed, error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean ' at line 1                                                                      
query: ROLLBACK                                                                                                                                                                                                                                                                                                                                                               
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean ' at line 1                                                                                                          
    at QueryFailedError.TypeORMError [as constructor] (/app/medusa/node_modules/typeorm/error/TypeORMError.js:9:28)                                                                                                                                                                                                                                                           
    at new QueryFailedError (/app/medusa/node_modules/typeorm/error/QueryFailedError.js:13:28)                                                                                                                                                                                                                                                                                
    at Query.<anonymous> (/app/medusa/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:220:57)                                                                                                                                                                                                                                                                           
    at Query.<anonymous> (/app/medusa/node_modules/mysql/lib/Connection.js:526:10)                                                                                                                                                                                                                                                                                            
    at Query._callback (/app/medusa/node_modules/mysql/lib/Connection.js:488:16)                                                                                                                                                                                                                                                                                              
    at Query.Sequence.end (/app/medusa/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)                                                                                                                                                                                                                                                                           
    at Query.ErrorPacket (/app/medusa/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)                                                                                                                                                                                                                                                                                
    at Protocol._parsePacket (/app/medusa/node_modules/mysql/lib/protocol/Protocol.js:291:23)                                                                                                                                                                                                                                                                                 
    at Parser._parsePacket (/app/medusa/node_modules/mysql/lib/protocol/Parser.js:433:10)                                                                                                                                                                                                                                                                                     
    at Parser.write (/app/medusa/node_modules/mysql/lib/protocol/Parser.js:43:10) {                                                                                                                                                                                                                                                                                           
  query: 'CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))',                                                                                                                                                                               
  parameters: undefined,                                                                                                                                                                                                                                                                                                                                                      
  driverError: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean ' at line 1                                                                                                      
      at Query.Sequence._packetToError (/app/medusa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)                                                                                                                                                                                                                                                              
      at Query.ErrorPacket (/app/medusa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)                                                                                                                                                                                                                                                                             
      at Protocol._parsePacket (/app/medusa/node_modules/mysql/lib/protocol/Protocol.js:291:23)                                                                                                                                                                                                                                                                               
      at Parser._parsePacket (/app/medusa/node_modules/mysql/lib/protocol/Parser.js:433:10)                                                                                                                                                                                                                                                                                   
      at Parser.write (/app/medusa/node_modules/mysql/lib/protocol/Parser.js:43:10)                                                                                                                                                                                                                                                                                           
      at Protocol.write (/app/medusa/node_modules/mysql/lib/protocol/Protocol.js:38:16)                                                                                                                                                                                                                                                                                       
      at Socket.<anonymous> (/app/medusa/node_modules/mysql/lib/Connection.js:88:28)                                                                                                                                                                                                                                                                                          
      at Socket.<anonymous> (/app/medusa/node_modules/mysql/lib/Connection.js:526:10)                                                                                                                                                                                                                                                                                         
      at Socket.emit (node:events:526:28)                                                                                                                                                                                                                                                                                                                                     
      at addChunk (node:internal/streams/readable:315:12)                                                                                                                                                                                                                                                                                                                     
      --------------------                                                                                                                                                                                                                                                                                                                                                    
      at Protocol._enqueue (/app/medusa/node_modules/mysql/lib/protocol/Protocol.js:144:48)                                                                                                                                                                                                                                                                                   
      at PoolConnection.query (/app/medusa/node_modules/mysql/lib/Connection.js:198:25)                                                                                                                                                                                                                                                                                       
      at MysqlQueryRunner.<anonymous> (/app/medusa/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:211:56)                                                                                                                                                                                                                                                              
      at step (/app/medusa/node_modules/tslib/tslib.js:144:27)                                                                                                                                                                                                                                                                                                                
      at Object.next (/app/medusa/node_modules/tslib/tslib.js:125:57)                                                                                                                                                                                                                                                                                                         
      at fulfilled (/app/medusa/node_modules/tslib/tslib.js:115:62)                                                                                                                                                                                                                                                                                                           
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {                                                                                                                                                                                                                                                                                                 
    code: 'ER_PARSE_ERROR',                                                                                                                                                                                                                                                                                                                                                   
    errno: 1064,                                                                                                                                                                                                                                                                                                                                                              
    sqlMessage: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean ' at line 1`,                                                                                                                         
    sqlState: '42000',                                                                                                                                                                                                                                                                                                                                                        
    index: 0,                                                                                                                                                                                                                                                                                                                                                                 
    sql: 'CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))'                                                                                                                                                                                
  },                                                                                                                                                                                                                                                                                                                                                                          
  code: 'ER_PARSE_ERROR',                                                                                                                                                                                                                                                                                                                                                     
  errno: 1064,                                                                                                                                                                                                                                                                                                                                                                
  sqlMessage: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean ' at line 1`,                                                                                                                           
  sqlState: '42000',                                                                                                                                                                                                                                                                                                                                                          
  index: 0,                                                                                                                                                                                                                                                                                                                                                                   
  sql: 'CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))'                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                             
Successfully compiled 0 files with Babel (19ms).                                                                                                                                                                                                                                                                                                                              
info:    Using fake Redis                                                                                                                                                                                                                                                                                                                                                     

```

**Comment by teddybee** [comment]
The errors are the same with mysql 5.7. Probably the medusa-db.sql is not compatible.

**Comment by adrien2p** [comment]
@olivermrbl in order to be able to run our queries into different dbms, we should always use the typeorm queryBuilder. What do you think?
It would mean that raw queries must be translated with the query builder that should allow us to do it exactly how we want it to be but translated to the right target.

**Comment by olivermrbl** [comment]
> If you are alright with this approach in the migrations file, then I can continue

I like the idea of being able to support multiple drivers, but I don't believe this should be a priority as of now, since it's quite a large refactor.

**Comment by adrien2p** [comment]
@teddybee as mention by @olivermrbl after a deep looking it is quite a huge refactoring. Plus we have not many users on mysql and postgres is quite a good to go as it is equivalent to oracle but free.

**Comment by teddybee** [comment]
MariaDB could be a free and good alternative as well.

**Comment by adrien2p** [comment]
@teddybee the mariaDb support would require the same amount of work since mariaDb is a fork of mysql, there types are the same

**Comment by olivermrbl** [comment]
Closing this for now, since it's not a priority nor will be in the near future. Will re-open when / if it becomes relevant.

**Comment by JesseKoldewijn** [comment]
Bumped into this issue while taking a look into possibly using Medusa for a project. Though due to the global scope it would be nice to be able to use alternative DB connectors. Think about using MySQL through Planetscale's HTTP based connector to allow running Medusa possibly on the Edge runtime for the benefits this would bring with regards to Performance & Costs.

**Comment by arimus** [comment]
Just to voice a bit of support for MySQL support. More than anything, having an option to run on MySQL just so that you don't have to introduce another database to a MySQL-based set of solutions would be great. Love Postgres, but having to manage a second DB for a customer can be problematic at times.

And yes, given TypeORM you should be able to support MySQL pretty easily as long as you aren't running raw queries that are Postgres-specific (or where you do you also have a MySQL equivalent). We use TypeORM extensively ourselves and yes, using the query builder is a good idea to support as many of the underlying DBs as possible.

**Comment by MicahBCode** [comment]
Wanted to place my interest in a solution for that here as well. It wouldn't be very complicated to add another DB to our ecosystem but still it does add quite some complexity that comes with it. Therefore we're looking into a solution for getting this up and running using MariaDB. I would highly support a solution to support different DB drivers here.

**Comment by ramumanavalan** [comment]
It would be great if we support MySQL

**Comment by nadahmed** [comment]
A lot of cheap Cpanel hosting supports MariaDB or MySQL and not many of them support Postgres. It would be great if we can have those database support from Medusa.

**Comment by gsqrt2** [comment]
> A lot of cheap Cpanel hosting supports MariaDB or MySQL and not many of them support Postgres. It would be great if we can have those database support from Medusa.

Love Postgresql too, but truth is clients' hosting solutions often offer mysql/mariadb only, so the opportunities to use MedusaJS are narrowing significantly.

**Comment by gauel** [comment]
Any updates on this?

**Comment by bazo** [comment]
> [@teddybee](https://github.com/teddybee) as mention by [@olivermrbl](https://github.com/olivermrbl) after a deep looking it is quite a huge refactoring. Plus we have not many users on mysql and postgres is quite a good to go as it is equivalent to oracle but free.

you don't have many users on mysql because you only support postgres...
