### ISSUE TITLE
Could not resolve 'fileService'.

### ISSUE THREAD

**Issue by Garnett1314** [medusajs/medusa#1478]
When I add products via medusa-admin, the following error occurs：
`Resolution path: fileService
    at Object.resolve (/home/linux/shouta/node_modules/@medusajs/medusa/node_modules/awilix/lib/container.js:240:23)
    at /home/linux/shouta/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:67:43
    at step (/home/linux/shouta/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:33:23)
    at Object.next (/home/linux/shouta/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:14:53)
    at /home/linux/shouta/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/linux/shouta/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:4:12)
    at /home/linux/shouta/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:61:49
    at exports.default (/home/linux/shouta/node_modules/@medusajs/medusa/dist/api/middlewares/await-middleware.js:34:19)
    at Layer.handle [as handle_request] (/home/linux/shouta/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/linux/shouta/node_modules/express/lib/router/route.js:144:13)
    at Immediate._onImmediate (/home/linux/shouta/node_modules/multer/lib/make-middleware.js:53:37)
    at processImmediate (node:internal/timers:468:21)
error:   Could not resolve 'fileService'.

Resolution path: fileService
AwilixResolutionError: Could not resolve 'fileService'.`
Am I missing something, please?

**Comment by kasperkristensen** [comment]
You need to install a FileService plugin to handle uploading images, there are several, both official and community, options available on [npm](https://www.npmjs.com/search?q=medusa-file). You can read more about it in our [documentation](https://docs.medusajs.com/add-plugins/spaces). 😄

**Comment by Garnett1314** [comment]
Thank you very much for your reply, I think I can solve this problem now!
