### ISSUE TITLE
Resolution path: db_entities

### ISSUE THREAD

**Issue by accpliuchen** [medusajs/medusa#1515]
when I run command medusa develop, show error below

Resolution path: db_entities
    at Object.resolve (E:\medusa\medusa-server\my-medusa-serverside\node_modules\awilix\lib\container.js:240:23)
    at E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\database.js:48:42
    at step (E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\database.js:33:23)
    at Object.next (E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\database.js:14:53)
    at E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\database.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\database.js:4:12)
    at E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\database.js:43:12
    at E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\index.js:140:65
    at step (E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\index.js:52:23)
    at Object.next (E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\index.js:33:53)
    at fulfilled (E:\medusa\medusa-server\my-medusa-serverside\node_modules\@medusajs\medusa\dist\loaders\index.js:24:58)

**Comment by adrien2p** [comment]
Link to [this issue](https://github.com/medusajs/medusa/issues/1514)

**Comment by srindom** [comment]
Duplicate of https://github.com/medusajs/medusa/issues/1514
