### ISSUE TITLE
Cannot run integration tests in watch mode

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#1542]
**Steps to reproduce**
- In the root run `yarn bootstrap && yarn build`
- `cd integration-tests/api`
- `medusa-dev --scan-once`
- `yarn test --watch`

Jest will be able to go through the tests now, but if you make a change to the code (and thereby trigger a new run), Jest typically runs the test once more but then fails with:

```
  Test suite failed to run

    TypeORMError: Driver not Connected

      at new TypeORMError (../../node_modules/typeorm/error/TypeORMError.js:18:24)
      at ../../node_modules/typeorm/driver/postgres/PostgresDriver.js:1051:14
      at PostgresDriver.obtainMasterConnection (../../node_modules/typeorm/driver/postgres/PostgresDriver.js:1049:12)
      at PostgresQueryRunner.connect (../../node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:116:52)
      at PostgresQueryRunner.<anonymous> (../../node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:391:20)
      at step (../../node_modules/typeorm/node_modules/tslib/tslib.js:294:21)
      at Object.next (../../node_modules/typeorm/node_modules/tslib/tslib.js:224:16)
      at ../../node_modules/typeorm/node_modules/tslib/tslib.js:196:69
```

I have not been able to track down where this error stems from, but think it might be related to a warning that also appears when running the tests:

```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
```

Have tried adding the `--detectOpenHandles` flag, but it doesn't give additional information.

**Comment by ianriosbaf** [comment]
I get the same error, but I am not using MedusaJS; I use NestJS. I get the exact same error and it only occurs when I start my app to run CLI commands to seed my database, not as an always-on web server. It makes me think that it truly is a TypeORMError, not a NestJS error (or in your case, a MedusaJS error) - Good Luck, and if I find a solution, ill link it here
