### ISSUE TITLE
when i try medusa develop or medusa start, it show type error

### ISSUE THREAD

**Issue by crazypatient0** [medusajs/medusa#1663]
TypeError: cmd is not a function
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:284:7
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
    at Object.handler (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:54:24)
    at Object.runCommand (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:584:29)
    at module.exports (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:392:6)
    at Object.<anonymous> (/usr/lib/node_modules/@medusajs/medusa-cli/dist/index.js:70:27)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

**Comment by pKorsholm** [comment]
Hi @crazypatient0 

Have you run yarn/npm install in your medusa folder, it could be caused by not having the medusajs project in your `/node_modules `

**Comment by xavierchow** [comment]
@crazypatient0 
I encountered the same error, it was hard to diagnose until I added a console.log to the catch clause,
https://github.com/medusajs/medusa/blob/8e43ef2b3ac5c5b3ee4792cae89d30c20da348ac/packages/medusa-cli/src/create-cli.js#L56-L58

My case was that the `require` as below failed as an outdated `snappy` in the path that nodes try to find dependencies.
After removing the snappy module installed with the old node version, it's working now.
https://github.com/medusajs/medusa/blob/8e43ef2b3ac5c5b3ee4792cae89d30c20da348ac/packages/medusa-cli/src/create-cli.js#L52-L55


```
caught err = Error: Module did not self-register: '/Users/xavier/dev/node_modules/snappy/build/Release/binding.node'.
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Users/xavier/dev/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/xavier/dev/node_modules/snappy/snappy.js:2:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  [stack]: "Error: Module did not self-register: '/Users/xavier/dev/node_modules/snappy/build/Release/binding.node'.\n" +
    '    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
    '    at bindings (/Users/xavier/dev/node_modules/bindings/bindings.js:112:48)\n' +
    '    at Object.<anonymous> (/Users/xavier/dev/node_modules/snappy/snappy.js:2:34)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:981:32)',
  [message]: "Module did not self-register: '/Users/xavier/dev/node_modules/snappy/build/Release/binding.node'.",
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by olivermrbl** [comment]
@crazypatient0 Did you manage to resolve your issue?

**Comment by olivermrbl** [comment]
Closing due to inactivity

**Comment by rightalign-io** [comment]
This error is still persistent on one of my dev's machine
