### ISSUE TITLE
medusa-plugin-meilisearch: "Services must inherit from BaseService" after upgrade.

### ISSUE THREAD

**Issue by javimey** [medusajs/medusa#1711]
Hello! 

After upgrading to the latest version, using node v16.11.1 when I try to run the app I keep getting a crash. 

Here is a list of our dependencies (we added joi due a warning on the upgrade).

```
        "@medusajs/medusa": "^1.3.0",
        "@medusajs/medusa-cli": "^1.3.0",
        "dotenv": "^16.0.0",
        "joi": "^17.6.0",
        "medusa-extender": "^1.6.1",
        "medusa-file-s3": "^1.0.12",
        "medusa-fulfillment-manual": "^1.1.26",
        "medusa-interfaces": "^1.1.27",
        "medusa-marketplace": "^1.0.7",
        "medusa-payment-manual": "^1.0.8",
        "medusa-payment-stripe": "^1.1.30",
        "medusa-plugin-meilisearch": "^0.2.2",
        "mongoose": "^5.13.3",
        "typeorm": "^0.2.36"
```

The medusa-plugin-meilisearch doesn't seem to work: I keep receiving this error when running the server (after running `npm run build && NODE_ENV=development node ./dist/main.js`)

```
...
[Server]      - 6/23/2022, 1:54:05 PM   [ServicesLoader] 0 services overridden
✔ Services initialized – 14ms
✔ Express intialized – 13ms
⠋ Initializing pluginserror:   Services must inherit from BaseService, please check /myProject/node_modules/medusa-plugin-meilisearch/services/meilisearch.js
/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:308
                                            throw new Error(message);
                                                  ^

Error: Services must inherit from /myProject/node_modules/medusa-plugin-meilisearch/services/meilisearch.js
    at /myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:308:51
    at step (/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
    at /myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:4:12)
    at /myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:296:87
    at Array.map (<anonymous>)
    at /myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:296:60
    at step (/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
    at /myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:4:12)
    at registerServices (/myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:289:12)
    at /myProject/node_modules/@medusajs/medusa/dist/loaders/plugins.js:86:62
error Command failed with exit code 1.
```

I managed to run the server by removing the plugin, but we kinda need it to search products :). Here is our medusa-config.js

```
require("dotenv").config()
// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001"

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000"

// Database URL (here we use a local database called medusa-development)
const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store"

// Medusa uses Redis, so this needs configuration as well
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379"

const S3_URL = process.env.S3_URL
const S3_BUCKET_NAME = process.env.S3_BUCKET_NAME
const S3_REGION = process.env.S3_REGION
const AWS_ACCESS_ID = process.env.AWS_ACCESS_ID
const AWS_SECRET_KEY = process.env.AWS_SECRET_KEY

let ENV_FILE_NAME = '';
switch (process.env.NODE_ENV) {
case 'production':
  ENV_FILE_NAME = '.env.production';
  break;
case 'staging':
  ENV_FILE_NAME = '.env.staging';
  break;
case 'test':
  ENV_FILE_NAME = '.env.test';
  break;
case 'development':
default:
  ENV_FILE_NAME = '.env';
  break;
}

try {
  dotenv.config({ path: process.cwd() + '/' + ENV_FILE_NAME });
} catch (e) {
  console.log('--> ', e)
}

// Stripe keys
// const STRIPE_API_KEY = process.env.STRIPE_API_KEY || "";
// const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "";

// This is the place to include plugins. See API documentation for a thorough guide on plugins.
const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `medusa-file-s3`,
    options: {
      S3_URL,
      bucket: S3_BUCKET_NAME,
      S3_REGION,
      access_key_id: AWS_ACCESS_ID,
      secret_access_key: AWS_SECRET_KEY,
    },
  },
  {
    resolve: `medusa-plugin-meilisearch`,
    options: {
        // config object passed when creating an instance of the MeiliSearch client
        config: {
            host: process.env.MEILISEARCH_URL || "http://127.0.0.1:7700",
            apiKey: process.env.MEILISEARCH_MASTER_KEY || "your_master_key"
        },
        settings: {
            // index name
            products: {
                // MeiliSearch's setting options to be set on a particular index
                searchableAttributes: ["title", "handle", "description", "sku", "variant_sku", "tags"],
                displayedAttributes: ["id", "title", "thumbnail", "handle", "description", "variants", "variant_sku", "tags"],
            },
        },
    },
   }
]

module.exports = {
  projectConfig: {
    redis_url: REDIS_URL,
    // For more production-like environment install PostgresQL
    database_url: DATABASE_URL,
    database_type: "postgres",
    store_cors: STORE_CORS,
    admin_cors: ADMIN_CORS,
    database_extra: { ssl: { rejectUnauthorized: false } }, 
    // // database_extra: { },
    // process.env.NODE_ENV !== "development"
    //   ? { ssl: { rejectUnauthorized: false } }
    //   : {},
  },
  plugins,
}
```

Any ideas ? I will continue looking into it, unless you tell me it is some known issue.

Cheers!

**Comment by srindom** [comment]
Hi @javimey - thanks for reporting; please try upgrading the Meilisearch plugin to the latest version:

```
$ yarn add medusa-plugin-meilisearch
```

think the latest version is 0.2.2 :)

**Comment by srindom** [comment]
Hmm.. alright can I have you try `yarn remove medusa-interfaces` in your project :)

**Comment by javimey** [comment]
Hi @srindom !

That worked! You are a legend, thank you very much!
