### ISSUE TITLE
TransactionNotStartedError with clean installation

### ISSUE THREAD

**Issue by eusonlito** [medusajs/medusa#1741]
## Bug report

After a clean installation I get the error:

I'm using the demo nextjs frontend https://github.com/medusajs/nextjs-starter-medusa

```
$> npm install -g @medusajs/medusa-cli
$> medusa new medusa --seed
$> cd medusa
$> medusa develop
Successfully compiled 0 files with Babel (2ms).
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
info:    Using fake Redis
✔ Models initialized – 23ms
✔ Plugin models initialized – 2ms
✔ Repositories initialized – 33ms
✔ Database initialized – 637ms
✔ Strategies initialized – 10ms
✔ Services initialized – 100ms
✔ Express intialized – 7ms
✔ Plugins intialized – 6ms
✔ Subscribers initialized – 4ms
✔ API initialized – 25ms
⠋ Initializing defaultswarn:    You don't have any notification provider plugins installed. You may want to add one to your project.
warn:    You don't have any taxProviders provider plugins installed. You may want to add one to your project.
✔ Defaults initialized – 51ms
⠋ Initializing search engine indexingwarn:    No search engine provider was found: make sure to include a search plugin to enable searching
✔ Indexing completed – 11ms
✔ Server is ready on port: 9000 – 10ms
::ffff:127.0.0.1 - - [27/Jun/2022:14:49:02 +0000] "GET /store/products HTTP/1.1" 200 64640 "-" "axios/0.24.0"
::1 - - [27/Jun/2022:14:49:03 +0000] "OPTIONS /store/carts HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
::1 - - [27/Jun/2022:14:49:03 +0000] "OPTIONS /store/products HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
::1 - - [27/Jun/2022:14:49:03 +0000] "GET /store/products HTTP/1.1" 200 64640 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
::1 - - [27/Jun/2022:14:49:03 +0000] "POST /store/carts HTTP/1.1" 200 2225 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
::ffff:127.0.0.1 - - [27/Jun/2022:14:49:07 +0000] "GET /store/products HTTP/1.1" 200 64640 "-" "axios/0.24.0"
::ffff:127.0.0.1 - - [27/Jun/2022:14:49:07 +0000] "GET /store/products/prod_01G6JT1BEQG0EMFY614VR0FKF5 HTTP/1.1" 200 20152 "-" "axios/0.24.0"
::ffff:127.0.0.1 - - [27/Jun/2022:14:52:15 +0000] "GET /store/products HTTP/1.1" 200 64640 "-" "axios/0.24.0"
::ffff:127.0.0.1 - - [27/Jun/2022:14:52:15 +0000] "GET /store/products/prod_01G6JT1BEQG0EMFY614VR0FKF5 HTTP/1.1" 200 20152 "-" "axios/0.24.0"
::1 - - [27/Jun/2022:14:52:15 +0000] "OPTIONS /store/carts/cart_01G6JT6B9HS3H2G2G2PBKXC8JK HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
::1 - - [27/Jun/2022:14:52:15 +0000] "OPTIONS /store/products HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
error:   SQLITE_ERROR: cannot start a transaction within a transaction
QueryFailedError: SQLITE_ERROR: cannot start a transaction within a transaction
    at QueryFailedError.TypeORMError [as constructor] (/var/www/medusa/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/var/www/medusa/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at Statement.handler (/var/www/medusa/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:117:38)
    at Statement.replacement (/var/www/medusa/node_modules/sqlite3/lib/trace.js:25:27) {
  query: 'BEGIN TRANSACTION',
  parameters: undefined,
  driverError: Error: SQLITE_ERROR: cannot start a transaction within a transaction
  --> in Database#all('BEGIN TRANSACTION', undefined, [Function: handler])
      at SqliteQueryRunner.<anonymous> (/var/www/medusa/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:95:85)
      at step (/var/www/medusa/node_modules/tslib/tslib.js:144:27)
      at Object.next (/var/www/medusa/node_modules/tslib/tslib.js:125:57)
      at /var/www/medusa/node_modules/tslib/tslib.js:118:75
      at new Promise (<anonymous>)
      at __awaiter (/var/www/medusa/node_modules/tslib/tslib.js:114:16)
      at execute (/var/www/medusa/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:86:78)
      at SqliteQueryRunner.<anonymous> (/var/www/medusa/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:139:46)
      at step (/var/www/medusa/node_modules/tslib/tslib.js:144:27)
      at Object.next (/var/www/medusa/node_modules/tslib/tslib.js:125:57)
      at fulfilled (/var/www/medusa/node_modules/tslib/tslib.js:115:62) {
    errno: 1,
    code: 'SQLITE_ERROR',
    __augmented: true
  },
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}
::1 - - [27/Jun/2022:14:52:15 +0000] "GET /store/products HTTP/1.1" 500 86 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
error:   Transaction is not started yet, start transaction before committing or rolling it back.
TransactionNotStartedError: Transaction is not started yet, start transaction before committing or rolling it back.
    at TransactionNotStartedError.TypeORMError [as constructor] (/var/www/medusa/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new TransactionNotStartedError (/var/www/medusa/node_modules/typeorm/error/TransactionNotStartedError.js:12:23)
    at SqliteQueryRunner.<anonymous> (/var/www/medusa/node_modules/typeorm/driver/sqlite-abstract/AbstractSqliteQueryRunner.js:118:35)
    at step (/var/www/medusa/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/www/medusa/node_modules/tslib/tslib.js:125:57)
    at /var/www/medusa/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/var/www/medusa/node_modules/tslib/tslib.js:114:16)
    at SqliteQueryRunner.AbstractSqliteQueryRunner.commitTransaction (/var/www/medusa/node_modules/typeorm/driver/sqlite-abstract/AbstractSqliteQueryRunner.js:113:38)
    at EntityManager.<anonymous> (/var/www/medusa/node_modules/typeorm/entity-manager/EntityManager.js:79:58)
    at step (/var/www/medusa/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/www/medusa/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/www/medusa/node_modules/tslib/tslib.js:115:62)
```

### System information

Medusa version (including plugins): 1.3.0
Node.js version: v16.15.0
Database: SQLite
Operating system: Ubuntu 22.04
Browser (if relevant):

### Steps to reproduce the behavior

1. Install the project
2. Navigate

**Comment by eusonlito** [comment]
Okey! I'm using the default installation to test :)

**Comment by olivermrbl** [comment]
For a seamless and quick setup of Medusa, we run with SQLite as default because it runs on all operating systems. Though, SQLite is constrained to only allow for a single write transaction to run at a time, which is the culprit of the error you are seeing here.

I recommend setting up Postgres right away since it resolves the issue and is much closer to an eventual production environment. See guide here https://docs.medusa-commerce.com/tutorial/set-up-your-development-environment#postgresql.
