### ISSUE TITLE
QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore

### ISSUE THREAD

**Issue by z6vba** [medusajs/medusa#1844]
### Describe the bug

```
error:   Query runner already released. Cannot run queries anymore.
QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
    at QueryRunnerAlreadyReleasedError.TypeORMError [as constructor] (node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryRunnerAlreadyReleasedError (node_modules/typeorm/error/QueryRunnerAlreadyReleasedError.js:9:23)
    at PostgresQueryRunner.<anonymous> (node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:239:35)
    at step (node_modules/tslib/tslib.js:144:27)
    at Object.next (node_modules/tslib/tslib.js:125:57)
    at node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (node_modules/tslib/tslib.js:114:16)
    at PostgresQueryRunner.query (node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:233:38)
    at PostgresQueryRunner.<anonymous> (node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:137:51)
    at step (node_modules/tslib/tslib.js:144:27)
    at Object.next (node_modules/tslib/tslib.js:125:57)
    at fulfilled (node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
::1 - - [11/Jul/2022:02:45:55 +0000] "POST /store/carts/cart_01G7NJAN94RTADTFGGMD1F91AY/payment-sessions HTTP/1.1" 409 148 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
```

### System information

Medusa version (including plugins):
Node.js version: Medusa CLI version: 1.3.1
Database: postgres
Operating system: linux
Browser (if relevant): Chrome/103.0.5060.53

### Steps to reproduce the behavior

1. Post `/store/carts/{cart_id}/payment-sessions`
2. See error

**Comment by z6vba** [comment]
Relates to #1834

**Comment by olivermrbl** [comment]
Duplicate of #1834. See issue for more context. We are working on a solution that's gonna be part of next release :)
