### ISSUE TITLE
[ Generates token application ] has problem with create token

### ISSUE THREAD

**Issue by pawel-niedzwiecki** [medusajs/medusa#1924]
## Bug report

i cannot create a new jwt token for apps , when i try i get error 

```
{
	"code": "unknown_error",
	"type": "unknown_error",
	"message": "An unknown error occurred."
}
```

```
Cannot read properties of undefined (reading 'application_name')
TypeError: Cannot read properties of undefined (reading 'application_name')
    at Oauth.<anonymous> (/Users/uxu/localhost/curius/store.backend.new/node_modules/@medusajs/medusa/dist/services/oauth.js:137:65)
    at step (/Users/uxu/localhost/curius/store.backend.new/node_modules/@medusajs/medusa/dist/services/oauth.js:48:23)
    at Object.next (/Users/uxu/localhost/curius/store.backend.new/node_modules/@medusajs/medusa/dist/services/oauth.js:29:53)
    at fulfilled (/Users/uxu/localhost/curius/store.backend.new/node_modules/@medusajs/medusa/dist/services/oauth.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
::ffff:127.0.0.1 - - [27/Jul/2022:12:39:28 +0000] "POST /admin/apps/authorizations HTTP/1.1" 500 86 "-" "insomnia/2022.4.2"
```

but i added all data in body becuse when i not add i got answet that ,,add np. application_name" or when i will add all data i got answer with error like on top

**Comment by olivermrbl** [comment]
@pawel-niedzwiecki Have you created a service that extends the `OauthService`?

Upon starting up the server, we register all services of type `OauthService` named after its `application_name`. You can check out the loader here.

Attaching below here a barebones example:
```ts
import { OauthService } from "medusa-interfaces"

class TestOauth extends OauthService {
  constructor({}, options) {
    super()
  }

  static getAppDetails(options) {
    return {
      application_name: "example",
      display_name: "Example",
      install_url: "https://some_url.com"
    }
  }

  async refreshToken(token) {
     // should refresh the token for your given installation and return it
    return "newtoken"
  }

  async generateToken(data) {
    // should generate a token for your given installation and return it
    return "token"
  }
}

export default TestOauth
```

**Comment by pawel-niedzwiecki** [comment]
@olivermrbl hey no i'm not did  testing extends OauthService but i am going to testing :) so i i'll let you know , what's the score

**Comment by olivermrbl** [comment]
I will need some details on your implementation. It looks like your custom OauthService is not being registered properly in the Awilix dependency container.

**Comment by pawel-niedzwiecki** [comment]
@olivermrbl when i deleted extends its working all good

**Comment by pawel-niedzwiecki** [comment]
@olivermrbl  look on source in my repo : https://github.com/pawel-niedzwiecki/curius.store.backend/tree/b116503d32be37f8a31abdc82e35aa190e67f167
