### ISSUE TITLE
Unable to export products as CSV

### ISSUE THREAD

**Issue by akoenig** [medusajs/medusa#1940]
### Describe the bug

We're using the `medusa-file-minio` plugin and when we try to export the products to a CSV file, the following error occurs:

```sh
2022-07-30T13:16:49.178765659Z warn:    An error occurred while processing batch.confirmed: Error: Method not implemented.
2022-07-30T13:16:49.182186481Z Error: Method not implemented.
2022-07-30T13:16:49.182215175Z     at _callee$ (/app/medusa/node_modules/.pnpm/medusa-file-minio@1.0.7_gglcwene7hrrve5sg4fdscm2ey/node_modules/medusa-file-minio/services/minio.js:140:23)
2022-07-30T13:16:49.182223421Z     at tryCatch (/app/medusa/node_modules/.pnpm/@babel+runtime@7.18.9/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
2022-07-30T13:16:49.182229885Z     at Generator._invoke (/app/medusa/node_modules/.pnpm/@babel+runtime@7.18.9/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
2022-07-30T13:16:49.182256656Z     at Generator.next (/app/medusa/node_modules/.pnpm/@babel+runtime@7.18.9/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
2022-07-30T13:16:49.182263792Z     at asyncGeneratorStep (/app/medusa/node_modules/.pnpm/medusa-file-minio@1.0.7_gglcwene7hrrve5sg4fdscm2ey/node_modules/medusa-file-minio/services/minio.js:20:103)
2022-07-30T13:16:49.182269830Z     at _next (/app/medusa/node_modules/.pnpm/medusa-file-minio@1.0.7_gglcwene7hrrve5sg4fdscm2ey/node_modules/medusa-file-minio/services/minio.js:22:194)
2022-07-30T13:16:49.182276342Z     at /app/medusa/node_modules/.pnpm/medusa-file-minio@1.0.7_gglcwene7hrrve5sg4fdscm2ey/node_modules/medusa-file-minio/services/minio.js:22:364
2022-07-30T13:16:49.182282185Z     at new Promise (<anonymous>)
2022-07-30T13:16:49.182288211Z     at MinioService.<anonymous> (/app/medusa/node_modules/.pnpm/medusa-file-minio@1.0.7_gglcwene7hrrve5sg4fdscm2ey/node_modules/medusa-file-minio/services/minio.js:22:97)
2022-07-30T13:16:49.182294240Z     at MinioService.getUploadStreamDescriptor (/app/medusa/node_modules/.pnpm/medusa-file-minio@1.0.7_gglcwene7hrrve5sg4fdscm2ey/node_modules/medusa-file-minio/services/minio.js:151:43)
```

Not sure if it is related, but uploading a profile avatar of the current user is not working as well (no error in the logs though).

### System information

Medusa version (including plugins): medusa `1.3.4` / `medusa-file-minio` (`1.0.7`)
Node.js version: 18
Database: PostgreSQL 14.4.0
Operating system: Ubuntu 22.04
Browser (if relevant):

### Steps to reproduce the behavior

1. Install the latest `medusa-file-minio` plugin and configure it like described in the docs.
2. Click on 'Export Products` in the Admin UI (`/a/products`)
3. Check the log of the `engine` and see the error above.

### Expected behavior

It should be possible to export the products.

### Screenshots

n/a

### Code snippets

n/a

### Additional context

n/a

**Comment by olivermrbl** [comment]
Thanks for reporting it in @akoenig. It seems, that the recent release does not contain the correct build files. We'll attend to this asap and publish a new release early next week.

In the meantime, I've published a fix containing the correct files. You can install it using `yarn add medusa-file-minio@1.0.5-minio-fix.253`

**Comment by akoenig** [comment]
Awesome, @olivermrbl! Thanks for the quick solution. I can confirm that the hotfix version works. Looking forward to the release!

Thanks a lot!

**Comment by olivermrbl** [comment]
Great! Thanks for reporting back @akoenig 👍
