### ISSUE TITLE
Error on initialize payment (many request at the same time)

### ISSUE THREAD

**Issue by rrums123** [medusajs/medusa#2004]
### Describe the bug

I'm doing a test, many full-flow checkout process in one time (greater then 5 process at the same time).

The process:
1. Create cart
2. Update cart with address
3. Initialize payment (Stripe and manual)
4. Select payment (Manual)
5. Cart completion

I often get error (below) when hit Initialize payment (Step 3)
```
error:   Cannot read properties of undefined (reading 'queryRunner')
TypeError: Cannot read properties of undefined (reading 'queryRunner')
    at CustomerService.<anonymous> (/Users/ryanrumlaklak/Sites/medusa-test/node_modules/@medusajs/medusa/dist/interfaces/transaction-base-service.js:111:80)
    at step (/Users/ryanrumlaklak/Sites/medusa-test/node_modules/@medusajs/medusa/dist/interfaces/transaction-base-service.js:44:23)
    at Object.throw (/Users/ryanrumlaklak/Sites/medusa-test/node_modules/@medusajs/medusa/dist/interfaces/transaction-base-service.js:25:53)
    at rejected (/Users/ryanrumlaklak/Sites/medusa-test/node_modules/@medusajs/medusa/dist/interfaces/transaction-base-service.js:17:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System information

Medusa version (including plugins):
Node.js version: 16.15.0
Database: Postgres
Operating system: OSX
Browser (if relevant): 

### Steps to reproduce the behavior

Run this process many times at the same time (more than 5)
1. Create cart
2. Update cart with address
3. Initialize payment (Stripe and manual)
4. Select payment (Manual)
5. Cart completion

### Expected behavior

No error when initiate many checkout processes at one time.

### Screenshots

N/A

### Code snippets

N/A

### Additional context

N/A

**Comment by olivermrbl** [comment]
Can I get you to add the version of Medusa you are using?

**Comment by rrums123** [comment]
I am using v1.3.5 @olivermrbl

**Comment by adrien2p** [comment]
It is probably related to the work I told you about here
https://github.com/medusajs/medusa/pull/1773
https://github.com/medusajs/medusa/pull/1776
https://github.com/medusajs/medusa/pull/1780
https://github.com/medusajs/medusa/pull/1781
https://github.com/medusajs/medusa/pull/1789
https://github.com/medusajs/medusa/pull/1790
