### ISSUE TITLE
Errors running the monorepo locally

### ISSUE THREAD

**Issue by judocode** [medusajs/medusa#2114]
## Bug report

Hello, thanks for the work on this project! I was hoping to contribute as I found some bugs, but I ran into errors running the project. I also can't seem to find documentation on how to run this locally, so am I missing something?

### Describe the bug

Several errors trying to run medusa locally

### System information

Medusa version (including plugins): 1.3.6
Node.js version: v16.13.0
Database: Postgres 14
Operating system: Macbook 12.5.1 M1
Browser (if relevant): n/a

### Steps to reproduce the behavior

1. `git clone git@github.com:judocode/medusa.git forked-medusa && cd forked-medusa`
2. `yarn`
3. Searching around, I then figured maybe I could run the tests with: `./scripts/integration-tests.sh`, which errored on `medusa-dev` not being a command.
4. Then I ran `npm install -g medusa-dev-cli` followed by `./scripts/integration-tests.sh` and got the error:
5. `Error: Cannot find module 'medusa-interfaces'`
6. Then I tried following the README here: https://github.com/medusajs/medusa/tree/master/integration-tests#integration-tests
7. `cd /Users/me/web/forked-medusa`
8. `medusa-dev -p /Users/me/web/forked-medusa`
9. `npm run bootstrap`
10. Returned error:
```
> bootstrap
> lerna bootstrap

lerna notice cli v3.22.1
lerna info versioning independent
lerna info bootstrap root only
Unknown Syntax Error: Unsupported option name ("--mutex").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'root'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'root'
```
11. Tried to press on anyway to see what might happen
12. `cd integration-tests/api`
13. `medusa-dev -s`
Error:
```
+ babel-preset-medusa-package@1.1.19-dev-1661655457041
Published babel-preset-medusa-package@1.1.19-dev-1661655457041 to local registry
Publishing @medusajs/medusa@1.3.6-dev-1661655457041 to local registry
npm ERR! code 1
npm ERR! path /Users/me/Web/forked-medusa/packages/medusa
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_ENV=production yarn run build
npm ERR! src/strategies/__fixtures__/order-export-data.ts(2,23): error TS2307: Cannot find module 'medusa-test-utils' or its corresponding type declarations.
npm ERR! src/strategies/__fixtures__/product-export-data.ts(1,23): error TS2307: Cannot find module 'medusa-test-utils' or its corresponding type declarations.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2022-08-28T02_57_46_072Z-debug.log
Failed to publish @medusajs/medusa@1.3.6-dev-1661655457041 Error: Command failed with exit code 1: npm publish --tag medusa-dev --registry=http://localhost:4873
    at makeError (/Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/medusa-dev-cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/medusa-dev-cli/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: npm publish --tag medusa-dev --registry=http://localhost:4873',
  command: 'npm publish --tag medusa-dev --registry=http://localhost:4873',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
14. Tried to press on again, just to see.
15. `npm run build`
16. `cd - && npm run test:integration`
Error:
```
~/Web/forked-medusa

> test:integration
> NODE_ENV=test jest --runInBand --bail --config=integration-tests/jest.config.js

Error: Cannot find module '/Users/me/Web/forked-medusa/integration-tests/plugins/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations'
Require stack:
- /Users/me/Web/forked-medusa/integration-tests/helpers/use-template-db.js
- /Users/me/Web/forked-medusa/integration-tests/globalSetup.js
- /Users/me/Web/forked-medusa/node_modules/@jest/core/node_modules/@jest/transform/build/ScriptTransformer.js
- /Users/me/Web/forked-medusa/node_modules/@jest/core/node_modules/@jest/transform/build/index.js
- /Users/me/Web/forked-medusa/node_modules/@jest/core/node_modules/jest-runtime/build/index.js
- /Users/me/Web/forked-medusa/node_modules/@jest/core/build/cli/index.js
- /Users/me/Web/forked-medusa/node_modules/@jest/core/build/jest.js
- /Users/me/Web/forked-medusa/node_modules/jest-cli/build/cli/index.js
- /Users/me/Web/forked-medusa/node_modules/jest-cli/bin/jest.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at DatabaseFactory._callee$ (/Users/me/Web/forked-medusa/integration-tests/helpers/use-template-db.js:62:29)
    at tryCatch (/Users/me/Web/forked-medusa/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:92:17)
    at Generator._invoke (/Users/me/Web/forked-medusa/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:72:24)
    at Generator.next (/Users/me/Web/forked-medusa/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:123:21)
    at asyncGeneratorStep (/Users/me/Web/forked-medusa/node_modules/@babel/runtime/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/me/Web/forked-medusa/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
```

### Expected behavior

I expect documentation around running medusa locally for the purposes of contributing to it and be able to run the integration tests to see if my changes worked.

**Comment by olivermrbl** [comment]
@judocode Thanks for the detailed report. I've passed along the info to our docs team and we'll attend to an improvement of our setup documentation soon. 

Until then, could I get you to try the following steps:
- `cd forked-medusa`
- `yarn && yarn build`
- `cd packages/medusa && yarn test` <-- All tests should be green
- `cd forked-medusa/integration-tests/api`
- `medusa-dev --force-install --external-registry` <-- force install local packages
- `yarn test`

**Comment by judocode** [comment]
@olivermrbl Excellent, that seems to work now, thanks!
