### ISSUE TITLE
Meilisearch plugin results in error 405

### ISSUE THREAD

**Issue by pzehle** [medusajs/medusa#2117]
## Bug report

Installing the latest version of the medusa-plugin-meilisearch, and the latest version of Meilisearch, results in both platforms reporting `Method not allowed`.

### Describe the bug

**Medusa reports:**

```
⠙ Initializing pluginsError [MeiliSearchCommunicationError]: Method Not Allowed
    at /Users/pzehle/Sites/Repos/sellsly/sellsly-shop/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:181:21
    at step (/Users/pzehle/Sites/Repos/sellsly/sellsly-shop/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:81:27)
    at Object.throw (/Users/pzehle/Sites/Repos/sellsly/sellsly-shop/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:62:57)
    at rejected (/Users/pzehle/Sites/Repos/sellsly/sellsly-shop/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:53:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'MeiliSearchCommunicationError',
  errno: undefined,
  code: undefined
}
```

**Meilisearch reports:**

```
[2022-08-29T01:22:48Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/products/settings HTTP/1.1" 405 0 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000341
```

### System information

Medusa version (including plugins): ^1.3.5
Medusa plugin meilisearch: 0.2.5
Node.js version: 16.14.2
Database: Postgres 14
Operating system: MacOS

### Steps to reproduce the behavior

1. Install medusa as per the documentation.
2. Install meilisearch.
3. Restart medusa.
4. Check both errors.

### Expected behavior

Medusa should be able to send the indexes and Meilisearch should be able to receive them. Both platforms should work as expected.

**Comment by olivermrbl** [comment]
@pzehle Thanks for reporting this one. We'll dive into the issue and run it by the Meilisearch team. Will keep you posted 👍

**Comment by pzehle** [comment]
@olivermrbl Thanks for the reply. In my research from yesterday, I saw that Meilisearch's new version had the methods changed. They say now it has to be `PUT` instead of `POST`.

Could that be it?

**Comment by olivermrbl** [comment]
@pzehle That is very likely! Thanks for providing the insight

**Comment by ensidialabs** [comment]
Also encountered this error. Tried on 2 different computers, on a pure VPS. Tried to distribute search and medusa to different servers. Nothing helps.

**Comment by olivermrbl** [comment]
Updated `meilisearch` dependency in #2140. Will be part of next release 👍
