### ISSUE TITLE
Error: Method not implemented when exporting products

### ISSUE THREAD

**Issue by nicolama-dev** [medusajs/medusa#2367]
## Bug report

`{"level":"warn","message":"An error occurred while processing batch.confirmed: Error: Method not implemented.","timestamp":"2022-10-06 08:32:31"}
Error: Method not implemented.
     at _callee2$ (/app/node_modules/medusa-file-s3/services/s3.js:156:23)
     at tryCatch (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
     at Generator._invoke (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
     at Generator.next (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
     at asyncGeneratorStep (/app/node_modules/medusa-file-s3/services/s3.js:20:103)
     at _next (/app/node_modules/medusa-file-s3/services/s3.js:22:194)
     at /app/node_modules/medusa-file-s3/services/s3.js:22:364
     at new Promise (<anonymous>)
     at S3Service.<anonymous> (/app/node_modules/medusa-file-s3/services/s3.js:22:97)
     at S3Service.getUploadStreamDescriptor (/app/node_modules/medusa-file-s3/services/s3.js:167:43)`

### Describe the bug

When I click on export product on Medusa Admin I get a successful notification of export initiated but after I got this error in the medusa server. 

The uploading of files with s3 works fine with my config.

### System information

Medusa version (including plugins): 1.4.1
Medusa-file-s3: 1.1.5
Database: Postgresql

### Expected behavior

Export products into a .csv

**Comment by yersultanur** [comment]
Have same issue, are there any solutions to this?

**Comment by olivermrbl** [comment]
Hi there. We highly appreciate you filing an issue and showing an interest in improving Medusa.

I apologize for the delayed response.

Moving forward, we aim to do better. But we would like to start fresh. Therefore, we are considering all older issues as stale and closing them, even though they might still be relevant.

Please don’t hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️
