### ISSUE TITLE
Shopping as anonymous user not possible with Stripe payment provider

### ISSUE THREAD

**Issue by artkaas** [medusajs/medusa#2390]
## Bug report

```
::1 - - [09/Oct/2022:20:04:37 +0000] "OPTIONS /store/carts/cart_01GEZ5G7623T37EENJ44CBEA5H HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15"
WARN: withTransaction called without custom implementation
WARN: withTransaction called without custom implementation
error:   Customer with id,cus_01GEZ5JYCW4ZQXQZVHR1PMWSV9: 0 was not found
Error: Customer with id,cus_01GEZ5JYCW4ZQXQZVHR1PMWSV9: 0 was not found
    at CustomerService.<anonymous> (/medusa-server/node_modules/@medusajs/medusa/dist/services/customer.js:279:35)
    at step (/medusa-server/node_modules/@medusajs/medusa/dist/services/customer.js:59:23)
    at Object.next (/medusa-server/node_modules/@medusajs/medusa/dist/services/customer.js:40:53)
    at fulfilled (/medusa-server/node_modules/@medusajs/medusa/dist/services/customer.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'not_found',
  code: undefined,
  date: 2022-10-09T20:04:39.294Z
}
::1 - - [09/Oct/2022:20:04:39 +0000] "POST /store/carts/cart_01GEZ5G7623T37EENJ44CBEA5H HTTP/1.1" 404 97 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15"
```

### Describe the bug

Can not place transactions as anonymous (not logged-in) users with 'nextjs-starter-medusa' frontend and 'medusa-payment-stripe' provider.
It works fine when using 'medusa-payment-manual' provider.

### System information

Medusa version (including plugins): medusa (1.3.7), medusa-payment-stripe (1.1.43), nextjs-starter-medusa (latest)
Node.js version: v18.10.0
Database: postgresql@14 14.5_5
Operating system: macOS Monterey
Browser (if relevant): Safari

### Steps to reproduce the behavior

1. Go to 'Checkout' page of 'nextjs-starter-medusa' as new anonymous user 
2. Fill in the 'Shipping address' form
3. Click on 'Continue to Delivery' button
4. See error from bug report in the server logs
5. You are left on 'Shipping address' form, 'Delivery' and 'Payment' forms stay greyed out and can not be filled in

### Expected behavior

I should be able to place transactions as anonymous users with Stripe, same way I can do it using e.g. medusa-payment-manual

**Comment by artkaas** [comment]
I've decided to upgrade to the newest, just released version of medusa 1.5.0 and medusa-payment-stripe plugin 1.1.44, to see if that fixes the issue.

And now I can successfully pass 'Continue to Delivery' step of the Checkout wizard. But when clicking 'Checkout' button to finish payment I am getting this error:

```
::1 - - [11/Oct/2022:19:20:41 +0000] "OPTIONS /store/carts/cart_01GF47Q6MSZWHZW4DRGT1B3WTR/complete HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15"
::1 - - [11/Oct/2022:19:20:41 +0000] "POST /stripe/hooks HTTP/1.1" 204 - "-" "Stripe/1.0 (+https://stripe.com/docs/webhooks)"
::1 - - [11/Oct/2022:19:20:41 +0000] "POST /stripe/hooks HTTP/1.1" 204 - "-" "Stripe/1.0 (+https://stripe.com/docs/webhooks)"
::1 - - [11/Oct/2022:19:20:45 +0000] "POST /stripe/hooks HTTP/1.1" 200 2 "-" "Stripe/1.0 (+https://stripe.com/docs/webhooks)"
error:   duplicate key value violates unique constraint "UniquePaymentActive"
QueryFailedError: duplicate key value violates unique constraint "UniquePaymentActive"
    at QueryFailedError.TypeORMError [as constructor] (/medusa-server/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/medusa-server/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/medusa-server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/medusa-server/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/medusa-server/node_modules/tslib/tslib.js:125:57)
    at rejected (/medusa-server/node_modules/tslib/tslib.js:116:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  query: 'INSERT INTO "payment"("id", "created_at", "updated_at", "swap_id", "cart_id", "order_id", "amount", "currency_code", "amount_refunded", "provider_id", "data", "captured_at", "canceled_at", "metadata", "idempotency_key") VALUES ($1, DEFAULT, DEFAULT, DEFAULT, $2, DEFAULT, $3, $4, DEFAULT, $5, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING "created_at", "updated_at", "amount_refunded"',
  parameters: [
    'pay_01GF47W1HPT7C9FBP4ZMXZXJ5M',
    'cart_01GF47Q6MSZWHZW4DRGT1B3WTR',
    8000,
    'pln',
    'stripe',
    '{....}'
  ],
  driverError: error: duplicate key value violates unique constraint "UniquePaymentActive"
      at Parser.parseErrorMessage (/medusa-server/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/medusa-server/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/medusa-server/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/medusa-server/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 235,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key (cart_id)=(cart_01GF47Q6MSZWHZW4DRGT1B3WTR) already exists.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'payment',
    column: undefined,
    dataType: undefined,
    constraint: 'UniquePaymentActive',
    file: 'nbtinsert.c',
    line: '670',
    routine: '_bt_check_unique'
  },
  length: 235,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (cart_id)=(cart_01GF47Q6MSZWHZW4DRGT1B3WTR) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'payment',
  column: undefined,
  dataType: undefined,
  constraint: 'UniquePaymentActive',
  file: 'nbtinsert.c',
  line: '670',
  routine: '_bt_check_unique'
}
::1 - - [11/Oct/2022:19:20:45 +0000] "POST /store/carts/cart_01GF47Q6MSZWHZW4DRGT1B3WTR/complete HTTP/1.1" 500 86 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15"
```

**Comment by olivermrbl** [comment]
@artkaas This error is thrown when your cart already has a payment meaning it is likely to have been completed before. Can I get you to clear cache in your browser and try again?

**Comment by adrien2p** [comment]
This payment session was reworked some time ago, I believe that this issue should not be there anymore.

Please don't hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️
