### ISSUE TITLE
Initializing databaseTypeError: Class constructor DefaultNamingStrategy cannot be invoked without 'new'

### ISSUE THREAD

**Issue by maielo** [medusajs/medusa#2558]
### Describe the bug

Can not start backend

### System information

Medusa version (including plugins): 1.6.1
Node.js version: 18.9.0
Database: development - default one - sql-lite
Operating system: Windows
Browser (if relevant): -

### Steps to reproduce the behavior

```
npm run start
```

### Expected behavior

init database

### Screenshots

![image](https://user-images.githubusercontent.com/8983870/200295070-46aa6542-b4c0-4294-bb1b-0b137e4020a2.png)

```
Initializing databaseTypeError: Class constructor DefaultNamingStrategy cannot be invoked without 'new'
    at new ShortenedNamingStrategy (C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\utils\naming-strategy.js:23:42)
    at C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:62:41
    at step (C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:33:23)
    at Object.next (C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:14:53)
    at C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:4:12)
    at C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:43:12
    at C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\index.js:148:65
    at step (C:\web_projects\bonybons\backend\node_modules\@medusajs\medusa\dist\loaders\index.js:56:23)
```

**Comment by biroplane** [comment]
same problem with 1.7.8.
I've tried to remove `node_modules` and reinstall everything, with no luck.
