### ISSUE TITLE
Updating cart with Stripe paymentSessions fails  

### ISSUE THREAD

**Issue by artkaas** [medusajs/medusa#2578]
## Bug Report

```
::1 - - [08/Nov/2022:20:50:19 +0000] "OPTIONS /store/carts/cart_01GHCF1ZENMAD27QAHH4XDH8KE HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15"
WARN: withTransaction called without custom implementation
error:   sessionData is not defined
ReferenceError: sessionData is not defined
    at BlikProviderService._callee10$ (/Users/artur/Projects/auura-store/medusa-server/node_modules/medusa-payment-stripe/services/stripe-blik.js:503:52)
    at tryCatch (/Users/artur/Projects/auura-store/medusa-server/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:72:17)
    at Generator._invoke (/Users/artur/Projects/auura-store/medusa-server/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:55:24)
    at Generator.next (/Users/artur/Projects/auura-store/medusa-server/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:97:21)
    at asyncGeneratorStep (/Users/artur/Projects/auura-store/medusa-server/node_modules/medusa-payment-stripe/services/stripe-blik.js:18:103)
    at _next (/Users/artur/Projects/auura-store/medusa-server/node_modules/medusa-payment-stripe/services/stripe-blik.js:20:194)
    at /Users/artur/Projects/auura-store/medusa-server/node_modules/medusa-payment-stripe/services/stripe-blik.js:20:364
    at new Promise (<anonymous>)
    at BlikProviderService.<anonymous> (/Users/artur/Projects/auura-store/medusa-server/node_modules/medusa-payment-stripe/services/stripe-blik.js:20:97)
    at BlikProviderService.updatePayment (/Users/artur/Projects/auura-store/medusa-server/node_modules/medusa-payment-stripe/services/stripe-blik.js:528:31)

```
### Describe the bug

Updating cart, with Stripe payment sessions, fails with missing 'sessionData' variable.

The reasons for it being a typo in Stripe plugin code (stripe-provider.js) using _sessionData_ instead of _paymentSessionData_ 
https://github.com/medusajs/medusa/blob/master/packages/medusa-payment-stripe/src/services/stripe-provider.js#L306

### System information

Medusa version (including plugins): medusa 1.6.1, medusa-payment-stripe 1.1.45
Node.js version: v18.11.0
Database:  postgresql@14
Operating system: macOS Monterey
Browser (if relevant): Safari

**Comment by olivermrbl** [comment]
Solved in latest version. Please install `medusa-payment-stripe@latest` and try again :) 

Closing for now. Let me know if the issue persist.
