### ISSUE TITLE
error:   Not authorized to list orders

### ISSUE THREAD

**Issue by Anan-Saadi** [medusajs/medusa#2654]
### Describe the bug

when I navigate to orders page in account, I get `error:   Not authorized to list orders`

full log: 
```

 error:   Not authorized to list orders
medusa-server-default         | Error: Not authorized to list orders
medusa-server-default         |     at /app/medusa/node_modules/@medusajs/medusa/dist/api/routes/store/customers/list-orders.js:278:27
medusa-server-default         |     at step (/app/medusa/node_modules/@medusajs/medusa/dist/api/routes/store/customers/list-orders.js:68:23)
medusa-server-default         |     at Object.next (/app/medusa/node_modules/@medusajs/medusa/dist/api/routes/store/customers/list-orders.js:49:53)
medusa-server-default         |     at /app/medusa/node_modules/@medusajs/medusa/dist/api/routes/store/customers/list-orders.js:43:71
medusa-server-default         |     at new Promise (<anonymous>)
medusa-server-default         |     at __awaiter (/app/medusa/node_modules/@medusajs/medusa/dist/api/routes/store/customers/list-orders.js:39:12)
medusa-server-default         |     at /app/medusa/node_modules/@medusajs/medusa/dist/api/routes/store/customers/list-orders.js:270:49
medusa-server-default         |     at exports.default (/app/medusa/node_modules/@medusajs/medusa/dist/api/middlewares/await-middleware.js:12:16)
medusa-server-default         |     at Layer.handle [as handle_request] (/app/medusa/node_modules/express/lib/router/layer.js:95:5)
medusa-server-default         |     at next (/app/medusa/node_modules/express/lib/router/route.js:144:13) {
medusa-server-default         |   type: 'unexpected_state',
medusa-server-default         |   code: undefined,
medusa-server-default         |   date: 2022-11-22T19:36:26.301Z
medusa-server-default         | }
```
### System information

Medusa version : 1.6.0
Node.js version: 16.13.0
Database: postgres
Operating system: windows
Browser : chrome

### Additional context
I am using docker server with all default settings

**Comment by LWJerri** [comment]
It's also happens when you already authorized.

**Comment by olivermrbl** [comment]
@Anan-Saadi Did you try out the pre-release? 

In the meantime, I'll close the issue. Please do not hesitate to re-open if the issue persists.
