### ISSUE TITLE
Stripe hangs in store front showing spinner

### ISSUE THREAD

**Issue by Arsenalist** [medusajs/medusa#2690]
The Stripe widget where the credit card form is supposed to appear just hangs as seen below.

My server package.json:

```
  "dependencies": {
    "@medusajs/medusa": "1.6.5",
    "@medusajs/medusa-cli": "^1.3.3",
    "medusa-fulfillment-manual": "^1.1.31",
    "medusa-interfaces": "^1.3.3",
    "medusa-payment-manual": "^1.0.16",
    "medusa-payment-stripe": "^1.1.48",
    "typeorm": "^0.2.36"
  },
```

My Region configuration:

![image](https://user-images.githubusercontent.com/76740/204538175-d8c109e2-3418-4bc1-9818-c2fbdc31f66f.png)

What I see in storefront:

![image](https://user-images.githubusercontent.com/76740/204538223-c9d39d7d-d6d1-4fc0-9090-4afa3d255d9c.png)

Storefront .env.local:

```
# Your Medusa backend, should be updated to where you are hosting your server. Remember to update CORS settings for your server. See – https://docs.medusajs.com/usage/configurations#storefront-cors
NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost:9000

# Your Stripe public key. See – https://docs.medusajs.com/add-plugins/stripe
NEXT_PUBLIC_STRIPE_KEY=pk_test_c2m4epylx1Ek8mdVd2WHYJGI

# Your PayPal Client ID. See – https://docs.medusajs.com/add-plugins/paypal
NEXT_PUBLIC_PAYPAL_CLIENT_ID=
```

Error on server:

```
medusa-server-default         | error:   Invalid status code: null
medusa-server-default         | RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: null
medusa-server-default         |     at new NodeError (node:internal/errors:371:5)
medusa-server-default         |     at ServerResponse.writeHead (node:_http_server:272:11)
...
medusa-server-default         |     at ServerResponse.json (/app/medusa/node_modules/express/lib/response.js:278:15)
medusa-server-default         |     at /app/medusa/node_modules/@medusajs/medusa/dist/api/routes/store/carts/create-payment-sessions.js:202:58 {
medusa-server-default         |   code: 'ERR_HTTP_INVALID_STATUS_CODE'
```

This is the line of code where it bombs:

`res.status(idempotencyKey.response_code).json(idempotencyKey.response_body);
`

I'm running NextJS storefront, here's the package.json there:

```
  "dependencies": {
    "@headlessui/react": "^1.6.1",
    "@hookform/error-message": "^2.0.0",
    "@medusajs/medusa": "^1.6.5",
    "@medusajs/medusa-js": "^1.3.3",
    "@meilisearch/instant-meilisearch": "^0.7.1",
    "@paypal/paypal-js": "^5.0.6",
    "@paypal/react-paypal-js": "^7.8.1",
    "@stripe/react-stripe-js": "^1.7.2",
    "@stripe/stripe-js": "^1.29.0",
    "clsx": "^1.1.1",
    "lodash": "^4.17.21",
    "medusa-react": "^3.0.1",
    "next": "^12.2.0",
    "react": "17.0.2",
    "react-country-flag": "^3.0.2",
    "react-dom": "17.0.2",
    "react-hook-form": "^7.30.0",
    "react-instantsearch-hooks-web": "^6.29.0",
    "react-intersection-observer": "^9.3.4",
    "react-query": "^3.34.16",
    "sharp": "^0.30.7"
  },
```

**Comment by Arsenalist** [comment]
I implemented a custom storefront and I still get this exact error when I use the following client code:

      medusa.carts.createPaymentSessions(cartState.id)
            .then(({ cart }) => {
                console.log("payment session created", cart.payment_sessions)
            })

It bombs on this [line 136](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/carts/create-payment-sessions.ts):

     res.status(idempotencyKey.response_code).json(idempotencyKey.response_body)

**Comment by chemicalkosek** [comment]
FYI This has been resolved on discord. Issue was probably old deps when used within docker. To close.
