### ISSUE TITLE
Got unexpected Stripe issue when I try to cancel order

### ISSUE THREAD

**Issue by MatteoGauthier** [medusajs/medusa#2825]
### Describe the bug

When I try to delete an order in the admin UI, I got an error.

Here is a screen record 

https://user-images.githubusercontent.com/32040951/208328926-455c84a9-1508-4747-abac-988641ea80dd.mov

And here is the log from the server

```
error:   You cannot cancel this PaymentIntent because it has a status of succeeded. Only a PaymentIntent with one of the following statuses may be canceled: requires_payment_method, requires_capture, requires_confirmation, requires_action, processing.
StripeInvalidRequestError: You cannot cancel this PaymentIntent because it has a status of succeeded. Only a PaymentIntent with one of the following statuses may be canceled: requires_payment_method, requires_capture, requires_confirmation, requires_action, processing.
    at Function.generate (/Users/matteogauthier/dev/nearby-rental-store/server/node_modules/.pnpm/stripe@8.222.0/node_modules/stripe/lib/Error.js:40:16)
    at res.toJSON.then.StripeAPIError.message (/Users/matteogauthier/dev/nearby-rental-store/server/node_modules/.pnpm/stripe@8.222.0/node_modules/stripe/lib/StripeResource.js:220:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'payment_intent_unexpected_state',
    doc_url: 'https://stripe.com/docs/error-codes/payment-intent-unexpected-state',
    message: 'You cannot cancel this PaymentIntent because it has a status of succeeded. Only a PaymentIntent with one of the following statuses may be canceled: requires_payment_method, requires_capture, requires_confirmation, requires_action, processing.',
    payment_intent: {
      id: 'pi_3MGXVRK0YsJDBv3l0uGfl6Ga',
      object: 'payment_intent',
      amount: 3950,
      amount_capturable: 0,
      amount_details: [Object],
      amount_received: 3950,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'manual',
      client_secret: 'pi_3MGXVRK0YsJDBv3l0uGfl6Ga_secret_PcgRh2CLCssOA03kZYlLxDDaC',
      confirmation_method: 'automatic',
      created: 1671410821,
      currency: 'eur',
      customer: 'cus_N0YclWeZy40vXF',
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: 'ch_3MGXVRK0YsJDBv3l0qlculgq',
      livemode: false,
      metadata: [Object],
      next_action: null,
      on_behalf_of: null,
      payment_method: 'pm_1MGXVtK0YsJDBv3lBEUzrcCE',
      payment_method_options: [Object],
      payment_method_types: [Array],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null
    },
    request_log_url: 'https://dashboard.stripe.com/test/logs/req_75NleqUoM0QEdf?t=1671411047',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Mon, 19 Dec 2022 00:50:47 GMT',
      'content-type': 'application/json',
      'content-length': '2173',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'idempotency-key': '52730e91-b863-4026-8ab3-66029915151d',
      'original-request': 'req_75NleqUoM0QEdf',
      'request-id': 'req_75NleqUoM0QEdf',
      'stripe-should-retry': 'false',
      'stripe-version': '2022-11-15',
      'strict-transport-security': 'max-age=63072000; includeSubDomains; preload'
    },
    statusCode: 400,
    requestId: 'req_75NleqUoM0QEdf'
  },
  rawType: 'invalid_request_error',
  code: 'payment_intent_unexpected_state',
  doc_url: 'https://stripe.com/docs/error-codes/payment-intent-unexpected-state',
  param: undefined,
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Mon, 19 Dec 2022 00:50:47 GMT',
    'content-type': 'application/json',
    'content-length': '2173',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'idempotency-key': '52730e91-b863-4026-8ab3-66029915151d',
    'original-request': 'req_75NleqUoM0QEdf',
    'request-id': 'req_75NleqUoM0QEdf',
    'stripe-should-retry': 'false',
    'stripe-version': '2022-11-15',
    'strict-transport-security': 'max-age=63072000; includeSubDomains; preload'
  },
  requestId: 'req_75NleqUoM0QEdf',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: {
    id: 'pi_3MGXVRK0YsJDBv3l0uGfl6Ga',
    object: 'payment_intent',
    amount: 3950,
    amount_capturable: 0,
    amount_details: { tip: {} },
    amount_received: 3950,
    application: null,
    application_fee_amount: null,
    automatic_payment_methods: null,
    canceled_at: null,
    cancellation_reason: null,
    capture_method: 'manual',
    client_secret: 'pi_3MGXVRK0YsJDBv3l0uGfl6Ga_secret_PcgRh2CLCssOA03kZYlLxDDaC',
    confirmation_method: 'automatic',
    created: 1671410821,
    currency: 'eur',
    customer: 'cus_N0YclWeZy40vXF',
    description: null,
    invoice: null,
    last_payment_error: null,
    latest_charge: 'ch_3MGXVRK0YsJDBv3l0qlculgq',
    livemode: false,
    metadata: { cart_id: 'cart_01GMKX92VE2VGED6JGEGT73NWV' },
    next_action: null,
    on_behalf_of: null,
    payment_method: 'pm_1MGXVtK0YsJDBv3lBEUzrcCE',
    payment_method_options: { card: [Object] },
    payment_method_types: [ 'card' ],
    processing: null,
    receipt_email: null,
    review: null,
    setup_future_usage: null,
    shipping: null,
    source: null,
    statement_descriptor: null,
    statement_descriptor_suffix: null,
    status: 'succeeded',
    transfer_data: null,
    transfer_group: null
  },
  payment_method: undefined,
  payment_method_type: undefined,
  setup_intent: undefined,
  source: undefined
}
```

### System information

```
  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 222.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 15.6.1
```

Medusa version (including plugins): 
```
    "@medusajs/medusa": "^1.6.0",
    "@medusajs/medusa-cli": "^1.3.3",
    "medusa-payment-stripe": "^1.1.49",
```
Node.js version:16.18.1
Database:sqllite
Operating system: macos
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to an order
2. Click on Cancel order
3. See error

**Comment by olivermrbl** [comment]
As the error message from Stripe describes, you cannot cancel an order with a fully processed payment. 

I would recommend separating authorization from capture on payments, as it gives you an opportunity to cancel the order after it has been placed.

**Comment by MatteoGauthier** [comment]
Thanks for your reply, I understand the error but I think a visual feedback can be useful for users to better understand the "unexpected" 😁
