### ISSUE TITLE
database_schema doesn't work in db config

### ISSUE THREAD

**Issue by oakbani** [medusajs/medusa#3009]
I am setting up a new medusa project using the instructions provided in README. 

Setup works fine with the default public schema but if I try to use a custom schema it throws out errors on seeding the db and creates only two tables. 

Attaching screenshots below: 

<img width="555" alt="image" src="https://user-images.githubusercontent.com/14175871/212079250-62f6f937-8365-4414-97d8-a8dd05c82d44.png">

<img width="591" alt="image" src="https://user-images.githubusercontent.com/14175871/212079307-b31618f0-27ac-438d-b9c9-87c52df50b5f.png">

> owaisakbani@its-MacBook-Pro server % medusa seed -f data/seed.json                                     
query: SELECT * FROM current_schema()
query: SHOW server_version;
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'customschema' AND "table_name" = 'migrations'
query: CREATE TABLE "customschema"."migrations" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id"))
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'customschema' AND "table_name" = 'typeorm_metadata'
query: CREATE TABLE "customschema"."typeorm_metadata" ("type" character varying NOT NULL, "database" character varying, "schema" character varying, "table" character varying, "name" character varying, "value" text)
query: SELECT * FROM "customschema"."migrations" "migrations" ORDER BY "id" DESC
query: START TRANSACTION
query: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))
query failed: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))
error: error: relation "fulfillment_provider" already exists
    at Parser.parseErrorMessage (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 114,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heap.c',
  line: '1202',
  routine: 'heap_create_with_catalog'
}
Migration "initialSchema1611063162649" failed, error: relation "fulfillment_provider" already exists
query: ROLLBACK
QueryFailedError: relation "fulfillment_provider" already exists
    at QueryFailedError.TypeORMError [as constructor] (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:125:57)
    at rejected (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:116:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  query: 'CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))',
  parameters: undefined,
  driverError: error: relation "fulfillment_provider" already exists
      at Parser.parseErrorMessage (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 114,
    severity: 'ERROR',
    code: '42P07',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'heap.c',
    line: '1202',
    routine: 'heap_create_with_catalog'
  },
  length: 114,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heap.c',
  line: '1202',
  routine: 'heap_create_with_catalog'
}

### When tried with -m false in seed command, it throws out these errors:

> owaisakbani@its-MacBook-Pro server % medusa seed -f data/seed.json -m false
✔ Models initialized – 29ms
✔ Plugin models initialized – 13ms
✔ Repositories initialized – 157ms
✔ Database initialized – 153ms
✔ Strategies initialized – 40ms
✔ Modules initialized – 2ms
✔ Services initialized – 17ms
✔ Express intialized – 23ms
✔ Plugins intialized – 18ms
✔ Subscribers initialized – 40ms
✔ API initialized – 78ms
⠋ Initializing defaults
QueryFailedError: relation "customschema.staged_job" does not exist
    at QueryFailedError.TypeORMError [as constructor] (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:125:57)
    at rejected (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:116:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  query: 'SELECT "StagedJob"."id" AS "StagedJob_id", "StagedJob"."event_name" AS "StagedJob_event_name", "StagedJob"."data" AS "StagedJob_data", "StagedJob"."options" AS "StagedJob_options" FROM "customschema"."staged_job" "StagedJob" LIMIT 1000',
  parameters: [],
  driverError: error: relation "customschema.staged_job" does not exist
      at Parser.parseErrorMessage (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 123,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '186',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1363',
    routine: 'parserOpenTable'
  },
  length: 123,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '186',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1363',
  routine: 'parserOpenTable'
}
QueryFailedError: relation "customschema.country" does not exist
    at QueryFailedError.TypeORMError [as constructor] (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:125:57)
    at rejected (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/tslib/tslib.js:116:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  query: 'SELECT "Country"."id" AS "Country_id", "Country"."iso_2" AS "Country_iso_2", "Country"."iso_3" AS "Country_iso_3", "Country"."num_code" AS "Country_num_code", "Country"."name" AS "Country_name", "Country"."display_name" AS "Country_display_name", "Country"."region_id" AS "Country_region_id" FROM "customschema"."country" "Country" LIMIT 1',
  parameters: [],
  driverError: error: relation "customschema.country" does not exist
      at Parser.parseErrorMessage (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/owaisakbani/Documents/medusa-bazar/server/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 120,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '298',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1363',
    routine: 'parserOpenTable'
  },
  length: 120,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '298',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1363',
  routine: 'parserOpenTable'
⠼

**Comment by josetr** [comment]
See https://github.com/medusajs/medusa/pull/2819#issuecomment-1356385232. Looks like the documentation is incomplete.

**Comment by shahednasser** [comment]
Thanks for pointing this out @josetr ! I'll make sure to add the `search_path` option

**Comment by shahednasser** [comment]
Fixed in #3037
