### ISSUE TITLE
Window is not defined (Storefront issue)

### ISSUE THREAD

**Issue by robbyklein** [medusajs/medusa#3020]
Hey there, I was trying to build a medusa app and I'm running into an issue on the storefront (generated from create-medusa-app):

```
eady - started server on 0.0.0.0:8000, url: http://localhost:8000
event - compiled client and server successfully in 663 ms (926 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 399 ms (965 modules)
error - ReferenceError: window is not defined
    at Object.<anonymous> (/home/robby/Dev/my-medusa-store/storefront/node_modules/@medusajs/medusa-js/dist/index.js:1:93559)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/robby/Dev/my-medusa-store/storefront/node_modules/medusa-react/dist/medusa-react.cjs.development.js:10:30)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) {
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 77 ms (966 modules)
ReferenceError: window is not defined
    at Object.<anonymous> (/home/robby/Dev/my-medusa-store/storefront/node_modules/@medusajs/medusa-js/dist/index.js:1:93559)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/robby/Dev/my-medusa-store/storefront/node_modules/medusa-react/dist/medusa-react.cjs.development.js:10:30)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
```

I generated the site with create-medusa-app (on node 16):

```
npx create-medusa-app
medusa-starter-default
Next.js Starter
```

Same issue with the gatsby-starter and medusa.express (next.js).

Any idea?

**Comment by StephixOne** [comment]
Thank you for raising this! We are aware of the issue, and are testing a hotfix that should be out shortly.

**Comment by fsyntax** [comment]
Hey! We're getting a similiar error on a Nuxt 3 storefront after migrating the server to 1.7.3 and also updating the medusajs-client to 1.3.6 ..
`
[nuxt] [request error] [unhandled] [500] window is not defined
  at Object.<anonymous> (C:\***\node_modules\.pnpm\@medusajs+medusa-js@1.3.6\node_modules\@medusajs\medusa-js\dist\index.js:1:93559)
  at Module._compile (node:internal/modules/cjs/loader:1155:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
  at Module.load (node:internal/modules/cjs/loader:1033:32)
  at Function.Module._load (node:internal/modules/cjs/loader:868:12)

  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
`

**Comment by ask007learning** [comment]
Same issue here, when trying to run next's storefront. Getting error "window is not defined"

**Comment by imash96** [comment]
Is there any fix available

**Comment by ikritiuk** [comment]
have the same issue, looking forward the fix

**Comment by nekszt** [comment]
The front was not usable at all
The fix seems working for me #3016 (check my comment but I'm not sure about the snapshot to use)

**Comment by bentrynning** [comment]
For me he issue is going from  "medusa-react": "^0.3.6",  witch is the latest version I have had the last weeks. 
And today when updating the package to the lates version it jumps to  "medusa-react": "^4.0.1". 
Downgrading back to `^0.3.6"` fixes the issue. But why the big version jump ?

**Comment by YagoLopez** [comment]
Same problem here.

I found a temporary workaround until the bug is fixed running this commands in the storefron directory:

```
yarn add @medusajs/medusa-js@1.3.7-snapshot-20230112194226

yarn add medusa-react@4.0.2-snapshot-20230112194226
```

Source https://github.com/medusajs/medusa/pull/3016#issuecomment-1380918911

**Comment by andrelmlins** [comment]
Forcing version of `@medusajs/medusa-js`, solved the problem:

```
"resolutions": {
    "@medusajs/medusa-js": "1.3.3"
}
```

**Comment by hasibul-huq** [comment]
Same issue here

**Comment by nabilrt** [comment]
Same issue happening

**Comment by mahimtalukder** [comment]
Same issue here on storefront

**Comment by kasperkristensen** [comment]
Thanks for reporting it everybody, the issue has been fixed and merged and should be released later today as `@medusajs/medusa-js@1.3.7` and `medusa-react@4.0.2`. If this is blocking you right here and now, you can always downgrade your version to `@medusajs/medusa-js@1.3.5` and `medusa-react@4.0.0`, or use the snapshot version of the fixed packages that is available as `@medusajs/medusa-js@1.3.7-snapshot-20230116155119` and `medusa-react@4.0.2-snapshot-20230116155119`. When updating/downgrading your dependencies you may need to clear node modules and do a fresh `yarn/npm install` 😄

**Comment by dragosstancu** [comment]
This is embarrassing ... I wanted to demo the store to my boss, stuck for a week.

**Comment by olivermrbl** [comment]
@dragosstancu Sorry to hear, but your comment is not very constructive. 

Did the snapshot not work for you? What's your setup?

**Comment by dragosstancu** [comment]
OK, It looks like it took off using the snapshots.
Now I have another error, I'm guessing it's my fault:

Unhandled Runtime Error
Error: Network Error

Call Stack
createError
node_modules/@medusajs/medusa-js/node_modules/axios/lib/core/createError.js (16:0)
XMLHttpRequest.handleError
node_modules/@medusajs/medusa-js/node_modules/axios/lib/adapters/xhr.js (117:0)

**Comment by dragosstancu** [comment]
@ask007learning  - I am deeply grateful for anything open source and I'm sorry if my comment felt harsh. 
Yet nobody tested the storefront and the situation was the way it was.

**Comment by olivermrbl** [comment]
Part of `@medusajs/medusa-js@1.3.7`

**Comment by robbyklein** [comment]
Hey guys, tried it again just now, the npx command no longer completes.

```
robby@robby:~/Desktop $ node -v
v16.19.0
robby@robby:~/Desktop $ npx create-medusa-app
✔ Where should your project be installed? · my-medusa-store
✔ Which Medusa starter would you like to install? · medusa-starter-default
✔ Which storefront starter would you like to install? · Next.js Starter
⠋ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠙ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠹ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠸ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠼ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠴ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠦ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠧ Creating new project from git: https://github.com/medusajs/medusa-starter-defa⠇ Creating new project from git: https://github.com/medusajs/medusa-starter-default.git
✔ Created starter directory layout

⠇ Installing packages...
✔ Packages installed
Error: Command failed with exit code 1: npm install
    at gt (/home/robby/.npm/_npx/cc876d312f16923e/node_modules/create-medusa-app/dist/index.js:1:113620)
    at /home/robby/.npm/_npx/cc876d312f16923e/node_modules/create-medusa-app/dist/index.js:1:123343
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async js (/home/robby/.npm/_npx/cc876d312f16923e/node_modules/create-medusa-app/dist/index.js:1:183921)
    at async /home/robby/.npm/_npx/cc876d312f16923e/node_modules/create-medusa-app/dist/index.js:1:185433
    at async Is (/home/robby/.npm/_npx/cc876d312f16923e/node_modules/create-medusa-app/dist/index.js:1:184931)
    at async exports.run (/home/robby/.npm/_npx/cc876d312f16923e/node_modules/create-medusa-app/dist/index.js:1:497110) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
robby@robby:~/Desktop $
 ```

Am I doing something wrong?

**Comment by olivermrbl** [comment]
@robbyklein Thanks for reporting this one. We'll investigate your issue and get back asap!
