### ISSUE TITLE
payment-stripe: Cannot create patment session: `StripeInvalidRequestError` amount is `NaN`.

### ISSUE THREAD

**Issue by jimvandervoort** [medusajs/medusa#3028]
### Describe the bug

When testing the Stripe payment provider, I receive the following error calling `medusa.carts.createPaymentSessions`.

<details>
<summary>Full error log from medusa server</summary>

```
error:   Invalid integer: NaN
StripeInvalidRequestError: Invalid integer: NaN
    at StripeError.generate (/Users/jim/code/stoer/medusa-server/node_modules/stripe/lib/Error.js:40:16)
    at res.toJSON.then.StripeAPIError.message (/Users/jim/code/stoer/medusa-server/node_modules/stripe/lib/StripeResource.js:220:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'parameter_invalid_integer',
    doc_url: 'https://stripe.com/docs/error-codes/parameter-invalid-integer',
    message: 'Invalid integer: NaN',
    param: 'amount',
    request_log_url: 'https://dashboard.stripe.com/test/logs/req_AeP0ENOOqPhzO6?t=1673621883',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Fri, 13 Jan 2023 14:58:03 GMT',
      'content-type': 'application/json',
      'content-length': '337',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'idempotency-key': 'bd1c912b-15b5-46fd-93b4-983209c8fbec',
      'original-request': 'req_AeP0ENOOqPhzO6',
      'request-id': 'req_AeP0ENOOqPhzO6',
      'stripe-version': '2022-11-15',
      'strict-transport-security': 'max-age=63072000; includeSubDomains; preload'
    },
    statusCode: 400,
    requestId: 'req_AeP0ENOOqPhzO6'
  },
  rawType: 'invalid_request_error',
  code: 'parameter_invalid_integer',
  doc_url: 'https://stripe.com/docs/error-codes/parameter-invalid-integer',
  param: 'amount',
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Fri, 13 Jan 2023 14:58:03 GMT',
    'content-type': 'application/json',
    'content-length': '337',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'idempotency-key': 'bd1c912b-15b5-46fd-93b4-983209c8fbec',
    'original-request': 'req_AeP0ENOOqPhzO6',
    'request-id': 'req_AeP0ENOOqPhzO6',
    'stripe-version': '2022-11-15',
    'strict-transport-security': 'max-age=63072000; includeSubDomains; preload'
  },
  requestId: 'req_AeP0ENOOqPhzO6',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  payment_method_type: undefined,
  setup_intent: undefined,
  source: undefined
}
::ffff:127.0.0.1 - - [13/Jan/2023:14:58:03 +0000] "POST /store/carts/cart_01GPNT6H66NF47B9AEWGNAWRZ1/payment-sessions HTTP/1.1" 500 86 "http://localhost:9200/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0"
```

</details>

### System information

Medusa version (including plugins):
```
yarn list v1.22.19
├─ @medusajs/medusa-cli@1.3.4
├─ @medusajs/medusa@1.6.3
├─ babel-preset-medusa-package@1.1.19
├─ medusa-core-utils@1.1.34
├─ medusa-extender@1.7.7
├─ medusa-file-minio@1.1.1
├─ medusa-fulfillment-manual@1.1.31
├─ medusa-interfaces@1.3.3
├─ medusa-payment-manual@1.0.16
├─ medusa-payment-stripe@1.1.50
│  └─ medusa-core-utils@1.1.37
├─ medusa-telemetry@0.0.14
└─ medusa-test-utils@1.1.37
```

Node.js version: v19.0.1
Database: PostgreSQL 15.1
Operating system: macOS 13.1
Browser (if relevant): 109.0b9 (64-bit)

### Steps to reproduce the behavior

Minimal client code which reproduce the issue for me:

```js 
const medusa = new Medusa({
  baseUrl: "http://localhost:9000",
  maxRetries: 3,
});

const { product } = await medusa.products.retrieve(productId);
console.log({ product });

const variantId = product.variants[0].id;
const items = [{ quantity: 1, variant_id: variantId }];

// Removed shipping steps as described in
// https://docs.medusajs.com/advanced/backend/shipping/add-fulfillment-provider/
// the same Stripe error was triggered if those methods where added.

const { cart } = await medusa.carts.create({ items });
console.log({ cart });

const ps = await medusa.carts.createPaymentSessions(cart.id);
console.log(ps);
```

<details>
<summary>Product logged to console</summary>

```json
{
  "product": {
    "id": "prod_01GJ32VQW6NZVC2TKX5Y31W8MB",
    "created_at": "2022-11-17T15:21:03.261Z",
    "updated_at": "2022-12-01T14:53:03.110Z",
    "deleted_at": null,
    "title": "Under a Sinking Sun’",
    "subtitle": "",
    "description": "redacted",
    "is_giftcard": false,
    "status": "published",
    "thumbnail": "http://localhost:9300/medusa/poster-1669384266232.jpg",
    "profile_id": "sp_01GJ32VPZFXTW3A9PERCFSBHPG",
    "weight": 400,
    "length": null,
    "height": null,
    "width": null,
    "hs_code": null,
    "origin_country": null,
    "mid_code": null,
    "material": "",
    "collection_id": null,
    "type_id": null,
    "discountable": true,
    "external_id": null,
    "metadata": null,
    "bunnyVideoId": "408cc908-5bc2-4e16-ad58-633e5fc66c5e",
    "variants": [
      {
        "id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
        "created_at": "2022-11-17T15:21:03.261Z",
        "updated_at": "2023-01-13T14:47:19.400Z",
        "deleted_at": null,
        "title": "S",
        "product_id": "prod_01GJ32VQW6NZVC2TKX5Y31W8MB",
        "sku": null,
        "barcode": null,
        "ean": null,
        "upc": null,
        "inventory_quantity": 94,
        "allow_backorder": false,
        "manage_inventory": true,
        "hs_code": null,
        "origin_country": null,
        "mid_code": null,
        "material": null,
        "weight": null,
        "length": null,
        "height": null,
        "width": null,
        "metadata": null,
        "prices": [
          {
            "id": "ma_01GJ32VQXCZ3AJKN72HMW5GN1C",
            "created_at": "2022-11-17T15:21:03.261Z",
            "updated_at": "2022-11-17T15:21:03.261Z",
            "deleted_at": null,
            "currency_code": "eur",
            "amount": 2500,
            "min_quantity": null,
            "max_quantity": null,
            "price_list_id": null,
            "variant_id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
            "region_id": null,
            "price_list": null
          },
          {
            "id": "ma_01GJ32VQXGV1VVCR0HFN76DYRJ",
            "created_at": "2022-11-17T15:21:03.261Z",
            "updated_at": "2022-11-17T15:21:03.261Z",
            "deleted_at": null,
            "currency_code": "usd",
            "amount": 2850,
            "min_quantity": null,
            "max_quantity": null,
            "price_list_id": null,
            "variant_id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
            "region_id": null,
            "price_list": null
          }
        ],
        "options": [
          {
            "id": "optval_01GJ32VQX66KZV0D0YXTNEAQW9",
            "created_at": "2022-11-17T15:21:03.261Z",
            "updated_at": "2022-11-17T15:21:03.261Z",
            "deleted_at": null,
            "value": "S",
            "option_id": "opt_01GJ32VQWB6255QEP8VKS4QN41",
            "variant_id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
            "metadata": null
          }
        ],
        "original_price": null,
        "calculated_price": null,
        "original_price_incl_tax": null,
        "calculated_price_incl_tax": null,
        "original_tax": null,
        "calculated_tax": null,
        "tax_rates": null
      }
    ],
    "options": [
      {
        "id": "opt_01GJ32VQWB6255QEP8VKS4QN41",
        "created_at": "2022-11-17T15:21:03.261Z",
        "updated_at": "2022-11-17T15:21:03.261Z",
        "deleted_at": null,
        "title": "Size",
        "product_id": "prod_01GJ32VQW6NZVC2TKX5Y31W8MB",
        "metadata": null,
        "values": [
          {
            "id": "optval_01GJ32VQX66KZV0D0YXTNEAQW9",
            "created_at": "2022-11-17T15:21:03.261Z",
            "updated_at": "2022-11-17T15:21:03.261Z",
            "deleted_at": null,
            "value": "S",
            "option_id": "opt_01GJ32VQWB6255QEP8VKS4QN41",
            "variant_id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
            "metadata": null
          }
        ]
      }
    ],
    "images": [
      {
        "id": "img_01GJQGYPY80C1M9ME404408MS8",
        "created_at": "2022-11-25T13:52:10.149Z",
        "updated_at": "2022-11-25T13:52:10.149Z",
        "deleted_at": null,
        "url": "http://localhost:9300/medusa/poster-1669384330087.jpg",
        "metadata": null
      }
    ],
    "tags": [],
    "collection": null,
    "type": null
  }
}
```

</details>

<details>
<summary>Cart logged to console</summary>

```js
{
  "cart": {
    "object": "cart",
    "id": "cart_01GPNWE6Z54EVBZ2RX5FY483NC",
    "gift_cards": [],
    "region": {
      "id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA",
      "created_at": "2022-11-17T15:21:03.261Z",
      "updated_at": "2022-11-17T15:21:03.261Z",
      "deleted_at": null,
      "name": "EU",
      "currency_code": "eur",
      "tax_rate": 0,
      "tax_code": null,
      "gift_cards_taxable": true,
      "automatic_taxes": true,
      "tax_provider_id": null,
      "metadata": null,
      "countries": [
        {
          "id": 215,
          "iso_2": "se",
          "iso_3": "swe",
          "num_code": 752,
          "name": "SWEDEN",
          "display_name": "Sweden",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        },
        {
          "id": 157,
          "iso_2": "nl",
          "iso_3": "nld",
          "num_code": 528,
          "name": "NETHERLANDS",
          "display_name": "Netherlands",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        },
        {
          "id": 235,
          "iso_2": "gb",
          "iso_3": "gbr",
          "num_code": 826,
          "name": "UNITED KINGDOM",
          "display_name": "United Kingdom",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        },
        {
          "id": 82,
          "iso_2": "de",
          "iso_3": "deu",
          "num_code": 276,
          "name": "GERMANY",
          "display_name": "Germany",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        },
        {
          "id": 60,
          "iso_2": "dk",
          "iso_3": "dnk",
          "num_code": 208,
          "name": "DENMARK",
          "display_name": "Denmark",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        },
        {
          "id": 75,
          "iso_2": "fr",
          "iso_3": "fra",
          "num_code": 250,
          "name": "FRANCE",
          "display_name": "France",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        },
        {
          "id": 209,
          "iso_2": "es",
          "iso_3": "esp",
          "num_code": 724,
          "name": "SPAIN",
          "display_name": "Spain",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        },
        {
          "id": 109,
          "iso_2": "it",
          "iso_3": "ita",
          "num_code": 380,
          "name": "ITALY",
          "display_name": "Italy",
          "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA"
        }
      ],
      "payment_providers": [
        {
          "id": "stripe",
          "is_installed": true
        }
      ],
      "tax_rates": [],
      "fulfillment_providers": [
        {
          "id": "email",
          "is_installed": true
        }
      ]
    },
    "items": [
      {
        "id": "item_01GPNWE7KZPVDXHJEZ8W5B05YX",
        "created_at": "2023-01-13T15:37:10.728Z",
        "updated_at": "2023-01-13T15:37:10.728Z",
        "cart_id": "cart_01GPNWE6Z54EVBZ2RX5FY483NC",
        "order_id": null,
        "swap_id": null,
        "claim_order_id": null,
        "title": "Under a Sinking Sun",
        "description": "redacted",
        "thumbnail": "http://localhost:9300/medusa/poster-1669384266232.jpg",
        "is_return": false,
        "is_giftcard": false,
        "should_merge": true,
        "allow_discounts": true,
        "has_shipping": false,
        "unit_price": 2500,
        "variant_id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
        "quantity": 1,
        "fulfilled_quantity": null,
        "returned_quantity": null,
        "shipped_quantity": null,
        "metadata": {},
        "adjustments": [],
        "tax_lines": [
          {
            "rate": 0,
            "name": "default",
            "code": "default",
            "item_id": "item_01GPNWE7KZPVDXHJEZ8W5B05YX"
          }
        ],
        "variant": {
          "id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
          "created_at": "2022-11-17T15:21:03.261Z",
          "updated_at": "2023-01-13T14:47:19.400Z",
          "deleted_at": null,
          "title": "S",
          "product_id": "prod_01GJ32VQW6NZVC2TKX5Y31W8MB",
          "sku": null,
          "barcode": null,
          "ean": null,
          "upc": null,
          "inventory_quantity": 94,
          "allow_backorder": false,
          "manage_inventory": true,
          "hs_code": null,
          "origin_country": null,
          "mid_code": null,
          "material": null,
          "weight": null,
          "length": null,
          "height": null,
          "width": null,
          "metadata": null,
          "product": {
            "id": "prod_01GJ32VQW6NZVC2TKX5Y31W8MB",
            "created_at": "2022-11-17T15:21:03.261Z",
            "updated_at": "2022-12-01T14:53:03.110Z",
            "deleted_at": null,
            "title": "Under a Sinking Sun",
            "subtitle": "",
            "description": "redacted",
            "handle": "under-a-sinking-sun",
            "is_giftcard": false,
            "status": "published",
            "thumbnail": "http://localhost:9300/medusa/poster-1669384266232.jpg",
            "profile_id": "sp_01GJ32VPZFXTW3A9PERCFSBHPG",
            "weight": 400,
            "length": null,
            "height": null,
            "width": null,
            "hs_code": null,
            "origin_country": null,
            "mid_code": null,
            "material": "",
            "collection_id": null,
            "type_id": null,
            "discountable": true,
            "external_id": null,
            "metadata": null,
            "bunnyVideoId": "408cc908-5bc2-4e16-ad58-633e5fc66c5e"
          }
        },
        "subtotal": 2500,
        "discount_total": 0,
        "total": 2500,
        "original_total": 2500,
        "original_tax_total": 0,
        "tax_total": 0
      }
    ],
    "payment": null,
    "shipping_address": null,
    "billing_address": null,
    "shipping_methods": [],
    "payment_sessions": [],
    "discounts": [],
    "created_at": "2023-01-13T15:37:10.728Z",
    "updated_at": "2023-01-13T15:37:10.728Z",
    "deleted_at": null,
    "email": "jimmy@jim.computer",
    "billing_address_id": null,
    "shipping_address_id": null,
    "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA",
    "customer_id": "cus_01GKBZ0FSPYXC54M0M2Q332SXP",
    "payment_id": null,
    "type": "default",
    "completed_at": null,
    "payment_authorized_at": null,
    "idempotency_key": null,
    "context": {
      "ip": "::ffff:127.0.0.1",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0"
    },
    "metadata": null,
    "shipping_total": 0,
    "subtotal": 2500,
    "discount_total": 0,
    "item_tax_total": 0,
    "shipping_tax_total": 0,
    "gift_card_total": 0,
    "gift_card_tax_total": 0,
    "tax_total": 0,
    "total": 2500
  }
}
```

</details>

I used the manual fulfillment provider. I tried to run the example frontend against my backend and that gave me the same error.

I'm using Medusa extender, so far I only added a single string field to the `Product` entity.

In my own investigation I attached a node debugger and noticed that the createPayments method of the stripe plugin seems to expect a `PaymentContext`, but the method is passed a `Cart` resource. The plugin then [sets amount to undefined](https://github.com/medusajs/medusa/blob/master/packages/medusa-payment-stripe/src/helpers/stripe-base.js#L110). 

<details>
<summary>Full context passed to `createPayment`</summary>

```
{
  "object": "cart",
  "id": "cart_01GPNY5H6XA23Z7B51WV1AA5SN",
  "items": [
    {
      "id": "item_01GPNY5HX2E918QE112NXPN74P",
      "created_at": "2023-01-13T16:07:23.446Z",
      "updated_at": "2023-01-13T16:07:25.547Z",
      "cart_id": "cart_01GPNY5H6XA23Z7B51WV1AA5SN",
      "order_id": null,
      "swap_id": null,
      "claim_order_id": null,
      "title": "Under a Sinking Sun",
      "description": "S",
      "thumbnail": "http://localhost:9300/medusa/poster-1669384266232.jpg",
      "is_return": false,
      "is_giftcard": false,
      "should_merge": true,
      "allow_discounts": true,
      "has_shipping": true,
      "unit_price": 2500,
      "variant_id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
      "quantity": 1,
      "fulfilled_quantity": null,
      "returned_quantity": null,
      "shipped_quantity": null,
      "metadata": {},
      "adjustments": [],
      "tax_lines": [
        {
          "rate": 0,
          "name": "default",
          "code": "default",
          "item_id": "item_01GPNY5HX2E918QE112NXPN74P"
        }
      ],
      "variant": {
        "id": "variant_01GJ32VQX6GRD4YM9T1ARXJC51",
        "created_at": "2022-11-17T15:21:03.261Z",
        "updated_at": "2023-01-13T14:47:19.400Z",
        "deleted_at": null,
        "title": "S",
        "product_id": "prod_01GJ32VQW6NZVC2TKX5Y31W8MB",
        "sku": null,
        "barcode": null,
        "ean": null,
        "upc": null,
        "inventory_quantity": 94,
        "allow_backorder": false,
        "manage_inventory": true,
        "hs_code": null,
        "origin_country": null,
        "mid_code": null,
        "material": null,
        "weight": null,
        "length": null,
        "height": null,
        "width": null,
        "metadata": null,
        "product": {
          "id": "prod_01GJ32VQW6NZVC2TKX5Y31W8MB",
          "created_at": "2022-11-17T15:21:03.261Z",
          "updated_at": "2022-12-01T14:53:03.110Z",
          "deleted_at": null,
          "title": "Under a Sinking Sun",
          "subtitle": "",
          "description": "redacted",
          "handle": "under-a-sinking-sun",
          "is_giftcard": false,
          "status": "published",
          "thumbnail": "http://localhost:9300/medusa/poster-1669384266232.jpg",
          "profile_id": "sp_01GJ32VPZFXTW3A9PERCFSBHPG",
          "weight": 400,
          "length": null,
          "height": null,
          "width": null,
          "hs_code": null,
          "origin_country": null,
          "mid_code": null,
          "material": "",
          "collection_id": null,
          "type_id": null,
          "discountable": true,
          "external_id": null,
          "metadata": null,
          "bunnyVideoId": "408cc908-5bc2-4e16-ad58-633e5fc66c5e"
        }
      },
      "subtotal": 2500,
      "discount_total": 0,
      "total": 2500,
      "original_total": 2500,
      "original_tax_total": 0,
      "tax_total": 0
    }
  ],
  "discounts": [],
  "gift_cards": [],
  "shipping_methods": [
    {
      "id": "sm_01GPNY5KQBNX6YTQVDQ6G74FN3",
      "shipping_option_id": "so_01GPNS68QZK5P04J7CDYEBS8X8",
      "order_id": null,
      "claim_order_id": null,
      "cart_id": "cart_01GPNY5H6XA23Z7B51WV1AA5SN",
      "swap_id": null,
      "return_id": null,
      "price": 0,
      "data": {},
      "tax_lines": [
        {
          "rate": 0,
          "name": "default",
          "code": "default",
          "shipping_method_id": "sm_01GPNY5KQBNX6YTQVDQ6G74FN3"
        }
      ],
      "shipping_option": {
        "id": "so_01GPNS68QZK5P04J7CDYEBS8X8",
        "created_at": "2023-01-13T14:40:24.793Z",
        "updated_at": "2023-01-13T14:46:58.217Z",
        "deleted_at": null,
        "name": "Email",
        "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA",
        "profile_id": "sp_01GJ32VPZFXTW3A9PERCFSBHPG",
        "provider_id": "email",
        "price_type": "calculated",
        "amount": null,
        "is_return": false,
        "admin_only": false,
        "data": {
          "id": "email-fulfillment"
        },
        "metadata": null
      },
      "original_total": 0,
      "total": 0,
      "subtotal": 0,
      "original_tax_total": 0,
      "tax_total": 0
    }
  ],
  "billing_address": null,
  "shipping_address": {
    "id": "addr_01GPNY5JYGFS71HTSRAQZ8159J",
    "created_at": "2023-01-13T16:07:25.269Z",
    "updated_at": "2023-01-13T16:07:25.269Z",
    "deleted_at": null,
    "customer_id": null,
    "company": "ACME inc",
    "first_name": "Jim",
    "last_name": "James",
    "address_1": "Street 1",
    "address_2": "Steet 2",
    "city": "Amsterdam",
    "country_code": "nl",
    "province": "North-Holland",
    "postal_code": "1234AB",
    "phone": "+31622222222",
    "metadata": null
  },
  "region": {
    "id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA",
    "created_at": "2022-11-17T15:21:03.261Z",
    "updated_at": "2022-11-17T15:21:03.261Z",
    "deleted_at": null,
    "name": "EU",
    "currency_code": "eur",
    "tax_rate": 0,
    "tax_code": null,
    "gift_cards_taxable": true,
    "automatic_taxes": true,
    "tax_provider_id": null,
    "metadata": null,
    "tax_rates": [],
    "payment_providers": [
      {
        "id": "stripe",
        "is_installed": true
      }
    ],
    "fulfillment_providers": [
      {
        "id": "email",
        "is_installed": true
      }
    ]
  },
  "payment_sessions": [],
  "customer": {
    "id": "cus_01GKBZ0FSPYXC54M0M2Q332SXP",
    "created_at": "2022-12-03T12:22:37.075Z",
    "updated_at": "2022-12-03T12:22:37.075Z",
    "deleted_at": null,
    "email": "jimmy@jim.computer",
    "first_name": "Jim",
    "last_name": "van der Voort",
    "billing_address_id": null,
    "phone": null,
    "has_account": true,
    "metadata": null
  },
  "created_at": "2023-01-13T16:07:23.446Z",
  "updated_at": "2023-01-13T16:07:25.269Z",
  "deleted_at": null,
  "email": "jimmy@jim.computer",
  "billing_address_id": null,
  "shipping_address_id": "addr_01GPNY5JYGFS71HTSRAQZ8159J",
  "region_id": "reg_01GJ32VQ3MKDYAAQ1JKD3GBFYA",
  "customer_id": "cus_01GKBZ0FSPYXC54M0M2Q332SXP",
  "payment_id": null,
  "type": "default",
  "completed_at": null,
  "payment_authorized_at": null,
  "idempotency_key": null,
  "context": {
    "ip": "::ffff:127.0.0.1",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0"
  },
  "metadata": null,
  "shipping_total": 0,
  "subtotal": 2500,
  "discount_total": 0,
  "item_tax_total": 0,
  "shipping_tax_total": 0,
  "gift_card_total": 0,
  "gift_card_tax_total": 0,
  "tax_total": 0,
  "total": 2500
}
```

</details>

Later `Math.round(amount)` with `amount = undefined` returns NaN.

I'm not sure how to trigger a flow where the proper type is passed to this method (or if that is possible), however I believe the Stripe plugin should handle this flow gracefully hence the bug report.

### Expected behavior

I expect the amount to be the `total` of my cart + shipping.

### Code snippets

See above

### Additional Context

Thank you for creating an awesome open source product! All other implementations have been smooth sailing and I'm developing with the manual payment plugin until I can get this fixed.

**Comment by chemicalkosek** [comment]
You must be either on stripe plugin `1.1.48` and whatever medusa version OR `1.1.50` and medusa version >= 1.7.1

**Comment by jimvandervoort** [comment]
Thank you for the reply, I see now that my server is indeed < 1.7.1 and stripe plugin is on 1.1.50. Upgrading resolved the issue.
