### ISSUE TITLE
Fresh installed project throws Uncaught QueryClient Exception

### ISSUE THREAD

**Issue by avido** [medusajs/medusa#3086]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Fresh installation of medusa project. After auth (with demo credentials) in /admin throws uncaught exception

Used `https://docs.medusajs.com/usage/create-medusa-app` 
Node version: `v16.19.0`
Host: `Mac os Ventura Version 13.0.1 (22A400)` 

```
Unhandled Thrown Error!
No QueryClient set, use QueryClientProvider to set one
Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient2 (http://localhost:7000/node_modules/.vite/deps/react-query.js?v=4eef96cf:2645:11)
    at useBaseQuery (http://localhost:7000/node_modules/.vite/deps/react-query.js?v=4eef96cf:2814:21)
    at useQuery (http://localhost:7000/node_modules/.vite/deps/react-query.js?v=4eef96cf:2888:10)
    at useAdminAnalyticsConfig (http://localhost:7000/src/services/analytics.ts:35:29)
    at AnalyticsProvider (http://localhost:7000/src/context/analytics.tsx:36:7)
    at renderWithHooks (http://localhost:7000/node_modules/.vite/deps/chunk-ZRYTYW4C.js?v=40bd5073:11763:26)
    at mountIndeterminateComponent (http://localhost:7000/node_modules/.vite/deps/chunk-ZRYTYW4C.js?v=40bd5073:14492:21)
    at beginWork (http://localhost:7000/node_modules/.vite/deps/chunk-ZRYTYW4C.js?v=40bd5073:15447:22)
    at beginWork$1 (http://localhost:7000/node_modules/.vite/deps/chunk-ZRYTYW4C.js?v=40bd5073:19248:22)
    at performUnitOfWork (http://localhost:7000/node_modules/.vite/deps/chunk-ZRYTYW4C.js?v=40bd5073:18693:20)
```

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Thanks for reporting the issue. We are working on solving it as we speak. 

Until we've published a new release, you can follow the `medusa-react` [upgrade guide](https://docs.medusajs.com/advanced/backend/upgrade-guides/medusa-react/4-0-2) to resolve your issues.

**Comment by olivermrbl** [comment]
Solved in [Admin #870](https://github.com/medusajs/admin/pull/870)

**Comment by codyaweber** [comment]
Just an FYI, this appears to be an issue in `4.0.4` as well. I followed the upgrade guide, but it only works for `medusa-react` `4.0.2` and `4.0.3`.

**Comment by kenchoong** [comment]
> upgrade guide

this is helpful. thanks
