### ISSUE TITLE
Variant deletion is not working 

### ISSUE THREAD

**Issue by andriinuts** [medusajs/medusa#3379]
### System information

Medusa version (including plugins): 1.7.11

### Describe the bug

deleting variants is not working, receiving error:
```error:   column ProductVariant__inventory_items.required_quantity does not exist
QueryFailedError: column ProductVariant__inventory_items.required_quantity does not exist
    at QueryFailedError.TypeORMError [as constructor] (C:\...\node_modules\typeorm\error\TypeORMError.js:9:28)
    at new QueryFailedError (C:\...\node_modules\typeorm\error\QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (C:\...\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:281:31)
    at step (C:\...\node_modules\tslib\tslib.js:144:27)
    at Object.throw (C:\...\node_modules\tslib\tslib.js:125:57)
    at rejected (C:\...\node_modules\tslib\tslib.js:116:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'SELECT DISTINCT "distinctAlias"."ProductVariant_id" as "ids_ProductVariant_id" FROM (SELECT "ProductVariant"."id" AS "ProductVariant_id", "ProductVariant"."created_at" AS "ProductVariant_created_at", "ProductVariant"."updated_at" AS "ProductVariant_updated_at", "ProductVariant"."deleted_at" AS "Pr
oductVariant_deleted_at", "ProductVariant"."title" AS "ProductVariant_title", "ProductVariant"."product_id" AS "ProductVariant_product_id", "ProductVariant"."sku" AS "ProductVariant_sku", "ProductVariant"."barcode" AS "ProductVariant_barcode", "ProductVariant"."ean" AS "ProductVariant_ean", "ProductVariant"
."upc" AS "ProductVariant_upc", "ProductVariant"."inventory_quantity" AS "ProductVariant_inventory_quantity", "ProductVariant"."allow_backorder" AS "ProductVariant_allow_backorder", "ProductVariant"."manage_inventory" AS "ProductVariant_manage_inventory", "ProductVariant"."hs_code" AS "ProductVariant_hs_cod
e", "ProductVariant"."origin_country" AS "ProductVariant_origin_country", "ProductVariant"."mid_code" AS "ProductVariant_mid_code", "ProductVariant"."material" AS "ProductVariant_material", "ProductVariant"."weight" AS "ProductVariant_weight", "ProductVariant"."length" AS "ProductVariant_length", "ProductVa
riant"."height" AS "ProductVariant_height", "ProductVariant"."width" AS "ProductVariant_width", "ProductVariant"."metadata" AS "ProductVariant_metadata", "ProductVariant__prices"."id" AS "ProductVariant__prices_id", "ProductVariant__prices"."created_at" AS "ProductVariant__prices_created_at", "ProductVarian
t__prices"."updated_at" AS "ProductVariant__prices_updated_at", "ProductVariant__prices"."deleted_at" AS "ProductVariant__prices_deleted_at", "ProductVariant__prices"."currency_code" AS "ProductVariant__prices_currency_code", "ProductVariant__prices"."amount" AS "ProductVariant__prices_amount", "ProductVari
ant__prices"."min_quantity" AS "ProductVariant__prices_min_quantity", "ProductVariant__prices"."max_quantity" AS "ProductVariant__prices_max_quantity", "ProductVariant__prices"."price_list_id" AS "ProductVariant__prices_price_list_id", "ProductVariant__prices"."variant_id" AS "ProductVariant__prices_variant
_id", "ProductVariant__prices"."region_id" AS "ProductVariant__prices_region_id", "ProductVariant__options"."id" AS "ProductVariant__options_id", "ProductVariant__options"."created_at" AS "ProductVariant__options_created_at", "ProductVariant__options"."updated_at" AS "ProductVariant__options_updated_at", "P
roductVariant__options"."deleted_at" AS "ProductVariant__options_deleted_at", "ProductVariant__options"."value" AS "ProductVariant__options_value", "ProductVariant__options"."option_id" AS "ProductVariant__options_option_id", "ProductVariant__options"."variant_id" AS "ProductVariant__options_variant_id", "P
roductVariant__options"."metadata" AS "ProductVariant__options_metadata", "ProductVariant__inventory_items"."id" AS "ProductVariant__inventory_items_id", "ProductVariant__inventory_items"."created_at" AS "ProductVariant__inventory_items_created_at", "ProductVariant__inventory_items"."updated_at" AS "Product
Variant__inventory_items_updated_at", "ProductVariant__inventory_items"."deleted_at" AS "ProductVariant__inventory_items_deleted_at", "ProductVariant__inventory_items"."inventory_item_id" AS "ProductVariant__inventory_items_inventory_item_id", "ProductVariant__inventory_items"."variant_id" AS "ProductVarian
t__inventory_items_variant_id", "ProductVariant__inventory_items"."required_quantity" AS "ProductVariant__inventory_items_required_quantity", "ProductVariant_pr1"."id" AS "ProductVariant_pr1_id", "ProductVariant_pr1"."created_at" AS "ProductVariant_pr1_created_at", "ProductVariant_pr1"."updated_at" AS "Prod
uctVariant_pr1_updated_at", "ProductVariant_pr1"."deleted_at" AS "ProductVariant_pr1_deleted_at", "ProductVariant_pr1"."title" AS "ProductVariant_pr1_title", "ProductVariant_pr1"."subtitle" AS "ProductVariant_pr1_subtitle", "ProductVariant_pr1"."description" AS "ProductVariant_pr1_description", "ProductVari
ant_pr1"."handle" AS "ProductVariant_pr1_handle", "ProductVariant_pr1"."is_giftcard" AS "ProductVariant_pr1_is_giftcard", "ProductVariant_pr1"."status" AS "ProductVariant_pr1_status", "ProductVariant_pr1"."thumbnail" AS "ProductVariant_pr1_thumbnail", "ProductVariant_pr1"."profile_id" AS "ProductVariant_pr1
_profile_id", "ProductVariant_pr1"."weight" AS "ProductVariant_pr1_weight", "ProductVariant_pr1"."length" AS "ProductVariant_pr1_length", "ProductVariant_pr1"."height" AS "ProductVariant_pr1_height", "ProductVariant_pr1"."width" AS "ProductVariant_pr1_width", "ProductVariant_pr1"."hs_code" AS "ProductVarian
t_pr1_hs_code", "ProductVariant_pr1"."origin_country" AS "ProductVariant_pr1_origin_country", "ProductVariant_pr1"."mid_code" AS "ProductVariant_pr1_mid_code", "ProductVariant_pr1"."material" AS "ProductVariant_pr1_material", "ProductVariant_pr1"."collection_id" AS "ProductVariant_pr1_collection_id", "Produ
ctVariant_pr1"."type_id" AS "ProductVariant_pr1_type_id", "ProductVariant_pr1"."discountable" AS "ProductVariant_pr1_discountable", "ProductVariant_pr1"."external_id" AS "ProductVariant_pr1_external_id", "ProductVariant_pr1"."metadata" AS "ProductVariant_pr1_metadata" FROM "product_variant" "ProductVariant"
 LEFT JOIN "money_amount" "ProductVariant__prices" ON "ProductVariant__prices"."variant_id"="ProductVariant"."id" AND ("ProductVariant__prices"."deleted_at" IS NULL)  LEFT JOIN "product_option_value" "ProductVariant__options" ON "ProductVariant__options"."variant_id"="ProductVariant"."id" AND ("ProductVaria
nt__options"."deleted_at" IS NULL)  LEFT JOIN "product_variant_inventory_item" "ProductVariant__inventory_items" ON "ProductVariant__inventory_items"."variant_id"="ProductVariant"."id" AND ("ProductVariant__inventory_items"."deleted_at" IS NULL)  LEFT JOIN "product" "ProductVariant_pr1" ON "ProductVariant_p
r1"."id"="ProductVariant"."product_id" AND ("ProductVariant_pr1"."deleted_at" IS NULL) WHERE ( "ProductVariant"."id" = $1 ) AND ( "ProductVariant"."deleted_at" IS NULL )) "distinctAlias" ORDER BY "ProductVariant_id" ASC LIMIT 1',
  parameters: [ 'variant_01GTPFY2M9GE60W8G82MGFHAA7' ],
  driverError: error: column ProductVariant__inventory_items.required_quantity does not exist
      at Parser.parseErrorMessage (C:\...\node_modules\pg-protocol\dist\parser.js:287:98)
      at Parser.handlePacket (C:\...\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (C:\...\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\...\node_modules\pg-protocol\dist\index.js:11:42)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 149,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '3411',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3651',
    routine: 'errorMissingColumn'
  },
  length: 149,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '3411',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3651',
  routine: 'errorMissingColumn'
}

**Comment by olivermrbl** [comment]
@andriinuts I can't seem to reproduce on the latest version. The `required_quantity` column on ProductVariants was introduced in [this migration](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/migrations/1671711415179-multi_location.ts). 

Did you maybe forget to run migrations?

**Comment by chemicalkosek** [comment]
@olivermrbl I have the same thing and I have ran migrations

**Comment by olivermrbl** [comment]
@chemicalkosek Got it! It seems the two of you have run the migrations before we added `required_quantity` in a follow-up iteration. @pKorsholm Can you advise on the next steps to resolve the issue? 

Also, we should probably look into adding a migration that takes care of this without having to alter the table directly in the DB.

**Comment by pKorsholm** [comment]
👍 

yeah the easiest fix rn is probably to just rename the column manually

```
ALTER TABLE product_variant_inventory_item RENAME COLUMN quantity TO required_quantity
```

I'll add in another migration to ensure this is always the case

**Comment by olivermrbl** [comment]
@chemicalkosek @andriinuts Can I get you to install `yarn add @medusajs/medusa@1.7.12-snapshot-20230308114821` and run migrations again? :)

**Comment by andriinuts** [comment]
this fix work, thx!
