### ISSUE TITLE
 [ERR_IPC_SYNC_FORK] when creating a NotificationProvider

### ISSUE THREAD

**Issue by TBenTiCon** [medusajs/medusa#3632]
### Describe the bug

Creating a Notification Provider causes an [ERR_IPC_SYNC_FORK] error.

### System information

Medusa version (including plugins): 1.8.0-rc.3
Node.js version: v16.19.1
Database: Postgres
Operating system: Mac OS

### Steps to reproduce the behavior

1. Follow the Documentation on how to create a NotificationProvider in the "services" Folder
2. Save the File
3. Error gets thrown and Medusa Crashes

### Error Message
`
Error [ERR_IPC_SYNC_FORK]: IPC cannot be used with synchronous forks
at new NodeError (node:internal/errors:387:5)
at node:internal/child_process:1034:17
at Array.reduce (<anonymous>)
at getValidStdio (node:internal/child_process:1000:11)
at spawnSync (node:child_process:820:19)
at execSync (node:child_process:927:15)
at FSWatcher.<anonymous> (/Users/ticianstreifeneder/WebstormProjects/ps-medusa-1.8/ps-md/node_modules/@medusajs/medusa/dist/commands/develop.js:127:46)
at FSWatcher.emit (node:events:513:28)
at FSWatcher.emitWithAll (/Users/ticianstreifeneder/WebstormProjects/ps-medusa-1.8/ps-md/node_modules/chokidar/index.js:540:8)
at FSWatcher._emit (/Users/ticianstreifeneder/WebstormProjects/ps-medusa-1.8/ps-md/node_modules/chokidar/index.js:632:8
{
 code: 'ERR_IPC_SYNC_FORK'
}
`

### Expected behavior
Medusa identifies the changes and reloads

### Additional Context / Information
The Problem was tested on the RC of 1.8 and the Last stable release of 1.7. It only happens on 1.8.

**Comment by olavurdj** [comment]
Are you by change running `medusa develop`? I am experiencing the same issue since 1.8, but it happens regardless of what kind of service or change it is - i.e. not specific to NotificationProvider. Seems like this crash occurs whenever the watcher detects any change.

**Comment by TBenTiCon** [comment]
> Are you by change running `medusa develop`? I am experiencing the same issue since 1.8, but it happens regardless of what kind of service or change it is - i.e. not specific to NotificationProvider. Seems like this crash occurs whenever the watcher detects any change.

Exactly! Im running the server via "medusa develop". But it seems the Notificationprovider doesnt work at all for me. Even when restarting the server, the Provider never gets executed. In 1.7 it worked flawlessly.

**Comment by kasperkristensen** [comment]
Fixed in #3633
