### ISSUE TITLE
After successful payment and calling cart.complete receiving 'ConnectionNotFoundError' error

### ISSUE THREAD

**Issue by rasmuslian** [medusajs/medusa#3734]
### Describe the bug

After updating to the whole new 1.8 system I'm unable to complete my cart after a successful payment with Stripe (I can see the order in Stripe as succeeded) . No order is created in Medusa, not even an uncompleted one. It gives me the following error:

```
error:   Connection "default" was not found.
ConnectionNotFoundError: Connection "default" was not found.
    at ConnectionManager.get (D:\Code\solsting-medusa-updated\backend\node_modules\typeorm\connection\ConnectionManager.js:43:19)
    at getConnection (D:\Code\solsting-medusa-updated\backend\node_modules\typeorm\globals.js:90:35)
    at D:\Code\solsting-medusa-updated\backend\node_modules\@medusajs\medusa\dist\utils\manual-auto-increment.js:72:62
    at step (D:\Code\solsting-medusa-updated\backend\node_modules\@medusajs\medusa\dist\utils\manual-auto-increment.js:33:23)
    at Object.next (D:\Code\solsting-medusa-updated\backend\node_modules\@medusajs\medusa\dist\utils\manual-auto-increment.js:14:53)
    at D:\Code\solsting-medusa-updated\backend\node_modules\@medusajs\medusa\dist\utils\manual-auto-increment.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Code\solsting-medusa-updated\backend\node_modules\@medusajs\medusa\dist\utils\manual-auto-increment.js:4:12)
    at manualAutoIncrement (D:\Code\solsting-medusa-updated\backend\node_modules\@medusajs\medusa\dist\utils\manual-auto-increment.js:64:12)
    at Order.<anonymous> (D:\Code\solsting-medusa-updated\backend\node_modules\@medusajs\medusa\dist\models\order.js:134:94)
```

It seems to somewhat be related to Typeorm (probably with the new version)? I could be wrong though. However I don't know how to proceed further. 

### System information

Medusa version (including plugins): ^1.8.0
Typeorm: ^0.3.11
medusa-payment-stripe: ^2.0.0
Node.js version: 16.15
Database: sqlite
Operating system: Windows
Browser (if relevant): Chromium

### Steps to reproduce the behavior

1. Checkout cart and receive successfull payment from Stripe (with the medusa-stripe-payments plugin)
2. Call 
```
medusa.carts.complete(cartId)
.then(({ type, data }) => {
  console.log(type, data)
})
```
3. Error shows

### Expected behavior

That medusa successfully completes the cart since payment has gone through.

### Additional context

Using `nuxt-medusa` package as wrapper around `@medusajs/medusa-js`

**Comment by olivermrbl** [comment]
Closing for now. Let me know, if this is not resolved :)

**Comment by rasmuslian** [comment]
> Closing for now. Let me know, if this is not resolved :)

This resolved the issue (for anyone in the future experiencing the same issue). Thanks and keep up the good work with the amazing platform!
