### ISSUE TITLE
`@medusajs/admin` Cannot read properties of undefined (reading 'featureToggleList')  

### ISSUE THREAD

**Issue by durdenx** [medusajs/medusa#3772]
### Describe the bug

I get the following error when starting medusa admin:

```
Unexpected Application Error!
Cannot read properties of undefined (reading 'featureToggleList')
```

```
caught TypeError: Cannot read properties of undefined (reading 'featureToggleList')
    at isFeatureEnabled (feature-flag-provider.tsx:9:13)
    at useAdminAnalyticsConfig (analytics.ts:81:16)
    at AnalyticsProvider (analytics-provider.tsx:13:39)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
```

### System information

Medusa version (including plugins): v1.8
Node.js version: v18
Database: postgres
Operating system: macos
Browser (if relevant): chrome

### Steps to reproduce the behavior

```sh
$ medusa-admin dev 
```
### Expected behavior

Medusa admin is starting without errors.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
@kasperkristensen Do you know what might cause this?

**Comment by abathellier** [comment]
I managed to get it to work. I misunderstood the documentation, I didn't understand that the admin app runs with medusa on the same server (http://localhost:9000/app).
