### ISSUE TITLE
Tried to try to install according to the instructions; Internal error: medusa-starter-default@workspace:.: It looks like this package is missing from your lock file; run "run installation" to update the lock file

### ISSUE THREAD

**Issue by UsVfxArtia** [medusajs/medusa#3790]
Performed the installation according to the instructions in the documentation https://docs.medusajs.com/create-medusa-app
Error in step 4, when trying to launch backend and storefront

my node -v - 18.13.0

storefront

```
Internal Error: medusa-next@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:435:5145)
    at xf.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:391:1264)
    at C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7693
    at ff (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:11070)
    at ge (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7673)
    at async Promise.allSettled (index 0)
    at async to (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:10398)
    at async C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:8205
    at async ti.startProgressPromise (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:47579)
    at async je.resolveEverything (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:6233)
```

backend

```
Internal Error: medusa-starter-default@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:435:5145)
    at xf.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:391:1264)
    at C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7693
    at ff (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:11070)
    at ge (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7673)
    at async Promise.allSettled (index 0)
    at async to (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:10398)
    at async C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:8205
    at async ti.startProgressPromise (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:47579)
    at async je.resolveEverything (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:6233)
```

**Comment by olivermrbl** [comment]
I am not entirely sure, what is happening here, but it looks like you are installing incorrect dependencies or something similar.

Can I get you to ensure, that you are in `[your-project-name]/backend` and `[your-project-name]/storefront` respectively when running the start and dev commands.

**Comment by UsVfxArtia** [comment]
> I am not entirely sure, what is happening here, but it looks like you are installing incorrect dependencies or something similar.
> 
> Can I get you to ensure, that you are in `[your-project-name]/backend` and `[your-project-name]/storefront` respectively when running the start and dev commands.

Yes, I did everything according to the instructions

**Comment by UsVfxArtia** [comment]
Installation phase
```
PS D:\medusa> npx create-medusa-app
√ Where should your project be installed? · medusastore
√ Which Medusa starter would you like to install? · medusa-starter-default
√ Which storefront starter would you like to install? · Next.js Starter
| Creating new project from git: https://github.com/medusajs/medusa-starter-default.git
√ Created starter directory layout

/ Installing packages...
√ Packages installed
Initialising git in medusastore\backend
Create initial git commit in medusastore\backend
\ Seeding database
> medusa-starter-default@0.0.1 seed
> medusa seed -f ./data/seed.json

[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
info:    Using fake Redis
warn:    Local Event Bus installed. This is not recommended for production.
warn:    You don't have any notification provider plugins installed. You may want to add one to your project.
warn:    You don't have any taxProviders provider plugins installed. You may want to add one to your project.
warn:    No search engine provider was found: make sure to include a search plugin to enable searching
/ Seeding database
√ Seed completed
/ Creating new project from git: https://github.com/medusajs/nextjs-starter-medusa.git
√ Created starter directory layout

\ Installing packages...
√ Packages installed
Initialising git in medusastore\storefront
Create initial git commit in medusastore\storefront

  Your project is ready 🚀. The available commands are:

    Medusa API
    cd medusastore/backend
    yarn start


    Storefront
    cd medusastore/storefront
    yarn dev

PS D:\medusa> 
```


ERROR 1
```
PS D:\medusa> cd medusastore/backend 
PS D:\medusa\medusastore\backend> yarn start
Internal Error: medusa-starter-default@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:435:5145)
    at xf.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:391:1264)
    at C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7693
    at ff (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:11070)
    at ge (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7673)
    at async Promise.allSettled (index 0)
    at async to (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:10398)
    at async C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:8205
    at async ti.startProgressPromise (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:47579)
    at async je.resolveEverything (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:6233)
PS D:\medusa\medusastore\backend> 
```

ERROR 2
```
PS D:\medusa> cd medusastore\storefront
PS D:\medusa\medusastore\storefront> yarn dev  
Internal Error: medusa-next@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:435:5145)
    at xf.getCandidates (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:391:1264)
    at C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7693
    at ff (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:11070)
    at ge (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7673)
    at async Promise.allSettled (index 0)
    at async to (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:10398)
    at async C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:8205
    at async ti.startProgressPromise (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:390:47579)
    at async je.resolveEverything (C:\Users\Breee\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:6233)
PS D:\medusa\medusastore\storefront> 
```

**Comment by olivermrbl** [comment]
Can you log (e.g. with `ls`) the content in `/storefront` and `/backend` and paste it here?

**Comment by olivermrbl** [comment]
@UsVfxArtia I belive this was fixed in [this PR](https://github.com/medusajs/medusa-starter-default/pull/44). Can I get you to incorporate those changes and try again?

Closing until then.
