### ISSUE TITLE
SQLITE Error when running `medusa migrations run` on newly project

### ISSUE THREAD

**Issue by IAmNatch** [medusajs/medusa#3833]
### Describe the bug
When running `medusa migrations run` on a newly generated project, the ORM returns the following error: 
```
query failed: CREATE TABLE "fulfillment" ("id" character varying NOT NULL, "swap_id" character varying, "order_id" character varying, "tracking_numbers" jsonb NOT NULL DEFAULT '[]', "data" jsonb NOT NULL, "shipped_at" TIMESTAMP WITH TIME ZONE, "canceled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metadata" jsonb, "idempotency_key" character varying, "provider_id" character varying, CONSTRAINT "PK_50c102da132afffae660585981f" PRIMARY KEY ("id"))
error: Error: SQLITE_ERROR: near "(": syntax error
query: ROLLBACK
QueryFailedError: SQLITE_ERROR: near "(": syntax error
    at new TypeORMError (/Users/shanerobbins/Code/experiments/medusa-migrations-repro/node_modules/typeorm/error/TypeORMError.js:9:9)
    at new QueryFailedError (/Users/shanerobbins/Code/experiments/medusa-migrations-repro/node_modules/typeorm/error/QueryFailedError.js:11:9)
    at handler (/Users/shanerobbins/Code/experiments/medusa-migrations-repro/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26)
    at replacement (/Users/shanerobbins/Code/experiments/medusa-migrations-repro/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/Users/shanerobbins/Code/experiments/medusa-migrations-repro/node_modules/sqlite3/lib/sqlite3.js:15:21) {
  query: `CREATE TABLE "fulfillment" ("id" character varying NOT NULL, "swap_id" character varying, "order_id" character varying, "tracking_numbers" jsonb NOT NULL DEFAULT '[]', "data" jsonb NOT NULL, "shipped_at" TIMESTAMP WITH TIME ZONE, "canceled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metadata" jsonb, "idempotency_key" character varying, "provider_id" character varying, CONSTRAINT "PK_50c102da132afffae660585981f" PRIMARY KEY ("id"))`,
  parameters: undefined,
  driverError: Error: SQLITE_ERROR: near "(": syntax error
  --> in Database#all(`CREATE TABLE "fulfillment" ("id" character varying NOT NULL, "swap_id" character varying, "order_id" character varying, "tracking_numbers" jsonb NOT NULL DEFAULT '[]', "data" jsonb NOT NULL, "shipped_at" TIMESTAMP WITH TIME ZONE, "canceled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metadata" jsonb, "idempotency_key" character varying, "provider_id" character varying, CONSTRAINT "PK_50c102da132afffae660585981f" PRIMARY KEY ("id"))`, undefined, [Function: handler])
      at execute (/Users/shanerobbins/Code/experiments/medusa-migrations-repro/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:62:46)
      at /Users/shanerobbins/Code/experiments/medusa-migrations-repro/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:103:19 {
    errno: 1,
    code: 'SQLITE_ERROR',
    __augmented: true
  },
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}
```

This issue prevents developers from creating new migrations, and is present before calling `--seed`

### System information

Medusa version (including plugins):
```
    "@medusajs/admin": "^2.0.0",
    "@medusajs/cache-inmemory": "^1.8.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-local": "^1.8.0",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/medusa": "^1.8.0",
    "@medusajs/medusa-cli": "^1.3.9",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^2.0.0",
```
Node.js version: v14.21.2
Database: sqlite
Operating system: Mac

### Steps to reproduce the behavior

1. medusa new medusa-migrations-repro
2. cd medusa-migrations-repro
3. medusa migrations run
4. experience SQL error

### Expected behavior
Migrations run as expected.

**Comment by olivermrbl** [comment]
@IAmNatch – when using SQLite, all you have to do is run `yarn seed`. That will prepare the database and add a couple of initial resources, allowing you to play around with your store immediately.

**Comment by IAmNatch** [comment]
@olivermrbl, this does work, however `medusa migrations run` will still not work after seeding. I believe this means cannot extend any existing models with new fields, or create new models/tables, etc, as they require a migration.

**Comment by tgdn** [comment]
@IAmNatch https://github.com/medusajs/medusa/pull/4026 may be of interest

**Comment by IAmNatch** [comment]
@tgdn Thanks for highlighting this!
