### ISSUE TITLE
Medusa Plugin Sendgrid is not working inside Docker

### ISSUE THREAD

**Issue by tunchunairarko** [medusajs/medusa#3908]
## Bug report

When I installed medusa-plugin-sendgrid inside Medusa, it works fine locally in both development and production without Docker, but whenever I use Docker (the Dockerfile from medusa-starter-default) for spinning up the backend, it crashes. I followed the official documentation for installing the plugin. Here is an example error log, by example I mean that I tried several approaches to ensure the proper installation and migration of medusa, still no luck. I also checked into the filesystem of docker, and found it was indeed installed successfully alongside the other packages, with the right medusa-config.js as well, but it still gave the following error on all attempts I made:

```
Error: Unable to find plugin "medusa-plugin-sendgrid". Perhaps you need to install its package?
2023-04-23 22:11:08     at resolvePlugin (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:634:15)
2023-04-23 22:11:08     at /app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:131:23
2023-04-23 22:11:08     at Array.map (<anonymous>)
2023-04-23 22:11:08     at getResolvedPlugins (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:127:28)
2023-04-23 22:11:08     at /app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:152:32
2023-04-23 22:11:08     at step (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
2023-04-23 22:11:08     at Object.next (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
2023-04-23 22:11:08     at /app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:8:71
2023-04-23 22:11:08     at new Promise (<anonymous>)
2023-04-23 22:11:08     at __awaiter (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:4:12)
2023-04-23 22:11:09 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System information

Medusa version (including plugins): 1.8.0
medusa-plugin-sendgrid: 1.3.9
Node.js version: 16.20.0
Database: postgresql
Operating system: Ubuntu (node Debian docker image)
Browser (if relevant): no

**Comment by olivermrbl** [comment]
@tunchunairarko the Dockerfile from `medusa-starter-default` is not battle-tested, so I wouldn't rely on it to work.

In fact, in the latest versions of the starter, we've removed all Docker-related files, because we don't have the resources and time to maintain a robust Docker setup.

Can I get you to seek help in Discord? I am sure someone is capable of getting you up and running in no time. Closing this for now, as we will not attend to a fix.

**Comment by tunchunairarko** [comment]
Hi,

In that case, it's fine. Thank you for your advice, we've already deployed successfully on AWS, initially we wanted to add the backend to an ECS cluster as a service, but now we've moved to an EBS node app instead. It's working fine.

**Comment by olivermrbl** [comment]
I'm happy to hear. Let me know if there's anything else I can help with :)
