### ISSUE TITLE
SQLITE_ERROR: cannot start a transaction within a transaction (during checkout)

### ISSUE THREAD

**Issue by gukii** [medusajs/medusa#3960]
### Describe the bug

A clear and concise description of what the bug is, which might be related to me not having notification, 

I m trying to checkout an order of a registered user. After filling in all fields for shipping address, I am getting this transaction error.

Please note I do not have the following installed:
- no notification plugin
- no taxProvider plugin (using systemTax provider in settings)
- no search engine provider
see below for console output of server startup

### System information

Medusa version (including plugins):
```
"@babel/preset-typescript": "^7.21.4",
    "@medusajs/admin": "^3.0.0",
    "@medusajs/cache-inmemory": "^1.8.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-local": "^1.8.0",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/medusa": "^1.8.0",
    "@medusajs/medusa-cli": "^1.3.9",
    "babel-preset-medusa-package": "^1.1.13",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^2.0.0",
    "typeorm": "^0.3.11"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.13",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "mongoose": "^5.13.14",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },
```
Node.js version: v16.14.0
Database: 
  sqlite3: 3.37.2 2022-01-06
  redis server v=7.0.11
  
Operating system: Ubuntu Release 22.04.2 LTS (Jammy Jellyfish) 64-bit
Browser (if relevant):  Brave Browser, Release Notes v1.50.125 (Apr 20, 2023) (Linux Only)

### Steps to reproduce the behavior

1) I created a new region for Taiwan. 
2) Set product prices for that region. 
3) And created a customer for that region. 
4) A flat-fee shipping option was created for this region.
4) Payment was set to "manual" per default settings of the frontend app.

5) The user logs in
6) Adds products to cart
7) Goes to cart and checks out (without discount, giftcard, etc.)
8) Enter Taiwan shipping address
9) Choose flat-fee shipping option
10) Checkout flow ends here. No success message..

### Expected behavior

Checkout the order using manual processor. The payment is done in cash or later by bank transfer.

### Screenshots
![Screenshot at 2023-04-30 10-30-19](https://user-images.githubusercontent.com/1658650/235333186-69c660ec-1e32-4072-a9eb-5163a28f7c97.png)
![Screenshot at 2023-04-30 10-27-09](https://user-images.githubusercontent.com/1658650/235333037-5019f9bb-ed3c-4f32-80c8-c7cdc6236eff.png)
![Screenshot at 2023-04-30 10-26-29](https://user-images.githubusercontent.com/1658650/235333039-6ccbf347-75ca-4860-9a7b-da7743765514.png)
![Screenshot at 2023-04-30 10-27-27](https://user-images.githubusercontent.com/1658650/235333036-29426a6a-57ec-4713-9e9c-99e7fb6b70e1.png)

### Console output of client and server:

**Console when starting the server:**

```
...
Successfully compiled 0 files with Babel (5ms).
info:    Connection to Redis established
✔ Models initialized – 38ms
✔ Plugin models initialized – 5ms
✔ Strategies initialized – 56ms
⠙ Initializing modules
info:    Connection to Redis in module 'event-bus-redis' established
✔ Modules initialized – 92ms
✔ Database initialized – 1383ms
✔ Repositories initialized – 76ms
✔ Services initialized – 25ms
✔ Express intialized – 20ms
✔ Plugins intialized – 409ms
✔ Subscribers initialized – 30ms
✔ API initialized – 162ms
⠋ Initializing defaults
warn:    You don't have any notification provider plugins installed. You may want to add one to your project.
warn:    You don't have any taxProviders provider plugins installed. You may want to add one to your✔ Defaults initialized – 125ms
⠋ Initializing search engine indexing
warn:    No search engine provider was found: make sure to include a search plugin to enable searchi✔ Indexing event emitted – 20ms
✔ Server is ready on port: 9000 – 33ms
```

**Console of the client when adding an item and pressing CHECKOUT**
```

::1 - - [30/Apr/2023:02:33:15 +0000] "GET /store/customers/me HTTP/1.1" 401 - "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:15 +0000] "GET /store/collections?offset=0 HTTP/1.1" 304 - "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:15 +0000] "GET /store/collections HTTP/1.1" 304 - "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
error:   SQLITE_ERROR: cannot start a transaction within a transaction
QueryFailedError: SQLITE_ERROR: cannot start a transaction within a transaction
    at Statement.handler (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26)
    at Statement.replacement (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.replacement (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/sqlite3/lib/trace.js:25:27) {
  query: 'BEGIN TRANSACTION',
  parameters: undefined,
  driverError: Error: SQLITE_ERROR: cannot start a transaction within a transaction
  --> in Statement#all(undefined, [Function: replacement])
      at Database.<anonymous> (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/sqlite3/lib/sqlite3.js:88:19)
      at Database.<anonymous> (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/sqlite3/lib/sqlite3.js:20:19)
      at execute (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:62:46)
      at /home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:103:19 {
    errno: 1,
    code: 'SQLITE_ERROR',
    __augmented: true
  },
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}
::1 - - [30/Apr/2023:02:33:15 +0000] "GET /store/products?id%5B0%5D=prod_01GZ0A39GQ8NVH5GX8SAW8XD4D&id%5B1%5D=prod_01GZ0A39GQ8NVH5GX8SAW8XD4D&cart_id=cart_01GZ2VMHGJ5E6E9F02CDATCJGA HTTP/1.1" 500 86 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
error:   Transaction is not started yet, start transaction before committing or rolling it back.
TransactionNotStartedError: Transaction is not started yet, start transaction before committing or rolling it back.
    at SqliteQueryRunner.commitTransaction (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/typeorm/driver/sqlite-abstract/AbstractSqliteQueryRunner.js:92:19)
    at EntityManager.transaction (/home/santa/code/alpha/react/medusa/my-medusa-store/backend/node_modules/typeorm/entity-manager/EntityManager.js:74:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
::1 - - [30/Apr/2023:02:33:15 +0000] "GET /store/products?is_giftcard=false&limit=4&cart_id=cart_01GZ2VMHGJ5E6E9F02CDATCJGA HTTP/1.1" 409 148 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:16 +0000] "GET /store/products?is_giftcard=false&limit=4&cart_id=cart_01GZ2VMHGJ5E6E9F02CDATCJGA HTTP/1.1" 200 27440 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:16 +0000] "GET /store/customers/me HTTP/1.1" 401 - "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:16 +0000] "GET /store/products?id%5B0%5D=prod_01GZ0A39GQ8NVH5GX8SAW8XD4D&id%5B1%5D=prod_01GZ0A39GQ8NVH5GX8SAW8XD4D&cart_id=cart_01GZ2VMHGJ5E6E9F02CDATCJGA HTTP/1.1" 200 7642 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:21 +0000] "OPTIONS /store/carts/cart_01GZ2VMHGJ5E6E9F02CDATCJGA/line-items/item_01GZ2VPEY3W0ME9HBP0SSCHA3Z HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
WARN: withTransaction called without custom implementation
::1 - - [30/Apr/2023:02:33:21 +0000] "POST /store/carts/cart_01GZ2VMHGJ5E6E9F02CDATCJGA/line-items/item_01GZ2VPEY3W0ME9HBP0SSCHA3Z HTTP/1.1" 200 9024 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:25 +0000] "GET /store/customers/me HTTP/1.1" 401 - "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:25 +0000] "GET /store/shipping-options/cart_01GZ2VMHGJ5E6E9F02CDATCJGA HTTP/1.1" 304 - "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [30/Apr/2023:02:33:26 +0000] "GET /store/customers/me HTTP/1.1" 401 - "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"

```

***medusa-config.js**

```
const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

const DATABASE_TYPE = process.env.DATABASE_TYPE || "sqlite";
const DATABASE_URL = process.env.DATABASE_URL || "postgres://localhost/medusa-store";
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  // To enable the admin plugin, uncomment the following lines and run `yarn add @medusajs/admin`
   {
     resolve: "@medusajs/admin",
     /** @type {import('@medusajs/admin').PluginOptions} */
     options: {
       autoRebuild: true,
     },
   },
];

const modules = {
  eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: "127.0.0.1:6379"
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: "127.0.0.1:6379"
    }
  },
}

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  database_database: "./medusa-db.sql",
  database_type: DATABASE_TYPE,
  store_cors: STORE_CORS,
  admin_cors: ADMIN_CORS,
  // Uncomment the following lines to enable REDIS
  redis_url: REDIS_URL
}

if (DATABASE_URL && DATABASE_TYPE === "postgres") {
  projectConfig.database_url = DATABASE_URL;
  delete projectConfig["database_database"];
}


/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
	modules,
};
```

**Comment by olivermrbl** [comment]
@gukii SQLite does not handle concurrent write transactions very well. I recommend changing your configuration to use Postgres. This is also what we recommend for a production environment.
