### ISSUE TITLE
Complete checkout don't work with get started basic example store

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#4011]
### Describe the bug

Completing cart with default get started example results in error.

Backend:

```
::1 - - [03/May/2023:14:54:57 +0000] "OPTIONS /store/carts/cart_01GZH1PBHX37YMJJH5A2GM2VX1/complete HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
WARN: withTransaction called without custom implementation
WARN: withTransaction called without custom implementation
WARN: withTransaction called without custom implementation
error:   Connection "default" was not found.
ConnectionNotFoundError: Connection "default" was not found.
    at ConnectionManager.get (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/typeorm/connection/ConnectionManager.js:43:19)
    at getConnection (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/typeorm/globals.js:90:35)
    at /Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/@medusajs/medusa/dist/utils/manual-auto-increment.js:72:62
    at step (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/@medusajs/medusa/dist/utils/manual-auto-increment.js:33:23)
    at Object.next (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/@medusajs/medusa/dist/utils/manual-auto-increment.js:14:53)
    at /Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/@medusajs/medusa/dist/utils/manual-auto-increment.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/@medusajs/medusa/dist/utils/manual-auto-increment.js:4:12)
    at manualAutoIncrement (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/@medusajs/medusa/dist/utils/manual-auto-increment.js:64:12)
    at Order.<anonymous> (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/@medusajs/medusa/dist/models/order.js:134:94)
::1 - - [03/May/2023:14:54:57 +0000] "POST /store/carts/cart_01GZH1PBHX37YMJJH5A2GM2VX1/complete HTTP/1.1" 500 86 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::1 - - [03/May/2023:14:55:05 +0000] "OPTIONS /store/carts/cart_01GZH1PBHX37YMJJH5A2GM2VX1/complete HTTP/1.1" 204 0 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
WARN: withTransaction called without custom implementation
WARN: withTransaction called without custom implementation
error:   SQLITE_CONSTRAINT: UNIQUE constraint failed: payment.cart_id
QueryFailedError: SQLITE_CONSTRAINT: UNIQUE constraint failed: payment.cart_id
    at Statement.handler (/Users/vladimirpekez/Projects/my-medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26) {
  query: `INSERT INTO "payment"("id", "created_at", "updated_at", "swap_id", "cart_id", "order_id", "amount", "currency_code", "amount_refunded", "provider_id", "data", "captured_at", "canceled_at", "metadata", "idempotency_key") VALUES (?, datetime('now'), datetime('now'), NULL, ?, NULL, 6850, ?, 0, ?, ?, NULL, NULL, NULL, NULL)`,
  parameters: [
    'pay_01GZH1R6GRWKD96157D66TS5RV',
    'cart_01GZH1PBHX37YMJJH5A2GM2VX1',
    'eur',
    'manual',
    '{"status":"authorized"}'
  ],
  driverError: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: payment.cart_id] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT'
  },
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}

```

I have attached FE screenshot as well.

### System information

Medusa version: 1.8.0
Node.js version: 16
Database: SQLite
Operating system: Mac OS X Ventura
Browser (if relevant): latest chrome (not relevant)

### Steps to reproduce the behavior

1. Install medusa by following get started guide
2. Add item(s) to cart
3. Try to complete the checkout

**Comment by vladimirpekez** [comment]
![image](https://user-images.githubusercontent.com/4521621/236127854-9c398eb1-a0e2-4ca3-83c9-393dd4928901.png)

**Comment by olivermrbl** [comment]
This seems to be an issue related to sqlite. Can I get you to set up postgres and try again?

Only requires a couple of steps:
```
1. update .env DATABASE_TYPE to postgres
2. create a database locally called `medusa-store`
3. seed your db by running `yarn seed`
4. start your server `yarn start`
```

**Comment by nikhil-1911** [comment]
> ![image](https://user-images.githubusercontent.com/4521621/236127854-9c398eb1-a0e2-4ca3-83c9-393dd4928901.png)

I am also facing the same issue and I am using sqlite as my database

**Comment by gubarez** [comment]
Same here. Version 1.10.0

**Comment by vladimirpekez** [comment]
@olivermrbl Thanks for the workaround instructions. I have managed to create the order with postgres.

**Comment by vladimirpekez** [comment]
@olivermrbl After completing the payment and fulfillment, the order is still in pending status.

Is this expected behavior? What should I do to complete the order.

`{"order":{"id":"order_01GZKWG5CJ86AK30YFZ3RWZXY2","status":"pending","fulfillment_status":"fulfilled","payment_status":"captured", ...`

**Comment by nikhil-1911** [comment]
@olivermrbl It worked for me after changing database to postgres.

**Comment by vladimirpekez** [comment]
@nikhil-1911 

Can you please test the order completion as well on your quick start instance as well? Should order remain in processing (pending) status after payment and fulfilment is complete? Is this expected behaviour, bug or am I missing a step that I should perform to complete the order?

![image](https://user-images.githubusercontent.com/4521621/236397166-ded70ca3-c4a9-40c8-a429-2ff0898b1469.png)

**Comment by olivermrbl** [comment]
@vladimirpekez – the order remains in the processing state by default. If you want to flip the order status, add a subscriber to an event of your choosing and update it using the OrderService.
