### ISSUE TITLE
Deleting EU region throws "not found (JS error)" and causes stacktrace on Store Front

### ISSUE THREAD

**Issue by gamesguru** [medusajs/medusa#4088]
### Describe the bug

Created a fresh postgres database with seed.

But then in the admin panel when I attempt to delete the `EU` region, it apparently succeeds, only to have the following logs in the back end and presenting the following error when refreshing the front end.

```text
May 12 16:36:40 vps16 npm[375374]: ::ffff:127.0.0.1 - - [12/May/2023:16:36:40 +0000] "DELETE /admin/regions/reg_01H08CQPEZ3D1WTBWV38KS91RJ HTTP/1.0" 200 72 "https://store-api.nutra.tk/app/a/settings/regions/reg_01H08CQPEZ3D1WTBWV38KS91RJ" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
May 12 16:36:40 vps16 npm[375374]: ::ffff:127.0.0.1 - - [12/May/2023:16:36:40 +0000] "GET /admin/regions HTTP/1.0" 200 757 "https://store-api.nutra.tk/app/a/settings/regions/reg_01H08CQPEZ3D1WTBWV38KS91RJ" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
May 12 16:36:40 vps16 npm[375374]: error:   Region with reg_01H08CQPEZ3D1WTBWV38KS91RJ was not found
May 12 16:36:40 vps16 npm[375374]: Error: Region with reg_01H08CQPEZ3D1WTBWV38KS91RJ was not found
May 12 16:36:40 vps16 npm[375374]:     at RegionService.<anonymous> (/home/gg/store/backend/node_modules/@medusajs/medusa/dist/services/region.js:552:35)
May 12 16:36:40 vps16 npm[375374]:     at step (/home/gg/store/backend/node_modules/@medusajs/medusa/dist/services/region.js:59:23)
May 12 16:36:40 vps16 npm[375374]:     at Object.next (/home/gg/store/backend/node_modules/@medusajs/medusa/dist/services/region.js:40:53)
May 12 16:36:40 vps16 npm[375374]:     at fulfilled (/home/gg/store/backend/node_modules/@medusajs/medusa/dist/services/region.js:31:58)
May 12 16:36:40 vps16 npm[375374]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
May 12 16:36:40 vps16 npm[375374]:   type: 'not_found',
May 12 16:36:40 vps16 npm[375374]:   code: undefined,
May 12 16:36:40 vps16 npm[375374]:   date: 2023-05-12T16:36:40.465Z
May 12 16:36:40 vps16 npm[375374]: }
May 12 16:36:40 vps16 npm[375374]: ::ffff:127.0.0.1 - - [12/May/2023:16:36:40 +0000] "GET /admin/regions/reg_01H08CQPEZ3D1WTBWV38KS91RJ HTTP/1.0" 404 89 "https://store-api.nutra.tk/app/a/settings/regions/reg_01H08CQPEZ3D1WTBWV38KS91RJ" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
May 12 16:36:41 vps16 npm[375374]: info:    Processing region.deleted which has 0 subscribers
```

And then when I refresh the store front end something appears very broken.

**NOTE:** This can be fixed by the following (which suggests the seeded data does not entirely "play well" with the server). Is there any guidance on the best way to start a store from scratch? What order the tables need to be inserted in? If the seeded data causes issues, I would consider we should not use it.

```psql
UPDATE REGION SET deleted_at=NULL WHERE name='EU';
```

```text
May 12 16:41:08 vps16 npm[375374]: ::ffff:127.0.0.1 - - [12/May/2023:16:41:08 +0000] "GET /store/regions HTTP/1.0" 200 725 "https://store.nutra.tk/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
May 12 16:41:08 vps16 npm[375374]: ::ffff:127.0.0.1 - - [12/May/2023:16:41:08 +0000] "GET /store/carts/cart_01H08CS23WDNA4ZZZR72V2VQRK HTTP/1.0" 200 1197 "https://store.nutra.tk/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
May 12 16:41:09 vps16 npm[375374]: error:   Cannot read properties of null (reading 'currency_code')
May 12 16:41:09 vps16 npm[375374]: TypeError: Cannot read properties of null (reading 'currency_code')
May 12 16:41:09 vps16 npm[375374]:     at /home/gg/store/backend/node_modules/@medusajs/medusa/dist/api/routes/store/products/list-products.js:321:68
May 12 16:41:09 vps16 npm[375374]:     at step (/home/gg/store/backend/node_modules/@medusajs/medusa/dist/api/routes/store/products/list-products.js:68:23)
May 12 16:41:09 vps16 npm[375374]:     at Object.next (/home/gg/store/backend/node_modules/@medusajs/medusa/dist/api/routes/store/products/list-products.js:49:53)
May 12 16:41:09 vps16 npm[375374]:     at fulfilled (/home/gg/store/backend/node_modules/@medusajs/medusa/dist/api/routes/store/products/list-products.js:40:58)
May 12 16:41:09 vps16 npm[375374]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
May 12 16:41:09 vps16 npm[375374]: ::ffff:127.0.0.1 - - [12/May/2023:16:41:09 +0000] "GET /store/products?limit=12&offset=0&cart_id=cart_01H08CS23WDNA4ZZZR72V2VQRK&is_giftcard=false HTTP/1.0" 500 86 "https://store.nutra.tk/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
```
![image](https://github.com/medusajs/medusa/assets/30691680/c7f554e0-b457-4179-a508-aa990e7d77da)

### System information

Medusa version (including plugins): 1.10.0
Node.js version: 18
Database: Postgres
Operating system: Ubuntu 22.04 (Linux)
Browser (if relevant):

**Comment by pevey** [comment]
You likely have all sorts of stuff from the seed data still tied to that region, and now it can't be found because it was deleted.  If you don't want that region, you are better off restarting fresh without the seed data.

**Comment by gamesguru** [comment]
How can I log in to the admin panel without seeding a user?

Is the admin panel even a recommended best practice for setting up products, regions, shipment methods, etc. Or is there a way to do it directly in the database or with CSV saved files?

**Comment by pevey** [comment]
medusa user -e some@email.com -p some-password

**Comment by pevey** [comment]
depending on your setup, you may need to add npx at the beginning.

**Comment by gamesguru** [comment]
Ok. That seems like the better way to go. Some of this could be better documented perhaps.

The admin panel seems reliable for basic functions (viewing orders, etc) but it has some usability issues in edge cases like this.

**Comment by gamesguru** [comment]
When adding the user against an empty schema / database, i get the following errors and then it exits.

```text
$ npx medusa user -e ...
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
info:    Using fake Redis
✔ Models initialized – 58ms
✔ Plugin models initialized – 8ms
✔ Strategies initialized – 65ms
⠋ Initializing modules
✔ Modules initialized – 12ms
✔ Database initialized – 176ms
✔ Repositories initialized – 57ms
✔ Services initialized – 134ms
✔ Express intialized – 16ms
⠙ Initializing plugins
QueryFailedError: relation "staged_job" does not exist
    at PostgresQueryRunner.query (/home/gg/store/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/home/gg/store/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/gg/store/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
    at async SelectQueryBuilder.getRawAndEntities (/home/gg/store/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/home/gg/store/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25) {
  query: 'SELECT "StagedJob"."id" AS "StagedJob_id", "StagedJob"."event_name" AS "StagedJob_event_name", "StagedJob"."data" AS "StagedJob_data", "StagedJob"."options" AS "StagedJob_options" FROM "staged_job" "StagedJob" LIMIT 1000',
✔ Plugins intialized – 523ms
✔ Subscribers initialized – 33ms
✔ API initialized – 261ms
⠋ Initializing defaults
QueryFailedError: relation "country" does not exist
    at PostgresQueryRunner.query (/home/gg/store/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/home/gg/store/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeCountQuery (/home/gg/store/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1706:25)
    at async SelectQueryBuilder.getCount (/home/gg/store/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:770:29) {
  query: 'SELECT COUNT(1) AS "cnt" FROM "country" "Country"',
  parameters: [],
  driverError: error: relation "country" does not exist
      at Parser.parseErrorMessage (/home/gg/store/backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/gg/store/backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/gg/store/backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/gg/store/backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
```

**Comment by pevey** [comment]
Try stopping the server and doing `medusa migrations run`

That is the first thing I try after any db error like that.

**Comment by pevey** [comment]
On this page, on the sidebar, under Backend Setup, make sure you do the things on all 3 pages, not just the first page.  On the 3rd page, Configurations, it tells you about setting up the db.

https://docs.medusajs.com/development/backend/configurations

**Comment by gamesguru** [comment]
That definitely created a bunch of tables and after creating a region, I was able to view the shop without any errors. Thanks!

I guess the big things for me now are attaching my paypal client_id and stuff, and also getting `postfix` or something connected so the emails for password resets and such are actually getting sent.

**Comment by pevey** [comment]
Congrats.  I suggest joining the Medusa Discord community if you haven't already. It's pretty active and a good place to ask questions and get pointers.  https://discord.com/invite/medusajs

**Comment by gamesguru** [comment]
Ok I did. I will try asking questions and lurking around there.

Now the problem is it won't load payments or shipments on the checkout page (even tho I added shipping to the region).

![image](https://github.com/medusajs/medusa/assets/30691680/392ad5ce-cf1e-4f7a-95a3-6a8fb58212bd)

**Comment by pevey** [comment]
Medusa provides building blocks for developers who would otherwise probably build a system from scratch.  It's for people who want that level of control, putting in each piece of the puzzle they need and nothing they don't.

Translation: You need to configure your payment and fulfillment solutions of choice.

I suggest closing this issue so as not to distract the developers, and ask your questions of other users in Discord after reading through the documentation on medusajs.com.  Medusa's documentation is very good and is improved upon almost daily.
