### ISSUE TITLE
404 Page not found after placing the order.

### ISSUE THREAD

**Issue by Dakai** [medusajs/medusa#4111]
### Describe the bug

A new Medusa Store was just setup, when testing with the PayPal sandbox account, the store shows a 404 Page not found Error after payment, the backend outputs:

```
⠹ Creating servererror:   Order with id,cart_01H0HX9NYXTYJWRKYFBXCDD7KH: 0 was not found
Error: Order with id,cart_01H0HX9NYXTYJWRKYFBXCDD7KH: 0 was not found
    at OrderService.<anonymous> (/home/user/store/backend/node_modules/@medusajs/medusa/dist/services/order.js:372:35)
    at step (/home/user/store/backend/node_modules/@medusajs/medusa/dist/services/order.js:59:23)
    at Object.next (/home/user/store/backend/node_modules/@medusajs/medusa/dist/services/order.js:40:53)
    at fulfilled (/home/user/store/backend/node_modules/@medusajs/medusa/dist/services/order.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'not_found',
  code: undefined,
  date: 2023-05-16T09:23:11.275Z
}
```

### System information

Medusa version (including plugins):
- Medusa 1.3.12
- medusajs/medusa: ^1.8.0
- medusajs/medusa-cli: ^1.3.9
- medusa-payment-paypal: ^4.0.1 
Node.js version: v19.9.0
Database:
- PostgreSQL 15.2
Operating system:
- Arch Linux
Browser (if relevant):
- Microsoft Edge

### Expected behavior

Shows the order confirmation page.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Just tested the payment process with both the Manual providers of payment and fulfillment, the order confirmation page showed.

**Comment by Dakai** [comment]
Turns out there is an error in my fulfillment code that caused this error:
```
 createFulfillment() {
    // No data is being sent anywhere
    return Promise.resolve()
  }
```
There should be an pair of brackets inside the resolve(), correct code:
```
return Promise.resolve({})
```
