### ISSUE TITLE
error:   provider.retrieveSavedMethods is not a function

### ISSUE THREAD

**Issue by winston0410** [medusajs/medusa#4224]
## Bug report

I bumped into this error, when I tried to call `/store/customers/me/payment-methods`, and getting `error:   provider.retrieveSavedMethods is not a function`

### Describe the bug

```
::ffff:127.0.0.1 - - [31/May/2023:11:50:07 +0000] "GET /store/auth HTTP/1.1" 200 334 "-" "undici"
error:   provider.retrieveSavedMethods is not a function
TypeError: provider.retrieveSavedMethods is not a function
    at /Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:107:67
    at step (/Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:33:23)
    at Object.next (/Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:14:53)
    at /Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:4:12)
    at /Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:101:107
    at Array.map (<anonymous>)
    at /Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:101:67
    at step (/Users/xxx/Desktop/medusa/backend/node_modules/@medusajs/medusa/dist/api/routes/store/customers/get-payment-methods.js:33:23)
::ffff:127.0.0.1 - - [31/May/2023:11:50:07 +0000] "GET /store/customers/me/payment-methods HTTP/1.1" 500 86 "-" "undici"
```

### System information

Medusa version (including plugins): 1.12.0, medusa-payment-stripe: "6.0.0",
Node.js version: 16
Database: postgres
Operating system: macos
Browser (if relevant):

NPM version:

```json
  "dependencies": {
    "@babel/preset-typescript": "7.21.5",
    "@medusajs/cache-redis": "1.8.7",
    "@medusajs/event-bus-redis": "1.8.7",
    "@medusajs/medusa": "1.12.0",
    "@medusajs/medusa-cli": "1.3.15",
    "babel-preset-medusa-package": "1.1.19",
    "body-parser": "1.20.2",
    "cors": "2.8.5",
    "express": "4.18.2",
    "medusa-file-s3": "1.2.0",
    "medusa-fulfillment-manual": "1.1.37",
    "medusa-interfaces": "1.3.7",
    "medusa-payment-manual": "1.0.23",
    "medusa-payment-stripe": "6.0.0",
    "medusa-plugin-meilisearch": "2.0.7",
    "typeorm": "0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "7.21.5",
    "@babel/core": "7.22.1",
    "@types/express": "4.17.17",
    "@types/jest": "29.5.1",
    "@types/node": "20.2.5",
    "babel-preset-medusa-package": "1.1.19",
    "cross-env": "7.0.3",
    "eslint": "8.41.0",
    "jest": "29.5.0",
    "rimraf": "5.0.1",
    "ts-jest": "29.1.0",
    "ts-loader": "9.4.3",
    "typescript": "5.0.4"
  },
```

### Steps to reproduce the behavior

- 1. login and create a session
- 2 Use the `connect.sid` cookie and call `GET /store/customers/me/payment-methods`

### Expected behavior

I expect I can get all payment methods from `GET /store/customers/me/payment-methods` without error

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
