### ISSUE TITLE
create-medusa-app not working

### ISSUE THREAD

**Issue by david-adewoyin** [medusajs/medusa#4323]
### Describe the bug
npm create medusa-app returning error, i trying to create my first store, and while the create medusa-app successfully create a backend  folder, it doesnt create the storefront but returns an error.

### System information

Medusa version (including plugins): 1.3.15
Node.js version: 19.0.0
Database: postgres
Operating system: linux
Browser (if relevant):

### Steps to reproduce the behavior

1. npm create medusa-app
2. choose Next.js Starter

### Expected behavior
Medusa should create both a backend and a storefront for me

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets
```
  create-medusa-app@0.0.10
Ok to proceed? (y) y
(##################) ⠏ reify:@babel/runtime: timing reifyNode:node_modules/create-medusa-a(##################) ⠋ reify:@babel/runtime: timing reifyNode:node_modules/create-medusa-a
? Where should your project be
✔ Where should your project be installed? · my-medusa-store
✔ Which Medusa starter would you like to install? · medusa-starter-default
✔ Which storefront starter would you like to install? · Next.js Starter
⠇ Creating new project from git: https://github.com/medusajs/medusa-starter-default.git
✔ Created starter directory layout

⠦ Installing packages...
✔ Packages installed
Error: Command was killed with SIGTERM (Termination): npm install
    at gt (/home/codespace/.npm/_npx/97f955c160668ccc/node_modules/create-medusa-app/dist/index.js:1:113620)
    at /home/codespace/.npm/_npx/97f955c160668ccc/node_modules/create-medusa-app/dist/index.js:1:123343
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async js (/home/codespace/.npm/_npx/97f955c160668ccc/node_modules/create-medusa-app/dist/index.js:1:183921)
    at async /home/codespace/.npm/_npx/97f955c160668ccc/node_modules/create-medusa-app/dist/index.js:1:185433
    at async Is (/home/codespace/.npm/_npx/97f955c160668ccc/node_modules/create-medusa-app/dist/index.js:1:184931)
    at async exports.run (/home/codespace/.npm/_npx/97f955c160668ccc/node_modules/create-medusa-app/dist/index.js:1:498272) {
  shortMessage: 'Command was killed with SIGTERM (Termination): npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: undefined,
  signal: 'SIGTERM',
  signalDescription: 'Termination',
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by pevey** [comment]
Do you get the same result with node v18? I don’t know that compatibility with v19 is confirmed.

**Comment by david-adewoyin** [comment]
It works perfectly with node v18, thank you.
