### ISSUE TITLE
SendGrid plugin references this.transporter_ which is never assigned.

### ISSUE THREAD

**Issue by ripvannwinkler** [medusajs/medusa#4522]
### Describe the bug

Installing and attempting to use the `medusa-plugin-sendgrid` plugin throws an error such as:

```
TypeError: Cannot read properties of undefined (reading 'sendMail')
    at SendGridService._callee3$ (D:\myproject\node_modules\medusa-plugin-sendgrid\services\sendgrid.js:441:42)
    at tryCatch (D:\myproject\node_modules\medusa-plugin-sendgrid\services\sendgrid.js:28:2407)
    at Generator._invoke (D:\myproject\node_modules\medusa-plugin-sendgrid\services\sendgrid.js:28:1967)
    at Generator.next (D:\myproject\node_modules\medusa-plugin-sendgrid\services\sendgrid.js:28:3258)
    at asyncGeneratorStep (D:\myproject\node_modules\medusa-plugin-sendgrid\services\sendgrid.js:30:103)
    at _next (D:\myproject\node_modules\medusa-plugin-sendgrid\services\sendgrid.js:32:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Looking at [this commit](https://github.com/medusajs/medusa/commit/f65a501da5101da75217a2b69a61ccd4fd3a3b4d) @ line 256, it looks like this was changed recently, but I don't see where `this.transporter_` is assigned to the SendGrid api. Perhaps this is an oversight, or am I missing something?

### System information

Medusa version (including plugins): 1.12.1
Node.js version: 16.20.0
Database: postgres
Operating system: Windows 11
Browser (if relevant):

### Steps to reproduce the behavior

1. Install `medusa-plugin-sendgrid`
2. Configure it on the backend project
3. Create a new order
4. See error in backend log

### Expected behavior

The email should be sent.

### Code snippets

medusa-config.js:

```
	{
		resolve: `medusa-plugin-sendgrid`,
		options: {
			api_key: process.env.SENDGRID_API_KEY,
			from: process.env.SENDGRID_FROM_EMAIL,
			order_placed_template: process.env.SENDGRID_ORDER_PLACED_ID,
			order_shipped_template: process.env.SENDGRID_ORDER_SHIPPED_ID,
		},
	},
```

**Comment by olivermrbl** [comment]
Thanks for reporting. Fixed in https://github.com/medusajs/medusa/pull/4524 ... wil publish a new version, as soon as it has been merged

cc @pevey

**Comment by olivermrbl** [comment]
I've published a new version of the SendGrid plugin :)

**Comment by pevey** [comment]
Yikes!  Thanks for fixing this, @olivermrbl

**Comment by iamanle** [comment]
I pull the new version and got this error. Anyone else encounter it?

```
3|fliv-medusa-v1  | 130.176.162.72 - - [20/Jul/2023:05:36:12 +0000] "GET /store/products?cart_id=cart_01H5RWQD7AX4YMCMETAJ2YAEEN&id%5B0%5D=prod_01H4QMRWVTR856HXCVYZTR6QNT&is_giftcard=false HTTP/1.1" 200 4120 "-" "Dart/2.19 (dart:io)"
3|fliv-medusa-v1  | {"level":"error","message":"Forbidden","stack":[{"columnNumber":29,"fileName":"node_modules/@sendgrid/client/src/classes/client.js","functionName":null,"lineNumber":146,"methodName":null,"native":false,"typeName":null},{"columnNumber":null,"fileName":null,"functionName":"runMicrotasks","lineNumber":null,"methodName":null,"native":false,"typeName":null},{"columnNumber":5,"fileName":"node:internal/process/task_queues","functionName":"processTicksAndRejections","lineNumber":96,"methodName":null,"native":false,"typeName":null}],"timestamp":"2023-07-20 05:36:13"}
2|fliv-medusa-v1  | 130.176.162.163 - - [20/Jul/2023:05:36:14 +0000] "GET /store/products?cart_id=cart_01H5RWQD7AX4YMCMETAJ2YAEEN&id%5B0%5D=prod_01H4QMRWVTR856HXCVYZTR6QNT&is_giftcard=false HTTP/1.1" 200 4120 "-" "Dart/2.19 (dart:io)"
```

**Comment by iamanle** [comment]
Created an issue here https://github.com/medusajs/medusa/issues/4573
