### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by muhammeddilmacc** [medusajs/medusa#4603]
### Describe the bug

I am trying to build a plugin, while creating the plugin I am following the steps in documantaion. at the end of steps am getting this error

### System information

Medusa version (including plugins): 1.3.17
Node.js version: v18.17.0
Database: Postgresql
Operating system: windows
Browser (if relevant): chrome

### Steps to reproduce the behavior

1. npm run dev(backend)
2. npm run dev (custom-plugin)

### Expected behavior

after running server I I need to connect the plugin to the backend.

### Code snippets
 
$ npm run dev

> medusa-starter-default@0.0.1 dev
> cross-env npm run build && medusa develop

> medusa-starter-default@0.0.1 build
> tsc -p ./tsconfig.server.json && medusa-admin build

TypeError: Cannot read properties of undefined (reading 'options')
    at loadConfig (C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\utils\load-config.js:18:30)
    at Command.<anonymous> (C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\commands\build.js:101:53)
    at step (C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\commands\build.js:44:23)
    at Object.next (C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\commands\build.js:25:53)
    at C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\commands\build.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\commands\build.js:15:12)
    at Command.build (C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\commands\build.js:83:12)
    at Command.listener [as _actionHandler] (C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\node_modules\commander\lib\command.js:482:17)
    at C:\Users\muham\OneDrive\Masaüstü\Medusa\medusa-plugin-custom\node_modules\@medusajs\admin\node_modules\commander\lib\command.js:1283:65

**Comment by olivermrbl** [comment]
@muhammeddilmacc, can you share the plugin repository with me? That would be helpful for me to debug :)

**Comment by Gene027** [comment]
I am experiencing exactly the same build error. I followed the exact steps on documentation to build custom plugin
Here is my github repository https://github.com/Gene027/igr-blog.git
clone the praise-dev branch

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by AkshitBhati33** [comment]
Cannot read properties of undefined (reading 'plugins')
facing this error when putting service in my plugin also cannot find module error Error: Cannot find module './src/services/review.services' while the path is correct
