### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/events/create-subscriber

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#4607]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Using the snippet from the docs results in an error. I have the exact same subscriber created and I get the following when starting Medusa:
```shell
Initializing plugins
error:   Error starting server
TypeError: loaded is not a constructor
    at /Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:484:77
    at Object.resolve (/Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/awilix/lib/resolvers.js:295:20)
    at Object.build (/Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/awilix/lib/container.js:325:37)
    at /Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:484:19
    at Array.forEach (<anonymous>)
    at registerSubscribers (/Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:482:11)
    at /Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:109:41
    at step (/Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (/Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
    at fulfilled (/Users/boriskamp/Documents/bk-development/birdblocker-shop-medusa/node_modules/@medusajs/medusa/dist/loaders/plugins.js:5:58)
```

<img width="796" alt="Screenshot 2023-07-26 at 11 53 26" src="https://github.com/medusajs/medusa/assets/8350740/82546f90-ca9a-4cf4-89f0-1f3873af9567">

**Comment by BorisKamp** [comment]
I found out I had old cached files in the `/dist/subscribers` directory. Removing the whole `/dist` folder and starting medusa again did the trick.

**Comment by BorisKamp** [comment]
So can be closed
