### ISSUE TITLE
The tutorial process fails to execute migrations and shows no error messages

### ISSUE THREAD

**Issue by tsojcanth** [medusajs/medusa#4658]
## Bug report

The tutorial fails to execute migrations and shows no error messages.

```
vagrant@ubuntu2204:~$ npx create-medusa-app
? What's the name of your project? xxxxxxx
? Enter your Postgres username postgres
? Enter your Postgres password [hidden]
? Enter an email for your admin dashboard user xxxxxxxxx@gmail.com
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
✔ Database medusa-JBkg created
✔ Installed Dependencies
✔ Project Built
An error occurred while preparing project: Error: An error occurred while running migrations:
vagrant@ubuntu2204:~$
```

### System information

Medusa version (including plugins): Medusa CLI version: 1.3.17
Node.js version:  v18.16.1 (from snap)
Database: Postgres 15
Operating system: ubuntu 22.04 on vagrant (hosted by virtualbox on windows 11) 
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to (https://medusajs.com/)
2. press S as instructed
3. copy "npx create-medusa-app", paste in bash and run
4. type postgres credentials
5. type email

### Expected behavior

The script should run successfully or at least output errors (in this case the migration errors).

### Screenshots
![image](https://github.com/medusajs/medusa/assets/4179777/9f657b3a-dc32-4bef-a205-130e4f437e1e)

### Additional context

This is my first experience with medusajs, I'm evaluating some ecommerce platforms, and the onboarding did not work for me :(

**Comment by shahednasser** [comment]
Hi @tsojcanth , can I get you to change to the created directory (it's the name of your project) and run the command:

```bash
npx @medusajs/medusa-cli@latest migrations run
```

Then please share the output?

**Comment by tsojcanth** [comment]
@shahednasser here it is:

```
vagrant@ubuntu2204:~$ npx @medusajs/medusa-cli@latest migrations run
medusa migrations [action]

Manage migrations from the core and your own project

Options:
  --verbose                Turn on verbose output                                                                                                                                      [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output                                                                                                                                [boolean] [default: false]
  --json                   Turn on the JSON logger                                                                                                                                     [boolean] [default: false]
  --action                                                                                                                                                          [required] [choices: "run", "revert", "show"]
  -h, --help               Show help                                                                                                                                                                    [boolean]
  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project                                                                                             [boolean]
--------------- ERROR ---------------------
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Module.require (node:internal/modules/cjs/loader:1136:3)
    at require (node:internal/modules/cjs/helpers:110:18)
    at resolveLocalCommand (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/create-cli.js:33:20)
    at /home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/create-cli.js:46:30
    at Object.handler (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/create-cli.js:16:21)
    at Object.runCommand (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/yargs/build/lib/yargs.js:584:29) {
  code: 'ERR_INVALID_ARG_TYPE'
}
-------------------------------------------
medusa migrations [action]

Manage migrations from the core and your own project

Options:
  --verbose                Turn on verbose output                                                                                                                                      [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output                                                                                                                                [boolean] [default: false]
  --json                   Turn on the JSON logger                                                                                                                                     [boolean] [default: false]
  --action                                                                                                                                                          [required] [choices: "run", "revert", "show"]
  -h, --help               Show help                                                                                                                                                                    [boolean]
  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project                                                                                             [boolean]
TypeError: cmd is not a function
    at /home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/create-cli.js:152:20
    at /home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/create-cli.js:48:30
    at Object.handler (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/create-cli.js:16:21)
    at Object.runCommand (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/yargs/build/lib/yargs.js:584:29)
    at exports.default (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/create-cli.js:321:10)
    at Object.<anonymous> (/home/vagrant/.npm/_npx/29597ac69b58a7e9/node_modules/@medusajs/medusa-cli/dist/index.js:38:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
vagrant@ubuntu2204:~$
```

**Comment by shahednasser** [comment]
You need to run it from inside the project directory. So if you chose to name your project `my-medusa-store`, change to the `my-medusa-store` directory and run it from there

**Comment by tsojcanth** [comment]
Sorry, that was not me at my best :D

```
vagrant@ubuntu2204:~/xxxxxxx$ npx @medusajs/medusa-cli@latest migrations run
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
query: SELECT * FROM current_schema()
query: SELECT version();
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
No migrations are pending
info:    Migrations completed.
vagrant@ubuntu2204:~/xxxxxxx$
```

**Comment by shahednasser** [comment]
Hmm seems like the migrations ran correctly but something else is causing the error, we'd need to investigate this further.

In the meantime, you can still use Medusa since the project is fully setup. You just need to perform the following steps:

1. `npx medusa user -e user@test.com -p supersecret` to create a user. You can also use `npx medusa seed -f ./data/seed.json` to seed with demo data
2. `npx medusa develop` to start Medusa.

Let me know if this works. Sorry for the inconvenience and thank you for reporting the issue! It will help us continue improving Medusa

**Comment by tsojcanth** [comment]
Thank you. I'm available to support you.

I managed to log in, but I had to map both port 9000 and 7001 on the vm port forwarding.
