### ISSUE TITLE
Bug: yarn not working with create-medusa-app

### ISSUE THREAD

**Issue by yersultanur** [medusajs/medusa#4812]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

yarn create medusa-app

Don't know if issue in my laptop, but pnpm works fine

```
$ yarn create medusa-app
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 7s 90ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ medusa-telemetry@npm:0.0.16 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 0s 441ms
➤ YN0000: Done with warnings in 7s 644ms

C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.pnp.cjs:11117
      Error.captureStackTrace(firstError);
            ^

Error: medusa-telemetry tried to access @babel/runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @babel/runtime (via "@babel\runtime\helpers\interopRequireDefault")
Required by: medusa-telemetry@npm:0.0.16 (via C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.yarn\unplugged\medusa-telemetry-npm-0.0.16-2d26cb6409\node_modules\medusa-telemetry\dist\)

Require stack:
- C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.yarn\unplugged\medusa-telemetry-npm-0.0.16-2d26cb6409\node_modules\medusa-telemetry\dist\index.js
    at require$$0.Module._resolveFilename (C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.pnp.cjs:11117:13)
    at require$$0.Module._load (C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.pnp.cjs:10967:42)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.yarn\unplugged\medusa-telemetry-npm-0.0.16-2d26cb6409\node_modules\medusa-telemetry\dist\index.js:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at require$$0.Module._extensions..js (C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.pnp.cjs:11161:33)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at require$$0.Module._load (C:\Users\ersin\AppData\Local\Temp\xfs-129ec15a\dlx-17468\.pnp.cjs:10980:22)

Node.js v18.17.1
```

### How can this issue be resolved?

1. Work fine on yarn create medusa-app
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by pmltechpile** [comment]
Not sure if this issue is related but I get a slightly different error on `yarn create medusa-app`: 


`import { clearProject } from "@medusajs/utils";
         ^^^^^^^^^^^^
SyntaxError: Named export 'clearProject' not found. The requested module '@medusajs/utils' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@medusajs/utils';
const { clearProject } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.13.0
error Command failed.
Exit code: 1`

I've ran the command using npm as well and get the same error

**Comment by shahednasser** [comment]
Thank you for submitting this issue @yersultanur . I was able to reproduce the bug and will look into it further.

@pmltechpile can you ensure that you're using the latest version of `create-medusa-app`?
