### ISSUE TITLE
Tax inclusive feature flag results in QueryFailedError: column includes_tax does not exist

### ISSUE THREAD

**Issue by GenuineGuineapig** [medusajs/medusa#4903]
### Describe the bug

I've started with a fresh install following the readme and installed the next js starter template. However, after setting the tax includes feature flag, I can no longer edit regions or products. The browser shows 4 errors regarding undefined, and the logfile from the backend is attached.

### System information

Medusa version (including plugins): 1.15.0 (latest)
Node.js version: 18.7.0
Database: postgresql
Operating system: ubuntu 22.10
Browser (if relevant):

### Steps to reproduce the behavior

1. npx create-medusa-app@latest
2. edit medusa-config.js, add `module.exports = {
  projectConfig,
  plugins,
  modules,
  featureFlags: {
          tax_inclusive_pricing: true,
  }
};
`
4. npm run dev
5. Browse to region settings
 
### Expected behavior

It should allow me to browse the region settings 

### Code snippets

Logfile:

```
::1 - - [29/Aug/2023:17:20:58 +0000] "GET /admin/collections?offset=0&limit=10 HTTP/1.1" 304 - "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
error:   column Store__Store_currencies.includes_tax does not exist
QueryFailedError: column Store__Store_currencies.includes_tax does not exist
    at PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
    at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25) {
  query: 'SELECT "Store"."id" AS "Store_id", "Store"."created_at" AS "Store_created_at", "Store"."updated_at" AS "Store_updated_at", "Store"."name" AS "Store_name", "Store"."default_currency_code" AS "Store_default_currency_code", "Store"."swap_link_template" AS "Store_swap_link_template", "Store"."payment_link_template" AS "Store_payment_link_template", "Store"."invite_link_template" AS "Store_invite_link_template", "Store"."default_location_id" AS "Store_default_location_id", "Store"."metadata" AS "Store_metadata", "Store"."default_sales_channel_id" AS "Store_default_sales_channel_id", "Store__Store_currencies"."code" AS "Store__Store_currencies_code", "Store__Store_currencies"."symbol" AS "Store__Store_currencies_symbol", "Store__Store_currencies"."symbol_native" AS "Store__Store_currencies_symbol_native", "Store__Store_currencies"."name" AS "Store__Store_currencies_name", "Store__Store_currencies"."includes_tax" AS "Store__Store_currencies_includes_tax", "Store__Store_default_currency"."code" AS "Store__Store_default_currency_code", "Store__Store_default_currency"."symbol" AS "Store__Store_default_currency_symbol", "Store__Store_default_currency"."symbol_native" AS "Store__Store_default_currency_symbol_native", "Store__Store_default_currency"."name" AS "Store__Store_default_currency_name", "Store__Store_default_currency"."includes_tax" AS "Store__Store_default_currency_includes_tax", "Store__Store_default_sales_channel"."id" AS "Store__Store_default_sales_channel_id", "Store__Store_default_sales_channel"."created_at" AS "Store__Store_default_sales_channel_created_at", "Store__Store_default_sales_channel"."updated_at" AS "Store__Store_default_sales_channel_updated_at", "Store__Store_default_sales_channel"."deleted_at" AS "Store__Store_default_sales_channel_deleted_at", "Store__Store_default_sales_channel"."name" AS "Store__Store_default_sales_channel_name", "Store__Store_default_sales_channel"."description" AS "Store__Store_default_sales_channel_description", "Store__Store_default_sales_channel"."is_disabled" AS "Store__Store_default_sales_channel_is_disabled", "Store__Store_default_sales_channel"."metadata" AS "Store__Store_default_sales_channel_metadata" FROM "public"."store" "Store" LEFT JOIN "public"."store_currencies" "Store_Store__Store_currencies" ON "Store_Store__Store_currencies"."store_id"="Store"."id" LEFT JOIN "public"."currency" "Store__Store_currencies" ON "Store__Store_currencies"."code"="Store_Store__Store_currencies"."currency_code"  LEFT JOIN "public"."currency" "Store__Store_default_currency" ON "Store__Store_default_currency"."code"="Store"."default_currency_code"  LEFT JOIN "public"."sales_channel" "Store__Store_default_sales_channel" ON "Store__Store_default_sales_channel"."id"="Store"."default_sales_channel_id" AND ("Store__Store_default_sales_channel"."deleted_at" IS NULL) WHERE (NOT("Store"."id" IS NULL))',
  parameters: [],
  driverError: error: column Store__Store_currencies.includes_tax does not exist
      at /home/paul/medusa/demo/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
      at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25) {
    length: 135,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '880',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3656',
    routine: 'errorMissingColumn'
  },
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '880',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3656',
  routine: 'errorMissingColumn'
}
::1 - - [29/Aug/2023:17:20:58 +0000] "GET /admin/product-tags HTTP/1.1" 304 - "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
::1 - - [29/Aug/2023:17:20:58 +0000] "GET /admin/store/ HTTP/1.1" 500 86 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
::1 - - [29/Aug/2023:17:20:58 +0000] "GET /admin/products?fields=id%2Ctitle%2Cthumbnail%2Cstatus%2Chandle%2Ccollection_id&expand=variants%2Coptions%2Cvariants.prices%2Cvariants.options%2Ccollection%2Ctags%2Ctype%2Cimages&is_giftcard=false&offset=0&limit=15 HTTP/1.1" 304 - "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
error:   column Store__Store_currencies.includes_tax does not exist
QueryFailedError: column Store__Store_currencies.includes_tax does not exist
    at PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
    at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25) {
  query: 'SELECT "Store"."id" AS "Store_id", "Store"."created_at" AS "Store_created_at", "Store"."updated_at" AS "Store_updated_at", "Store"."name" AS "Store_name", "Store"."default_currency_code" AS "Store_default_currency_code", "Store"."swap_link_template" AS "Store_swap_link_template", "Store"."payment_link_template" AS "Store_payment_link_template", "Store"."invite_link_template" AS "Store_invite_link_template", "Store"."default_location_id" AS "Store_default_location_id", "Store"."metadata" AS "Store_metadata", "Store"."default_sales_channel_id" AS "Store_default_sales_channel_id", "Store__Store_currencies"."code" AS "Store__Store_currencies_code", "Store__Store_currencies"."symbol" AS "Store__Store_currencies_symbol", "Store__Store_currencies"."symbol_native" AS "Store__Store_currencies_symbol_native", "Store__Store_currencies"."name" AS "Store__Store_currencies_name", "Store__Store_currencies"."includes_tax" AS "Store__Store_currencies_includes_tax", "Store__Store_default_currency"."code" AS "Store__Store_default_currency_code", "Store__Store_default_currency"."symbol" AS "Store__Store_default_currency_symbol", "Store__Store_default_currency"."symbol_native" AS "Store__Store_default_currency_symbol_native", "Store__Store_default_currency"."name" AS "Store__Store_default_currency_name", "Store__Store_default_currency"."includes_tax" AS "Store__Store_default_currency_includes_tax", "Store__Store_default_sales_channel"."id" AS "Store__Store_default_sales_channel_id", "Store__Store_default_sales_channel"."created_at" AS "Store__Store_default_sales_channel_created_at", "Store__Store_default_sales_channel"."updated_at" AS "Store__Store_default_sales_channel_updated_at", "Store__Store_default_sales_channel"."deleted_at" AS "Store__Store_default_sales_channel_deleted_at", "Store__Store_default_sales_channel"."name" AS "Store__Store_default_sales_channel_name", "Store__Store_default_sales_channel"."description" AS "Store__Store_default_sales_channel_description", "Store__Store_default_sales_channel"."is_disabled" AS "Store__Store_default_sales_channel_is_disabled", "Store__Store_default_sales_channel"."metadata" AS "Store__Store_default_sales_channel_metadata" FROM "public"."store" "Store" LEFT JOIN "public"."store_currencies" "Store_Store__Store_currencies" ON "Store_Store__Store_currencies"."store_id"="Store"."id" LEFT JOIN "public"."currency" "Store__Store_currencies" ON "Store__Store_currencies"."code"="Store_Store__Store_currencies"."currency_code"  LEFT JOIN "public"."currency" "Store__Store_default_currency" ON "Store__Store_default_currency"."code"="Store"."default_currency_code"  LEFT JOIN "public"."sales_channel" "Store__Store_default_sales_channel" ON "Store__Store_default_sales_channel"."id"="Store"."default_sales_channel_id" AND ("Store__Store_default_sales_channel"."deleted_at" IS NULL) WHERE (NOT("Store"."id" IS NULL))',
  parameters: [],
  driverError: error: column Store__Store_currencies.includes_tax does not exist
      at /home/paul/medusa/demo/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
      at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25) {
    length: 135,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '880',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3656',
    routine: 'errorMissingColumn'
  },
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '880',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3656',
  routine: 'errorMissingColumn'
}
::1 - - [29/Aug/2023:17:20:59 +0000] "GET /admin/store/ HTTP/1.1" 500 86 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
::1 - - [29/Aug/2023:17:21:01 +0000] "OPTIONS /admin/products/prod_01H914PE0MEJVF8X83JRHEEM83 HTTP/1.1" 204 0 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
::1 - - [29/Aug/2023:17:21:01 +0000] "DELETE /admin/products/prod_01H914PE0MEJVF8X83JRHEEM83 HTTP/1.1" 200 74 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
::1 - - [29/Aug/2023:17:21:01 +0000] "GET /admin/products?fields=id%2Ctitle%2Cthumbnail%2Cstatus%2Chandle%2Ccollection_id&expand=variants%2Coptions%2Cvariants.prices%2Cvariants.options%2Ccollection%2Ctags%2Ctype%2Cimages&is_giftcard=false&offset=0&limit=15 HTTP/1.1" 200 47 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
info:    Processing product.deleted which has 0 subscribers
::1 - - [29/Aug/2023:17:21:06 +0000] "GET /admin/batch-jobs?limit=100 HTTP/1.1" 304 - "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
error:   column PriceList.includes_tax does not exist
QueryFailedError: column PriceList.includes_tax does not exist
    at PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
    at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async Promise.all (index 0) {
  query: 'SELECT "PriceList"."id" AS "PriceList_id", "PriceList"."created_at" AS "PriceList_created_at", "PriceList"."updated_at" AS "PriceList_updated_at", "PriceList"."deleted_at" AS "PriceList_deleted_at", "PriceList"."name" AS "PriceList_name", "PriceList"."description" AS "PriceList_description", "PriceList"."type" AS "PriceList_type", "PriceList"."status" AS "PriceList_status", "PriceList"."starts_at" AS "PriceList_starts_at", "PriceList"."ends_at" AS "PriceList_ends_at", "PriceList"."includes_tax" AS "PriceList_includes_tax" FROM "public"."price_list" "PriceList" WHERE "PriceList"."deleted_at" IS NULL ORDER BY "PriceList"."created_at" DESC LIMIT 15',
  parameters: [],
  driverError: error: column PriceList.includes_tax does not exist
      at /home/paul/medusa/demo/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
      at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
      at async Promise.all (index 0) {
    length: 121,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '474',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3656',
    routine: 'errorMissingColumn'
  },
  length: 121,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '474',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3656',
  routine: 'errorMissingColumn'
}
::1 - - [29/Aug/2023:17:21:07 +0000] "GET /admin/price-lists?expand=customer_groups&offset=0&limit=15 HTTP/1.1" 500 86 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
error:   column PriceList.includes_tax does not exist
QueryFailedError: column PriceList.includes_tax does not exist
    at PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
    at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async Promise.all (index 0) {
  query: 'SELECT "PriceList"."id" AS "PriceList_id", "PriceList"."created_at" AS "PriceList_created_at", "PriceList"."updated_at" AS "PriceList_updated_at", "PriceList"."deleted_at" AS "PriceList_deleted_at", "PriceList"."name" AS "PriceList_name", "PriceList"."description" AS "PriceList_description", "PriceList"."type" AS "PriceList_type", "PriceList"."status" AS "PriceList_status", "PriceList"."starts_at" AS "PriceList_starts_at", "PriceList"."ends_at" AS "PriceList_ends_at", "PriceList"."includes_tax" AS "PriceList_includes_tax" FROM "public"."price_list" "PriceList" WHERE "PriceList"."deleted_at" IS NULL ORDER BY "PriceList"."created_at" DESC LIMIT 15',
  parameters: [],
  driverError: error: column PriceList.includes_tax does not exist
      at /home/paul/medusa/demo/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
      at async SelectQueryBuilder.getRawAndEntities (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
      at async Promise.all (index 0) {
    length: 121,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '474',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3656',
    routine: 'errorMissingColumn'
  },
  length: 121,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '474',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3656',
  routine: 'errorMissingColumn'
}
::1 - - [29/Aug/2023:17:21:08 +0000] "GET /admin/price-lists?expand=customer_groups&offset=0&limit=15 HTTP/1.1" 500 86 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
error:   column Region.includes_tax does not exist
QueryFailedError: column Region.includes_tax does not exist
    at PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.getRawMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1973:26)
    at async SelectQueryBuilder.getManyAndCount (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:850:36) {
  query: 'SELECT DISTINCT "distinctAlias"."Region_id" AS "ids_Region_id" FROM (SELECT "Region"."id" AS "Region_id", "Region"."created_at" AS "Region_created_at", "Region"."updated_at" AS "Region_updated_at", "Region"."deleted_at" AS "Region_deleted_at", "Region"."name" AS "Region_name", "Region"."currency_code" AS "Region_currency_code", "Region"."tax_rate" AS "Region_tax_rate", "Region"."tax_code" AS "Region_tax_code", "Region"."gift_cards_taxable" AS "Region_gift_cards_taxable", "Region"."automatic_taxes" AS "Region_automatic_taxes", "Region"."tax_provider_id" AS "Region_tax_provider_id", "Region"."metadata" AS "Region_metadata", "Region"."includes_tax" AS "Region_includes_tax", "Region__Region_countries"."id" AS "Region__Region_countries_id", "Region__Region_countries"."iso_2" AS "Region__Region_countries_iso_2", "Region__Region_countries"."iso_3" AS "Region__Region_countries_iso_3", "Region__Region_countries"."num_code" AS "Region__Region_countries_num_code", "Region__Region_countries"."name" AS "Region__Region_countries_name", "Region__Region_countries"."display_name" AS "Region__Region_countries_display_name", "Region__Region_countries"."region_id" AS "Region__Region_countries_region_id", "Region__Region_fulfillment_providers"."id" AS "Region__Region_fulfillment_providers_id", "Region__Region_fulfillment_providers"."is_installed" AS "Region__Region_fulfillment_providers_is_installed", "Region__Region_payment_providers"."id" AS "Region__Region_payment_providers_id", "Region__Region_payment_providers"."is_installed" AS "Region__Region_payment_providers_is_installed" FROM "public"."region" "Region" LEFT JOIN "public"."country" "Region__Region_countries" ON "Region__Region_countries"."region_id"="Region"."id"  LEFT JOIN "public"."region_fulfillment_providers" "Region_Region__Region_fulfillment_providers" ON "Region_Region__Region_fulfillment_providers"."region_id"="Region"."id" LEFT JOIN "public"."fulfillment_provider" "Region__Region_fulfillment_providers" ON "Region__Region_fulfillment_providers"."id"="Region_Region__Region_fulfillment_providers"."provider_id"  LEFT JOIN "public"."region_payment_providers" "Region_Region__Region_payment_providers" ON "Region_Region__Region_payment_providers"."region_id"="Region"."id" LEFT JOIN "public"."payment_provider" "Region__Region_payment_providers" ON "Region__Region_payment_providers"."id"="Region_Region__Region_payment_providers"."provider_id" WHERE "Region"."deleted_at" IS NULL) "distinctAlias" ORDER BY "Region_id" ASC LIMIT 50',
  parameters: [],
  driverError: error: column Region.includes_tax does not exist
      at /home/paul/medusa/demo/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/home/paul/medusa/demo/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.getRawMany (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1973:26)
      at async SelectQueryBuilder.getManyAndCount (/home/paul/medusa/demo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:850:36) {
    length: 118,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '631',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3656',
    routine: 'errorMissingColumn'
  },
  length: 118,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '631',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3656',
  routine: 'errorMissingColumn'
}
::1 - - [29/Aug/2023:17:21:10 +0000] "GET /admin/regions HTTP/1.1" 500 86 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"



```

**Comment by olivermrbl** [comment]
You'll need to run migrations after enabling the feature flag:
```
npx medusa migrations run
```

**Comment by GenuineGuineapig** [comment]
Oh wow, I must have missed that. Thanks for the super quick reply!
