### ISSUE TITLE
Using Custom Validator results in Unknown Error

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#4996]
## Bug report

Adding a custom validator, results in unknown eror

### Describe the bug
I've created a customer validator like so
```
export class StoreGetProductsParams extends MedusaStoreGetProductsParams {
    @IsString()
    @IsOptional()
    stores?: string;
}


export class StoreGetProductsProductParams extends MedusaStoreGetProductsProductParams {
    @IsString()
    stores?: string;
}

registerOverriddenValidators(StoreGetProductsParams);

registerOverriddenValidators(StoreGetProductsProductParams);

```
### steps to check
when i curl localhost:9000/store/products?stores="megastore"
it throws an error {"code":"unknown_error","type":"unknown_error","message":"An unknown error occurred."}
and medusa server results gives error: error: column product.productid does not exist
however 
when i curl localhost:9000/store/products
it works as expected, displaying all products. 

### System information

Medusa version (including plugins): 1.15.0
Node.js version: 18
Database: Postgres sql
Operating system: Amazon Linux
Browser (if relevant):

### Steps to reproduce the behavior with code snippet
I've over ridden the product-service listAndCount like so 
```
async listAndCount(
        selector: ProductSelector,
        config: FindProductConfig = {
            relations: [],
            skip: 0,
            take: 20,
            include_discount_prices: false
        }
    ): Promise<[Product[], number]> {
        return await this.atomicPhase_(async (manager) => {
            const productRepo = manager.getRepository(Product);
            if (!config.relations?.includes("stores")) {
                config.relations?.push("stores");
            } else if (!config.relations) {
                config.relations = ["stores"];
            }
            this.logger.debug(
                `listAndCount:selector:${JSON.stringify(selector)}`
            );
            this.logger.debug(`listAndCount:config:${JSON.stringify(config)}`);

            const result = (await super.listAndCount(
                selector,
                config as any
            )) as [Product[], number];

            
            return result;
        });
    }
```

### Expected behavior
Should return the same, 
A clear and concise description of what you expected to happen

### Additional context - database log
```
query failed: SELECT DISTINCT "distinctAlias"."product_id" AS "ids_product_id", "distinctAlias"."product_created_at" FROM (SELECT "product"."id" AS "product_id", "product"."created_at" AS "product_created_at" FROM "public"."product" "product" INNER JOIN "public"."product_sales_channel" "product_sales_channels" ON "product_sales_channels"."product_id"="product"."id" INNER JOIN "public"."sales_channel" "sales_channels" ON "sales_channels"."id"="product_sales_channels"."sales_channel_id" AND ( "sales_channels"."id" IN ($1) AND "sales_channels"."deleted_at" IS NULL)  LEFT JOIN "public"."product_category_product" "product_categories" ON "product_categories"."product_id"="product"."id" LEFT JOIN "public"."product_category" "categories" ON "categories"."id"="product_categories"."product_category_id" AND ("categories"."is_internal" = $2 AND "categories"."is_active" = $3) WHERE ( (product.productId = $4 AND "product"."status" IN ($5) AND "product"."id" > $6) ) AND ( "product"."deleted_at" IS NULL )) "distinctAlias" ORDER BY "distinctAlias"."product_created_at" DESC, "product_id" ASC LIMIT 100 -- PARAMETERS: ["sc_01H14A35QQ6Y25BSG4W248TB5J",false,true,null,"published",""]
error: error: column product.productid does not exist
query: ROLLBACK
query failed: SELECT COUNT(DISTINCT("product"."id")) AS "cnt" FROM "public"."product" "product" INNER JOIN "public"."product_sales_channel" "product_sales_channels" ON "product_sales_channels"."product_id"="product"."id" INNER JOIN "public"."sales_channel" "sales_channels" ON "sales_channels"."id"="product_sales_channels"."sales_channel_id" AND ( "sales_channels"."id" IN ($1) AND "sales_channels"."deleted_at" IS NULL)  LEFT JOIN "public"."product_category_product" "product_categories" ON "product_categories"."product_id"="product"."id" LEFT JOIN "public"."product_category" "categories" ON "categories"."id"="product_categories"."product_category_id" AND ("categories"."is_internal" = $2 AND "categories"."is_active" = $3) WHERE ( (product.productId = $4 AND "product"."status" IN ($5) AND "product"."id" > $6) ) AND ( "product"."deleted_at" IS NULL ) -- PARAMETERS: ["sc_01H14A35QQ6Y25BSG4W248TB5J",false,true,null,"published",""]
error: error: current transaction is aborted, commands ignored until end of transaction block
error:   column product.productid does not exist
QueryFailedError: column product.productid does not exist
    at PostgresQueryRunner.query (###/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.getRawMany (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1973:26)
    at async SelectQueryBuilder.getRawAndEntities (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async Promise.all (index 0) {
  query: 'SELECT DISTINCT "distinctAlias"."product_id" AS "ids_product_id", "distinctAlias"."product_created_at" FROM (SELECT "product"."id" AS "product_id", "product"."created_at" AS "product_created_at" FROM "public"."product" "product" INNER JOIN "public"."product_sales_channel" "product_sales_channels" ON "product_sales_channels"."product_id"="product"."id" INNER JOIN "public"."sales_channel" "sales_channels" ON "sales_channels"."id"="product_sales_channels"."sales_channel_id" AND ( "sales_channels"."id" IN ($1) AND "sales_channels"."deleted_at" IS NULL)  LEFT JOIN "public"."product_category_product" "product_categories" ON "product_categories"."product_id"="product"."id" LEFT JOIN "public"."product_category" "categories" ON "categories"."id"="product_categories"."product_category_id" AND ("categories"."is_internal" = $2 AND "categories"."is_active" = $3) WHERE ( (product.productId = $4 AND "product"."status" IN ($5) AND "product"."id" > $6) ) AND ( "product"."deleted_at" IS NULL )) "distinctAlias" ORDER BY "distinctAlias"."product_created_at" DESC, "product_id" ASC LIMIT 100',
  parameters: [
    'sc_01H14A35QQ6Y25BSG4W248TB5J',
    false,
    true,
    undefined,
    'published',
    ''
  ],
  driverError: error: column product.productid does not exist
      at ###/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (###/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.getRawMany (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1973:26)
      at async SelectQueryBuilder.getRawAndEntities (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (###/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
      at async Promise.all (index 0) {
    length: 116,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '872',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3656',
    routine: 'errorMissingColumn'
  },
  length: 116,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '872',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3656',
  routine: 'errorMissingColumn'
}
```

**Comment by SGFGOV** [comment]
Discovered it was an error in my code
