### ISSUE TITLE
 Not able to start Medusa after upgrading to Medusa v1.15.1

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#4998]
### Describe the bug

Not able to start Medusa after upgrading to Medusa v1.15.1

### System information

Medusa version (including plugins): v1.15.1
Node.js version: v18.16.0
Database: Postgres 
Operating system: Ubuntu
Browser (if relevant):

### Steps to reproduce the behavior

1. Upgrade from v1.15.0 to v1.15.1
2. Build Medusa project and run `medusa start`
3. See error below

### Expected behavior

Medusa server would start. There is no issue after downgrading to v1.15.0.

### Code snippets

Error log:
```
error:   Error starting server
Error: Workflow with id "create-cart" is already defined.
    at WorkflowManager.register (/apps/medusa/node_modules/@medusajs/orchestration/dist/workflow/workflow-manager.js:27:19)
    at Object.<anonymous> (/node_modules/@medusajs/workflows/dist/definition/cart/create-cart.js:146:33)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/node_modules/@medusajs/workflows/dist/definition/cart/index.js:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

**Comment by olivermrbl** [comment]
@pepijn-vanvlaanderen, I am unable to reproduce your issue on my machine and in our staging environment.

Can I get you to check what versions of `@medusajs/workflows` and `@medusajs/orchestration` are resolved in your lock-file?

**Comment by pepijn-vanvlaanderen** [comment]
Hi @olivermrbl, thanks for your reply. There was indeed an issue with package versioning, I had duplicate workflow packages that were in the yarn.lock, due to a local plugin package that had a different version set of `@medusajs/medusa`.

After syncing the dependencies version, the issue is gone.
