### ISSUE TITLE
Admin onboarding: Unable to "Create an Order" (Railway)

### ISSUE THREAD

**Issue by jpizzle34** [medusajs/medusa#5062]
### Describe the bug
When completing the admin onboarding, clicking the `Create a sample order` button fails silently. In addition, the product preview url uses the localhost url instead of the public url at which the admin-ui is deployed to. This is occurring for me on a fresh instance when deploying the backend to Railway and deploying the admin-ui to Netlify.

### System information

Medusa version (including plugins): 1.15.0
Node.js version: Default railway env
Database: Postgres
Operating system: Default railway env
Browser (if relevant):

```
  "dependencies": {
    "@medusajs/admin": "^7.0.1",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/icons": "^1.0.0",
    "@medusajs/medusa": "^1.15.0",
    "@medusajs/ui": "^1.0.0",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.0.3",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.3",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.16",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.13",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "mongoose": "^5.13.14",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },
```

### Steps to reproduce the behavior

1. Click on Railway one-click deploy button in Medusa docs.
2. Create first admin user using `railway run npx medusa user --email ...` and login.
3. Start the onboarding process
4. At the 'Create an Order' step, click the `Create a sample order` button.
5. See console log error `TypeError: Cannot read properties of undefined (reading 'id')`

### Expected behavior

A sample order to be created successfully. Also, preview product should show the public admin url instead of localhost.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/48883158/f56dc0aa-3c82-4318-b4e7-47107c7642fe)

### Code snippets

console log
```
318.36906e2f.chunk.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at 318.36906e2f.chunk.js:1:5843
    at 318.36906e2f.chunk.js:1:5127
    at Object.next (318.36906e2f.chunk.js:1:5232)
    at v (318.36906e2f.chunk.js:1:3915)
    at a (318.36906e2f.chunk.js:1:4112)
    at 318.36906e2f.chunk.js:1:4171
    at new Promise (<anonymous>)
    at 318.36906e2f.chunk.js:1:4053
    at v (318.36906e2f.chunk.js:1:6069)
    at onClick (318.36906e2f.chunk.js:1:6680)
    at Object.eB (main.2e2c4544.js:18:16708)
    at eZ (main.2e2c4544.js:18:16862)
    at eY (main.2e2c4544.js:18:16919)
    at nS (main.2e2c4544.js:18:37998)
    at nE (main.2e2c4544.js:18:38414)
    at main.2e2c4544.js:18:43311
    at s9 (main.2e2c4544.js:18:108682)
    at eF (main.2e2c4544.js:18:15846)
    at nT (main.2e2c4544.js:18:39705)
    at tX (main.2e2c4544.js:18:24056)
    at tY (main.2e2c4544.js:18:23840)
```
source

```
  var g = function(e) {
            var t, r = e.onNext, n = e.isComplete, a = e.data, s = (0,
            i.useAdminProduct)(a.product_id).product, c = (0,
            i.useAdminCreateDraftOrder)(), u = c.mutateAsync, l = c.isLoading, p = (0,
            i.useMedusa)().client, m = (0,
            i.useAdminRegions)().regions, h = (0,
            i.useAdminShippingOptions)().shipping_options, v = (t = y(function() {
                var e, t, n;
                return b(this, function(o) {
                    switch (o.label) {
                    case 0:
                        t = null !== (e = s.variants[0]) && void 0 !== e ? e : null,
                        o.label = 1;
                    case 1:
                        return o.trys.push([1, 4, , 5]),
                        [4, u({
                            email: "customer@medusajs.com",
                            items: [t ? {
                                quantity: 1,
                                variant_id: t.id
                            } : {
                                quantity: 1,
                                title: s.title,
                                unit_price: 50
                            }],
                            shipping_methods: [{
                                option_id: h[0].id
                            }],
                            region_id: m[0].id
                        })];
                    case 2:
                        return n = o.sent().draft_order,
                        [4, p.admin.draftOrders.markPaid(n.id)];
                    case 3:
                        return r(o.sent().order),
                        [3, 5];
                    case 4:
                        return console.error(o.sent()),
                        [3, 5];
                    case 5:
                        return [2]
                    }
                })
            }),
...
```

### Additional context

I haven't tried deploying a non-containerized version of Medusa other than locally, so not sure if this is specific to Railway one-click deploy. Could it be Netlify related? I was expecting to have to set an env var like MEDUSA_ADMIN_URL but I didn't see any mention of it in the docs (although it's written for deploying the admin to Vercel).

**Comment by shahednasser** [comment]
Thank you for opening this issue! The onboarding was tailored more towards local setups, so looks like we need to address some issues related to onboarding on a deployed server. Will look into fixing it.

**Comment by jpizzle34** [comment]
Ah ok, no worries! Thanks

**Comment by shahednasser** [comment]
This issue has now been resolved in the `medusa-starter-default`
