### ISSUE TITLE
Issue with Editing Price lists in latest Medusa Admin

### ISSUE THREAD

**Issue by brendansimcox** [medusajs/medusa#5347]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

We have upgraded our staging environment as a pre-release test before deploying to production but found that the edit price list functionality isn't working

All packages are updated to the latest and manually added medusa-react to the latest as a dependency, running node 16, but getting this issue

```
Unexpected Application Error!
(0 , en.useAdminDeletePriceListProductsPrices) is not a function
TypeError: (0 , en.useAdminDeletePriceListProductsPrices) is not a function
    at Os (https://ommitedurl/app/918.af1075aa.chunk.js:1:1253518)
    at oO (https://ommitedurl/app/main.1be561c0.js:18:60913)
    at u (https://ommitedurl/app/main.1be561c0.js:18:119434)
    at sI (https://ommitedurl/app/main.1be561c0.js:18:99087)
    at https://ommitedurl/app/main.1be561c0.js:18:98954
    at sN (https://ommitedurl/app/main.1be561c0.js:18:98961)
    at sP (https://ommitedurl/app/main.1be561c0.js:18:95713)
    at s_ (https://ommitedurl/app/main.1be561c0.js:18:96102)
    at n6 (https://ommitedurl/app/main.1be561c0.js:18:44823)
    at https://ommitedurl/app/main.1be561c0.js:18:93613
```

### Steps to reproduce

1. upgrade all packages to latest medusa (medusa, medusa-admin and all supporting packages)
2. go to prices lists
3. select a price list to edit
4. error shows

### package.json

```
"dependencies": {
    "@medusajs/admin": "^7.1.4",
    "@medusajs/cache-redis": "1.8.8",
    "@medusajs/event-bus-redis": "1.8.8",
    "@medusajs/inventory": "^1.9.1",
    "@medusajs/medusa": "^1.17.1",
    "@medusajs/medusa-cli": "^1.3.21",
    "@medusajs/medusa-oas-cli": "0.2.20-snapshot-20230921172817",
    "@medusajs/types": "^1.11.2",
    "@medusajs/utils": "^1.10.3",
    "@medusajs/workflows": "^0.2.3",
    "@radix-ui/react-dialog": "^1.0.5",
    "@tanstack/react-query": "^4.36.1",
    "medusa-extender": "^1.8.8",
    "medusa-file-s3": "^1.3.1",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-paypal": "^6.0.2",
    "medusa-payment-stripe": "^6.0.4",
    "medusa-plugin-meilisearch": "^2.0.8",
    "medusa-plugin-sendgrid": "^1.3.11",
    "medusa-plugin-ses": "^2.0.17",
    "medusa-plugin-wishlist": "^1.1.43",
    "medusa-react": "^9.0.7",
    "typeorm": "^0.3.17",
    "yarn": "^1.22.19"
  },
  "repository": "https://github.com/medusajs/medusa-starter-default.git",
  "keywords": [
    "sqlite",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "devDependencies": {
    "@babel/cli": "^7.22.5",
    "@babel/core": "^7.22.5",
    "@babel/preset-typescript": "^7.22.5",
    "babel-preset-medusa-package": "^1.1.19",
    "nodemon": "^2.0.22",
    "patch-package": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "typescript": "^5.1.6"
  }
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by brendansimcox** [comment]
In wrong section
