### ISSUE TITLE
Crashed checkout after enable Stripe Payment - Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Sylvesterx1** [medusajs/medusa#5570]
Browser:
`Application error: a client-side exception has occurred (see the browser console for more information).`

Plugin used: https://medusajs.com/plugins/medusa-payment-stripe/
Log console:
```
472-aa43d874bf760c9f.js:1 TypeError: Cannot read properties of undefined (reading 'title')
    at payment_container (https://aray.pl/_next/static/chunks/app/(checkout)/checkout/page-84103bef2140ebbf.js:1:21950)
    at Mf (fd9d1056-1e0094a0f19d2256.js:9:39686)
    at rC (fd9d1056-1e0094a0f19d2256.js:9:112346)
    at Jk (fd9d1056-1e0094a0f19d2256.js:9:102245)
    at Ik (fd9d1056-1e0094a0f19d2256.js:9:101422)
    at df (fd9d1056-1e0094a0f19d2256.js:9:101240)
    at ef (fd9d1056-1e0094a0f19d2256.js:9:98669)
    at qf (fd9d1056-1e0094a0f19d2256.js:9:98092)
    at MessagePort.P (472-aa43d874bf760c9f.js:25:1668)
```

This above is after enable Payment Stripe or Paypal or Klarna. From admin panel i can enable example Stripe. Now after run checkout this above error.

I see in checkout module is definied Stripe:
```
import { PaymentSession } from "@medusajs/medusa"
import Radio from "@modules/common/components/radio"
import clsx from "clsx"
import React from "react"
import PaymentStripe from "../payment-stripe"
import PaymentTest from "../payment-test"

type PaymentContainerProps = {
  paymentSession: PaymentSession
  selected: boolean
  setSelected: () => void
  disabled?: boolean
}

const PaymentInfoMap: Record<string, { title: string; description: string }> = {
  stripe: {
    title: "Credit card",
    description: "Secure payment with credit card",
  },
  paypal: {
    title: "PayPal",
    description: "Secure payment with PayPal",
  },
  manual: {
    title: "Test payment",
    description: "Test payment using medusa-payment-manual",
  },
}

const PaymentContainer: React.FC<PaymentContainerProps> = ({
  paymentSession,
  selected,
  setSelected,
  disabled = false,
}) => {
  return (
    <div
      className={clsx(
        "flex flex-col gap-y-4 border-b border-gray-200 last:border-b-0",
        {
          "bg-gray-50": selected,
        }
      )}
    >
      <button
        className={"grid grid-cols-[12px_1fr] gap-x-4 py-4 px-8"}
        onClick={setSelected}
        disabled={disabled}
      >
        <Radio checked={selected} />
        <div className="flex flex-col text-left">
          <h3 className="text-base-semi leading-none text-gray-900">
            {PaymentInfoMap[paymentSession.provider_id].title}
          </h3>
          <span className="text-gray-700 text-small-regular mt-2">
            {PaymentInfoMap[paymentSession.provider_id].description}
          </span>
          {selected && (
            <div className="w-full mt-4">
              <PaymentElement paymentSession={paymentSession} />
            </div>
          )}
        </div>
      </button>
    </div>
  )
}

const PaymentElement = ({
  paymentSession,
}: {
  paymentSession: PaymentSession
}) => {
  switch (paymentSession.provider_id) {
    case "stripe":
      return (
        <div className="pt-8 pr-7">
          <PaymentStripe />
        </div>
      )
    case "manual":
      // We only display the test payment form if we are in a development environment
      return process.env.NODE_ENV === "development" ? <PaymentTest /> : null
    default:
      return null
  }
}

export default PaymentContainer
```

**Comment by chrislaai** [comment]
Hi, how did you resolve this issue?

**Comment by Sylvesterx1** [comment]
I think it's some cache/dependencies error.

When I disabled e.g. "Manual payment method" in the backend, Storefront remembered it before and still tried to read the value in the cart from the backend api, which was already disabled in the backend and was not in the API response and caused the application to crash.

After clear cache, rebuild app issue resolved.

**Comment by chrislaai** [comment]
Thanks for the info, it helped me👍
