### ISSUE TITLE
Error in server when uploading image through admin ui

### ISSUE THREAD

**Issue by inallermunde** [medusajs/medusa#562]
When I try to upload an image through the admin ui, I get an error in the console from the server:
```
error:   Could not resolve 'fileService'.
Resolution path: fileService
AwilixResolutionError: Could not resolve 'fileService'.
```

The stacktrace points to the `/api/routes/admin/uploads/create-upload.js` file:
```
AwilixResolutionError: Could not resolve 'fileService'.

Resolution path: fileService
    at Object.resolve (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/awilix/lib/container.js:240:23)
    at _callee2$ (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:24:37)
    at tryCatch (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:74:17
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@medusajs/medusa/dist/api/middlewares/await-middleware.js:10:15
    at Layer.handle [as handle_request] (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/express/lib/router/route.js:137:13)
    at Immediate._onImmediate (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/multer/lib/make-middleware.js:53:37)
    at processImmediate (node:internal/timers:466:21)
error:   Could not resolve 'fileService'.

Resolution path: fileService
AwilixResolutionError: Could not resolve 'fileService'.

Resolution path: fileService
    at Object.resolve (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/awilix/lib/container.js:240:23)
    at _callee2$ (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:24:37)
    at tryCatch (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:74:17
    at /Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/@medusajs/medusa/dist/api/middlewares/await-middleware.js:10:15
    at Layer.handle [as handle_request] (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/express/lib/router/route.js:137:13)
    at Immediate._onImmediate (/Users/marczinser/Documents/inallermunde-shop/medusa-test-nextjs/backend/node_modules/multer/lib/make-middleware.js:53:37)
    at processImmediate (node:internal/timers:466:21)
```

The image gets placed into the uploads folder though (as a file with a random hex string as a name and without a file-extension).
But afterwards, the image does not show up in the product response.
This is also the case when uploading an image as a thumbnail.

My project is the default project after installation with the nextjs starter (created with `create-medusa-app`).

**Comment by juanzgc** [comment]
Hi @inallermunde, would be great to see an example of how you implemented the custom service 😇 Even something as small as a code snippet would be of great help

**Comment by qutek** [comment]
@olivermrbl @juanzgc  I was able to add a custom service to upload images directly to the server. Peek at how the s3 plugin works [here](https://github.com/medusajs/medusa/blob/master/packages/medusa-file-s3/src/services/s3.js).

Basically, we just need to create a class that extends the `FileService` and override the `upload` and `delete` methods but since the file should be accessible we need to create a custom router to serve the static files as well, I put it to the gist
https://gist.github.com/qutek/224aae26c676f440218731757d09e9c4 in case someone wants to take a look

**Comment by juanzgc** [comment]
Thanks @qutek, how would you go about calling the Extended class that overrides `upload` and `delete`? I may be confusing myself, but if I'm not mistaken extending the `FileService` class allows for overwriting methods but as long as you also call the new class correct?

**Comment by qutek** [comment]
@juanzgc yeah, correct.
But the `src/services` directory is a special directory in medusa. It will be autoloaded and we don't need to manually call it.

From the doc
> When Medusa starts up it will look for files in this folder and register exports from these files to the global container. The global container holds all services and repositories in your Medusa project allowing for dependency injection.

**Comment by edihasaj** [comment]
You can also check this plugin that I've developed and I use for my own purposes: [https://www.npmjs.com/package/medusa-file-local](link)

**Comment by rohitnairtech** [comment]
You can use https://www.npmjs.com/package/@medusajs/file-local for the same (correct me if I'm wrong)
