### ISSUE TITLE
Medusa OAS CLI latest cannot install

### ISSUE THREAD

**Issue by sats268842** [medusajs/medusa#5657]
### Describe the bug

 when yarn add @medusajs/medusa-oas-cli, it throws error like this

➤ YN0000: · Yarn 4.0.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @medusajs/types@workspace:^: Workspace not found (@medusajs/types@workspace:^)
    at St.getWorkspaceByDescriptor (/home/s/user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:210:3520)
    at o1.getCandidates (/home/user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:140:115282)
    at Bd.getCandidates (/home//user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:141:1311)
    at Bd.getCandidates (/home/user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:141:1311)
    at /home/user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:210:8334
    at Yy (/home/user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:140:53922)
    at xe (/home/user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:210:8314)
    at async Promise.allSettled (index 2)
    at async Uc (/home/user/Documents/project/.yarn/releases/yarn-4.0.1.cjs:140:53250)
➤ YN0000: └ Completed in 1s 444ms
➤ YN0000: · Failed with errors in 1s 468ms

### System information

Medusa version (including plugins):
Node.js version: 20
Database: Postgres
Operating system: Ubuntu

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
