### ISSUE TITLE
Error after updating from 1.12 to 1.18 when I add an item to the cart.

### ISSUE THREAD

**Issue by ensidialabs** [medusajs/medusa#5677]
## Bug report
error: error: column product.profile_id does not exist
QueryFailedError: column product.profile_id does not exist
    at PostgresQueryRunner.query (/app/medusa/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
    at async SelectQueryBuilder.getRawAndEntities (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async Promise.allSettled (index 0) {
  query: 'SELECT "product"."id" AS "product_id", "product"."created_at" AS "product_created_at", "product"."updated_at" AS "product_updated_at", "product"."title" AS "product_title", "product"."subtitle" AS "product_subtitle", "product"."description" AS "product_description", "product"."handle" AS "product_handle", "product"."is_giftcard" AS "product_is_giftcard", "product"."thumbnail" AS "product_thumbnail", "product"."weight" AS "product_weight", "product"."length" AS "product_length", "product"."height" AS "product_height", "product"."width" AS "product_width", "product"."hs_code" AS "product_hs_code", "product"."origin_country" AS "product_origin_country", "product"."mid_code" AS "product_mid_code", "product"."material" AS "product_material", "product"."type_id" AS "product_type_id", "product"."metadata" AS "product_metadata", "collection"."id" AS "collection_id", "collection"."created_at" AS "collection_created_at", "collection"."updated_at" AS "collection_updated_at", "collection"."deleted_at" AS "collection_deleted_at", "collection"."title" AS "collection_title", "collection"."handle" AS "collection_handle", "collection"."metadata" AS "collection_metadata", collection_id, product.profile_id FROM "public"."product" "product" LEFT JOIN "public"."product_collection" "collection" ON "collection"."id"="product"."collection_id" AND ("collection"."deleted_at" IS NULL) WHERE ( "product"."id" IN ($1) ) AND ( "product"."deleted_at" IS NULL )',
  parameters: [ 'prod_01H3C3BQKZADDWHZNN75TV1TY7' ],
  driverError: error: column product.profile_id does not exist
      at /app/medusa/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/app/medusa/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)
      at async SelectQueryBuilder.getRawAndEntities (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (/app/medusa/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
      at async Promise.allSettled (index 0) {
    length: 118,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '1189',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3601',
    routine: 'errorMissingColumn'
  },
  length: 118,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '1189',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3601',
  routine: 'errorMissingColumn'
}
### Describe the bug

The error occurs when I try to add an item to the cart.

### System information

Medusa version (including plugins): 1.18
All migrations done.

**Comment by olivermrbl** [comment]
The database relationship between Products and ShippingProfiles was changed in 1.13.0. 

Can I get you to ensure migrations are run? More specifically, please ensure the migration `addTableProductShippingProfile1680857773273` has been applied. 

You can check this by querying the migrations table in your database: `select * from migrations`

**Comment by ensidialabs** [comment]
@olivermrbl Checked. Yes, this migration has been applied successfully, it is in the database.
When I updated from 1.12 to 1.18, I added all migrations sequentially, there were no errors.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
