### ISSUE TITLE
Get a product with publishable key header

### ISSUE THREAD

**Issue by hampusboas** [medusajs/medusa#5724]
### Describe the bug

Hi, When i try to get a product who not exists with a publishable api key header set through the store API the api endpoint dies with following error: 

Error: Product with id: prod_01HFP4EY66W4KHDKV6HC1SXX4Ess was not found

at ProductService.<anonymous> (/app/node_modules/@medusajs/medusa/dist/services/product.js:322:35)

at step (/app/node_modules/@medusajs/medusa/dist/services/product.js:59:23)

at Object.next (/app/node_modules/@medusajs/medusa/dist/services/product.js:40:53)

at fulfilled (/app/node_modules/@medusajs/medusa/dist/services/product.js:31:58)

at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

type: 'not_found',

code: undefined,

date: 2023-11-27T09:29:33.531Z

}

When i run it through eg postman the services is not giving me a return and runs as a pending status.

### System information

Medusa version (including plugins): v1.18.0
Database: postgrees

### Steps to reproduce the behavior

1. Create a publishable key
2. Try to fetch a product who not exists through the store API with the publishable key header

### Expected behavior

A JSON Response similar to the 404 without the publishable header.

**Comment by hampusboas** [comment]
@pKorsholm Wow, thank you for fixing this ASAP!
