### ISSUE TITLE
API Route Validator extending issue

### ISSUE THREAD

**Issue by westwebdev** [medusajs/medusa#5924]
Hello, i've tried to extend system entity, and was succeed in it but, have some issues with extending validator

Context:
extending product entity, and moving through doc, was added new attribute and successfully displayed it in raw product object on admin product detail page.

But when i'd extended validator i caught error: 

```
error:   my_custom_attribute must be a string
Error: my_custom_attribute must be a string
    at /Users/admin/Raccoon/medusajs-test/medusa-azure/B2B/b2b-core/node_modules/@medusajs/medusa/dist/utils/validator.js:157:31
    at step (/Users/admin/Raccoon/medusajs-test/medusa-azure/B2B/b2b-core/node_modules/@medusajs/medusa/dist/utils/validator.js:44:23)
    at Object.next (/Users/admin/Raccoon/medusajs-test/medusa-azure/B2B/b2b-core/node_modules/@medusajs/medusa/dist/utils/validator.js:25:53)
    at fulfilled (/Users/admin/Raccoon/medusajs-test/medusa-azure/B2B/b2b-core/node_modules/@medusajs/medusa/dist/utils/validator.js:16:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid_data',
  code: undefined,
  date: 2023-12-18T17:56:12.665Z
}
```

Tried dig into validator and found a bit more info about it:

  ```
ValidationError {
    target: AdminGetProductParams { my_custom_attribute: undefined },
    value: undefined,
    property: 'my_custom_attribute',
    children: [],
    constraints: { isString: 'my_custom_attribute must be a string' }
  }
```
But in same time i see data in database and on page, so it should means that value of 'my_custom_attribute' in not empty, and have type 'string': 
![image](https://github.com/medusajs/medusa/assets/32311270/108b3deb-6ad2-48d4-96c5-ab27fc9c3530)

here is code examples: 

- related to validator:

```
// src/api/index.ts
import { registerOverriddenValidators } from "@medusajs/medusa";
import AdminGetProductParams from "./routes/admin/products/get-product";

registerOverriddenValidators(AdminGetProductParams);

```

```
// src/api/routes/admin/products/get-product.ts
import {AdminGetProductParams as MedusaAdminGetProductParams} from "@medusajs/medusa/dist/api/routes/admin/products/get-product"
import { IsString } from "class-validator"

class AdminGetProductParams extends MedusaAdminGetProductParams {
    @IsString()
    my_custom_attribute: string
}

export default AdminGetProductParams;

```

- related to extending system attribute:

```
// src/models/product.ts
import { Column, Entity } from "typeorm"
import { Product as MedusaProduct } from "@medusajs/medusa"

@Entity()
export class Product extends MedusaProduct {
    @Column()
    my_custom_attribute: string
}
```

```
// src/index.d.ts

export declare module "@medusajs/medusa/dist/models/product" {
    declare interface Product {
        my_custom_attribute: string;
    }
}

```

```
// src/migrations/1702653348231-ProductCustomAttr.ts

import { MigrationInterface, QueryRunner } from "typeorm"

export class ProductCustomAttr1702653348231 implements MigrationInterface {
    name = "ProductCustomAttr1702653348231";

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" ADD COLUMN "my_custom_attribute" character varying`)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "my_custom_attribute"`)
    }

}

```

```
// src/loaders/product-entity-extend.ts

export default async function () {
    const imports = (await import("@medusajs/medusa/dist/api/routes/admin/products/index")) as any;

    imports.defaultAdminProductFields = [
        ...imports.defaultAdminProductFields,
        "my_custom_attribute",
    ]
}

```

Dependencies from package.json

```
"dependencies": {
    "@medusajs/admin": "7.1.8",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "1.18.1",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.5",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.21",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.19",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  }
```

I will be thankful for any hint how to fix my issue with validator

**Comment by adrien2p** [comment]
There is an issue in your admin get product params. You are requesting the custom attr to be passed as part of the request which i don't think should be the case right? Here you are saying that when you hit the corresponding end point you must provide a value for the custom attr. It is not related to what is in the db but what mist be provided in the request such as limit, offset etc

**Comment by olivermrbl** [comment]
If it is intentional, you can use the `@IsOptional()` decorator to not require it on all requests.

Closing the issue as the current setup is the expected behavior.
