### ISSUE TITLE
esta fallando la pagina

### ISSUE THREAD

**Issue by dev7Tecclas** [medusajs/medusa#5968]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

lo siguiente es el error en consola:  main.3b555fb1.js:2 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at lc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1466848)
    at gc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1472000)
    at yc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1469075)
    at bc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1468757)
    at yc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1468870)
    at bc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1468757)
    at yc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1468870)
    at bc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1468757)
    at yc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1468870)
    at bc (https://docs.medusajs.com/assets/js/main.3b555fb1.js:2:1468757)
mo @ main.3b555fb1.js:2
VM235:168 Uncaught TypeError: Cannot read properties of undefined (reading 'gzip')
    at dp.ph (eval at xhr.onreadystatechange (overview:430:9), <anonymous>:168:470)
    at rm.flush (eval at xhr.onreadystatechange (overview:430:9), <anonymous>:70:138)
    at rm.eval (eval at xhr.onreadystatechange (overview:430:9), <anonymous>:66:445)
    at Wd (m=el_conf:524:469)
    at _.k.dispatchEvent (m=el_conf:523:373)
    at Xl.tick (eval at xhr.onreadystatechange (overview:430:9), <anonymous>:65:214)
    at eval (eval at xhr.onreadystatechange (overview:430:9), <anonymous>:64:349)

### How can this issue be resolved?

1.nose
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by adrien2p** [comment]
could you share the step to reproduce it, did you created a custom component to insert?

**Comment by olivermrbl** [comment]
As Adrien touches upon, this issue does not meet the requirements described in the issue template. Closing until further details have been provided.
