### ISSUE TITLE
When I try starting the server using the medusa-file-spaces plugin in 'feat/deploy-heroku' branch it crushes with this Initializing pluginsTypeError

### ISSUE THREAD

**Issue by ikritiuk** [medusajs/medusa#6005]
**Describe the bug**

When I run the server I get this error:

Initializing pluginsTypeError: Super expression must either be null or a function
    at _inherits (/Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/medusa-file-spaces/services/digital-ocean.js:27:113)
    at /Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/medusa-file-spaces/services/digital-ocean.js:35:3
    at Object.<anonymous> (/Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/medusa-file-spaces/services/digital-ocean.js:245:2)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/@medusajs/medusa/dist/loaders/plugins.js:302:50
    at step (/Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (/Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
    at /Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/@medusajs/medusa/dist/loaders/plugins.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/@medusajs/medusa/dist/loaders/plugins.js:4:12)
    at /Users/ilya.krityuk/WebstormProjects/medusa-starter-default/node_modules/@medusajs/medusa/dist/loaders/plugins.js:296:87

**A clear and concise description of what the bug is.**

System information
Medusa version (including plugins):
Node.js version:v16.13.0
Database: postgresql 13.10
Operating system: macOs 13.6.1 (22G313)
Browser (if relevant): Chrome
medusa-file-spaces: "^1.4.0"

**Steps to reproduce the behavior**
checkout  'feat/deploy-heroku' branch
Follow this integration steps: [(https://docs.medusajs.com/plugins/file-service/spaces)]
Go to server directory
run: npm start
See error
Expected behavior
server is started

**Comment by olivermrbl** [comment]
Why are you using this specific branch? You should always use the default branch of the starter, as this is stable.
