### ISSUE TITLE
medusa develop on windows -  stdin compilation requires either

### ISSUE THREAD

**Issue by luluhoc** [medusajs/medusa#6024]
### Describe the bug

when trying to run medusa develop on windows i'm getting this error on mac it is working..

```
babel:
  stdin compilation requires either -f/--filename [filename] or --no-babelrc
Error: Command failed: "C:\Users\admin\Desktop\ecomm-stack\retro\node_modules\@babel\cli\bin\babel.js" src -d dist --ignore "src/admin/**"
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at C:\Users\admin\Desktop\ecomm-stack\retro\node_modules\@medusajs\medusa\dist\commands\develop.js:120:42
    at step (C:\Users\admin\Desktop\ecomm-stack\retro\node_modules\@medusajs\medusa\dist\commands\develop.js:44:23)
    at Object.next (C:\Users\admin\Desktop\ecomm-stack\retro\node_modules\@medusajs\medusa\dist\commands\develop.js:25:53)
    at C:\Users\admin\Desktop\ecomm-stack\retro\node_modules\@medusajs\medusa\dist\commands\develop.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\admin\Desktop\ecomm-stack\retro\node_modules\@medusajs\medusa\dist\commands\develop.js:15:12)
    at default_1 (C:\Users\admin\Desktop\ecomm-stack\retro\node_modules\@medusajs\medusa\dist\commands\develop.js:93:12) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 23972,
  stdout: null,
  stderr: null
}
Done in 8.06s.

```

### System information

Medusa version (including plugins): 1.19.0
Node.js version: 18.12.1
Database: postgres
Operating system: windows 10
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Can you please try to install the latest version and run the command again?

**Comment by luluhoc** [comment]
> Can you please try to install the latest version and run the command again?

@olivermrbl 1.20.0 fixed it
