### ISSUE TITLE
Cannot build medusa for local development on WSL

### ISSUE THREAD

**Issue by ivanushkaPr** [medusajs/medusa#6118]
### Describe the bug

After running build commang on wsl, then trying to build cloned repo for local development Yarn throws error.
Because he cannot parse the following code snippet  SyntaxError: Unexpected token '??='

### System information

Medusa version (including plugins):
Node.js version: v14.21.3
Yarn version:  3.2.1
Database:
Operating system: WSL - Ubuntu.

### Steps to reproduce the behavior

1. Install WSL(Default ubuntu)
2. Install VsCode
3. Install WSL VCcode extension.
4. Open directory on wsl.
5. Fork medusa repo.
6. Clone medusa repo.
7. Run yarn install
8. Run yarn build
9. Get following bug:

@medusajs/vite-plugin-extension:build: /home/superadmin/medusa/packages/admin-next/vite-plugin-extension/node_modules/rollup/dist/shared/rollup.js:58
@medusajs/vite-plugin-extension:build:             textEncoder ??= new TextEncoder();
@medusajs/vite-plugin-extension:build:                         ^^^
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build: SyntaxError: Unexpected token '??='
@medusajs/vite-plugin-extension:build:     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
@medusajs/vite-plugin-extension:build:     at Module._compile (internal/modules/cjs/loader.js:1078:27)
@medusajs/vite-plugin-extension:build:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
@medusajs/vite-plugin-extension:build:     at Module.load (internal/modules/cjs/loader.js:979:32)
@medusajs/vite-plugin-extension:build:     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
@medusajs/vite-plugin-extension:build:     at Module.require (internal/modules/cjs/loader.js:1003:19)
@medusajs/vite-plugin-extension:build:     at require (internal/modules/cjs/helpers.js:107:18)
@medusajs/vite-plugin-extension:build:     at Module.<anonymous> (/home/superadmin/medusa/packages/admin-next/vite-plugin-extension/node_modules/rollup/dist/rollup.js:14:16)

### Expected behavior

Succesfull installation for local development.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/26376786/0fcdc84c-45f1-4f75-a1b7-5401619d620f)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by ivanushkaPr** [comment]
After changing nvm version to 18, its all works correctly.
