### ISSUE TITLE
Unable to build admin

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#6364]
Hi,

i am unable to build the admin . the error i get 

```

Error: 
  × The left-hand side of an assignment expression must be a variable or a property access.
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────

  × Invalid assignment target
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────


Caused by:
    0: failed to parse input file
    1: Syntax Error
HookWebpackError: 
  × The left-hand side of an assignment expression must be a variable or a property access.
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────

  × Invalid assignment target
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────


Caused by:
    0: failed to parse input file
    1: Syntax Error
    at makeWebpackError (/X/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /X/node_modules/webpack/lib/Compilation.js:3075:12
    at eval (eval at create (/X/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:55:1)
-- inner error --
Error: 
  × The left-hand side of an assignment expression must be a variable or a property access.
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────

  × Invalid assignment target
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────


Caused by:
    0: failed to parse input file
    1: Syntax Error
caused by plugins in Compilation.hooks.processAssets
Error: 
  × The left-hand side of an assignment expression must be a variable or a property access.
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────

  × Invalid assignment target
      ╭─[7705:1]
 7705 │             },
 7706 │         },
 7707 │         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 7708 │             "production" = "production" || 0;
      ·             ────────────
 7709 │             return cmd(args);
 7710 │         })),
 7711 │     })
      ╰────


Caused by:
    0: failed to parse input file
    1: Syntax Error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Medusa Veration 1.20.2
admin version @medusajs/admin@7.1.11"

**Comment by SGFGOV** [comment]
This was due to an error in my code where I'd imported from @medusas/medusa instead of @medusajs/types
