### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Kushal-starr** [medusajs/medusa#6553]
While I'm running my staging server giving me the below error:

**Could not resolve module: cartCartSalesChannelSalesChannelLink. Error: Loaders for module cartCartSalesChannelSalesChannelLink failed: Class extends value undefined is not a constructor or null

Error initializing link modules. TypeError: Cannot set properties of undefined (setting '__definition')
    at MedusaModule.bootstrapLink (/var/sites/medusa-staging/medusa-api/node_modules/@medusajs/modules-sdk/dist/medusa-module.js:234:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initialize (/var/sites/medusa-staging/medusa-api/node_modules/@medusajs/link-modules/dist/initialize/index.js:90:24)
    at async initializeLinks (/var/sites/medusa-staging/medusa-api/node_modules/@medusajs/modules-sdk/dist/medusa-app.js:92:32)
    at async MedusaApp (/var/sites/medusa-staging/medusa-api/node_modules/@medusajs/modules-sdk/dist/medusa-app.js:165:81)**

With the same configs my local running fine. 

I haven't done any changes related to cart/salechannel mentioned above in the error.

Any helping hand will be appreciated!!!!!!

**Comment by ahonore42** [comment]
I am experiencing the same issue when running migrations in version 1.20 with:

```
npx medusa migrations run
```

Nothing has changed regarding the project structure and the error seems to be coming directly from `@medusajs`.

```
Could not resolve module: cartCartSalesChannelSalesChannelLink. Error: Loaders for module cartCartSalesChannelSalesChannelLink failed: Class extends value undefined is not a constructor or null

Error initializing link modules. TypeError: Cannot set properties of undefined (setting '__definition')
    at MedusaModule.bootstrapLink (node_modules/@medusajs/modules-sdk/dist/medusa-module.js:234:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initialize (node_modules/@medusajs/link-modules/dist/initialize/index.js:90:24)
    at async initializeLinks (node_modules/@medusajs/modules-sdk/dist/medusa-app.js:92:32)
    at async MedusaApp (node_modules/@medusajs/modules-sdk/dist/medusa-app.js:165:81)
   ```

**Comment by Kushal-starr** [comment]
[like]  Kushal Jain reacted to your message:
________________________________

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
