### ISSUE TITLE
Docs(Code Issue): Code Issue in /plugins/other/wishlist

### ISSUE THREAD

**Issue by Honest0** [medusajs/medusa#6615]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

medusa-plugin-wishlist plugin is old version. Can't install this plugin in newest medusa starter project

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: medusa-starter-default@0.0.1
npm ERR! Found: medusa-interfaces@1.3.8
npm ERR! node_modules/medusa-interfaces
npm ERR!   medusa-interfaces@"^1.3.8" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer medusa-interfaces@"1.3.7" from medusa-plugin-wishlist@1.1.43
npm ERR! node_modules/medusa-plugin-wishlist
npm ERR!   medusa-plugin-wishlist@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by suganyasai1026** [comment]
hi , 
it has been installed with some waring 
warning " > medusa-payment-paytm@1.0.0" has incorrect peer dependency "@medusajs/medusa@latest".
warning " > medusa-payment-paytm@1.0.0" has incorrect peer dependency "medusa-interfaces@latest".
warning " > medusa-payment-phonepe@1.1.46-next-v6" has unmet peer dependency "api@^6.1.0".
warning " > medusa-payment-phonepe@1.1.46-next-v6" has unmet peer dependency "axios@0.27".
warning " > medusa-payment-phonepe@1.1.46-next-v6" has unmet peer dependency "medusa-core-utils@^1.2.0".
warning " > medusa-react@9.0.15" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning " > ts-loader@9.5.1" has unmet peer dependency "webpack@^5.0.0".
warning " > medusa-plugin-wishlist@1.1.43" has incorrect peer dependency "medusa-interfaces@1.3.7".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ medusa-plugin-wishlist@1.1.43
info All dependencies
└─ medusa-plugin-wishlist@1.1.43


but while checking with api calls its showing error 
localhost:9000/store/customers/<CUSTOMERID>/wishlist



Error: Unable to generate the line item because one or more required argument(s) are missing. Ensure quantity, regionId, and variantId are passed
    at LineItemService.validateGenerateArguments (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\services\line-item.js:631:23)
    at LineItemService.<anonymous> (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\services\line-item.js:270:46)
    at step (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\services\line-item.js:59:23)
    at Object.next (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\services\line-item.js:40:53)
    at E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\services\line-item.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\services\line-item.js:30:12)
    at E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\services\line-item.js:263:107
    at LineItemService.<anonymous> (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:140:62)
    at step (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:33:23)
    at Object.next (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:14:53)
    at E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:8:71        
    at new Promise (<anonymous>)
    at __awaiter (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:4:12)
    at doWork_1 (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:130:58)
    at LineItemService.<anonymous> (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:183:55)
    at step (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:33:23)
    at Object.next (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:14:53)
    at E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:8:71        
    at new Promise (<anonymous>)
    at __awaiter (E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:4:12)
    at E:\voltix\medusa project\e-commerce-api\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:182:94 {    
  type: 'invalid_data',
  code: undefined,
  date: 2024-03-11T12:29:05.755Z
}

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
