### ISSUE TITLE
Medusa vercel-commerce installation fails

### ISSUE THREAD

**Issue by Tkko** [medusajs/medusa#6673]
### Describe the bug

I'm trying to run [Next.js Commerce](https://vercel.com/templates/next.js/nextjs-commerce)  project with [Medusa](https://github.com/medusajs/vercel-commerce) locally but the installation command:

    npx create-medusa-app@nextjs-commerce

throws an error:

```
npx create-medusa-app@nextjs-commerce
✔ Where should your project be installed? · ttt
⠴ Creating new project from git: https://github.com/medusajs/medusa-vercel-commerce.git
✔ Created starter directory layout

⠼ Installing packages...
✔ Packages installed
Error: Command failed with exit code 1: npm install
    at gt (/Users/tornike/.npm/_npx/b25226fc149cf28a/node_modules/create-medusa-app/dist/index.js:1:113620)
    at /Users/tornike/.npm/_npx/b25226fc149cf28a/node_modules/create-medusa-app/dist/index.js:1:123343
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async js (/Users/tornike/.npm/_npx/b25226fc149cf28a/node_modules/create-medusa-app/dist/index.js:1:183921)
    at async /Users/tornike/.npm/_npx/b25226fc149cf28a/node_modules/create-medusa-app/dist/index.js:1:185433
    at async Is (/Users/tornike/.npm/_npx/b25226fc149cf28a/node_modules/create-medusa-app/dist/index.js:1:184931)
    at async exports.run (/Users/tornike/.npm/_npx/b25226fc149cf28a/node_modules/create-medusa-app/dist/index.js:1:497534) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Note that the issue creation is disabled in the [Medusa repository](https://github.com/medusajs/vercel-commerce)

### System information

Medusa version (including plugins):
Node.js version: v20.11.0
Database:
Operating system: Mac OS 14.4
Browser (if relevant):

### Steps to reproduce the behavior

1. run 
`npx create-medusa-app@nextjs-commerce`

**Comment by thejufo** [comment]
Facing the same issue here

**Comment by SubhrajitDG** [comment]
Facing same issue. Anyone found a solution?

**Comment by Joker9090** [comment]
Same issue with node:
v16.20.2
v18.18.2
v20.8.0

**Comment by victorraguin** [comment]
Still the same issue...

**Comment by robin-scharf** [comment]
Still happening.
