### ISSUE TITLE
PayPal initiatePayment error 

### ISSUE THREAD

**Issue by samhenderson511** [medusajs/medusa#6714]
### Describe the bug

When selecting paypal as the payment provider in checkout (using nextjs starter) I get this error in the backend:

```
Error: An error occurred in initiatePayment:
An error occurred while requesting Paypal API after 2 attempts
    at PaymentProviderService.throwFromPaymentProcessorError (/Users/samhenderson/Development/arkive-backend/node_modules/@medusajs/medusa/dist/services/payment-provider.js:1052:15)
    at PaymentProviderService.<anonymous> (/Users/samhenderson/Development/arkive-backend/node_modules/@medusajs/medusa/dist/services/payment-provider.js:285:50)
    at step (/Users/samhenderson/Development/arkive-backend/node_modules/@medusajs/medusa/dist/services/payment-provider.js:48:23)
    at Object.next (/Users/samhenderson/Development/arkive-backend/node_modules/@medusajs/medusa/dist/services/payment-provider.js:29:53)
    at fulfilled (/Users/samhenderson/Development/arkive-backend/node_modules/@medusajs/medusa/dist/services/payment-provider.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid_data',
  code: '',
  date: 2024-03-16T12:35:49.987Z
}
```

I've double and triple checked the Paypal client ID, client secret and sandbox boolean so I'm not sure why it isn't working

### System information

Medusa version (including plugins):
```
    "@medusajs/admin": "7.1.11",
    "@medusajs/cache-inmemory": "^1.8.10",
    "@medusajs/cache-redis": "^1.9.0",
    "@medusajs/event-bus-local": "^1.9.8",
    "@medusajs/event-bus-redis": "^1.8.11",
    "@medusajs/file-local": "^1.0.3",
    "@medusajs/medusa": "1.20.2",
    "medusa-file-s3": "^1.4.1",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.8",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-paypal": "^6.0.2",
    "medusa-payment-stripe": "^6.0.7",
    "medusa-plugin-algolia": "^0.2.20",
    "medusa-plugin-sendgrid": "^1.3.12",
    "medusa-plugin-variant-images": "^1.0.5",
    "medusa-plugin-wishlist": "^1.1.43",
```
Node.js version: 20.11.1
Database: postgres
Operating system: MacOS
Browser (if relevant):

### Steps to reproduce the behavior

<img width="851" alt="Screenshot 2024-03-16 at 12 47 09" src="https://github.com/medusajs/medusa/assets/86521077/285b8444-b486-4236-aaaa-7b718ff5ddfc">

1. Select Paypal as the provider
2. See console logs in the backend

### Expected behavior

A paypal button should appear to complete the payment

logging the payment session here:
```
        {Boolean(cart?.payment_sessions?.length) &&
          cart.payment_sessions
            .filter(Boolean)
            .sort((a, b) => {
              return a.provider_id > b.provider_id ? 1 : -1
            })
            .map((paymentSession) => {
              return (
                <PaymentContainer
                  paymentSession={paymentSession}
                  key={paymentSession.id}
                  selected={
                    cart?.payment_session?.provider_id ===
                    paymentSession.provider_id
                  }
                  setSelected={() => {
                    console.log("setPaymentSession", paymentSession)
                    return setPaymentSession(paymentSession.provider_id)
                  }}
                />
              )
            })}
```

```
{
    "id": "ps_01HS3KVF8M336RZFKYF1CT35NQ",
    "created_at": "2024-03-16T12:30:12.231Z",
    "updated_at": "2024-03-16T12:32:10.068Z",
    "cart_id": "cart_01HS3KSJKY2ZA4YMJ1PT4TQMQK",
    "provider_id": "paypal",
    "is_selected": null,
    "is_initiated": false,
    "status": "pending",
    "data": {},
    "idempotency_key": null,
    "amount": 2999,
    "payment_authorized_at": null
}
```

**Comment by rkmcdonnell** [comment]
I am also seeing this - anyone found a fix?  Sandbox mode works perfectly, but as soon as environment variables are reconfigured to live, I see this issue.

**Comment by ggboypro** [comment]
About paypal live failure solution
The problem comes from the judgment of `PAYPAL_SANDBOX` in `env`. You only need to set it to empty to handle the payment problem.

**Comment by JinFoolish** [comment]
> About paypal live failure solution The problem comes from the judgment of `PAYPAL_SANDBOX` in `env`. You only need to set it to empty to handle the payment problem.

Thanks for your answer!! I almost get headache by this question.
