### ISSUE TITLE
Medusa migrations run bug after update to 1.20.4

### ISSUE THREAD

**Issue by ensidialabs** [medusajs/medusa#6835]
## Bug report
```npx medusa migrations run
query: SELECT * FROM current_schema()
query: SELECT version();
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "public"."migrations" "migrations" ORDER BY "id" DESC
77 migrations are already loaded in the database.
78 migrations were found in the source code.
PublishableKeySalesChannelLink1701894188811 is the last executed migration. It was executed on Wed Dec 06 2023 22:23:08 GMT+0200 (Eastern European Standard Time).
1 migrations are new migrations must be executed.
query: START TRANSACTION
query: 
      ALTER TABLE "customer" DROP CONSTRAINT "UQ_unique_email_for_guests_and_customer_accounts";

      CREATE UNIQUE INDEX "IDX_unique_email_for_guests_and_customer_accounts" ON "customer" ("email", "has_account") WHERE "deleted_at" IS NULL;
    
query: INSERT INTO "public"."migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1709888477798,"AlterCustomerUniqueConstraint1709888477798"]
Migration AlterCustomerUniqueConstraint1709888477798 has been  executed successfully.
query: COMMIT
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
warn:    Local Event Bus installed. This is not recommended for production.
warn:    Could not resolve module: orderOrderSalesChannelSalesChannelLink. Error: Loaders for module orderOrderSalesChannelSalesChannelLink failed: Cannot read properties of undefined (reading 'className')

Error initializing link modules. TypeError: Cannot set properties of undefined (setting '__definition')
    at MedusaModule.bootstrapLink (/project/node_modules/.pnpm/@medusajs+modules-sdk@1.12.10_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/dist/medusa-module.js:249:44)
    at async initialize (/project/node_modules/.pnpm/@medusajs+link-modules@0.2.10_@types+node@17.0.45_pg@8.11.3/node_modules/@medusajs/link-modules/dist/initialize/index.js:101:24)
    at async initializeLinks (/project/node_modules/.pnpm/@medusajs+modules-sdk@1.12.10_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/dist/medusa-app.js:99:32)
    at async MedusaApp_ (/project/node_modules/.pnpm/@medusajs+modules-sdk@1.12.10_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/dist/medusa-app.js:183:64)
    at async MedusaApp (/project/node_modules/.pnpm/@medusajs+modules-sdk@1.12.10_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/dist/medusa-app.js:230:16)
```
### System information

Medusa version (including plugins): 1.20.4
Node.js version: 20.11.1
Database: pg
Operating system: linux

### Steps to reproduce the behavior

1. Update packages to 1.20.4
2. Run "npx medusa migrations run"

**Comment by ensidialabs** [comment]
After deleting the node_modules folder and reinstalling npm run install. Everything was successful. I don't know what it was.

**Comment by Skwarek71830** [comment]
Solution for me (fixed the mentioned error, as well as "GraphQLError: Syntax Error: Unexpected .") and Module x not found in over 1400 places:

-  sync medusa related packages with medusa-starter template
-  remove unnecessary @medusajs/utils from package.json
-  medusa version changed from 1.20.0 to medusa 1.20.7
-  shamefully-hoist=true (in .npmrc)
