### ISSUE TITLE
Error starting fresh install with medusa_v2 enabled

### ISSUE THREAD

**Issue by guyathomas** [medusajs/medusa#7021]
## Bug report
`yarn dev` crashes when `medusa_v2` is enabled. I'm aware this is experimental - but I wanted to flag it.

### Describe the bug

With a fresh install of Medusa, running the server with `yarn dev` crashes with the following stack trace. I'm unsure of the root cause, but it seems like it can't resolve on the `sales-channel` module.

```
Error starting server
Error: Cannot read properties of undefined (reading 'list')
TypeError: Cannot read properties of undefined (reading 'list')
    at exports.createDefaultSalesChannelStep.async.container.container (/Users/guy/src/test-v2/node_modules/@medusajs/core-flows/dist/sales-channel/steps/create-default-sales-channel.js:10:52)
    at Object.invoke (/Users/guy/src/test-v2/node_modules/@medusajs/workflows-sdk/dist/utils/composer/create-step.js:41:53)
    at async DistributedTransaction.handler (/Users/guy/src/test-v2/node_modules/@medusajs/orchestration/dist/workflow/workflow-manager.js:83:24)
    at async Promise.allSettled (index 0)
    at originalExecution (/Users/guy/src/test-v2/node_modules/@medusajs/workflows-sdk/dist/helper/workflow-export.js:31:19)
    at async LocalWorkflow.newRun [as run] (/Users/guy/src/test-v2/node_modules/@medusajs/workflows-sdk/dist/helper/workflow-export.js:71:16
```

### System information

Medusa version (including plugins): 1.20.4
Node.js version: 20.12.1
Database: PostgreSQL
Operating system: Sonoma 14.4.1
Browser (if relevant): N/A

### Steps to reproduce the behavior

1. Create a fresh setup with `npx create-medusa-app@latest`
2. Add the product and pricing modules `yarn add @medusajs/product; yarn add @medusajs/pricing`
3. Add the flag into `medusa-config.js` with `featureFlags: {medusa_v2: true}`
4. Run `yarn dev`

### Expected behavior

The server should start successfully.

**Comment by kanrio** [comment]
did you find a solution ?

**Comment by olivermrbl** [comment]
Thanks for flagging this @guyathomas. We will soon share a version, you can successfully give a spin! :D
