### ISSUE TITLE
A bug occurs in the remote connection to pgsql

### ISSUE THREAD

**Issue by czw333221** [medusajs/medusa#7104]
### Describe the bug

Password authentication failed for user

### Steps to reproduce the behavior

1.The DATABASE_URL of .env is changed from the local pgsql URL to the remote pgsql URL
2.npx medusa user --email admin@medusa-test.com --password supersecret

### Expected behavior

create new admin user 

### Screenshots

![image](https://github.com/medusajs/medusa/assets/134688991/d23ce10a-259a-4277-a5dd-6bc65818849a)

### Additional context

error: Password authentication failed for user
    at Parser.parseErrorMessage (D:\programming\code\my-medusa-store\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (D:\programming\code\my-medusa-store\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (D:\programming\code\my-medusa-store\node_modules\pg-protocol\dist\parser.js:39:38)
    at TLSSocket.<anonymous> (D:\programming\code\my-medusa-store\node_modules\pg-protocol\dist\index.js:11:42)
    at TLSSocket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 46,
  severity: undefined,
  code: undefined,
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: undefined,
  line: undefined,
  routine: undefined
}

**Comment by czw333221** [comment]
I accidentally set the wrong password.
