### ISSUE TITLE
Yarn Build fails.

### ISSUE THREAD

**Issue by Crymzix** [medusajs/medusa#7167]
### Describe the bug

Following the documentation specified here: https://docs.medusajs.com/development/fundamentals/local-development
does not result in successfully building the `medusa` project locally.

### System information

Medusa version (including plugins): develop (commit 82cb6cfd361db4147584b0073cfd01ff100a52e6)
Node.js version: v18.17.0
Yarn version: 3.2.1
Database: PostgreSQL
Operating system: macOS Sonoma 14.0

### Steps to reproduce the behavior

1. Clone `medusa` via `git clone https://github.com/medusajs/medusa.git`
2. cd into `medusa` folder
3. Run `yarn install`
4. Run `yarn build`

### Expected behavior

The build should succeed.

### Code snippets
Log below:
```
• Packages in scope: @medusajs/admin, @medusajs/admin-bundler, @medusajs/admin-shared, @medusajs/admin-ui, @medusajs/api-key, @medusajs/auth, @medusajs/cache-inmemory, @medusajs/cache-redis, @medusajs/cart, @medusajs/client-types, @medusajs/core-flows, @medusajs/currency, @medusajs/customer, @medusajs/dashboard, @medusajs/event-bus-local, @medusajs/event-bus-redis, @medusajs/file, @medusajs/file-local, @medusajs/file-local-next, @medusajs/file-s3, @medusajs/fulfillment, @medusajs/fulfillment-manual, @medusajs/icons, @medusajs/inventory, @medusajs/inventory-next, @medusajs/link-modules, @medusajs/medusa, @medusajs/medusa-cli, @medusajs/medusa-js, @medusajs/medusa-oas-cli, @medusajs/modules-sdk, @medusajs/oas-github-ci, @medusajs/openapi-typescript-codegen, @medusajs/orchestration, @medusajs/order, @medusajs/payment, @medusajs/payment-stripe, @medusajs/pricing, @medusajs/product, @medusajs/promotion, @medusajs/region, @medusajs/sales-channel, @medusajs/stock-location, @medusajs/stock-location-next, @medusajs/store, @medusajs/tax, @medusajs/toolbox, @medusajs/types, @medusajs/ui, @medusajs/ui-preset, @medusajs/user, @medusajs/utils, @medusajs/vite-plugin-extension, @medusajs/workflow-engine-inmemory, @medusajs/workflow-engine-redis, @medusajs/workflows-sdk, babel-preset-medusa-package, create-medusa-app, gatsby-source-medusa, integration-tests-api, integration-tests-modules, integration-tests-plugins, integration-tests-repositories, medusa-core-utils, medusa-dev-cli, medusa-file-minio, medusa-file-s3, medusa-file-spaces, medusa-fulfillment-manual, medusa-fulfillment-webshipper, medusa-interfaces, medusa-payment-adyen, medusa-payment-klarna, medusa-payment-manual, medusa-payment-paypal, medusa-payment-stripe, medusa-plugin-algolia, medusa-plugin-brightpearl, medusa-plugin-contentful, medusa-plugin-discount-generator, medusa-plugin-economic, medusa-plugin-ip-lookup, medusa-plugin-mailchimp, medusa-plugin-meilisearch, medusa-plugin-restock-notification, medusa-plugin-segment, medusa-plugin-sendgrid, medusa-plugin-slack-notification, medusa-plugin-twilio-sms, medusa-plugin-wishlist, medusa-react, medusa-source-shopify, medusa-telemetry, medusa-test-utils
• Running build in 94 packages
• Remote caching disabled
@medusajs/toolbox:build: cache miss, executing d1eec2418ee80051
@medusajs/types:build: cache miss, executing 422867890d0309a0
@medusajs/admin-shared:build: cache hit, replaying logs 6de14e2fc9bea68c
@medusajs/openapi-typescript-codegen:build: cache hit, replaying logs cc57fb5b5587d43a
@medusajs/openapi-typescript-codegen:build: 
@medusajs/openapi-typescript-codegen:build: ./src/index.ts → ./dist/index.js...
@medusajs/openapi-typescript-codegen:build: created ./dist/index.js in 1.8s
@medusajs/vite-plugin-extension:build: cache miss, executing 06b8fd0eb875772a
gatsby-source-medusa:build: cache hit, replaying logs a00ee493847b924d
medusa-core-utils:build: cache hit, replaying logs 104c3fa3cf182d87
medusa-dev-cli:build: cache hit, replaying logs 7566bc03036a8a92
medusa-telemetry:build: cache hit, replaying logs 4e792f01e4c087c9
medusa-telemetry:build: Successfully compiled 13 files with Babel (713ms).
create-medusa-app:build: cache hit, replaying logs 360847550f318a08
@medusajs/toolbox:build: CLI Building entry: src/index.ts
@medusajs/toolbox:build: CLI Using tsconfig: tsconfig.json
@medusajs/toolbox:build: CLI tsup v7.1.0
@medusajs/toolbox:build: CLI Using tsup config: /Users/chrisli/Documents/medusa/packages/design-system/toolbox/tsup.config.ts
@medusajs/toolbox:build: CLI Target: node16
@medusajs/toolbox:build: CLI Cleaning output folder
@medusajs/toolbox:build: ESM Build start
@medusajs/toolbox:build: CJS Build start
@medusajs/toolbox:build: ✘ [ERROR] Could not resolve "axios-retry"
@medusajs/toolbox:build: 
@medusajs/toolbox:build:     src/figma/client.ts:2:23:
@medusajs/toolbox:build:       2 │ import axiosRetry from "axios-retry"
@medusajs/toolbox:build:         ╵                        ~~~~~~~~~~~~~
@medusajs/toolbox:build: 
@medusajs/toolbox:build:   The Yarn Plug'n'Play manifest forbids importing "axios-retry" here because it's not listed as a dependency of this package:
@medusajs/toolbox:build: 
@medusajs/toolbox:build:     ../../../../../.pnp.cjs:36:31:
@medusajs/toolbox:build:       36 │         "packageDependencies": [\
@medusajs/toolbox:build:          ╵                                ~~
@medusajs/toolbox:build: 
@medusajs/toolbox:build:   You can mark the path "axios-retry" as external to exclude it from the bundle, which will remove this error.
@medusajs/toolbox:build: 
@medusajs/toolbox:build: ESM Build failed
@medusajs/toolbox:build: Error: Build failed with 1 error:
@medusajs/toolbox:build: src/figma/client.ts:2:23: ERROR: Could not resolve "axios-retry"
@medusajs/toolbox:build:     at failureErrorWithLog (/Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:1649:15)
@medusajs/toolbox:build:     at /Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:1058:25
@medusajs/toolbox:build:     at runOnEndCallbacks (/Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:1484:45)
@medusajs/toolbox:build:     at buildResponseToResult (/Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:1056:7)
@medusajs/toolbox:build:     at /Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:1085:16
@medusajs/toolbox:build:     at responseCallbacks.<computed> (/Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:703:9)
@medusajs/toolbox:build:     at handleIncomingPacket (/Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:762:9)
@medusajs/toolbox:build:     at Socket.readFromStdout (/Users/chrisli/Documents/medusa/node_modules/esbuild/lib/main.js:679:7)
@medusajs/toolbox:build:     at Socket.emit (node:events:514:28)
@medusajs/toolbox:build:     at addChunk (node:internal/streams/readable:324:12)
@medusajs/toolbox:build: ✘ [ERROR] Could not resolve "axios-retry"
@medusajs/toolbox:build: 
@medusajs/toolbox:build:     src/figma/client.ts:2:23:
@medusajs/toolbox:build:       2 │ import axiosRetry from "axios-retry"
@medusajs/toolbox:build:         ╵                        ~~~~~~~~~~~~~
@medusajs/toolbox:build: 
@medusajs/toolbox:build:   The Yarn Plug'n'Play manifest forbids importing "axios-retry" here because it's not listed as a dependency of this package:
@medusajs/toolbox:build: 
@medusajs/toolbox:build:     ../../../../../.pnp.cjs:36:31:
@medusajs/toolbox:build:       36 │         "packageDependencies": [\
@medusajs/toolbox:build:          ╵                                ~~
@medusajs/toolbox:build: 
@medusajs/toolbox:build:   You can mark the path "axios-retry" as external to exclude it from the bundle, which will remove this error.
@medusajs/toolbox:build: 
@medusajs/toolbox:build: CJS Build failed
@medusajs/toolbox:build: DTS Build start
@medusajs/vite-plugin-extension:build: CLI Building entry: ./src/index.ts
@medusajs/vite-plugin-extension:build: CLI Using tsconfig: tsconfig.json
@medusajs/vite-plugin-extension:build: CLI tsup v8.0.1
@medusajs/vite-plugin-extension:build: CLI Using tsup config: /Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/tsup.config.ts
@medusajs/vite-plugin-extension:build: CLI Target: es2020
@medusajs/vite-plugin-extension:build: CJS Build start
@medusajs/vite-plugin-extension:build: ESM Build start
@medusajs/vite-plugin-extension:build: ✘ [ERROR] Could not resolve "@medusajs/admin-shared"
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:     src/index.ts:17:46:
@medusajs/vite-plugin-extension:build:       17 │ ...rt { InjectionZone, injectionZones } from "@medusajs/admin-shared"
@medusajs/vite-plugin-extension:build:          ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:   The Yarn Plug'n'Play manifest forbids importing "@medusajs/admin-shared" here because it's not listed as a dependency of this package:
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:     ../../../../../.pnp.cjs:36:31:
@medusajs/vite-plugin-extension:build:       36 │         "packageDependencies": [\
@medusajs/vite-plugin-extension:build:          ╵                                ~~
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:   You can mark the path "@medusajs/admin-shared" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build: ✘ [ERROR] Could not resolve "@medusajs/admin-shared"
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:     src/index.ts:17:46:
@medusajs/vite-plugin-extension:build:       17 │ ...rt { InjectionZone, injectionZones } from "@medusajs/admin-shared"
@medusajs/vite-plugin-extension:build:          ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:   The Yarn Plug'n'Play manifest forbids importing "@medusajs/admin-shared" here because it's not listed as a dependency of this package:
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:     ../../../../../.pnp.cjs:36:31:
@medusajs/vite-plugin-extension:build:       36 │         "packageDependencies": [\
@medusajs/vite-plugin-extension:build:          ╵                                ~~
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build:   You can mark the path "@medusajs/admin-shared" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
@medusajs/vite-plugin-extension:build: 
@medusajs/vite-plugin-extension:build: ESM Build failed
@medusajs/vite-plugin-extension:build: Error: Build failed with 1 error:
@medusajs/vite-plugin-extension:build: src/index.ts:17:46: ERROR: Could not resolve "@medusajs/admin-shared"
@medusajs/vite-plugin-extension:build:     at failureErrorWithLog (/Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:1651:15)
@medusajs/vite-plugin-extension:build:     at /Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:1059:25
@medusajs/vite-plugin-extension:build:     at runOnEndCallbacks (/Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:1486:45)
@medusajs/vite-plugin-extension:build:     at buildResponseToResult (/Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:1057:7)
@medusajs/vite-plugin-extension:build:     at /Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:1086:16
@medusajs/vite-plugin-extension:build:     at responseCallbacks.<computed> (/Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:704:9)
@medusajs/vite-plugin-extension:build:     at handleIncomingPacket (/Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:764:9)
@medusajs/vite-plugin-extension:build:     at Socket.readFromStdout (/Users/chrisli/Documents/medusa/packages/admin-next/vite-plugin-extension/node_modules/esbuild/lib/main.js:680:7)
@medusajs/vite-plugin-extension:build:     at Socket.emit (node:events:514:28)
@medusajs/vite-plugin-extension:build:     at addChunk (node:internal/streams/readable:324:12)
@medusajs/vite-plugin-extension:build: CJS Build failed
@medusajs/vite-plugin-extension:build: DTS Build start
@medusajs/toolbox:build: DTS ⚡️ Build success in 1664ms
@medusajs/toolbox:build: DTS dist/index.d.mts 12.00 B
@medusajs/toolbox:build: DTS dist/index.d.ts  12.00 B
@medusajs/toolbox:build: ERROR: command finished with error: command (/Users/chrisli/Documents/medusa/packages/design-system/toolbox) yarn run build exited (1)
@medusajs/utils:build: cache miss, executing dcf5f007afc1b2f1
@medusajs/medusa-cli:build: cache miss, executing aabee7d70d5e5a5a
@medusajs/file-local-next:build: cache miss, executing bc9c58eb9530271e
@medusajs/fulfillment-manual:build: cache miss, executing d2252d401f5a2a11
medusa-test-utils:build: cache miss, executing 2c0f9664bb48f0d7
@medusajs/file-s3:build: cache miss, executing 1412e05c82c591f4
@medusajs/orchestration:build: cache miss, executing 3188893eb81046ea
medusa-interfaces:build: cache miss, executing a59a71bcfbf87515
medusa-fulfillment-manual:build: cache miss, executing ff52098f9a52557b
medusa-plugin-sendgrid:build: cache miss, executing c4890cbbbb690776
medusa-payment-adyen:build: cache miss, executing 892f9fa388687339
medusa-plugin-contentful:build: cache miss, executing 5475738826128d5c
medusa-payment-manual:build: cache miss, executing 282175d54c9d0c1a
medusa-payment-klarna:build: cache miss, executing 3ecfc04c61f89d9e
medusa-source-shopify:build: cache miss, executing 578ef2d883e2018c
medusa-plugin-slack-notification:build: cache miss, executing 739f8b3272e7af61
medusa-plugin-ip-lookup:build: cache miss, executing 2de751cf5d84ec6d
medusa-plugin-discount-generator:build: cache miss, executing 34ef3c055c60803e
medusa-plugin-segment:build: cache miss, executing fd7a565ef6ee01ce
medusa-plugin-wishlist:build: cache miss, executing cbd554aaa95dc4fa
medusa-plugin-economic:build: cache miss, executing d282a397c2ab310d
medusa-plugin-twilio-sms:build: cache miss, executing 925adba606b7dafe
@medusajs/modules-sdk:build: cache miss, executing 29fe7c8189f6a5c1
command (/Users/chrisli/Documents/medusa/packages/design-system/toolbox) yarn run build exited (1)

 Tasks:    7 successful, 33 total
Cached:    7 cached, 33 total
  Time:    5.327s 
Failed:    @medusajs/toolbox#build

 ERROR  run failed: command  exited (1)
```

### Additional context

I can fix the first error (`Could not resolve "axios-retry"`) by navigating to the `design-system/toolbox` directory and running `yarn add axios-retry@^3.1.9` due to the fact that that package actually has `retry-axios` as a dependency instead of `axios-retry` but either way the second error remains `Could not resolve "@medusajs/admin-shared"` and I haven't found a way to get this to work no matter what I do.

**Comment by sradevski** [comment]
Hey, since you are trying to build the project from source, please see if this is still an issue, as things move quite fast. Thanks!
