### ISSUE TITLE
Startup failure: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by haf** [medusajs/medusa#7180]
## Bug report

When adding new models (in a bad manner by not making migrations for them; just declaring them) Medusa doesn't start, because for the get currency query, a previously executed query failed (and was rolled back)

```
info:    Connection to Redis in module 'event-bus-redis' established
✔ Modules initialized – 90ms
✔ Express intialized – 2ms
✔ Plugins intialized – 263ms
✔ Subscribers initialized – 6ms
✔ API initialized – 33ms
⠋ Initializing defaults
error:   Error starting server
 QueryFailedError: current transaction is aborted, commands ignored until end of transaction block
     at PostgresQueryRunner.query (web/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async SelectQueryBuilder.loadRawResults (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
     at async SelectQueryBuilder.executeEntitiesAndRawResults (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
     at async SelectQueryBuilder.getRawAndEntities (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
     at async SelectQueryBuilder.getOne (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25) {
   query: 'SELECT "Currency"."code" AS "Currency_code", "Currency"."symbol" AS "Currency_symbol", "Currency"."symbol_native" AS                  "Currency_symbol_native", "Currency"."name" AS "Currency_name" FROM "public"."currency" "Currency" WHERE (("Currency"."code" = $1)) LIMIT 1',
   parameters: [ 'usd' ],
   driverError: error: current transaction is aborted, commands ignored until end of transaction block
       at web/node_modules/pg/lib/client.js:526:17
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at async PostgresQueryRunner.query (web/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
       at async SelectQueryBuilder.loadRawResults (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
       at async SelectQueryBuilder.executeEntitiesAndRawResults (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
       at async SelectQueryBuilder.getRawAndEntities (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
       at async SelectQueryBuilder.getOne (web/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25) {
    length: 145,
    severity: 'ERROR',
    code: '25P02',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postgres.c',
    line: '1492',
    routine: 'exec_parse_message'
  },
  length: 145,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1492',
  routine: 'exec_parse_message'
}
```

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

Log error messages

**Comment by akramaskar** [comment]
Hi @haf , i'm having this issue as well while running the integration tests.

Did you solve it?

**Comment by haf** [comment]
Yes, I solved *my* problem by **guessing** the cause correctly. Thankfully I hadn’t changed much

**Comment by akramaskar** [comment]
@haf Thank you for the quick answer! Can you show me what kind of issue that was?

**Comment by haf** [comment]
Sure, I followed the multi-tenant guide and added store;

```
+import {
+  // alias the core entity to not cause a naming conflict
+  Product as MedusaProduct,
+  Store,
+} from "@medusajs/medusa"
+import { Entity, JoinColumn, ManyToOne } from "typeorm"
+
+@Entity()
+export class Product extends MedusaProduct {
+  @ManyToOne(() => Store)
+  @JoinColumn({ name: "store_id" })
+  store: Store
+}
```

then 

```
+import {
+  Store as MedusaStore,
+} from "@medusajs/medusa"
+import { Entity, JoinColumn, ManyToOne } from "typeorm"
+import { Tenant } from "./tenant"
+
+@Entity()
+export class Store extends MedusaStore {
+  @ManyToOne(() => Tenant)
+  @JoinColumn({ name: "tenant_id" })
+  tenant: Tenant
+}
```

without creating the tenant table. So when Medusa started, it crashed.

**Comment by lacymorrow** [comment]
I got a 500 creating a product and now when the server starts I receive this message

**Comment by jerald-dechavez** [comment]
I'm getting same error whenever I extend medusa Product model.

I resolved the issue when I created migration file for the changes on Product model. Then run the `npm run build` and `medusa migrations run`

Then start your medusa application. the error didn't show again

**Comment by Avia-Code** [comment]
I'm encountering an issue when starting my project. The server fails to start, and I receive the following error:

```
QueryFailedError: current transaction is aborted, commands ignored until end of transaction block
    at PostgresQueryRunner.query (/app/medusa/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/app/medusa/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33) {
  query: 'UPDATE "public"."payment_provider" SET "is_installed" = $1',
  parameters: [ 0 ],
  driverError: error: current transaction is aborted, commands ignored until end of transaction block
      at /app/medusa/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/app/medusa/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async UpdateQueryBuilder.execute (/app/medusa/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33) {
    length: 145,
    severity: 'ERROR',
    code: '25P02',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postgres.c',
    line: '1496',
    routine: 'exec_parse_message'
  },
  length: 145,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1496',
  routine: 'exec_parse_message'
}
```


**Details:**

- The issue occurs during the execution of loaders -> defaults.ts when starting the project.
- The table payment_provider is empty.
- This problem is reproducible with Postgres versions 10.4 and 16.4.
- I'm using Medusa version 1.20.7.

**Additional Information:**

It seems that this log may not be very informative, and the actual issue might be elsewhere in the code.
Has anyone encountered a similar issue or could offer insights into what might be causing this problem?

**Steps to Reproduce:**

1. Start the project with the provided configuration.
2. Observe the server startup error related to the transaction block.

**Expected Behavior:**
The server should start without errors related to transaction aborts.

**Actual Behavior:**
The server fails to start due to a QueryFailedError indicating that the transaction is aborted.
Request for Help:

Any suggestions or guidance on resolving this issue would be greatly appreciated.
Thank you!

**Comment by shiva05010** [comment]
@Avia-Code have you found any solution to your problem.

**Comment by IgorKhomenko** [comment]
If I'm not mistaken, this was solved by adjusting user permissions in Postgres, so was related to this

**Comment by haf** [comment]
And I'm not using v1 of Medusa anymore so we can close it.
