### ISSUE TITLE
The customer's in the admin panel is not displaying.

### ISSUE THREAD

**Issue by rakshit-Launchpad** [medusajs/medusa#7461]
### Describe the bug

I am unable to get the customers in the customer's sections in the admin panel.
They were there before when I started the project file, in between I have extended entities and all, maybe due to that I am not able to get them anymore.

Note: I am able to get the single customer details.

here is the error:
````
error:   customerRepo.listAndCount is not a function
TypeError: customerRepo.listAndCount is not a function       
    at CustomerService.<anonymous> (R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\services\customer.js:234:59)
    at step (R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\services\customer.js:59:23)
    at Object.next (R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\services\customer.js:40:53)
    at R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\services\customer.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\services\customer.js:30:12)
    at CustomerService.listAndCount (R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\services\customer.js:223:16)
    at R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\controllers\customers\list-customers.js:81:54
    at step (R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\controllers\customers\list-customers.js:33:23)
    at Object.next (R:\aster test\aster-backend 6 working\6\aster-backend\aster\node_modules\@medusajs\medusa\dist\controllers\customers\list-customers.js:14:53)
::1 - - [26/May/2024:17:34:39 +0000] "GET /admin/customers HTTP/1.1" 500 86 "-" "PostmanRuntime/7.39.0"
````

### System information

Medusa version (including plugins):
    "@medusajs/admin": "7.1.10",
    "@medusajs/medusa": "1.20.0",
    "@medusajs/medusa-js": "^6.1.7",

### Expected behavior

 I should have gotten the customers list.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/133632455/27ee90fe-ccd5-4f07-ad65-5d0603d0ffec)

### Code snippets

I used default medusa admin panel though, but I can get the error using there api as well.
 here is the curl:
````
curl -L -X GET '<BACKEND_URL>/admin/customers' \
-H 'x-medusa-access-token: <API_TOKEN>'
````

### Additional context

If possible please review it as an urgent matter, as I have a project deadline to approach.

**Comment by rakshit-Launchpad** [comment]
@MedusaNick @olivermrbl

**Comment by humbleEwan** [comment]
Extending entities is bugged. Best to avoid that or do a workaround using manual connection tables. (sounds strange, but that is the fastest solution I could find) Create a table that stores the ID of the Entity you wish to extend and place the fields you wish to add into this new table. Now you just have to find the entry associated whit that entity.
