### ISSUE TITLE
How to Extend an Entity | error: relation "public.custom_product" does not exist

### ISSUE THREAD

**Issue by CanTuerk** [medusajs/medusa#7574]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hello Team,

I followed the steps in the official documentation to extend an entity in MedusaJS. Specifically, I need to extend the Product entity for our use case, as it is crucial for our project to customize Products and other entities.

I carefully followed each step in the documentation: [Extend an Entity in MedusaJS](https://docs.medusajs.com/development/entities/extend-entity).

However, when I run npx medusa develop, I encounter the following error in my console output:

```
error:   relation "public.custom_product" does not exist
QueryFailedError: relation "public.custom_product" does not exist
    at PostgresQueryRunner.query (C:\Users\ctuerk\Desktop\medusaJS\mjs\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (C:\Users\ctuerk\Desktop\medusaJS\mjs\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.getRawMany (C:\Users\ctuerk\Desktop\medusaJS\mjs\node_modules\typeorm\query-builder\SelectQueryBuilder.js:646:29)
    at async Promise.allSettled (index 0) {
  query: 'SELECT "customproduct_id" FROM (SELECT "customproduct"."id" AS "customproduct_id", "customproduct"."created_at" AS "customproduct_created_at", row_number() OVER (PARTITION BY "customproduct"."id" ORDER BY "customproduct"."created_at" DESC) AS rownum FROM "public"."custom_product" "customproduct" LEFT JOIN "public"."product_category_product" "customproduct_categories" ON "customproduct_categories"."product_id"="customproduct"."id" LEFT JOIN "public"."product_category" "categories" ON "categories"."id"="customproduct_categories"."product_category_id" WHERE ( "customproduct"."is_giftcard" = $1 ) AND ( "customproduct"."deleted_at" IS NULL ) ORDER BY "customproduct_created_at" DESC) "customproduct" WHERE customproduct.rownum = 1 LIMIT 15',
  parameters: [ false ],
  driverError: error: relation "public.custom_product" does not exist
      at C:\Users\ctuerk\Desktop\medusaJS\mjs\node_modules\pg\lib\client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (C:\Users\ctuerk\Desktop\medusaJS\mjs\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:184:25)
      at async SelectQueryBuilder.loadRawResults (C:\Users\ctuerk\Desktop\medusaJS\mjs\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2192:25)
      at async SelectQueryBuilder.getRawMany (C:\Users\ctuerk\Desktop\medusaJS\mjs\node_modules\typeorm\query-builder\SelectQueryBuilder.js:646:29)
      at async Promise.allSettled (index 0) {
    length: 121,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '256',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1428',
    routine: 'parserOpenTable'
  },
  length: 121,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '256',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1428',
  routine: 'parserOpenTable'
}
```  

Can anyone help me understand what might be causing this issue and how to resolve it?

I was also wondering how one can Customize the New Product Form in the Admin Dashboard. I couldnt find anything helpful in the Documentation regarding this Issue. I would greatly appreciate any ressources on that matter :) 

Thank you!

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by CanTuerk** [comment]
Found the Issue myself. I wanted to name my extended Product CustomProduct this caused the Problem.
