### ISSUE TITLE
Payment with cart_id cart_01HZYMY5ZEGBJZQ7TXJDTQ4NAJ already exists.

### ISSUE THREAD

**Issue by khalilxg** [medusajs/medusa#7657]
scenario

user purchase, continue to payment, make a paypal payment (i only use paypal), after paypal pop-up successful payment disappear, i got on the medusajs nextjs on the UI "An error occurred, please try again."

IN NEXTJS terminal im having:  ⨯ src/lib/util/medusa-error.ts (14:10) @ medusaError
 ⨯ Error: Payment with cart_id cart_01HZYMY5ZEGBJZQ7TXJDTQ4NAJ already exists..
    at medusaError (./src/lib/util/medusa-error.ts:16:15)
    at eval (./src/lib/data/index.ts:168:194)
    at async placeOrder (./src/modules/checkout/actions.ts:188:16)
  12 |     const message = error.response.data.message || error.response.data
  13 |
> 14 |     throw new Error(message.charAt(0).toUpperCase() + message.slice(1) + ".")
     |          ^
  15 |   } else if (error.request) {
  16 |     // The request was made but no response was received
  17 |     throw new Error("No response received: " + error.request)

on medusajs backend: error:   Payment with cart_id cart_01HZYMY5ZEGBJZQ7TXJDTQ4NAJ already exists.
Error: Payment with cart_id cart_01HZYMY5ZEGBJZQ7TXJDTQ4NAJ already exists.
    at formatException (/home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/@medusajs/medusa/dist/utils/exception-formatter.js:16:20)
    at exports.default (/home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/@medusajs/medusa/dist/api/middlewares/error-handler.js:14:43)
    at Layer.handle_error (/home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/index.js:326:13)
    at /home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/index.js:346:12)
    at next (/home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/index.js:280:10)
    at /home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/index.js:646:15
    at next (/home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/index.js:265:14)
    at /home/ubuntu/Desktop/medusa-comic-store-master (1)/medusa-comic-store-master/bookai/node_modules/express/lib/router/index.js:646:15 {
  type: 'duplicate_error',
  code: undefined,
  date: 2024-06-09T14:12:11.748Z
}
::ffff:127.0.0.1 - - [09/Jun/2024:14:12:11 +0000] "POST /store/carts/cart_01HZYMY5ZEGBJZQ7TXJDTQ4NAJ/complete HTTP/1.1" 422 138 "-" "axios/0.24.0"

error conclusion: duplicate cart_id

**Comment by khalilxg** [comment]
solution delete all indices from the table cart TRUNCATE TABLE cart CASCADE; which is not a fiable solution

**Comment by humbleEwan** [comment]
Could you please provide code on how you implemented the payment service class?

**Comment by xyangwang** [comment]
I have the same problem.

**Comment by gujiavv** [comment]
I have the same problem.
