### ISSUE TITLE
Unable to run core-workflows in custom API Route.

### ISSUE THREAD

**Issue by thipokch** [medusajs/medusa#7757]
### Describe the bug

Unable to run `core-flows` in a custom API route. The application throws a `TypeError: Cannot read properties of undefined (reading 'create')` when attempting to execute the `createProductsWorkflow` function. This error occurs because resolving `ProductService` within the custom route returns `undefined`.

### System information

- **Medusa version (including plugins):** MedusaJS v1.20.6
- **Node.js version:** v20.11.1
- **Database:** Postgres
- **Operating system:**: macOS
- **Browser (if relevant):** Not applicable

### Steps to reproduce the behavior
1. Clone the medusa-starter-default
2. Go to the custom route for product creation located at `src/api/admin/products/custom/route.ts`.
3. Execute a POST request to this route with an authenticated Medusa request.
4. Observe the error in the response or server logs.

### Expected behavior

The `createProductsWorkflow` function should execute successfully, creating products without throwing any errors. The `ProductService` should be correctly resolved within the custom route.

### Screenshots

Not applicable.

#### Source code:

```typescript
// src/api/admin/products/custom/route.ts
import { AuthenticatedMedusaRequest, MedusaResponse } from "@medusajs/medusa";
import { createProductsWorkflow } from "@medusajs/core-flows";

export async function POST(
  req: AuthenticatedMedusaRequest,
  res: MedusaResponse
): Promise<void> {
  const { result } = await createProductsWorkflow(req.scope).run({
    input: { products: [] },
  });

  res.json({});
}
```

#### Error Log:

```
error:   Cannot read properties of undefined (reading 'create')
TypeError: Cannot read properties of undefined (reading 'create')
    at exports.createProductsStep.async.container.container (/medusa-starter-default/node_modules/@medusajs/core-flows/dist/product/steps/create-products.js:9:35)
    at Object.invoke (/medusa-starter-default/node_modules/@medusajs/workflows-sdk/dist/utils/composer/create-step.js:42:53)
    at async DistributedTransaction.handler (/medusa-starter-default/node_modules/@medusajs/orchestration/dist/workflow/workflow-manager.js:85:24)
    at async Promise.allSettled (index 0)
Error: Cannot read properties of undefined (reading 'create')
TypeError: Cannot read properties of undefined (reading 'create')
    at exports.createProductsStep.async.container.container (/medusa-starter-default/node_modules/@medusajs/core-flows/dist/product/steps/create-products.js:9:35)
    at Object.invoke (/medusa-starter-default/node_modules/@medusajs/workflows-sdk/dist/utils/composer/create-step.js:42:53)
    at async DistributedTransaction.handler (/medusa-starter-default/node_modules/@medusajs/orchestration/dist/workflow/workflow-manager.js:85:24)
    at async Promise.allSettled (index 0)
    at originalExecution (/medusa-starter-default/node_modules/@medusajs/workflows-sdk/dist/helper/workflow-export.js:31:19)
    at async LocalWorkflow.newRun [as run] (/medusa-starter-default/node_modules/@medusajs/workflows-sdk/dist/helper/workflow-export.js:77:16)
    at async POST (/medusa-starter-default/dist/api/admin/products/custom/route.js:6:24)
```

### Additional context

The issue seems to stem from the `ProductService` not being correctly resolved within the custom route, leading to the `TypeError` when the `createProductsWorkflow` function attempts to access the `create` property. This might be related to an incorrect or missing configuration, dependencies not being correctly injected, or a bug within the `core-flows` or its dependencies.

Please review the setup and ensure all dependencies and configurations are correctly applied. If further assistance is needed, additional context or a minimal reproducible example would be helpful.

**Comment by sradevski** [comment]
Hey, can you please follow the documentation and see if that resolves your issue? A lot of things move fast in v2, so it's possible your issue is already resolved, or it is a configuration issue on your side. https://docs.medusajs.com/v2

Closing for now, please reopen if you are still having issues
