### ISSUE TITLE
Plesk VPN installation failure

### ISSUE THREAD

**Issue by FMaz008** [medusajs/medusa#7768]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Installation failed when running the command  `sudo npx create-medusa-app@latest`

### How can this issue be resolved?

1. Using a Plesk server, log in with SSH
2. sudo apt-get install npm
3. sudo npx create-medusa-app@latest

Obtain the following errors:
```internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/7159/lib/node_modules/create-medusa-app/node_modules/medusa-telemetry/dist/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Unexpected token {
```

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, can you share more details on your setup? Which node version are you using?
