### ISSUE TITLE
Initialization problem with cloned medusa project 

### ISSUE THREAD

**Issue by SpyrosMourelatos** [medusajs/medusa#792]
Hi there thanks for the project. I would like to ask a question related with `medusa new`  command.
When I am running `medusa new project` and then using the file named `project` the server runs normally.
On the other hand when I am trying to `git clone` a project created with the  way described above the server doesn't run and instead 
medusa develop hangs on `Initializing express`
```
Successfully compiled 0 files with Babel (5ms).
info:    Using fake Redis
✔ Models initialized – 139ms
✔ Plugin models initialized – 4ms
✔ Repositories initialized – 111ms
✔ Database initialized – 935ms
✔ Services initialized – 224ms
⠋ Initializing expressexpress-session deprecated req.secret; provide secret option node_modules/@medusajs/medusa/dist/loaders/express.js:70:52
TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/passport-jwt/lib/strategy.js:45:15)
    at _callee4$ (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@medusajs/medusa/dist/loaders/passport.js:83:38)
    at tryCatch (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at /home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@medusajs/medusa/dist/loaders/passport.js:154:18
    at _callee$ (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@medusajs/medusa/dist/loaders/index.js:180:45)
    at tryCatch (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/spy/Documents/bagWebpage/main/medusa_back_2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
Initializing express
```

**Comment by srindom** [comment]
Hi @SpyrosMourelatos! Thanks for highlighting this - the error you are getting stems from not having a `JWT_SECRET` configured in your environment variables. Medusa requires a `JWT_SECRET` and a `COOKIE_SECRET` to be configured in order to bootstrap correctly. 

The `medusa new` command automatically takes [the `.env.template` file](https://github.com/medusajs/medusa-starter-default/blob/master/.env.template) that might exist in a starter project and converts them to a `.env` which is why you don't experience the issue when using the CLI.

**Comment by kasperkristensen** [comment]
Hi, @SpyrosMourelatos thanks for reaching out you! 

For your server to run correctly you should configure your `COOKIE_SECRET` and `JWT_SECRET` environment variables by adding a `.env` file to the root of your Medusa project. :)

**Comment by SpyrosMourelatos** [comment]
Thank you very much,it works. Now this makes me curious as this files needs to be secret but it's kind of underproductive to have it on gitignore. I don't know if there is an optimal solution to that except documentation.
