### ISSUE TITLE
Unable to create module (from documentation)

### ISSUE THREAD

**Issue by QuentinScDS** [medusajs/medusa#7972]
### Describe the bug

  Got a very unclear error after module declaration in medusa config
```
error:   Could not resolve module: Custom: helloModuleService. Error: getCallerFile(position) requires position be less then Error.stackTraceLimit but position was: `10` and Error.stackTraceLimit was: `10`

error:   Error starting server
TypeError: getCallerFile(position) requires position be less then Error.stackTraceLimit but position was: `10` and Error.stackTraceLimit was: `10`
    at getCallerFilePath (C:\src\my-medusa-store\node_modules\@medusajs\utils\src\common\get-caller-file-path.ts:7:11)  
    at defineJoinerConfig (C:\src\my-medusa-store\node_modules\@medusajs\utils\src\modules-sdk\joiner-config-builder.ts:76:41)
    at Module (C:\src\my-medusa-store\node_modules\@medusajs\utils\src\modules-sdk\module.ts:36:49)
    at Object.<anonymous> (C:\src\my-medusa-store\src\modules\hello\index.ts:4:22)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module.m._compile (C:\src\my-medusa-store\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Object.require.extensions.<computed> [as .ts] (C:\src\my-medusa-store\node_modules\ts-node\src\index.ts:1621:12) 
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1021:12)
```
### System information

Medusa version (including plugins): v2.0-preview
Node.js version: 21.7.3
Database: postgres 16
Operating system: Windows 11

### Steps to reproduce the behavior

1. Follow tutorial : https://docs.medusajs.com/v2/basics/modules-and-services
2. Add Module configuration (step 3)
3. RUn app

### Expected behavior

Expect no error

**Comment by QuentinSc** [comment]
Fixed in last utils module version, following discord thread in bug reporting channel
