### ISSUE TITLE
Example: Access Logged-In User => not working

### ISSUE THREAD

**Issue by raquelhortab** [medusajs/medusa#8004]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

We followed the docs but it seems there is some problem with the container (and the docs don't say what it is).

The error:
```
Resolution path: favouriteSolutionService -> container
AwilixResolutionError: Could not resolve 'container'.

Resolution path: favouriteSolutionService -> container
    at resolve (.../node_modules/awilix/lib/container.js:252:23)
    at Object.get (.../node_modules/awilix/lib/container.js:66:33)

```

Service: 

```
import {TransactionBaseService, User} from "@medusajs/medusa";
import {FavouriteSolution} from "../models/favourite_solution";

class FavouriteSolutionService extends TransactionBaseService {

    protected readonly loggedInCustomer: User | null

    constructor({ container }) {
        super(container);
        try {
            this.loggedInCustomer = container.loggedInCustomer
        } catch (e) {
            // avoid errors when backend first runs
        }
    }

    async listFavouriteSolutions() {
        const repo = this.activeManager_.getRepository(FavouriteSolution)
        return await repo.find({ where: { customer_id: this.loggedInCustomer.id } });
    }
}

export default FavouriteSolutionService;
```

api/middleware.ts 

```
import {
    authenticate, Customer, CustomerService,
} from "@medusajs/medusa"
import type {
    MedusaNextFunction,
    MedusaRequest,
    MedusaResponse,
    MiddlewaresConfig,
    User,
    UserService,
} from "@medusajs/medusa"

const registerLoggedInUser = async (
    req: MedusaRequest,
    res: MedusaResponse,
    next: MedusaNextFunction
) => {
    let loggedInUser: User | null = null

    if (req.user && req.user.userId) {
        const userService =
            req.scope.resolve("userService") as UserService
        loggedInUser = await userService.retrieve(req.user.userId)
    }

    req.scope.register({
        loggedInUser: {
            resolve: () => loggedInUser,
        },
    })

    next()
}

const registerLoggedInCustomer = async (
    req: MedusaRequest,
    res: MedusaResponse,
    next: MedusaNextFunction
) => {
    let loggedInCustomer: Customer | null = null

    if (req.user && req.user.userId) {
        const customerService =
            req.scope.resolve("customerService") as CustomerService
        loggedInCustomer = await customerService.retrieve(req.user.customer_id)
    }

    req.scope.register({
        loggedInCustomer: {
            resolve: () => loggedInCustomer,
        },
    })

    next()
}


export const config: MiddlewaresConfig = {
    routes: [
        {
            matcher: "/store/favourite_solutions",
            middlewares: [authenticate(), registerLoggedInCustomer],
        },
        {
            matcher: "/admin/*",
            middlewares: [authenticate(), registerLoggedInUser],
        },
    ],
}
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
@raquelhortab thanks for reporting this! I think you have a typo in the constructor of your service.

can you change this:

```ts
constructor({ container }) {
```

Into this:

```ts
constructor(container) {
```

And try again?

**Comment by raquelhortab** [comment]
Hi! sorry, yes, we saw it and did not think to update the issue. Thanks!

**Comment by shahednasser** [comment]
So do you still have a problem with this update or is it resolved?
