### ISSUE TITLE
Error with CLI

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#807]
I'm working on setting up a development environment for Medusa.

I'm trying to add a yarn command that will migrate the medusa database. It looks like the CLI allows you to do that with `medusa migrations run`, but when I try to do that I get:

```
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
    at Object.continueSession (/Users/derekwene/src/nibll/nibll-home/node_modules/pg/lib/sasl.js:24:11)
    at Client._handleAuthSASLContinue (/Users/derekwene/src/nibll/nibll-home/node_modules/pg/lib/client.js:257:10)
    at Connection.emit (events.js:400:28)
    at /Users/derekwene/src/nibll/nibll-home/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/Users/derekwene/src/nibll/nibll-home/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/Users/derekwene/src/nibll/nibll-home/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
```

But, I was able to add a `seed` command that runs:
`medusa seed -f ./data/seed.json` and it works just fine.

Maybe `medusa migrations run` doesn't pull from .env?

**Comment by srindom** [comment]
Is your connection string configured in your `medusa-config.js` at `projectConfig.database_url`? The migration script pulls connection details from your `medusa-config.js` so if you are running the migrations in the root of your medusa project it should work. 

See the migrate command here: https://github.com/medusajs/medusa/blob/master/packages/medusa/src/commands/migrate.js

**Comment by dwene** [comment]
Hey @srindom ,

Yea, I have all my database environments configured in `medusa-config.js`, I set that up a few days ago.

I tried again this morning and it worked fine... so I guess I'm going to chalk it up to doing something dumb while coding too late at night 😅.
