### ISSUE TITLE
Migration fails when using Postgres docker container. Error: "could not access file "$libdir/plpgsql": No such file or directory"

### ISSUE THREAD

**Issue by IbrahimSwaiss** [medusajs/medusa#8239]
### Running the Migration fails for a new project.

I just created a new project using this command
`npx create-medusa-app@latest --seed --no-boilerplate --db-url=postgres://postgres:123456@localhost:5432/mydatabase --with-nextjs-starter`

I have the db running fine inside a docker container. And the db url is correct since the `migrations` table was created successfully.

Here are the logs for the error:

---
```
Migration productCategoryProduct1674455083104 has been  executed successfully.
query:
      ALTER TABLE sales_channel_location
      ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

      DROP INDEX "IDX_6caaa358f12ed0b846f00e2dcd";
      DROP INDEX "IDX_c2203162ca946a71aeb98390b0";

      CREATE INDEX "IDX_sales_channel_location_sales_channel_id" ON "sales_channel_location" ("sales_channel_id") WHERE deleted_at IS NULL;
      CREATE INDEX "IDX_sales_channel_location_location_id" ON "sales_channel_location" ("location_id") WHERE deleted_at IS NULL;

      ALTER TABLE product_variant_inventory_item
      ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

      DROP INDEX "IDX_c74e8c2835094a37dead376a3b";
      DROP INDEX "IDX_bf5386e7f2acc460adbf96d6f3";

      CREATE INDEX "IDX_product_variant_inventory_item_inventory_item_id" ON "product_variant_inventory_item" ("inventory_item_id") WHERE deleted_at IS NULL;
      CREATE INDEX "IDX_product_variant_inventory_item_variant_id" ON "product_variant_inventory_item" ("variant_id") WHERE deleted_at IS NULL;

query: INSERT INTO "public"."migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1675689306130,"multiLocationSoftDelete1675689306130"]
Migration multiLocationSoftDelete1675689306130 has been  executed successfully.
query:
      ALTER TABLE "product_category"
      ADD COLUMN "rank" integer DEFAULT '0' NOT NULL CHECK ("rank" >= 0);

query:
      CREATE UNIQUE INDEX "UniqProductCategoryParentIdRank"
      ON "product_category" ("parent_category_id", "rank");

query: INSERT INTO "public"."migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1677234878504,"productCategoryRank1677234878504"]
Migration productCategoryRank1677234878504 has been  executed successfully.
query:
        DO
        $$
            BEGIN
                ALTER TABLE product_variant_inventory_item
                    RENAME COLUMN quantity TO required_quantity;
            EXCEPTION
                WHEN undefined_column THEN
            END;
        $$;

query failed:
        DO
        $$
            BEGIN
                ALTER TABLE product_variant_inventory_item
                    RENAME COLUMN quantity TO required_quantity;
            EXCEPTION
                WHEN undefined_column THEN
            END;
        $$;

error: error: could not access file "$libdir/plpgsql": No such file or directory
query: ROLLBACK
QueryFailedError: could not access file "$libdir/plpgsql": No such file or directory
    at PostgresQueryRunner.query (/Users/test/Developer/my/my-app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  query: '\n' +
    '        DO\n' +
    '        $$\n' +
    '            BEGIN\n' +
    '                ALTER TABLE product_variant_inventory_item\n' +
    '                    RENAME COLUMN quantity TO required_quantity;\n' +
    '            EXCEPTION\n' +
    '                WHEN undefined_column THEN\n' +
    '            END;\n' +
    '        $$;\n' +
    '    ',
  parameters: undefined,
  driverError: error: could not access file "$libdir/plpgsql": No such file or directory
      at /Users/test/Developer/my/my-app/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/Users/test/Developer/my/my-app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25) {
    length: 131,
    severity: 'ERROR',
    code: '58P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'dfmgr.c',
    line: '210',
    routine: 'internal_load_library'
  },
  length: 131,
  severity: 'ERROR',
  code: '58P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'dfmgr.c',
  line: '210',
  routine: 'internal_load_library'
}
```
---

### System information

Medusa version (including plugins):
Node.js version: v18.20.3
Database: postgres
Operating system: mac os
Browser (if relevant): firefox

### Steps to reproduce the behavior

1. Create Postgres DB: `docker run --name mydb -e POSTGRES_PASSWORD=123456 -e POSTGRES_USER=postgres -e POSTGRES_DB=mydb -v MyDbData:/VAR/LIB/POSTGRESQL/DATA -p 5432:5432 -d postgres`
2. Create Medusa App: `npx create-medusa-app@latest --seed --no-boilerplate --db-url=postgres://postgres:123456@localhost:5432/mydatabase --with-nextjs-starter`
3. Check the error form the logs > QueryFailedError: could not access file "$libdir/plpgsql": No such file or directory

### Expected behavior

Migrations should run normally without issues.

**Comment by srindom** [comment]
Don't think this is related to Medusa. Can you check if this helps: https://stackoverflow.com/questions/20827761/could-not-access-file-libdir-plpgsql-no-such-file-or-directory

**Comment by IbrahimSwaiss** [comment]
I've checked the answer, everything seems to be in order from the container side.

**Comment by srindom** [comment]
Unfortunately, not able to reproduce this. Think it's caused by a misconfiguration of Postgres. 

Will close for now - feel free to reopen with a minimal reproduction in a repo.

**Comment by IbrahimSwaiss** [comment]
Just in case someone faced the same issue, it was because of the password was all numbers, I changed the db password to string, and it worked just fine.
