### ISSUE TITLE
Can't run migrations after installation

### ISSUE THREAD

**Issue by opeah** [medusajs/medusa#8476]
### Describe the bug

I can't run the migrations after installation. I'm receiving this error.
```
info:    MODULE: cacheService
error:   Failed with error The "path" argument must be of type string. Received undefined
TypeError: The "path" argument must be of type string. Received undefined
    at basename (node:path:1312:5)
    at new Migrator (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@mikro-orm+migrations@5.9.7_@mikro-orm+core@5.9.7_@types+node@17.0.45_pg@8.12.0/node_modules/@mikro-orm/migrations/Migrator.js:27:44)
    at Configuration.getCachedService (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgresql@5.9.7/node_modules/@mikro-orm/core/utils/Configuration.js:149:38)
    at PostgreSqlPlatform.getMigrator (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@mikro-orm+knex@5.9.7_@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgresql_mtwcxawuweqnxdrkwb5wng5c5i/node_modules/@mikro-orm/knex/AbstractSqlPlatform.js:40:28)
    at MikroORM.getMigrator (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgresql@5.9.7/node_modules/@mikro-orm/core/MikroORM.js:170:42)
    at Migrations.run (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+utils@1.12.0-preview-20240806210444_@types+node@17.0.45_pg@8.12.0/node_modules/@medusajs/utils/src/migrations/index.ts:77:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+utils@1.12.0-preview-20240806210444_@types+node@17.0.45_pg@8.12.0/node_modules/@medusajs/utils/src/modules-sdk/migration-scripts/migration-up.ts:47:22
    at async Function.migrateUp (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240806210444_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:633:9)
    at async applyMigration (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240806210444_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:473:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I'm also receiving error for all other modules like `eventBus`, `workflows`, `stockLocationService`, etc.

### System information

Medusa version (including plugins): preview
Node.js version: 20.16.0
Database: postgres@14
Operating system: macOs

### Steps to reproduce the behavior

1. Create new app with `npx create-medusa-app@preview --skip-db`
2. Replace `DATABASE_URL` in `.env`
3. Launch `npx @medusajs/medusa-cli@preview migrations run`

### Expected behavior

Migrations should be applied

### Additional context

- I'm using `pnpm@9.5.0`
- The `medusa` folder is in a monorepo
- I'm using Docker for my local database

**Comment by thetutlage** [comment]
Hey @opeah 👋

Can you please share the `.env` file contents?

**Comment by opeah** [comment]
Hello @thetutlage,

```
MEDUSA_ADMIN_ONBOARDING_TYPE=nextjs
STORE_CORS=http://localhost:8000,https://docs.medusajs.com
ADMIN_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
AUTH_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
REDIS_URL=redis://localhost:6379
JWT_SECRET=supersecret
COOKIE_SECRET=supersecret
MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=my-medusa-store-storefront
DATABASE_URL=postgres://postgres:password@localhost:9991
```

**Comment by thetutlage** [comment]
Thanks. Can you please try running the following command to run the migrations? Also, are you able to connect to your PostgreSQL instance directly via CLI on port `9991`?

```sh
npx medusa migrations run
```

**Comment by thetutlage** [comment]
Alright. I just noticed that you are using `pnpm`. Unfortunately, we are not supporting pnpm for now. So can you please use `yarn` instead? 

Do note: Pnpm is something we want to support, but during the preview phase we are spending time on other high priority issues and feature requests

**Comment by opeah** [comment]
No I can't switch to `yarn` unfortunately. Do you plan to support it for the final release?

**Comment by olivermrbl** [comment]
@opeah, your `.env` might be missing a few details:
- Database name in the URL path
- Postgres URL

Can you try to add the following but with your DB name at the end

```
DATABASE_URL="postgres://postgres@localhost/<DB NAME>"
POSTGRES_URL="postgres://postgres@localhost/<DB NAME>"
```

Right now, we require two different URLs, but we will likely simplify this in the near future.

**Comment by opeah** [comment]
Thanks @olivermrbl, it's working, migrations was successful.
However, now when I execute `medusa develop`, I encounter a different error.

```
error:   Could not resolve module: cartCartPaymentPaymentCollectionLink. Error: Loaders for module cartCartPaymentPaymentCollectionLink failed: Cannot read properties of undefined (reading 'className')

Error initializing link modules. Error: Loaders for module cartCartPaymentPaymentCollectionLink failed: Cannot read properties of undefined (reading 'className')
    at runLoaders (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:378:14)
    at async loadInternalModule (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:152:17)
    at async loadModule (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:88:10)
    at async moduleLoader (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:21:32)
    at async Function.bootstrapLink (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:505:7)
    at async initialize (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+link-modules@0.2.12-preview-20240808120639_@mikro-orm+migrations@5.9.7_@mikro-orm+c_zdodb72hczltl5fwbrbmsp2eq4/node_modules/@medusajs/link-modules/dist/initialize/index.js:109:24)
    at async initializeLinks (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:172:28)
    at async MedusaApp_ (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:401:47)
    at async MedusaApp (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:539:10)
    at async MedusaAppLoader.load (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+framework@0.0.2-preview-20240808120639_@types+ioredis-mock@8.2.5_@types+node@17.0.45_pg@8.12.0/node_modules/@medusajs/framework/dist/medusa-app-loader.js:139:27)
Error: Loaders for module cartCartPaymentPaymentCollectionLink failed: Cannot read properties of undefined (reading 'className')
    at runLoaders (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:378:14)
    at async loadInternalModule (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:152:17)
    at async loadModule (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:88:10)
    at async moduleLoader (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:21:32)
    at async Function.bootstrapLink (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:505:7)
    at async initialize (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+link-modules@0.2.12-preview-20240808120639_@mikro-orm+migrations@5.9.7_@mikro-orm+c_zdodb72hczltl5fwbrbmsp2eq4/node_modules/@medusajs/link-modules/dist/initialize/index.js:109:24)
    at async initializeLinks (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:172:28)
    at async MedusaApp_ (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:401:47)
    at async MedusaApp (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+modules-sdk@1.13.0-preview-20240808120639_@types+node@17.0.45/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:539:10)
    at async MedusaAppLoader.load (/Users/sebastiencrepin/Data/Projects/ecom-template-v2/node_modules/.pnpm/@medusajs+framework@0.0.2-preview-20240808120639_@types+ioredis-mock@8.2.5_@types+node@17.0.45_pg@8.12.0/node_modules/@medusajs/framework/dist/medusa-app-loader.js:139:27)
```
Is it due to `pnpm`?
Thanks

**Comment by carlos-r-l-rodrigues** [comment]
hi @opeah, yes. This is an issue using `pnpm` that we are investigating.

**Comment by carlos-r-l-rodrigues** [comment]
@opeah Meanwhile, you can create a `.npmrc` file in your project, and add that in it:
`node-linker=hoisted`

Tha should enable you to use `pnpm`

We will continue investigating the issue when symlinks are used.

**Comment by sradevski** [comment]
@opeah Also, you'll need to run
`npx medusa links sync` to sync the link definitions between modules, if you haven't already.

**Comment by haf** [comment]
@carlos-r-l-rodrigues Did you make MedusaJS work with pnpm out of the box now?

**Comment by carlos-r-l-rodrigues** [comment]
Not yet @haf, only with `node-linker=hoisted` for now.
We are reorganizing our packages and I hope we can find the root cause in the next couple of weeks.

**Comment by opeah** [comment]
I set up a new project from scratch today using the latest preview, and everything went smoothly. Thanks for the help!
I'm looking forward to using it without the `node-linker=hoisted` setting

**Comment by carlos-r-l-rodrigues** [comment]
@haf @opeah could you please give it another try using latest `@preview` version?

**Comment by opeah** [comment]
Hi @carlos-r-l-rodrigues,
I just tested with the latest `@preview` version and removed `node-linker=hoisted`. Everything is working perfectly now. No issues with `npx medusa develop` or `npx medusa migrations run`. Thanks for the fix!

**Comment by opeah** [comment]
I just needed to install:
- `@medusajs/admin-shared`
- `@medusajs/core-flows`
- `@medusajs/modules-sdk`
- `@medusajs/types`
- `@medusajs/ui`
- `@medusajs/utils`

because they were missing in `package.json`

**Comment by carlos-r-l-rodrigues** [comment]
Yes, we'll update our medusa starter to include these dependencies.
Thanks @opeah

**Comment by pmb0** [comment]
If it helps anyone: I just had a very similar problem in a slightly different context (pnpm monorepo, `@mikro-orm/nestjs` and `node-linker=hoisted`, but no medusa) -- the problem was that pnpm automatically installs “optional peer deps”. after disabling it via `auto-install-peers` in the `.npmrc` the problem of this issue was solved here.

**Comment by Sander-Voogt** [comment]
For me this issue occured because i was using node24. I switched to 22 and the issue is gone

**Comment by aldo-roman** [comment]
+1, It also happened to me because of Node 24

@shahednasser Perhaps we should document that the project supports only up to Node 22

Although Node 24 is the new LTS

**Comment by shahednasser** [comment]
Hi @aldo-roman , can you share more details about the issue you're facing? Is it the same error in the original issue?

**Comment by aldo-roman** [comment]
@shahednasser When trying to run `medusa db:generate <module>`, I got the same error as reported here:

```
error:   Failed with error The "path" argument must be of type string. Received undefined
TypeError: The "path" argument must be of type string. Received undefined
```

This happens only with Node 24. Downgrading to Node 22 makes it work.

**Comment by shahednasser** [comment]
Hey everyone, I just tested with Node 24 and couldn't reproduce this issue. Does anyone have a reproducible repo?

**Comment by amo-si** [comment]
> [@shahednasser](https://github.com/shahednasser) When trying to run `medusa db:generate <module>`, I got the same error as reported here:
> 
> ```
> error:   Failed with error The "path" argument must be of type string. Received undefined
> TypeError: The "path" argument must be of type string. Received undefined
> ```
> 
> This happens only with Node 24. Downgrading to Node 22 makes it work.

Unable to generate migrations with Node 24. Downgraded to 22.22.0 and migrations were generated successfully, even though I'm using pnpm. Unfortunately, I don't have a min repo to reproduce the issue. I'll try to create it this week.
