### ISSUE TITLE
Error running create-medusa-app@preview, Service "salesChannelService" was not found

### ISSUE THREAD

**Issue by bytevault** [medusajs/medusa#8530]
### Describe the bug

Error running create-medusa-app@preview, Service "salesChannelService" was not found

### System information

Medusa version (including plugins):  create-medusa-app@1.2.9-preview-20240808180650
Node.js version: 20.16
Package Manager: Yarn
Database: Postgres 16.2
Operating system: MacOS

### Steps to reproduce the behavior

1. npx create-medusa-app@preview
2. See error

``` 
⠋ Running Migrations...
An error occurred while preparing project: Error: An error occurred while running migrations: redisUrl not found. A fake redis instance will be used.
info:    No link to load from /Users/xxx/Desktop/DEV/yyy/apps/backend/src/links. skipped.
info:    Running migrations...
warn:    Link modules schema: No linkable key found for id on module cart.
warn:    Link modules schema: No linkable key found for id on module cart.
warn:    Link modules schema: No linkable key found for id on module cart.
warn:    Link modules schema: No linkable key found for id on module order.
warn:    Link modules schema: No linkable key found for id on module order.
warn:    Link modules schema: No linkable key found for default_currency_code on module currency.
Error: Service "salesChannelService" was not found
    at RemoteJoiner.buildReferences (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:263:15)
    at new RemoteJoiner (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:138:32)
    at new RemoteQuery (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/modules-sdk/src/remote-query.ts:61:25)
    at MedusaApp_ (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:411:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MedusaAppMigrateUp (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:547:29)
    at async MedusaAppLoader.runModulesMigrations (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/framework/dist/medusa-app-loader.js:93:13)
    at async main (/Users/xxx/Desktop/DEV/yyy/apps/backend/node_modules/@medusajs/medusa/src/commands/migrate.ts:64:5)
redisUrl not found. A fake redis instance will be used.
info:    No link to load from /Users/xxx/Desktop/DEV/yyy/apps/backend/src/links. skipped.
warn:    Link modules schema: No linkable key found for id on module cart.
warn:    Link modules schema: No linkable key found for id on module cart.
warn:    Link modules schema: No linkable key found for id on module cart.
warn:    Link modules schema: No linkable key found for id on module order.
warn:    Link modules schema: No linkable key found for id on module order.
warn:    Link modules schema: No linkable key found for default_currency_code on module currency.
error:   Service "salesChannelService" was not found
Error: Service "salesChannelService" was not found
    at RemoteJoiner.buildReferences (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:263:15)
    at new RemoteJoiner (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:138:32)
    at new RemoteQuery (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/modules-sdk/src/remote-query.ts:61:25)
    at MedusaApp_ (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:411:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MedusaAppGetLinksExecutionPlanner (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:588:45)
    at async MedusaAppLoader.getLinksExecutionPlanner (/Users/xxx/Desktop/DEV/yyy/node_modules/@medusajs/framework/dist/medusa-app-loader.js:112:16)
    at async main (/Users/xxx/Desktop/DEV/yyy/apps/backend/node_modules/@medusajs/medusa/src/commands/links.ts:112:21)

```

**Comment by bytevault** [comment]
Issue might be related to turbo monorepo. Command ran successfully outside of the monorepo. Can someone provide some insights of why it is the case?

**Comment by gacek1123** [comment]
Having the same issue outisde a monorepo
Node 20.15
Postgres 15
Windows 10
Yarn 1.22.22

**Comment by bytevault** [comment]
> Having the same issue outisde a monorepo Node 20.15 Postgres 15 Windows 10 Yarn 1.22.22

So I got it up running with a couple manual steps.

Try run
```
>>> npx medusa migrations run
>>> npx medusa links sync
```
If you run into errors, you might want to delete the associated db, then rerun the above commands.
The db connection string is in .env

If you wanna populate db with data, run the following:
```
>>> yarn seed
```

**Comment by olivermrbl** [comment]
@ByteVault, how is your monorepo set up and from which directory do you run the commands?

@gacek1123, please open an issue with more details, if the issue persists.

**Comment by olivermrbl** [comment]
We are unable to help with the provided information. I'll close the issue until more information has been shared.

**Comment by bytevault** [comment]
After using the latest preview version of create-medusa-app@1.2.9-preview-20240819120703,
I am not experiencing the above issues anymore, instead the following error is produced.

```
An error occurred while preparing project: Error: Command failed: npx medusa migrations run && npx medusa links sync
npm warn config ignoring workspace config at /Users/xxx/Desktop/DEV/my-turborepo/apps/my-medusa-store/.npmrc
npm error could not determine executable to run
```

turbo configs:
```json
{
  "$schema": "https://turbo.build/schema.json",
  "ui": "tui",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", ".env*"],
      "outputs": [".next/**", "!.next/cache/**"]
    },
    "lint": {
      "dependsOn": ["^lint"]
    },
    "dev": {
      "cache": false,
      "persistent": true
    }
  }
}
```

Min reproduction steps:
```zsh
yarn dlx create-turbo@latest
cd my-turborepo/

# Update yarn version & settings
yarn set version berry

# Disable Plug&Play
echo nodeLinker: node-modules > .yarnrc.yml
rm -rf node-modules .yarn.lock
yarn install

# Create medusa app
cd apps
yarn create medusa-app@preview
```

After getting the error, tried to run the said command 
```zsh
cd apps/my-medusa-store
npx medusa migrations run && npx medusa links sync
# Error
npm warn config ignoring workspace config at /Users/xxx/Desktop/DEV/my-turborepo/apps/my-medusa-store/.npmrc
npm error could not determine executable to run
```

Instead the following command worked
```zsh
yarn exec 'medusa migrations run && medusa links sync'
```

**Comment by bytevault** [comment]
@olivermrbl Please see above for the updated issue and details, thank you
