### ISSUE TITLE
Failed to create order due to tax_code being an integer

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#869]
I received this error while running complete-cart.
```
error:   invalid input syntax for type integer: "8.25"
QueryFailedError: invalid input syntax for type integer: "8.25"
    at QueryFailedError.TypeORMError [as constructor] (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:250:31)
    at step (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  query: 'INSERT INTO "order"("id", "status", "fulfillment_status", "payment_status", "cart_id", "customer_id", "email", "billing_address_id", "shipping_address_id", "region_id", "currency_code", "tax_rate", "draft_order_id", "canceled_at", "created_at", "updated_at", "metadata", "no_notification", "idempotency_key") VALUES ($1, DEFAULT, DEFAULT, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, DEFAULT, DEFAULT, DEFAULT, $12, $13, DEFAULT) RETURNING "status", "fulfillment_status", "payment_status", "display_id", "created_at", "updated_at"',
  parameters: [
    'order_01FNYP83A369450YWNA5D2KC40',
    'awaiting',
    'cart_01FNYP7Z4VG730KXFHWV0RP47Q',
    'cus_01FNVM61CBER1N8XJSJEXWQTV8',
    'derek@lambdacurry.dev',
    'addr_01FNYP7Z4VP76XFAHBGRG9DGDH',
    'addr_01FNYP7Z4V2QBA2D4QEA8ND6SN',
    'reg_01FNSH93ME2Z792Z84BWV97GZJ',
    'usd',
    '8.25',
    'dorder_01FNYP7Z52T2NW73HC2GA16SZQ',
    '{}',
    false
  ],
  driverError: error: invalid input syntax for type integer: "8.25"
      at Parser.parseErrorMessage (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 143,
    severity: 'ERROR',
    code: '22P02',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: "unnamed portal parameter $10 = '...'",
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'numutils.c',
    line: '320',
    routine: 'pg_strtoint32'
  },
  length: 143,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: "unnamed portal parameter $10 = '...'",
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '320',
  routine: 'pg_strtoint32'
}
```

**Comment by adrien2p** [comment]
Hi @dwene, this is because if I am not wrong the format should be in cents which allow a better management of decimal amount in later (taxes, etc) I remember that from the accountancy  ahah

**Comment by dwene** [comment]
Hey @adrien2p , thanks for your quick response.

`tax_rate` should be a percentage. Here in texas we have an 8.25% sales tax rate applied to all purchases. Unless we store it as tax_rate*100, it would be impossible to store as an integer.

**Comment by adrien2p** [comment]
My bad, I thought it was the amount :D

**Comment by jaruesink** [comment]
For reference, I think tax rates can be up to 4 decimals in some places (kinda silly if you ask me): https://stripe.com/docs/billing/taxes/tax-rates
