### ISSUE TITLE
After deploy, when app is not used throws relation does not exist

### ISSUE THREAD

**Issue by EvaldasOff** [medusajs/medusa#9003]
When I deployed with a Docker to VPS, after some time of inactivity I found this in my terminal:
` error: relation "public.batch_job" does not exist`
I can log in, but I can't see anything
I have already dropped DB several times.
After getting this error I tried to run the migration function, I got this:

```
query: SELECT * FROM current_schema() query: SELECT version(); query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations' query: CREATE TABLE "migrations" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id")) query: SELECT * FROM "public"."migrations" "migrations" ORDER BY "id" DESC 0 migrations are already loaded in the database. 80 migrations were found in the source code. 80 migrations are new migrations must be executed. query: START TRANSACTION query: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id")) query: CREATE TABLE "fulfillment_item" ("fulfillment_id" character varying NOT NULL, "item_id" character varying NOT NULL, "quantity" integer NOT NULL, CONSTRAINT "PK_bc3e8a388de75db146a249922e0" PRIMARY KEY ("fulfillment_id", "item_id")) query: CREATE TABLE "fulfillment" ("id" character varying NOT NULL, "swap_id" character varying, "order_id" character varying, "tracking_numbers" jsonb NOT NULL DEFAULT '[]', "data" jsonb NOT NULL, "shipped_at" TIMESTAMP WITH TIME ZONE, "canceled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metadata" jsonb, "idempotency_key" character varying, "provider_id" character varying, CONSTRAINT "PK_50c102da132afffae660585981f" PRIMARY KEY ("id")) query: CREATE TABLE "return_item" ("return_id" character varying NOT NULL, "item_id" character varying NOT NULL, "quantity" integer NOT NULL, "is_requested" boolean NOT NULL DEFAULT true, "requested_quantity" integer, "received_quantity" integer, "metadata" jsonb, CONSTRAINT "PK_46409dc1dd5f38509b9000c3069" PRIMARY KEY ("return_id", "item_id")) query failed: CREATE TABLE "return_item" ("return_id" character varying NOT NULL, "item_id" character varying NOT NULL, "quantity" integer NOT NULL, "is_requested" boolean NOT NULL DEFAULT true, "requested_quantity" integer, "received_quantity" integer, "metadata" jsonb, CONSTRAINT "PK_46409dc1dd5f38509b9000c3069" PRIMARY KEY ("return_id", "item_id")) error: error: relation "return_item" already exists query: ROLLBACK QueryFailedError: relation "return_item" already exists     at PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {   query: 'CREATE TABLE "return_item" ("return_id" character varying NOT NULL, "item_id" character varying NOT NULL, "quantity" integer NOT NULL, "is_requested" boolean NOT NULL DEFAULT true, "requested_quantity" integer, "received_quantity" integer, "metadata" jsonb, CONSTRAINT "PK_46409dc1dd5f38509b9000c3069" PRIMARY KEY ("return_id", "item_id"))',   parameters: undefined,   driverError: error: relation "return_item" already exists       at /app/node_modules/pg/lib/client.js:526:17       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)       at async PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25) {     length: 105,     severity: 'ERROR',     code: '42P07',     detail: undefined,     hint: undefined,     position: undefined,     internalPosition: undefined,     internalQuery: undefined,     where: undefined,     schema: undefined,     table: undefined,     column: undefined,     dataType: undefined,     constraint: undefined,     file: 'heap.c',     line: '1149',     routine: 'heap_create_with_catalog'   },   length: 105,   severity: 'ERROR',   code: '42P07',   detail: undefined,   hint: undefined,   position: undefined,   internalPosition: undefined,   internalQuery: undefined,   where: undefined,   schema: undefined,   table: undefined,   column: undefined,   dataType: undefined,   constraint: undefined,   file: 'heap.c',   line: '1149',   routine: 'heap_create_with_catalog' }
```

When I drop the database and start a fresh project everything is perfect, until hours of inactive. I found nothing interesting in the logs.

Medusa version (including plugins): "@medusajs/medusa": "^1.20.8",
Node.js version: v18.20.4
Database: postgres
Operating system: linux

**Comment by olivermrbl** [comment]
Can you reproduce this locally on your machine? If so, please provide reproducible steps. The details shared here are insufficient for us to help.

Closing until then.
