### ISSUE TITLE
Error when adding draft order using Multi-Warehouse Modules

### ISSUE THREAD

**Issue by urumat** [medusajs/medusa#9024]
Hello, I'm getting this error when adding draft order from Admin Panel after installing the Multi-Warehouse Modules.

I'm using a fresh medusa installation with npx create-medusa-app@latest.

## Bug report

Unexpected Application Error!
Cannot read properties of undefined (reading 'label')
TypeError: Cannot read properties of undefined (reading 'label')
    at O (http://localhost:7001/node_modules_moment_locale_sync_recursive_-_cache_admin_src_pages_a_tsx.chunk.js:945:20542)
    at le (http://localhost:7001/main.bundle.js:510:55325)
    at http://localhost:7001/main.bundle.js:510:109743
    at c7 (http://localhost:7001/main.bundle.js:510:111085)
    at eh (http://localhost:7001/main.bundle.js:510:170853)
    at fq (http://localhost:7001/main.bundle.js:510:156931)
    at http://localhost:7001/main.bundle.js:510:156652
    at fF (http://localhost:7001/main.bundle.js:510:156659)
    at fP (http://localhost:7001/main.bundle.js:510:152820)
    at fR (http://localhost:7001/main.bundle.js:510:153290)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>

### Steps to reproduce the behavior

1. npx create-medusa-app@latest
2. Install Multi-Warehouse Modules
3. Add draft order

Any help is much appreciated.

**Comment by olivermrbl** [comment]
Are there more steps to the `Add draft order` step described here? E.g. do you complete the draft order, do you create fulfillment, do you add shipping, etc.
