### ISSUE TITLE
 medusa user -e randomemail@gmail.com -p iammedusa , TypeError: cmd is not a function

### ISSUE THREAD

**Issue by onedawa** [medusajs/medusa#905]
Hi,
I wanted to test out medusa today in my free time, but am stuck at this point
 `medusa user -e randomemail@gmail.com -p iammedusa`
I am using wsl debian 10

```
medusa user

Create a user

Options:
  --verbose                Turn on verbose output                                             [boolean] [default: false]  --no-color, --no-colors  Turn off the color in output                                       [boolean] [default: false]  --json                   Turn on the JSON logger                                            [boolean] [default: false]  -e, --email              User's email.                                                                        [string]  -p, --password           User's password.                                                                     [string]  -i, --id                 User's id.                                                                           [string]  -h, --help               Show help                                                                           [boolean]  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project    [boolean]medusa user

Create a user

Options:
  --verbose                Turn on verbose output                                             [boolean] [default: false]  --no-color, --no-colors  Turn off the color in output                                       [boolean] [default: false]  --json                   Turn on the JSON logger                                            [boolean] [default: false]  -e, --email              User's email.                                                                        [string]  -p, --password           User's password.                                                                     [string]  -i, --id                 User's id.                                                                           [string]  -h, --help               Show help                                                                           [boolean]  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project    [boolean]TypeError: cmd is not a function
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:309:7
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
    at Object.handler (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:54:24)
    at Object.runCommand (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:584:29)
    at module.exports (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:392:6)
    at Object.<anonymous> (/usr/lib/node_modules/@medusajs/medusa-cli/dist/index.js:70:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

How am I supposed to create users

**Comment by adrien2p** [comment]
Hi @onedawa where did you run your command and where is you medusa-config file located ?

**Comment by onedawa** [comment]
I re ran everything today and it succeded without errors
