### ISSUE TITLE
Issue with "ajv" and "medusa-cli"

### ISSUE THREAD

**Issue by KareemAbbas1** [medusajs/medusa#9145]
### Describe the bug

My project was working fine with no problems and suddenly out of nowhere I started the server using the command "npm run dev" as usual, but I got two errors in my terminal. The first one is "TypeErro: applicator_1 is not a function" and the second one is "cmd is not a function" and I became unable to login to my admin dashboard. When I log in to the dashboard I get an error that my credentials are wrong which they're not, I'm very sure that these are the right credentials. Full errors are listed below.

### System information

Medusa version (including plugins): 1.20.6
Node.js version: 1.18.18
Database: Postgres
Operating system: Windows
Browser (if relevant): not relevant

### Expected behavior

The server should run as usual and I get to log into my admin dashboard.

### Code snippets

```
--------------- ERROR ---------------------
TypeError: applicator_1.default is not a function
    at Object.<anonymous> (D:\Projects\fourpets-final\node_modules\ajv-draft-04\dist\vocabulary\draft4.js:11:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\Projects\fourpets-final\node_modules\ajv-draft-04\dist\index.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[boolean]TypeError: cmd is not a function
    at D:\Projects\fourpets-final\node_modules\@medusajs\medusa-cli\dist\create-cli.js:198:13
    at D:\Projects\fourpets-final\node_modules\@medusajs\medusa-cli\dist\create-cli.js:48:30
    at Object.handler (D:\Projects\fourpets-final\node_modules\@medusajs\medusa-cli\dist\create-cli.js:16:21)
    at Object.runCommand (D:\Projects\fourpets-final\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\Projects\fourpets-final\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.parse (D:\Projects\fourpets-final\node_modules\yargs\build\lib\yargs.js:584:29)
    at exports.default (D:\Projects\fourpets-final\node_modules\@medusajs\medusa-cli\dist\create-cli.js:353:10)
    at Object.<anonymous> (D:\Projects\fourpets-final\node_modules\@medusajs\medusa-cli\dist\index.js:38:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
```

**Comment by KareemAbbas1** [comment]
@sidd-kulk @Arsenalist @l4u @madsleejensen 
Sorry for the disturbance, but could someone close this issue? The issues mentioned here are fixed alongside another issue related to BullMQ. If anyone runs into any of these issues upgrade to Medusa version 1.2010. 
```
npm install @medusajs/medusa@1.2010
```
