### ISSUE TITLE
TypeError: handler is not a function

### ISSUE THREAD

**Issue by joekendal** [medusajs/medusa#9362]
### Describe the bug

Following the official v2.0 docs causes the Scheduled Jobs to not work on the `preview` release.

### System information

Medusa version (including plugins): "preview"
Node.js version: 20
Database: Postgres
Operating system: Not applicable
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to [https://docs.medusajs.com/v2/basics/scheduled-jobs](https://docs.medusajs.com/v2/basics/scheduled-jobs)
2. Reproduce the code as shown in the guide. Using "preview" for each of the dependencies.
3. `yarn dev`

```
yarn dev   
yarn run v1.22.19
$ medusa develop
info:    Watching filesystem to reload dev server on file change
info:    OTEL registered
info:    Connection to Redis in module 'event-bus-redis' established
info:    Connection to Redis in module 'cache-redis' established
info:    Connection to Redis in module 'workflow-engine-redis' established
info:    Connection to Redis PubSub in module 'workflow-engine-redis' established
[HELLO MODULE] Just started the Medusa application!
info:    No job to load from ./node_modules/@medusajs/medusa/dist/jobs. skipped.
info:    Geneated modules types
✔ Server is ready on port: 9000 – 7ms
error:   Scheduled job every-minute-message failed with error: handler is not a function
error:   job-every-minute-message:every-minute-message-as-step:invoke - handler is not a function
TypeError: handler is not a function
    at Object.<anonymous> (./node_modules/@medusajs/framework/src/jobs/job-loader.ts:99:29)
    at Object.invoke (./node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:58:67)
    at DistributedTransaction.handler (./node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:43)
    at stepHandler (./node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:788:38)
    at ./node_modules/@medusajs/medusa/src/instrumentation/index.ts:235:22
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorageContextManager.with (./node_modules/@opentelemetry/context-async-hooks/src/AsyncLocalStorageContextManager.ts:40:36)
    at ContextAPI.with (./node_modules/@opentelemetry/api/src/api/context.ts:77:42)
    at Tracer.startActiveSpan (./node_modules/@opentelemetry/sdk-trace-base/src/Tracer.ts:241:28)
    at ProxyTracer.startActiveSpan (./node_modules/@opentelemetry/api/src/trace/ProxyTracer.ts:51:20)
```

### Expected behavior

Working as in guide

### Screenshots

Not applicable

### Code snippets

As in guide

### Additional context

Tried with and without redis. Tried with `yarn build` first or `yarn dev` only and no difference. 

Bug seems to have been introduced recently: https://discord.com/channels/876835651130097704/1288938916636004456/1288938916636004456

**Comment by sradevski** [comment]
Thanks for opening the ticket, we'll investigate.
