### ISSUE TITLE
Unable to update quantity of line items added with cartModuleService.addLineItems

### ISSUE THREAD

**Issue by matt-rolley** [medusajs/medusa#9863]
### Describe the bug

We use cartModuleService.addLineItems to allow the customers to add their custom created products to the cart. We can add them into the cart fine.

If/when the user wants to update their cart, using the either:

```JS
sdk.carts.lineItems.update(<the new line item ID>)
sdk.carts.update()
``` 

we get the following error:

```JS
Error: ProductVariant id not found: 
```

### System information

Medusa version (including plugins): 2.0.1
Node.js version: 20.11.1
Database: Postgres
Operating system: Mac Sonoma 14.5
Browser (if relevant): N/A - Happens server side

### Steps to reproduce the behavior

1. Create an Medusa API route that calls the following: 
```JS
await cartModuleService.addLineItems({
    cart_id: cartId,
    product_title: 'My Title',
    quantity: 1,
    unit_price: 150,
    title: 'Testing',
    thumbnail,
    // Tried it with and without variant ID too
    variant_id: 'testing-1234'.
})
```
2. Call sdk.carts.lineItems.update(cartId, lineItemId, { quantity: 5 })
3. See error 

```JS
error:   ProductVariant id not found: testing-1234
{
  message: 'ProductVariant id not found: testing-1234',
  name: 'Error',
  stack: 'Error: ProductVariant id not found: testing-1234\n' +
    '    at RemoteJoiner.checkIfKeysExist (<PROJECT_ROOT>/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:556:13)\n' +
    '    at RemoteJoiner.fetchData (<PROJECT_ROOT>/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:493:10)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async RemoteJoiner.query (<PROJECT_ROOT>/node_modules/@medusajs/orchestration/src/joiner/remote-joiner.ts:1230:22)\n' +
    '    at async RemoteQuery.query (<PROJECT_ROOT>/node_modules/@medusajs/modules-sdk/src/remote-query/remote-query.ts:289:12)\n' +
    '    at async Query.query (<PROJECT_ROOT>/node_modules/@medusajs/modules-sdk/src/remote-query/query.ts:126:12)\n' +
    '    at async Object.<anonymous> (<PROJECT_ROOT>/node_modules/@medusajs/core-flows/src/common/steps/use-remote-query.ts:165:22)\n' +
    '    at async Object.invoke (<PROJECT_ROOT>/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:72:52)\n' +
    '    at async DistributedTransaction.handler (<PROJECT_ROOT>/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (<PROJECT_ROOT>/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:806:20)\n' +
    '⮑ sat <PROJECT_ROOT>/node_modules/@medusajs/core-flows/dist/cart/workflows/refresh-cart-items.js: [refresh-cart-items -> fetch-variants (invoke)]\n' +
    '⮑ sat <PROJECT_ROOT>/node_modules/@medusajs/core-flows/dist/cart/workflows/update-cart.js: [update-cart -> refresh-cart-items-as-step (invoke)]',
  __isMedusaError: true,
  type: 'not_found',
  code: undefined,
  date: 2024-10-29T16:28:11.934Z
}
```

### Expected behavior

Allow the newly created line item quantity to be updated as any other item added via the admin area, or allow the user to update their cart after creating a line item.

**Comment by matt-rolley** [comment]
Bump - linked to https://github.com/medusajs/medusa/issues/9995

**Comment by olivermrbl** [comment]
Available in https://github.com/medusajs/medusa/releases/tag/v2.1.3
